### ISSUE TITLE
Width of field contains cyrillic values

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#12585]
Author Name: **dr -** (dr -)
Original Redmine Issue: [2525](https://issues.qgis.org/issues/2525)

Redmine category:vectors
Assignee: nobody -

---
I'm not sure is it bug or not, but it could throw into confusion some users. When create new vector layer and set its width need keep in mind, that width of field it is size of field in bytes, not in symbols! For example, I create text field and set width=3. I try to fill this field with Cyrillic word 'баг' and when I've save changes in layer I've get the following results:
[http://gis-lab.info/share/DR/utf.png]
I guess this is because for encoding cyrillic symbols in utf uses 2 bytes.

---

- [example.7z](https://issues.qgis.org/attachments/download/2612/example.7z) (Maxim Dubinin)

**Comment by suricactus** [comment]
I have tried on 3.12 and I cannot reproduce the problem anymore. As far as I am remember, this issue is not present at least from 3.4 onwards,as I regularly work with data in Cyrillic.

![image](https://user-images.githubusercontent.com/2820439/76491151-b91dbe80-6435-11ea-9cf6-03879523de92.png)
 

[cyrillic.zip](https://github.com/qgis/QGIS/files/4322449/cyrillic.zip)

This issue should be closed.
