### ISSUE TITLE
Enhancement: ability to search for a plugin to run

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#14052]
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [4069](https://issues.qgis.org/issues/4069)

Redmine category:gui

---
*Problem description*
Quoting from an old ticket: "With the explosion of QGIS plugins, people will eventually have so many plugins that it would get hard to find them in the Plugin menu or Plugin toolbar."

"eventually" is now!

This is particularly a problem when a plugin is not grouped into one of the categories (e.g. "analysis" or "vector"), and its name is different from the label of its menu entry e.g. "shaded relief" vs "DEM relief shader".

In the plugin manager and the plugin installer there is a "filter", which allows the user to search for a plugin to install/uninstall or enable/disable it.  It would be good if there was also somewhere where the user could search for a plugin to _run_ it.

*Possible Solutions*
1. Add to the plugin manager the ability to start a plugin.
1. Implement something like #11794: "Use a dockable tabbed window for plugins", and include a filter.  Personally I don't like the idea of an array of buttons (a list like the plugin manager would be better), and rather than category tabs it may be better to have a single list of plugins, with the ability to filter by category.
1. Combine 1 and 2, i.e. modify the plugin manager to be a dockable modeless window with the ability to launch plugins.
1. ?

The need for this would probably be reduced significantly if #11662: "Grouping plugins in the menu" was implemented, i.e. if all plugin developers put their plugins into category submenus.

**Comment by m-kuhn** [comment]
What exactly is the definition of *running a plugin* (sometimes in here also refered to as *starting a plugin*?

There are a lot of different things a plugin can do:

* Adding processing algorithms (https://plugins.qgis.org/plugins/processing_r/)
* Adding locator filers (https://plugins.qgis.org/plugins/swiss_locator/)
* Adding expression functions (https://plugins.qgis.org/plugins/refFunctions/)
* Adding toolbar buttons, menu entries, other UI elements that
  * open a modal dialog
  * open dock widgets
  * start map tools
* ... or they do all sort of other crazy stuff

from what I can see, extracting a common "start" concept from this is (maybe not even) close to impossible.

That's probably the reason that after all this time this ticket isn't gaining much traction.

I think that it's not something that QGIS itself needs to solve, but that instead plugins should improve their description.
What could help here is

 1. to make it possible/easier to add screenshots to the plugin description that help people to get started
 2. to go over plugins with poor description and add more information

I would propose that one or more of the following steps happen
 * a new issue is opened for 1. above
 * interested parties start working on 2.
 * use cases are listed in here that would benefit from a new unified *run plugin* concept with detailed GUI and workflow descriptions
 * the guides to write plugins are reworked so people don't add new menu items to the plugin menu
 * this issue is closed

**Comment by borysiasty** [comment]
@AlisterH wrote:
> As far as I can see there is no way to use it to run a plugin, 
> except if the plugin has provided a processing algorithm.

From the Locator you can also trigger menu actions (including show/hide docks created by plugins). Isn't it all you can "run" from the plugin?

**Comment by AlisterH** [comment]
Ah, right, thanks for the keyword - "actions".

When I saw "Actions" I thought it meant "layer actions", but actually if I type ". " and then part of the label for a menu item or a panel or toolbar, then it is listed.  So "Actions" really means "gui actions".  

I guess this won't be so obscure when there is some documentation, but surely there is a better way of describing it?  How about ". menu entries and panels/toolbars" (even though that is a bit redundant because the panels and toolbars are actually listed in the menu)?  Does it provide access to anything else that isn't a menu entry?

**Comment by AlisterH** [comment]
I guess the main thing that was tripping me up is that you actually need to type ". " to search menu entries, when you don't need to type e.g. "a " to search processing algorithms.  Is there a reason menu entries aren't searched by default?

**Comment by borysiasty** [comment]
> When I saw "Actions" I thought it meant "layer actions"

Ah, now I see. I fully agree it's misleading, so in Polish translation I translated it more descriptively (just as a fast fix before a release), and forgot that the problem still remains in the source! I think it deserves a separate ticket.

> Does it provide access to anything else that isn't a menu entry?

Well, if I create a QAction and add it to a toolbar but not to the main menu, it seems it's not accessible. It could be improved. 

> Is there a reason menu entries aren't searched by default?

Maybe they are too many, so the results list would be cluttered? I guess it was a fast decision which filters are active by default (without the prefix), and it can be re-discussed.

Anyway, you can still configure it (in the main settings window, btw. accessible from the Locator). From my experience, in various user profiles I'd use different settings. In some projects I have 50+ layers and all I need from Locator is to easily seek the desired layer - so I don't want the list cluttered by any other kinds of results.

**Comment by AlisterH** [comment]
Oh, I can't edit my tickets that have been migrated from redmine; annoying.

> Well, if I create a QAction and add it to a toolbar but not to the main menu, it seems it's not accessible. 

Confirmed - that means this ticket is something like 75% complete, I guess :)
This was actually one of the situations that prompted me to file this ticket.  After you install a plugin you have to go on a treasure hunt, because you have no way of knowing whether it will add things in the menus, or in the toolbars, or both (or even neither, I guess).

> I think it deserves a separate ticket.
#30186

**Comment by borysiasty** [comment]
Thanks! I see you also mentioned the toolbar-only actions there, so maybe we can close this ticket now?

**Comment by AlisterH** [comment]
I thought you wanted a separate ticket because you thought the two changes might be implemented separately...

Feel free to manage the tickets how you like, but I am unable to edit or close this one.

**Comment by borysiasty** [comment]
1. Yes, I guess they can be implemented separately
2. I guess this topic became so long and outdated there is very little chance anyone will ever find its conclusion among all the 3000 tickets. 
3. I'm not able to manage any tickets because of complete lack of time. I just wanted to say "From the Locator you can also trigger menu actions" and not take over maintenance of this ticket ;-)

**Comment by AlisterH** [comment]
As Borys suggested, it would probably be good if someone could close this ticket, unless they want to update the description with the current status, which is:
- menu entries can be searched in the locator bar, using `.` by default (discoverability is a minor issue as per #30186).
- toolbar buttons that aren't also menu entries can't be searched.
