### ISSUE TITLE
Transparency of markers in marker line is neither applied nor stored

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18022]
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [9428](https://issues.qgis.org/issues/9428)
Affected QGIS version: 3.7(master)
Redmine category:gui
Assignee: Martin Dobias

---
The GUI for markers in a marker line has a transparency slider but the setting is not applied to the markers in the preview or in the map itself. The setting isn't stored either.

**Comment by alexbruy** [comment]
Looks like the problem is that we have multiple places to change opacity for this symbol type:
1. slider in the top-level "Line" symbol layer
2. slider in the "Marker" symbol layer
3. fill and stroke at the "Simple Marker" level also allow to set opacity

If opacity changed at the top-level "Line" level it saved/restored in/from QML and applied in the preview as well as when rendering layer both on canvas and in the layer tree. Changing opacity at the "Marker" does not have any effect except in the preview area.

Don't know if this is by design or not.

**Comment by klakar** [comment]
Noted this issue in master 3.15.

![Skärmbild från 2020-10-17 15-57-17](https://user-images.githubusercontent.com/6375959/96338919-7e49cc00-1091-11eb-9e2c-d5fc25cbd0f5.png)

Simple markers (and svg markers) in a line will be affected by the overall line opacity slider, but filled markers (and ellipse markers) will not.

If I use the opacity for the whole layer in "Layer Rendering" it will affect all parts of the symbology.


QGIS version | 3.15.0-Master | QGIS code revision | 2659c411a6
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20 | This copy of QGIS writes debugging output.
Active python plugins | LmOpenData; latlontools; MetaSearch; processing; db_manager
