### ISSUE TITLE
Marker placement options for marker line should be checkboxes

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#18433]
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [9922](https://issues.qgis.org/issues/9922)

Redmine category:symbology

---
Currently, all options are radio buttons. The user cannot - in one symbol layer - put the same symbol e.g. on the first and the last vertex. The symbol layer has to be duplicated to achieve this. I think that's unnecessary and more difficult to maintain. Therefore, I suggest to use checkboxes instead of radio buttons for the options "on first vertex", "on last vertex" and "on central point".

**Comment by pjshelton** [comment]
![image](https://user-images.githubusercontent.com/39154868/103178916-f70ba680-48d2-11eb-868d-b8b0e9c81d1b.png)

Because we can create multi-symbols (?) by adding multiple marker lines in the symbology, you don't have to use duplicate layers, you just add two, or more, Marker Line's to the symbology and use a different radio button on each Marker Line.

@anitagraser, @gioman I think we can close this.

**Comment by anitagraser** [comment]
@pjshelton I still stand by my original request. As stated originally, it would be nice not to have to duplicate the **symbol layer**.
