### ISSUE TITLE
Limit amount of fonts used in QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#19903]
Author Name: **Tobias Schneider** (Tobias Schneider)
Original Redmine Issue: [11651](https://issues.qgis.org/issues/11651)

Redmine category:unknown

---
I would like it very much if I could choose a subset from all the fonts that are installed on my OS to be used in QGIS. On Linux the list always fills the screen and it is difficult to select the correct one. Why not have a dialogue on the options menu where users can select their usual mapping fonts, and only those are shown in all other dialogues of QGIS (for example the layer styles, label menu, ...).

**Comment by jgrocha** [comment]
I'm not aware of any other application that provides this functionality. 

We try to rely on the OS native dialogues for fonts, instead of write our own functionality to manage fonts. Font selection should be similar in all applications.

If there are many unused fonts, is up to the user to clean them.
