### ISSUE TITLE
Save to last used directory, not home, when entering filename directly in layer Save As dialog

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#20106]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [11892](https://issues.qgis.org/issues/11892)

Redmine category:unknown

---
If you enter a filename directly in the "Save as" field of the layer Save As dialog, QGIS will save the file to the home directory (at least to ~/ on Linux).
If you click on Browse QGIS knows what directory you last used and automatically opens the chooser dialog in it.

Would it be possible to change that behaviour so that when you enter a filename directly in the "Save as" field, it will save to the last used directory? At least for me this matches my workflow 99% of the time and I accidentally wrote to my home directory many times because it was my intentional expectation.
I know you can enter absolute and relative paths manually in the field, maybe pre-filling the paths to the last used directory would be a feasible workaround? This might use the "Save Paths" project preference for the choice between filling the absolute or relative path.

See the attached image if you are not sure what dialog I am talking about.

---

- [save_as_dialog.png](https://issues.qgis.org/attachments/download/8223/save_as_dialog.png) (Johannes Kroeger)

---

Related issue(s): #20285 (relates)
Redmine related issue(s): [12089](https://issues.qgis.org/issues/12089)

---

**Comment by stragu** [comment]
This is still reproducible in QGIS 3.10.6 (Ubuntu 18.04)
I agree with the original issue report in that it is fairly inconsistent. Clicking "Browse" will take you to the last used folder, whereas using the field titled "name" will place the file into the user's home directory.

The idea of pre-filling the field with a path is a good idea, although it's hard to handle the difference between path and file name (which most people understand as distinct things). What happens if the user does not add a filename to the pre-filled path?

One was to fix it would be to have:
* a location field, pre-filled with a path that's the same as the default for the browser
* a name field

When testing, I noticed a linked bug that appears when only inputting a filename directly in the field: the green banner pop up that notifies of having saved successfully gives a broken link to the file, because it uses a path that does not include the user's home directory path.

**Comment by alexbruy** [comment]
Duplicates #35651
