### ISSUE TITLE
no style backward compatibility

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22771]
Author Name: **Andre Jesus** (Andre Jesus)
Original Redmine Issue: [14816](https://issues.qgis.org/issues/14816)
Affected QGIS version: 2.8.9
Redmine category:project_loading/saving

---
*2.8.7 and prior versions*
1. Create a style for a vector layer
2. Set style as default

*2.8.9 onward*
1. copy qgis.qmldb file (2.8.7 -) to 2.8.9+
2. Open same vector layer, no style has been applied

==================

*2.8.7 and prior versions*
1. Create a style for a vector layer
2. Save QGIS project

*2.8.9 onward*
1. Open QGIS project (style loaded fine)
2. Set style as deafult
3. Reopen QGIS: style not loaded

================== ==================

So I can only set default styles in QGIS 2.8.9 if I create them in the current version

*2.8.9 onward*
1. Create a style for a vector layer
2. Set style as default
3. Reopen QGIS and load the vector
4. Default style loaded

==================

I have to say, recreate styles for 150 layers will be a pain....

**Comment by strk** [comment]
If I may, I'm reopening this because I don't understand why it was closed.

I've had the same problem (no style backward compatibility when going from 1.9 to 3.0, #31471).

There's code to handle conversions so I think any failed conversion has to be considered a bug.

The code to handle conversion is here: https://github.com/qgis/QGIS/blob/final-3_8_2/src/core/qgsprojectfiletransform.cpp

@homann do you have any word of wisdom about that class, you being the author ? Is it correct to consider lack of proper conversion as bugs ?

**Comment by gioman** [comment]
> If I may, I'm reopening this because I don't understand why it was closed.
Hi Sandro,
it was closed because we did a mass cleanup of the tracker back in March. We asked people to confirm if the tickets they filed against 2.* were still valid against 3.*. If no answer was given then the tickets were closed.

**Comment by strk** [comment]
According to [mailing list thread](https://lists.osgeo.org/pipermail/qgis-developer/2019-September/058449.html) the compatibility code for layer styles was in the layer class rather than in the qgsprojectfiletransform.cpp class. I'm still trying to find the commit that removed this compatibility code.

\cc @m-kuhn @nyalldawson

**Comment by nyalldawson** [comment]
Let's close -- there's no current demand for this.
