### ISSUE TITLE
Layer name completion in Virtual Layer query window fails on whitespace

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#22904]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [14955](https://issues.qgis.org/issues/14955)
Affected QGIS version: 3.6.0
Redmine category:db_manager

---
I have a layer named "natural_earth_vector ne_10m_admin_0_countries" from opening the NE sqlite file and selecting that.

If I type the beginning of its name in the "Create a virtual layer" Query window, QGIS will suggest to autocomplete to that name properly but on hitting Enter will only enter "natural_earth_vector". This will result in the query failing as there is no such layer.

QGIS should instead enter the whole name, enclosed in double quotes.

**Comment by benoitdm-oslandia** [comment]
Hi,
this issue is linked to the default behavior of code editor component (in which you type the sql query). This component from QScintilla (QsciListBoxQt) has a trim hardcoded when it handle the response from a autocompletion list (see ListBoxQt.cpp lines 176-224).

So, from my point of view, this is not a QGis bug.

**Comment by troopa81** [comment]
Regarding @benoitdm-oslandia comment, I closed this issue as it should be fixed upstream.
