### ISSUE TITLE
Wrong "Zoom to layer" extent on a shapefile layer with logically deleted records

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#23661]
Author Name: **Alessandro Sarretta** (@alesarrett)
Original Redmine Issue: [15739](https://issues.qgis.org/issues/15739)
Affected QGIS version: 3.4.4
Redmine category:unknown

---
When clicking on the "Zoom to layer" function on a shapefile with logically-deleted records in the DBF, the zoom wrongly considers also the logically deleted features.
Opening the attributes table for the layer correctly omits the logically-deleted records.

Test file can be found attached to this PostGIS ticket:
https://trac.osgeo.org/postgis/ticket/3645

---

Related issue(s): #23657 (relates), #23662 (relates)
Redmine related issue(s): [15735](https://issues.qgis.org/issues/15735), [15740](https://issues.qgis.org/issues/15740)

---

**Comment by gioman** [comment]
The extent shown is the same reported by OGR, so I guess this is an upstream problem, not QGIS's.

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3. (Windows 10)

**Comment by tarot231** [comment]
FYI, the same bug in GeoPackage has already been resolved: https://github.com/qgis/QGIS/issues/23209

The upstream also mentions that it is not a bug but by design.
https://gdal.org/drivers/vector/shapefile.html#spatial-extent
( https://trac.osgeo.org/gdal/ticket/6858 )

Attached python code is for reproduction.
As it happens, when uncommented out, the extents were correctly shrunk.
[bug_extent_of_shapefile.py.txt](https://github.com/qgis/QGIS/files/13325893/bug_extent_of_shapefile.py.txt)
