### ISSUE TITLE
make the 'create scratch layer dialog' more like the 'create new shape file' dialog' 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24397]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [16490](https://issues.qgis.org/issues/16490)

Redmine category:gui

---

Using scratch layers pretty often, I wonder why during the first creation dialog I'm not presented with (about) the same options as when I create a new shape file. That is: it would be cool to be able to add some attributes immediately. 

Maybe this can be part of the grant proposal 'ADD CONSISTENCY TO UI CONTROLS' ?

Ah... and please also add this to the python api :-)

**Comment by rduivenvoorde** [comment]
@alexbruy Super! Thanks! I'm going to use this a lot!

I've tested and found 2 little quircks (one new and one old):

- the length fields do not have a default (with me), so if you just add a 'Decimal number', you will end up with an integer because the Length and Precision apparently are 0 or null
In the create shapfile dialog, a decimal number defaults to length 10 (though does not have a precision with me here...). Should those inputs not have sane defaults? (don't know, like 50 chars for txt, 8/10 for decimals and 10 for integers or so?)

- one little annoyance I have pretty often is that I create an attribute, and I hit Enter... (instead of clicking the button 'add attribute') thereby loosing my last attribute. Not sure what to do there: maybe check if the fieldname is not empty before submitting the form?

Anyway: thanks, thanks for this work already!
