### ISSUE TITLE
Changing the setting 'Scan for valid items in browser' only works after restart of QGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#24712]
Author Name: **Richard Duivenvoorde** (@rduivenvoorde)
Original Redmine Issue: [16813](https://issues.qgis.org/issues/16813)
Affected QGIS version: master
Redmine category:browser

---

In the browser you can either choose to only Check the extension of files, OR to Check the file contents to determine their visibility in the browser (and the Data Source Manager | Browser).

It is done via the option Settings/Options/Data Sources/Data source handling/Scan for valid items ...

BUT the change of the dropdown currently only takes place AFTER you restart QGIS (which I think is not nessecary)...

To check:
- create a Geopackage file (gpkg) with only 1 vector file and put it in a visible directory
- if you have the option 'Check extension' you will see the file 2 times: one time as vector and one time as raster (because a gpkg can handle both, and only looking into the extension does not reveal what the gpkg actually contains)
- if you have the option 'Check file contents' you will see the gpkg only once (as vector, if you only put vector data it it).
- now change the option and look into the browser again. 
- Your change will not be seen UNTILL you restart QGIS

Not sure if the 'Treeview' is cached or if there is another reason, but I think the (re)setting should fire a Signal which should make the browser refresh it's view?

**Comment by roya0045** [comment]
can be closed due to lack of feedback?

**Comment by gioman** [comment]
> can be closed due to lack of feedback?

@roya0045 have you tested what is being reported? we usually close tickets for lack of feedback when we tested the scenario and could **not** replicate, followed by no further feedback by the issuer.

**Comment by rduivenvoorde** [comment]
@roya0045 thanks for checking issues, but yes please retest first... I put considerable time into creating valid and reproducable issues. And might miss calls for feedback because... lack of time or so.

IF retested and untestable or fail to test, feel free to close

In this case: I retested on master and 3.10 and both seem to be doing a better job now :-)
I cannot reproduce it with a gpkg anymore (apparently these are not shown twice anymore, even when looking only at extension). But with a (geo).pdf in the dir I could see that after a change of the checkbox and a 'refresh' of the dir things changed. So I'll close this one.
