### ISSUE TITLE
Save geopackage metadata inside the datasource

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25119]
Author Name: **shenriod -** (shenriod -)
Original Redmine Issue: [17220](https://issues.qgis.org/issues/17220)
Affected QGIS version: master
Redmine category:metadata

---
When I edit the metadata of a geopackage layer (right-click on the layer in the Layer panel - Properties / metadata), they are not saved in the Geopackage.

So if I right-click on the layer in the browser and choose "Properties", the metadata window that opens doesn't contain anything

**Comment by kmlawson** [comment]
I can confirm that this is still an issue in 3.14. I understand that this has been reclassified as a Feature Reqeust, but then it might be considered that from a UI perspective it is highly counter-intuitive. Workflow:

- add a geopackage to project
- modify metadata in properties
- remove geopackage
- add it again
- the metadata is now gone. 

This is very counterintuitive behavior. Unlike styling, adding metadata resembles modifying the attribute table's contents: you are adding data to a file, which one would assume would remain there when you share the package with someone (indeed, not clear to me why metadata is useful at all if it is just going to be attached to one's own project).

I would recommend either saving thet metadata to the geopackage on closing properties window, or offering some UI indication that adding metadata is basically just a project-specific note in some manner.

**Comment by elpaso** [comment]
Does it work if you store the project inside the geopackage itself? That way you can share your GPKG and it will contain one or more projects with their metadata (if any).

I understand your point of view, but that's not how metadata are implemented:  it wasn't me to do the implementation so I'm just guessing here but I think that the main blocker was that while you can add metadata to any layer, not all layer storage formats allow to store the metadata within the layer itself (gpkg being probably one of the few that in theory could do that because it's a DB). Hence the implementer had no choice than to store metadata within the QGIS project (or in a sidecar file).

@Gustry knows certainly more than me on this topic.

**Comment by kmlawson** [comment]
Thanks, I'm not sure I have ever stored projects inside of geopackages. My students and I work with historical sources and often share them between us. We are excited by the fact that geopackages are simple single files (at least when they are not open) to pass back and forth which is simple and straight forward. As historians, we are always concerned about our sources, and the metadata panel in the layers has all the possible things we would need to store that data. So when one student finishes a layer with lots of railroads for a particular time period, say, they could add the metadata on how they pieced that together from historical sources, citing books, tables, etc. appropriately, and then pass it on. Instead, as I understand it, we are always (unless we embed "projects" inside of packet of geographic data) forced to add our own external file (or export metadata to yet another format). Of course, I don't know the technical challenges, but just thought I would share a historian's persepctive! Thanks as always for all yoru hard work!

**Comment by nyalldawson** [comment]
I think this is a valid request -- just like we have the option of saving a default layer style inside the geopackage itself, we should also allow saving the layer metadata inside the geopackage.

**Comment by Gustry** [comment]
It's still on the roadmap indeed.
The metadata work has been split in many sub packages https://github.com/qgis/QGIS-Enhancement-Proposals/issues/91
Only Work Package 1 and 2 have been done in QGIS.

**Comment by mikedufty** [comment]
I believe this was fixed in 2021 and I enjoyed being able to save geopackage metadata as default.  It no longer seems work in 2022 though.  The 'save as default' option is there in the metadata pane, but seems to fail silently.
It does not prompt whether to save in the database or to a qmd file, but seems to do neither. 
Restore defaults always returns "Metadata not found in database"
The only way I've been able to get metadata to load with a geopackage is to put it in the comment field when creating the geopackage.
Should this be a new bug report or still part of this one?

**Comment by jackbuehner** [comment]
I came across this issue when attempting to learn how to save metadata to the GeoPackage. It appears that the **Layer Properties** > **Metadata** > **Save to Default Location** option is working for vector layers and **Layer Properties** > **Metadata** > **Save as Default** is working for raster layers in QGIS 3.44.2.
