### ISSUE TITLE
Circular string doesn't honor the coordinate system

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25167]
Author Name: **Loïc BARTOLETTI** (@lbartoletti)
Original Redmine Issue: [17269](https://issues.qgis.org/issues/17269)
Affected QGIS version: 3.5(master)
Redmine category:digitising

---
Problem found by Nyall "reviewing":https://github.com/qgis/QGIS/pull/4947#issuecomment-335291640 the new tools for Circle,etc. and reproduce by me in 2.18

Well, when you draw a circular string in a layer with a geographical system (eg WGS84) and a map in projected system (eg EPGS:3946), the circular arc is drawn in is system.

See the video.

---

- [circular.mp4](https://issues.qgis.org/attachments/download/11543/circular.mp4) (Loïc BARTOLETTI)

**Comment by sigmoe** [comment]
Still the same problem with QGIS 3.16:
- Project CRS = 2154
- Layer CRS = 4326
When you create a circle in the layer, the final shape saved into the layer is not correct. But if you copy that circle in a layer with CRS=2154, the copied circle has the right shape (a circle).
So the circle should have the correct shape in the first layer(4326) too, because the poject CRS is 2154.

**Comment by baswein** [comment]
Still an issue in 3.24. 
Also note that this also occurs when reprojecting existing curved geometries between Geo and non Geo CRS's.
