### ISSUE TITLE
Respect coordinate system (CRS) when outputFormat=GeoJSON

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25171]
Author Name: **Henrik Uggla** (@huggla)
Original Redmine Issue: [17273](https://issues.qgis.org/issues/17273)

Redmine category:qgis_server

---
Following request returns correct coordinate system:

http://193.17.67.229/cgi-bin/fastighetsindelning/?service=WFS&request=GetFeature&SRS=EPSG:3008&typename=fastyta_&width=1600&height=660&filter=%3Cogc:Filter%20xmlns:ogc=%22http://www.opengis.net/ogc%22%3E%3Cogc:PropertyIsEqualTo%20matchCase=%22false%22%3E%3Cogc:PropertyName%3EFASTIGHET%3C/ogc:PropertyName%3E%3Cogc:Literal%3EJULTOMTEN%203%3C/ogc:Literal%3E%3C/ogc:PropertyIsEqualTo%3E%3C/ogc:Filter%3E

Add outputFormat=GeoJSON and wrong coordinate system is returned:

http://193.17.67.229/cgi-bin/fastighetsindelning/?service=WFS&request=GetFeature&SRS=EPSG:3008&outputFormat=GeoJSON&typename=fastyta_&width=1600&height=660&filter=%3Cogc:Filter%20xmlns:ogc=%22http://www.opengis.net/ogc%22%3E%3Cogc:PropertyIsEqualTo%20matchCase=%22false%22%3E%3Cogc:PropertyName%3EFASTIGHET%3C/ogc:PropertyName%3E%3Cogc:Literal%3EJULTOMTEN%203%3C/ogc:Literal%3E%3C/ogc:PropertyIsEqualTo%3E%3C/ogc:Filter%3E

This doesn't happen in 2.14

**Comment by MattiasSp** [comment]
I think this issue should be changed to a bug again since QGIS Server is now implementing WFS 1.1.0 (I'm using 3.8.2).

The GetCapabilities document is advertising WFS version 1.1.0 with "application/vnd.geo+json" as a possible outputFormat and my SRS EPSG:3011 as "DefaultSRS". Still, I can only manage to get the GeoJSON output in EPSG:4326.

**Comment by elpaso** [comment]
AFAIK epsg 4326 is still the only admitted CRS for GeoJSON: https://tools.ietf.org/html/rfc7946

**Comment by MattiasSp** [comment]
> AFAIK epsg 4326 is still the only admitted CRS for GeoJSON: https://tools.ietf.org/html/rfc7946

I agree that epsg 4326 is the only _specified_ CRS, but reading section 4 of the standard it would seem to me that it could be admitted to use others as well (I added the bold font):

> https://tools.ietf.org/html/rfc7946#section-4
> Note: the use of alternative coordinate reference systems was
   specified in [GJ2008], but it has been removed from this version of
   the specification because the use of different coordinate reference
   systems -- especially in the manner specified in [GJ2008] -- has
   proven to have interoperability issues.  In general, GeoJSON
   processing software is not expected to have access to coordinate
   reference system databases or to have network access to coordinate
   reference system transformation parameters.  **However, where all
   involved parties have a prior arrangement, alternative coordinate
   reference systems can be used without risk of data being
   misinterpreted.**

In the case of QGIS Server's WFS implementation, I would argue that requesting and receiving a specific (advertised in the GetCapabilities document) CRS according to the WFS specification would constitute such a "prior arrangement" :)

**Comment by elpaso** [comment]
What I mean is that this is not a bug. 
But I agree with you that it would be nice to have.

**Comment by MattiasSp** [comment]
> What I mean is that this is not a bug.
> But I agree with you that it would be nice to have.

I see your point and agree, technically.

I'll just add that I believe the current behavior will _look like_ a bug to a lot of clients since the WFS is advertising an outputFormat and a CRS in the WFS Capabilities that are not "compatible". As I understand it, there is currently no way for a WFS to let clients know which CRSs are available for specific output formats, so clients will likely expect `outputFormat=GeoJSON&srsName=EPSG:XXXX` to be honored as long as they choose from the advertised alternatives.
