### ISSUE TITLE
3d: moving mouse cursor above plane will dragging destroys 3d viewpoint

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25551]
Author Name: **Nyall Dawson** (@nyalldawson)
Original Redmine Issue: [17654](https://issues.qgis.org/issues/17654)
Affected QGIS version: master
Redmine category:3d

---
While dragging a scene with the left mouse button depressed, if at any stage the mouse cursor is moved above the plane it results in a corrupted camera viewpoint in the window which cannot be recovered (except by resetting the view to the full extent).

See https://www.youtube.com/watch?v=CCIOVyrwBqA&feature=youtu.be

**Comment by uclaros** [comment]
Don't stale/close this, it is still the case in 3.18.
This is caused by the fact that instead of directly manipulating the camera's position and rotations, those values are computed based on the center of the scene instead, leading to various rounding errors like this, especially when zoomed out.
The 3d api needs a rework to allow direct camera translation and rotation which is hopefully in the context of https://github.com/qgis/QGIS-Enhancement-Proposals/issues/215

**Comment by Pedro-Murteira** [comment]
Hello @nyalldawson It seems I'm no longer able to reproduce this. Did you come across this more recently? It appears to be fixed
