### ISSUE TITLE
"resources/data/world_map.shp" should be only accessed read-only

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#25876]
Author Name: **Johannes Kroeger** (Johannes Kroeger)
Original Redmine Issue: [17980](https://issues.qgis.org/issues/17980)
Affected QGIS version: 3.6.0
Redmine category:unknown

---
QGIS tells me
```
Warning 4: Failed to open /opt/qgis-git/share/qgis/resources/data/world_map.shp, Permission denied.

```

The file exists and is world readable
```
-rw-r--r-- 1 root root 528032 Jan 23 23:06 /opt/qgis-git/share/qgis/resources/data/world_map.shp

```

strace suggests that QGIS is trying to access the file with write access.
```
openat(AT_FDCWD, "/opt/qgis-git/share/qgis/resources/data/world_map.shp", O_RDONLY) = 76
openat(AT_FDCWD, "/opt/qgis-git/share/qgis/resources/data/world_map.shp", O_RDWR) = -1 EACCES (Permission denied)
stat("/opt/qgis-git/share/qgis/resources/data/world_map.shp", {st_mode=S_IFREG|0644, st_size=528032, ...}) = 0
stat("/opt/qgis-git/share/qgis/resources/data/world_map.shp", {st_mode=S_IFREG|0644, st_size=528032, ...}) = 0
openat(AT_FDCWD, "/opt/qgis-git/share/qgis/resources/data/world_map.shp", O_RDONLY) = 76
stat("/opt/qgis-git/share/qgis/resources/data/world_map.shp", {st_mode=S_IFREG|0644, st_size=528032, ...}) = 0
openat(AT_FDCWD, "/opt/qgis-git/share/qgis/resources/data/world_map.shp", O_RDWR) = -1 EACCES (Permission denied)

```

As the file is used as source for the CRS display it does only require read access.

Opening it in read-only mode should get rid of the warning and be what was intended. :)

---

Related issue(s): #25446 (relates)
Redmine related issue(s): [17549](https://issues.qgis.org/issues/17549)

---

**Comment by jidanni** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929969

**Comment by pathmapper** [comment]
Still present in 3.8.3-Zanzibar

**Comment by marcmerlin** [comment]
just installed 3.10.5 and wasted my time trying to fix this non bug, until I found this page.
also found https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929969
Of course that it SEGV'ed the first time I ran it right after this non error, just added to the confusion
```
sauron:~$ qgis
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
QGIS died on signal 11Aborted (core dumped)
```
Given that this bug is over 2 years old, Is it hard to open the file with the right permissions?

**Comment by nyalldawson** [comment]
> Given that this bug is over 2 years old, Is it hard to open the file with the right permissions?

@marcmerlin 

Yes, yes it is. It's not a trivial change at all. If you want to tackle this you could start by resurrecting https://github.com/nyalldawson/QGIS/commit/e8d15e1bb89f740209ba3b3ac1e169cb62e26796

It's an incomplete fix though, more work is required.

**Comment by landryb** [comment]
> > Given that this bug is over 2 years old, Is it hard to open the file with the right permissions?
> 
> @marcmerlin
> 
> Yes, yes it is. It's not a trivial change at all. If you want to tackle this you could start by resurrecting [nyalldawson@e8d15e1](https://github.com/nyalldawson/QGIS/commit/e8d15e1bb89f740209ba3b3ac1e169cb62e26796)
> 
> It's an incomplete fix though, more work is required.

what additional work ? i've look at the aforementioned commit and it makes sense, fixing the two locations that try to open the geopackage..

sure there might be more work if one wants to add a checkbox to allow users to specifically open or mark datasets as readonly, or even detecting them (say, ogc services, db services with only select rights, files not belonging to the user..) but in the meantime afaict the commit fixes this issue at least :) which has been bugging/puzzling linux/bsd users since the addition of the geopackage....

**Comment by gioman** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/35383
