### ISSUE TITLE
More visible way to access Page Properties in QGIS3 Layout

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26237]
Author Name: **Alex Mackenzie** (Alex Mackenzie)
Original Redmine Issue: [18347](https://issues.qgis.org/issues/18347)

Redmine category:map_composer/printing

---
The only way I could find to change the page orientation for layouts in QGIS3 is by right-clicking the page. This isn't easily discover-able for the user, a menu or button option may help.

**Comment by kannes** [comment]
Considering that currently one has to find the right-click-on-page option to access this and https://github.com/qgis/QGIS/pull/42572 only works if there is empty space to left-click on the page, and that there is a tab in the panel for access the pages' guides already, I guess it would make most sense to add a tab "Page Properties" that shows the `QgsLayoutPagePropertiesWidget` or rework the current "Guides" tab so that it shows both guides and general page properties.

@rduivenvoorde had similar thoughts in https://lists.osgeo.org/pipermail/qgis-developer/2021-March/063414.html

**Comment by rduivenvoorde** [comment]
> @rduivenvoorde had similar thoughts in https://lists.osgeo.org/pipermail/qgis-developer/2021-March/063414.html

with some more background info in one of the replies: https://lists.osgeo.org/pipermail/qgis-developer/2021-March/063416.html
