### ISSUE TITLE
Trouble with geopackage fields length settings

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26330]
Author Name: **Dominique Lyszczarz** (@domlysz)
Original Redmine Issue: [18442](https://issues.qgis.org/issues/18442)
Affected QGIS version: 3.0.0
Redmine category:attribute_table

---
I encounter some annoying difficulties with fields length on geopackage layers

1. When creating a new gpkg layer with a decimal fields, the dialog does not allows to define the field length and precision (screenshoot 1). In layer properties the field appear to have 0 length and 0 precision (screenshoot 2). Consequence, when adding a new feature the popup form does not allow to enter any decimal value. The user must define specificaly the input form settings for each decimal field (screenshoot 3).

2. Saving a layer to gpkg always change fields parameters, for exemple a string with a length of 1000 is reduced to 255, a decimal field with length 20 and precision 5 is reduced to zero length and zero precision (screenshoot 4)

---

- [screenshoot 2 - resulting fields definition.jpg](https://issues.qgis.org/attachments/download/12444/screenshoot%202%20-%20resulting%20fields%20definition.jpg) (Dominique Lyszczarz)
- [screenshoot 1 - new gpkg layer no length setting for decimal field.jpg](https://issues.qgis.org/attachments/download/12445/screenshoot%201%20-%20new%20gpkg%20layer%20no%20length%20setting%20for%20decimal%20field.jpg) (Dominique Lyszczarz)
- [screenshoot 3 - setup decimal input form.jpg](https://issues.qgis.org/attachments/download/12446/screenshoot%203%20-%20setup%20decimal%20input%20form.jpg) (Dominique Lyszczarz)
- [screenshoot 4 - fields changes after saving to gpkg.jpg](https://issues.qgis.org/attachments/download/12447/screenshoot%204%20-%20fields%20changes%20after%20saving%20to%20gpkg.jpg) (Dominique Lyszczarz)

**Comment by kevin-garcia** [comment]
I'm having the same issue on 3.10 with geopackage layers. I can only set the field length for string fields, and not for any other field type. 

For example:

![image](https://user-images.githubusercontent.com/16250189/70254614-48537000-177d-11ea-88cf-82e9d49b27d0.png)
There should be "length"/"precision" options here, but there are none.

**Comment by Pedro-Murteira** [comment]
This issue is still true on QGIS 3.16.15 and 3.22.2.

**Comment by phidrho** [comment]
Hi all,

GeoPackage is file format based on SQLite DB which doesn't support limitations on length on any type by default. That's why you get 0 and 0, because it doesn't make sense in GPKG, but SQLite will use the best format for your data internally and you won't loose any precision.

If you want to add a limitation you must use a `STRICT` keyword while creating a table in SQLite, but as far as I know, that's not defined in GeoPackage standard as of today.
For the form input part it's locale based setting for `comma` and `point` decimal symbol as confirmed in [comment](https://github.com/qgis/QGIS/issues/26330#issuecomment-495886257).

@alexbruy I'm proposing closing this bug report.
