### ISSUE TITLE
Crash opening QGIS 3.0

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26454]
Author Name: **Maëlle DECHERF** (Maëlle DECHERF)
Original Redmine Issue: [18566](https://issues.qgis.org/issues/18566)
Affected QGIS version: 3.0.0
Redmine category:unknown

---
## Report Details

*Crash ID*: 09e3421a862f61ddd23eac4654a1bd44ec4a80fe

*Stack Trace*
```
QMapDataBase::rebalance :
GetProcAddress :

```

*QGIS Info*
QGIS Version: 3.0.0-Girona
QGIS code revision: 001c80b0c3
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3

*System Info*
CPU Type: i386
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by PeterPetrik** [comment]
@gioman can we maybe close this one?

**Comment by gioman** [comment]
Please reopen of the issue persist in recent QGIS versions.

**Comment by Danaozhong** [comment]
This is a super old ticket, I know - however it was the only useful search hit for the issue I faced.

For my situation, I was running into this issue when using QGIS 3.34.1 (identical stack trace). The problem was caused by a plugin I wrote, which adds data to vector layers in a multi-threaded environment. I messed up the signal handling, and the vector layers were modified by the worker thread instead of the main thread. It would work for the majority of the time, but in some rare cases that will cause a crash.

As per the documentation, vector layer content should only be modified from the main thread, so you may need to use signals to give the execution control to the main thread, and modify the vector layers from there.
QGIS actually prints out helpful debug warnings for that, but they are not visible in the release build. It took me quite a while to figure this issue out, so hopefully my experience here will be helpful for somebody?
