### ISSUE TITLE
Insert new record in form with one to many relation try to save sequence as string

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26759]
Author Name: **Luca Lanteri** (Luca Lanteri)
Original Redmine Issue: [18927](https://issues.qgis.org/issues/18927)
Affected QGIS version: 3.1(master)
Redmine category:forms

---
I have 2 tables postgres in relation one to many among them, connected with the classic fkey. I created a form that contains both tables using relationships. If I create a new parent and also a child record, qgis fails to save the child because it tries to assign the string value to "nextval ('gid_seq'::regclass), since the parent's primary key has not yet been assigned". In practice I am forced first to save the father (exiting the form) and only then create the child record. At the moment I solved using a uuid field as fkey but it's just a patch, not the behavior I would expect in a form.

---

- [test.backup](https://issues.qgis.org/attachments/download/12674/test.backup) (Luca Lanteri)
- [test.qgs](https://issues.qgis.org/attachments/download/12675/test.qgs) (Luca Lanteri)

**Comment by SrNetoChan** [comment]
This is not a bug and it has a better workaround. The foreign key constraint is set on the database, so if you try to save the child first, it will always fail. The problem is that without saving the parent, you may not know the parent id yet. For that, you can go to project properties and in the data sources tab enable the evaluate defaults on providers side.

![image](https://user-images.githubusercontent.com/3607161/106371932-7244fa00-6362-11eb-93c8-30f41ccde4d0.png)

@gioman I think we can close this one.
