### ISSUE TITLE
Variable list on layout items disabled when system locale is overriden

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26837]
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [19006](https://issues.qgis.org/issues/19006)
Affected QGIS version: 3.0.3
Redmine category:map_composer/printing

---
Try to override system locale and you get a disabled empty list of variables for layout (composer) items. 
Checked on both 2.18.15 and 3.0.3. Seems like every version is affected.

**Comment by SrNetoChan** [comment]
Confirmed on master (3.17 https://github.com/qgis/QGIS/commit/fba5093f18). Layout items properties don't show the variables list when I overrided my locale to Portuguese. This only happens when the layout item was created without the override (in my test in English).

Strangely enough, if you add a new item to the layout, the variables shows up and it fixes the other item too.

![image](https://user-images.githubusercontent.com/3607161/106372061-bd134180-6363-11eb-9e24-5f9e7e5876a8.png)

**Comment by elpaso** [comment]
@SrNetoChan please attach the failing test project and I'll have a look.

**Comment by SrNetoChan** [comment]
Here's a project with a single test layout. The project was created in English, and if the locale is English everything works fine.

If you change the locale to Portuguese the variables in the layout items won't show up.

I have tried in Italian locale and I wasn't able to replicate. So maybe it has something to do with the translations!?

[variables_layout.zip](https://github.com/qgis/QGIS/files/5903239/variables_layout.zip)

**Comment by SrNetoChan** [comment]
In Italian Layout is still called layout, while in Portuguese its called "Composição" :-S

**Comment by SrNetoChan** [comment]
It also works in french. But In Portuguese, I can't even create items from scratch that they won't show the variables. I guess it only happens in certain languages, maybe with strange characters or something.

**Comment by Pedro-Murteira** [comment]
Hello @SrNetoChan. I've tested this issue on QGIS 3.22.3, I've changed the locale to Portuguese and I can see all the variables for the items, aswell as the variables for every new item added to the layout. Could you confirm? Thank you!
![test_26837](https://user-images.githubusercontent.com/92830786/152343605-d528c643-a57d-49e1-90ce-62a90a97d798.png)
