### ISSUE TITLE
Reference layer is not optional in raster calculator

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27058]
Author Name: **Mario Reyes** (@ernesto561)
Original Redmine Issue: [19229](https://issues.qgis.org/issues/19229)
Affected QGIS version: 3.0.3
Redmine category:processing/qgis

---
When the raster calculator from the processing toolbox is used for example to sum two rasters, the following error message is displayed>

```
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins\processing\algs\qgis\RasterCalculator.py", line 136, in processAlgorithm
raise QgsProcessingException(self.tr("No reference layer selected nor extent box provided"))
_core.QgsProcessingException: No reference layer selected nor extent box provided

```

If an optional layer is provided, which specifies the output extent and CRS there's no problem.

**Comment by alexbruy** [comment]
Duplicates #27380

**Comment by AlisterH** [comment]
Just commenting for the benefit of anyone else who comes across this ticket when searching:

Recent versions of QGIS have a "new" raster calculator processing algorithm which can be run without specifying a reference layer.
The old algorithm is still included to avoid breaking old processing, but it is otherwise hidden from the user, and it does not tell the user that it is deprecated, leading to confusion.
So if you notice that "reference layer" is optional normally, but not when using the algorithm in a model, it is just that your model is old and using the old algorithm - you can replace it with the new algorithm and you won't need to specify a reference layer.
