### ISSUE TITLE
QGIS 3 does not save main window size and position (after being set as default app?)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27214]
Author Name: **Loren Amelang** (@LorenAmelang)
Original Redmine Issue: [19386](https://issues.qgis.org/issues/19386)
Affected QGIS version: 3.2
Redmine category:gui

---
I reported #27001 about "QGIS 3.0.3 main window does not remember chosen size (Win 10 with scaling...)". 

As I commented there, "So far 3.2 has always remembered my choices!" For two weeks after the update, it started exactly where I had left it, every time. 

Today I was looking at a shapefile in a Win 10 folder, and wanted to know what was in it. Windows showed no app claiming shapefiles, so I scrolled through the list of possibilities and chose QGIS. And left the "Always use this app" box checked. QGIS opened - in its extremely tiny centered location and size! I'd never seen 3.2 do that! And now it reverts to the tiny size on every start, from the Start menu or by any other mechanism. 

I wanted to edit 19172, but it seems there is no way to remove the "3.0.3" from the subject, which means it would probably get little attention. Whatever is happening to me definitely affects 3.2 as well! Perhaps it was triggered by being set as default app...  Or something else...  I do remember once setting 3.0.3 as Win 10 default app for some file type. Can't remember if that was related to the appearance of the size issue there. 

Where should the window size and position be stored? How can I debug this further?

**Comment by Pedro-Murteira** [comment]
@LorenAmelang Using 3.16.15 and 3.22.2 here and I can't reproduce this issue. Is this still happening in your case?

**Comment by LorenAmelang** [comment]
@Pedro-Murteira I haven't seen this particular problem for several versions and years. A new install defaults every window and dialog to drawing scaled-up content into tiny rectangles measured in hardware pixels, so everything has to be manually resized to be at all usable. But after that first miserable session it seems to remember my chosen sizes. But then sometimes that old version did, too...  I never discovered what triggered it to the chaos mode. 

It would be great if someone could figure out how to make QGIS think entirely in Windows scaled space! But I suspect the problem is deep in some underlying library you don't control...
