### ISSUE TITLE
enable\disable layer using shortcut QGIS 3.2

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27335]
Author Name: **Matteo Orlandi** (Matteo Orlandi)
Original Redmine Issue: [19507](https://issues.qgis.org/issues/19507)

Redmine category:actions

---
To be quicker and don't waste time with repetitive actions, I need to enable and disable a specific layer using just shortcut.
Something like "Show all layers" (ctrl+shift+U) but one by one.

Is there a way to do that?

I wonder if I can assign a number or letter to each layer and then use a custom shortcut to enable\disable it.

**Comment by AlisterH** [comment]
It might be a little restricted, but I think this might be what the "enable shortcuts" option in the "togglegroupvisibility" plugin does.

Otherwise, if you always have the same layers maybe you could write some python code for this and load it at startup.
If you don't always have the same layers, maybe you could write the code to refer to project variables, and when you want to set the shortcut for a layer, you could set the variable to refer to the layer.

I'm not really sure if this ticket deserves to stay open.  Maybe a more general purpose solution would be enhancing the project macros feature to allow users to put random python functions there, and allowing them to assign keyboard shortcuts to them.
