### ISSUE TITLE
PostgreSQL sequences not always used when adding feature

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27391]
Author Name: **Nicolas Boisteault** (@nboisteault)
Original Redmine Issue: [19564](https://issues.qgis.org/issues/19564)
Affected QGIS version: 3.3(master)
Redmine category:data_provider/postgis

---
I have several PostgreSQL layers with no geometries. All have an 'id' column with serial type so they have a primay key and a sequence. When I add a feature, with some of these tables I have 'nextval('schema.id_seq'::regclass)' in the id field (which is the correct behavior) and with some others I have a NULL value.
I can't see *no* difference between the tables with the good behavior and the others.
I've also noticed that when I open the 'Attributes form' tab for wrong behavior tables the id field has 'Range' Widget Type proposed. For good behavior tables it is 'Text Edit' Widget Type.
Issue also occurs in QGIS 2.18.x and I have tested with 3 different Windows machines. Database is PostgreSQL 9.6 on Ubuntu 16.04.
I can give limited access to my database if needed.

---

- [annuaire.sql](https://issues.qgis.org/attachments/download/13367/annuaire.sql) (Nicolas Boisteault)
- [not_working_gid_sequence.png](https://issues.qgis.org/attachments/download/14660/not_working_gid_sequence.png) (David Mancini)
- [working_gid_sequence.png](https://issues.qgis.org/attachments/download/14661/working_gid_sequence.png) (David Mancini)

**Comment by nboisteault** [comment]
I did not reproduce this issue for many years, so this ticket can be closed.
Thanks @Pedro-Murteira for testing.

**Comment by JKalina08** [comment]
This bug still prevails. Tested on version 3.16.11-Hannover and 3.28.3-Firenze. I have multiple tables ganerated with identity columns on PG side. Once in a time one or two tables are not working in qgis. the PRIMARYINDEX field is not recognised and there is no "nextval()" in this field. And that is the problem. Only workinng solution was to create table with "PRIMARYINDEX SERIAL NOT NULL" or in qgis create default value "maximum ("primaryindex") + 1". This bug was not solved and i see it since 2019 to present.
