### ISSUE TITLE
Incomplete install of 3.2 on Windows - Missing shortcuts

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27598]
Author Name: **belg4mit -** (belg4mit -)
Original Redmine Issue: [19773](https://issues.qgis.org/issues/19773)
Affected QGIS version: 3.2.2
Redmine category:windows_package
Assignee: Jürgen Fischer

---
I've tried to install 3.2.2 on my machine (Windows 10) twice, once with the giant installer file, and once with the net installer. Both times shortcuts for GRASS, SAGA and OSGeo shell are created, but not QGIS itself.

**Comment by AlisterH** [comment]
Is this still a problem with recent versions?

Are you talking about desktop shortcuts or start menu shortcuts?

I don't pay attention to desktop shortcuts - they are highly offensive and I delete them as long as I have permissions!  But I remember noticing at one point that some of them were being created in a folder on the desktop, but others were being created directly on the desktop.

If thIs is about start menu shortcuts, and it is still a problem with recent versions, can you check that the problem is truly that the shortcuts are not created, not just that Windows isn't displaying them in the start menu?  I've noticed that Windows 10 sometimes doesn't show all of the start menu shortcuts in a folder.  I think it is related to the number of shortcuts in the folder as it doesn't seem to occur if there are only a few (although it doesn't seem to be consistent - I see now that it is successfully listing 11 here for QGIS Lyon!).  Also, in some cases I believe more will appear if you reboot... this seems like typical Microsoft insanity and if you can I would recommend using a real operating system instead :)

**Comment by alexbruy** [comment]
Closed for the lack of feedback
