### ISSUE TITLE
Allow to set the order of inputs in processing models

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27787]
Author Name: **Olivier Dalang** (@olivierdalang)
Original Redmine Issue: [19965](https://issues.qgis.org/issues/19965)

Redmine category:processing/modeller

---
Hi,

It's not possible to control the order in which inputs appear in processing models execution dialog.

It seems (not confirmed) that the order used is the alphabetical order of the input internal name, which cannot be modified from the GUI once set and is often different than the display name.

This makes it easy to have models where less important fields appear before more important fields (e.g. an attribute dropdown appearing before the layer it refers to), making the dialogs a bit confusing.

Suggested fixes :
- by default, use the inputs position (X then Y value) to determine the order rather than alphabetical order of the input
- add an "order" field to the inputs, and sort according to that field (those with no order appearing at the end)

Maybe we could also consider adding an "advanced" checkbox, for the input to be displayed as an advanced parameter.

Thanks !

**Comment by PedroVenancio** [comment]
Since the order appears to be defined alphabetically, based in the input name, another solution could be to make available a "Description" field in the Input Parameter Definition dialogue, beyond the current "Parameter Name". By the way, the "Parameter Name" acts as a "Description", as the "Parameter Name" is in fact de input name lowercase and without spaces.

**Comment by alexbruy** [comment]
Implemented in master.
