### ISSUE TITLE
support serving projects stored in postgresql

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27987]
Author Name: **Sebastian Brocks** (@beerockxs)
Original Redmine Issue: [20166](https://issues.qgis.org/issues/20166)

Redmine category:qgis_server

---
now that QGIS can save projects in postgresql, QGIS Server should support serving them as WMS/WFS etc.

**Comment by beerockxs** [comment]
The postgres-URL referencing the projects containts ampersands. How do I need to escape these to make the WMS requests work when using the MAP= parameter in the request? I tried %26 and it resulted in this error:
qwc-qgis-server_1       | [97][08:37:29] Error, configuration file 'postgresql://user:passworld@url.example:5432?sslmode=disable6dbname=database6schema=test6project=testproject' does not exist

**Comment by beerockxs** [comment]
I managed to change the rewrite rule so that the ampersands get correctly passed to qgis-server, it then, however, does not find the project although it exists:

qwc-qgis-server_1       | [96][08:56:09] MAP:postgresql://user:pass@localhost:5432?sslmode=disable&dbname=database&schema=testschema&project=testproject
qwc-qgis-server_1       | [96][08:56:09] REQUEST:GetProjectSettings
qwc-qgis-server_1       | [96][08:56:09] SERVICE:WMS
qwc-qgis-server_1       | [96][08:56:09] VERSION:1.3.0
qwc-qgis-server_1       | [96][08:56:09] Error, configuration file 'postgresql://user:pass@localhost:5432?sslmode=disable&dbname=database&schema=testschema&project=testproject' does not exist
although the project exits and is accessible in desktop qgis using that URL

**Comment by beerockxs** [comment]
It turns out I was using an old version of qgis server, this works fine in the current version.

**Comment by jgrocha** [comment]
@beerockxs Can you close the issue please?
