### ISSUE TITLE
If any of the "topology checks" options is enabled, then cliking on "save layer edits" toggles editing off

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28592]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [20772](https://issues.qgis.org/issues/20772)
Affected QGIS version: 3.6.2
Redmine category:vectors

---
1) add a vector layer

2) in its options toggle one (or more) of the three "topology checks" options

3) toogle editing, draw a feature (tested polygons here)

4) click on "save layer edits" -> edits are saved, but editing is toggled off (not expected)

---

Related issue(s): #28757 (duplicates)
Redmine related issue(s): [20938](https://issues.qgis.org/issues/20938)

---

**Comment by j-lippmann** [comment]
hi matthias @m-kuhn 

this issue is still present in actual master 
3.9.0-Master | QGIS-Codeversion | f33dd71adc
AND
3.4.11 LTR

it would be very kind of you, if you can have a look at this issue.

thank you very much

**Comment by j-lippmann** [comment]
hello, 
this issue is still present in actual master and ltr.  can one of the kind developers fix this issue? :-) or its difficult to fix?

thank you very much


`
QGIS-Version | 3.9.0-Master | QGIS-Codeversion | 6d389215ab
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.0dev | Läuft mit GDAL/OGR | 3.1.0dev
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 7.0.0 | Läuft mit PROJ | Rel. 7.0.0, March 1st, 2020
BS-Version | Windows 7 SP 1 (6.1) | Diese QGIS-Kopie schreibt Debugausgaben.
Aktive Python-Erweiterungen | DbgGruen; plugin_reloader; db_manager; MetaSearch; processing

`

**Comment by j-lippmann** [comment]
hello @m-kuhn,

Can you tell me if it is difficult to fix the problem? In my opinion, this "small" bug prevents the use of geometry validation.

thank you very much.
greetings jan

**Comment by gioman** [comment]
Still valid on the latest 3.4

**Comment by m-kuhn** [comment]
Hi Jan,
It's not super simple unfortunately. It's on my todo list please keep pinging me.
I don't think it's a regression, it never really worked and is really annoying.

**Comment by roya0045** [comment]
Still valid in 3.12
