### ISSUE TITLE
QgsCheckableComboBox single item selection bug

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28658]
Author Name: **Andreas Rabe** (Andreas Rabe)
Original Redmine Issue: [20839](https://issues.qgis.org/issues/20839)
Affected QGIS version: 3.4.2
Redmine category:gui

---
Given a QgsCheckableComboBox with all items checked. Deselecting all items, but a single one. After clicking somewhere else in the GUI, the item that was still selected is also deselected most of the times.

Bug was observed in a small PyQt GUI programm and is reproducible inside the QtDesigner.

**Comment by tleppamaki** [comment]
I encountered this same issue while developing a plugin. I'd like to add that not all items need to be checked, two or more are enough. After reducing the selection to one, the box behaves as if no items are selected. For example calling combobox.checkedItems() returns an empty list.

**Comment by Gustry** [comment]
I could confirm this issue tuoo @tleppamaki.
AFAIK, this `QgsCheckableComboBox` is not used in QGIS application for now, so it's not impacting any core features, only plugins which are using it.

**Comment by YoannQDQ** [comment]
From what I understand, it relies on the `QCombBox ` `activated `signal to toggle on/off its items. The problem is that this signal is emitted when the combobox is opened and there's a single selected item, which is NOT the currentIndex. A solution would be to set the currentIndex to the first selected item in` QgsCheckableComboBox::setItemCheckState` when an item is toggled off.

Without modifying QGIS source, here is a PyQt implementation of a fixed CheckableComboBox
```
class CheckableComboBox(QgsCheckableComboBox):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.activated.connect(self.afterActivated)   

    def afterActivated(self):
        for i in range ( self.model().rowCount()):
            item = self.model().item(i)  
            if item.checkState() == Qt.Checked:
                self.setCurrentIndex(i)
                self.model().itemCheckStateChanged.emit()
                return
```
