### ISSUE TITLE
Starting the Application creates automatic a shortcut "QGIS3" in users startmenue "%appdata%\Microsoft\Windows\Start Menu\Programs"

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28709]
Author Name: **Daniel Neuhaus** (Daniel Neuhaus)
Original Redmine Issue: [20890](https://issues.qgis.org/issues/20890)
Affected QGIS version: 3.4.2
Redmine category:build/install

---
My OS is Windows 10 x64 (ver. 1709)
This appears by start from Link "link QGIS Desktop 3.4.2" or directly from programfiles-target "qgis-bin.exe" and the same for qgis.bat

**Comment by HeatherHillers** [comment]
We have shown that this link is created directly by qgis-bin.exe by wintoastlib when qgis starts.  

qgswinnative.cpp in the function:
 QgsWinNative::initializeMainWindow()

runs a wintoastlib instance initialize

  if ( WinToastLib::WinToast::instance()->initialize() )
  {
    mWinToastInitialized = true;
    mCapabilities = mCapabilities | NativeDesktopNotifications;
  }

The initialize code in wintoastlib creates the link.  

There is no way to prevent the creation of this link with an environment variable, for instance.

This is an intentional feature, but when qgis is installed as a networked installation for an organisation with many users, it is a bug.

The qgis-ltr.bat is where network profiles are set and global settings are used.  On windows 10, the creation of this link gives the user an attractive, shiny start menu item that is presented in some cases with preference over the real start menu item.  The QGIS created link is to the .exe, not to the .bat.  Thus the user will open a qgis where the profile is not properly set up.  This is especially problematic in 3.10, where global settings must be used to avoid having the user being presented with datum transform selection windows.  

We are going to try a workaround by running python code at qgis start up that deletes the link.  It is a very odious workaround, however.

**Comment by jef-n** [comment]
Not sure how wintoast is involve.  But the shortcuts created by the installer also point at the exe.  The batch files run the exe with --postinstall on install and create an .env and enable the exe to run without the batch file.  This was introduced at some point to support pinning the app to the taskbar - and that's probably what you see: the running app or the app pinned to the taskbar.

**Comment by HeatherHillers** [comment]
mm.  I am not sure we understand each other.

1. Just to clarify:  Qgis (ltr) is definitely explicitly creating a start menu link called QGIS3 under C:\Users\xxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs.  This happens when QGIS is loading the main window.   It is specifically created by Qgis on Windows 10, using wintoastlib.  (See wintoastlib.cpp in the initialize() function.  This is called by qgiswinnative.cpp.) 

The link is not created by Windows 10.  It does not happen in Windows 7, apparently because there is a compatability check inside wintoastlib, and perhaps only Windows 10 is "compatible" with the feature.  But Windows is not doing it.  I could show a Process Monitor log that shows qgis.exe creating the file.  And also the qgswinnative and wintoast code is quite clear about what it is doing.  It is very intentional.

2.  Running from qgis-ltr.bat is very important for running QGIS on a Windows Networked environment.  In the .bat we set environment variables (for instance we cant use geopackage in a windows network environment without setting  OGR_SQLITE_JOURNAL=DELETE).  We must use a networked profile directory, which is passed to qgis using the --profiles argument.  Thirdly, we have a network location for our qgis_global_settings.ini, which we also pass as an argument to qgis using the bat.  This is neccessary for setting the proper default coordinate transform from GK to UTM for our users, who are not able to handle the transform choice dialog new in QGIS 3.10.   If there is a way to accomplish always running qgis with command line options and the right environment variables without using the qgis-ltr.bat, I have not found it in the documentation. 

3.  If we establish that the qgis-ltr.bat is neccessary for administration of enterprise usage in a windows environment, then it becomes clear that if the usage of an organisation's qgis-ltr.bat is overridden by automatically generated links that lead to improper use of qgis (without a profile, without the right default coordinate transforms, breaking geopackages), that is not optimal.  This problem is amplified by the fact that Windows 10 displays the automatically generated link in some cases more prominently then the link set up by the administrator.

I hope I this was a clearer explanation.

**Comment by jef-n** [comment]
The batch file is only used on install (since 801184a8a14d92).  It calls the .exe with --postinstall, which in turn writes all environment variables listed in .vars to an .env file, which the .exe loads on subsequent invocations.  The shortcuts created by the batch file also point at the .exe: https://github.com/qgis/QGIS/blob/97fd45aebb9b18bfe70a97464a7570d49cca9ec7/ms-windows/osgeo4w/postinstall-desktop.bat#L15

But there is code in wintoast to create shortcuts that gets invoked: https://github.com/qgis/QGIS/blob/97fd45aebb9b18bfe70a97464a7570d49cca9ec7/external/wintoast/src/wintoastlib.cpp#L540)

Not sure if that's required for notifications (which wintoast was introduced for in 8876270c9f1).  @nyalldawson, do you know?

**Comment by HeatherHillers** [comment]
Ah.  You are talking about postinstall-desktop.bat and I am talking about qgis-ltr.bat.  That is why I was confused.  But I just want to be clear that the link I am talking about is not the one created by the nircmd on install, but rather the one created by qgis-bin.exe at runtime.

**Comment by jef-n** [comment]
> Ah. You are talking about postinstall-desktop.bat and I am talking about qgis-ltr.bat. That is why I was confused. But I just want to be clear that the link I am talking about is not the one created by the nircmd on install, but rather the one created by qgis-bin.exe at runtime.

Well, my point was that the shortcuts created by the installer are pointing at the .exe too.  There are no - shiny or otherwise - default shortcuts to the qgis-ltr.bat anymore.

**Comment by HeatherHillers** [comment]
mm.  But the ones constructed at installation can be adjusted.  Even if you delete the one created at the qgis start, it will be recreated for you the next time you run qgis.  So, it is very difficult to handle. If you look at it on a desktop, and you are an experienced user, it seems maybe like not a big deal.  But I have 50 users, of varying ability.  I have to make sure qgis is starting perfectly for everyone.

**Comment by jef-n** [comment]
> mm. But the ones constructed at installation can be adjusted. Even if you delete the one created at the qgis start, it will be recreated for you the next time you run qgis. So, it is very difficult to handle. If you look at it on a desktop, and you are an experienced user, it seems maybe like not a big deal. But I have 50 users, of varying ability. I have to make sure qgis is starting perfectly for everyone.

The shortcuts to the .exe are adjustable too (but you may have to update the .env (or .vars and rerun qgis.bat with --postinstall) if you introduce new variables that the .exe should restore.  Then qgis should also start as is was before (otherwise pinning wouldn't work).

**Comment by grl-sage** [comment]
> We have shown that this link is created directly by qgis-bin.exe by wintoastlib when qgis starts.
> 
> qgswinnative.cpp in the function:
> QgsWinNative::initializeMainWindow()
> 
> runs a wintoastlib instance initialize
> 
> if ( WinToastLib::WinToast::instance()->initialize() )
> {
> mWinToastInitialized = true;
> mCapabilities = mCapabilities | NativeDesktopNotifications;
> }
> 
> The initialize code in wintoastlib creates the link.
> 
> There is no way to prevent the creation of this link with an environment variable, for instance.
> 
> This is an intentional feature, but when qgis is installed as a networked installation for an organisation with many users, it is a bug.
> 
> The qgis-ltr.bat is where network profiles are set and global settings are used. On windows 10, the creation of this link gives the user an attractive, shiny start menu item that is presented in some cases with preference over the real start menu item. The QGIS created link is to the .exe, not to the .bat. Thus the user will open a qgis where the profile is not properly set up. This is especially problematic in 3.10, where global settings must be used to avoid having the user being presented with datum transform selection windows.
> 
> We are going to try a workaround by running python code at qgis start up that deletes the link. It is a very odious workaround, however.

Can you let me know how you solved this?  I have my own VB Script where I create a shortcut to QGIS after a user installs it and out custom toolbar and I want to get rid of the QGIS one.

**Comment by jef-n** [comment]
See also #42042

**Comment by HeatherHillers** [comment]
@grl-sage 

My solution is similar.

As you know, but just to establish background: The start menu link from installation (QGIS Desktop 3.16) is in the Windows Start Menu, but the QGIS3 start menu link gets put in the User's Start Menu.  It gets created after QGIS starts.  You can't prevent that.  But, if wintoast sees the link, it will not overwrite it, thank god.  So the user needs to put their own link in that spot before QGIS does.

1. I made my own QGIS3.lnk, which I have stored in a subdirectory I made under bin. 

2. I made my own qgis-ltr-bin.exe.  This is a python script that is compiled to an executable.  I set environment variables there, I set the global user settings and default transformations that the people in my organisation need to have, and I call qgis using the network profile directory.  These things I used to have in the .bat.  I also copy my QGIS3.lnk to the User Start Menu before QGIS gets a chance to do it.

3. The not so pretty bit: after installing qgis via osgeo4w, I copy over qgis-ltr-bin.* to qgis-ltr-bin_osgeo.*  I overwrite qgis-ltr-bin.exe with my qgis-ltr-bin.exe. My qgis-ltr-bin.exe is calling qgis-ltr-bin_osgeo.exe with the network installer.  The QGIS Desktop 3.16 link calls qgis-ltr-bin.exe, the QGIS3 link calls qgis-ltr-bin.exe, and every Desktop link or anything else the user might do will call qgis-ltr-bin.exe.  

If you do not copy the link,  The link will be created by QGIS referencing the executable that is called, rather than the executable that is calling.

If you want I can send you a link to the python script tomorrow.

**Comment by HeatherHillers** [comment]
@jef-n : Changing the QGIS Desktop X Start Menu Link to QGIS3, as mentioned in the linked issue, would maybe be a nice thing, but I don't see how it would effect this problem.  If OSGeo just changes the name of the link, which is installed in the Start Menu for all users, Windows 10 would still show preference to the QGIS3 link that is saved into the User's Start Menu.  As long as that QGIS3 link gets produced by QGIS, it gums up whatever the installer creates and prevents the administrator from consistently enforcing any kind of custom start, including starts with network profiles, which are not that custom.

**Comment by jef-n** [comment]
@HeatherHillers that would only work for one version of QGIS.

**Comment by haubourg** [comment]
Hi there, I confirm the behavior here with a custom enterprise package here.
My issue is that I really need to let the users launch QGIS via a shortcut deployed with a custom osgeo4W package. The QGIS.lnk does not have all the corporate logic I need and will let some users launch the right launcher, some other the wrong one :/

 @jef-n I see your commit that lets use a environnement variable to change the application name. Isn't ther any way to not create this shortcut at all?

**Comment by HeatherHillers** [comment]
> Hi there, I confirm the behavior here with a custom enterprise package here.
> My issue is that I really need to let the users launch QGIS via a shortcut deployed with a custom osgeo4W package. The QGIS.lnk does not have all the corporate logic I need and will let some users launch the right launcher, some other the wrong one :/
> 
> @jef-n I see your commit that lets use a environnement variable to change the application name. Isn't ther any way to not create this shortcut at all?

Exactly.

**Comment by haubourg** [comment]
I worked around my issue by creating on my package install a shortcut using nircmd with the same name. QGIS won't overwrite it.

**Comment by jef-n** [comment]
Apparently the shortcut is needed for notifications - otherwise they appear garbled.   The package now creates the shortcut and passed it's name to QGIS, so it doesn't (have to) recreate it (or `QGIS3.lnk`).

> Not sure if that's required for notifications (which wintoast was introduced for in [8876270](https://github.com/qgis/QGIS/commit/8876270c9f1098d6c0a626c28af10a0edd9cab49)). @nyalldawson, do you know?
