### ISSUE TITLE
sql "order by" does not work with the "Add/Edit Virtual Layer" feature

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29043]
Author Name: **Alain FERRATON** (@FERRATON)
Original Redmine Issue: [21225](https://issues.qgis.org/issues/21225)
Affected QGIS version: 3.4.4
Redmine category:virtual_layers

---
On a simple example
add a virtual layer with the functionality "Add/Edit a virtual layer" :
SELECT * FROM mylayer ORDER BY myfield 

the virtual layer created is not sorted.

If you use DBmanager it works correctly.

**Comment by troopa81** [comment]
When opening an attribute table, QGIS try to guess on what column attribute table [should be sorted](https://github.com/qgis/QGIS/pull/30245/files#diff-106be592650b55ccae79c83eecd15cebR3137). If none matches, it takes the first field. 

If you want to change attribute table column order, just click on the right column in the attribute table. The column use for sorting is saved in the project.

Still, QGIS takes care of the `ORDER BY` instruction, and if you run through the feature, they are in the given order. That's why it works in a layout.
