### ISSUE TITLE
File dialogs in FlatPak version of QGIS revert to default directory

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29047]
Author Name: **Frank Sokolic** (Frank Sokolic)
Original Redmine Issue: [21229](https://issues.qgis.org/issues/21229)
Affected QGIS version: 3.4.2
Redmine category:gui

---
File dialogs in the FlatPak version of QGIS always revert to a default directory and file type when they are opened. This behaviour is different to the standard install of QGIS where the previous directory and file type selection is used.

**Comment by kannes** [comment]
This should be tracked at the Flatpak repo I believe? https://github.com/flathub/org.qgis.qgis
cc @aleixpol

**Comment by aleixpol** [comment]
It's not really a packaging issue. In flatpak these standard dialogs come from the system (see xdg-desktop-portals).

What desktop environment are you using? KDE Plasma, GNOME, others?

**Comment by gioman** [comment]
This should be closed as we don't support officially flatpack.

**Comment by aleixpol** [comment]
> This should be closed as we don't support officially flatpack.

I've been putting a lot of effort in supporting this packaging and people are using it in the thousands (https://klausenbusk.github.io/flathub-stats/#ref=org.qgis.qgis&interval=infinity&downloadType=installs%2Bupdates).

I don't understand why you'd insist in putting it this way, I've shown myself open to work with you since the beginning.

**Comment by nyalldawson** [comment]
I actually suspect this is a wider issue in qt 5.15 or gnome Shell or the qt/gnome integration library. I get all kinds of bad behaviour with qt apps and file dialogue since updating to fedora 33 ( including this, and file dialogs always opening behind other windows)

**Comment by rdieter** [comment]
That particular bug should be fixed by update
https://bodhi.fedoraproject.org/updates/FEDORA-2021-dd40f54279

**Comment by nyalldawson** [comment]
@rdieter oh thanks goodness -- that was driving my insane 🙃! Thanks so much for getting the fix deployed! (By any chance you don't know if there's any fixes for the greyed out/disabled widget appearance you get in qt apps on f33+ when focusing different docks or other applications? That's my other major pain point with f33)

@aleixpol the Flatpack isn't **currently** official. I'd encourage you to open a discussion on the qgis PSC mailing list or open a proposal at https://github.com/qgis/QGIS-Enhancement-Proposals/issues?page=2&q=is%3Aissue+is%3Aopen so that the future "official" status of the package can be decided. I agree that there's a compelling argument to be made for official support for the Flatpack version 👍

**Comment by rdieter** [comment]
@nyalldawson sorry, that issue rings no bells.  Please file a bug if you're not already aware of one.

**Comment by nyalldawson** [comment]
@rdieter there's https://bugzilla.redhat.com/show_bug.cgi?id=1911734 which describes this one

**Comment by kannes** [comment]
@aleixpol I am sure @gioman did not mean it like you felt it. It would be great to have the package elevated to being an official download. :)

**Comment by aleixpol** [comment]
> @aleixpol the Flatpack isn't currently official. I'd encourage you to open a discussion on the qgis PSC mailing list or open a proposal

https://github.com/qgis/QGIS-Enhancement-Proposals/issues/220

**Comment by alexbruy** [comment]
Is this still an issue?
