### ISSUE TITLE
Bug with scale bar in 3.4.4

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29180]
Author Name: **Massimiliano Moraca** (Massimiliano Moraca)
Original Redmine Issue: [21363](https://issues.qgis.org/issues/21363)
Affected QGIS version: 3.4.4
Redmine category:map_composer/printing

---
Hi!
As you can see on attachments, there is a bug with the scale bar in the 3.4.4.
If I leave the same settings of 2.18 into the 3.4.4, the scale bar in print composer is shown incorrectly.

---

- [scalebar2.18.png](https://issues.qgis.org/attachments/download/14431/scalebar2.18.png) (Massimiliano Moraca)
- [scalebar2.18-2.png](https://issues.qgis.org/attachments/download/14432/scalebar2.18-2.png) (Massimiliano Moraca)
- [scalebar3.4.4.png](https://issues.qgis.org/attachments/download/14433/scalebar3.4.4.png) (Massimiliano Moraca)
- [scalebar3.4.4-2.png](https://issues.qgis.org/attachments/download/14434/scalebar3.4.4-2.png) (Massimiliano Moraca)
- [mappe_125k.zip](https://issues.qgis.org/attachments/download/14458/mappe_125k.zip) (Massimiliano Moraca)
- [QGIS3-125k.qgz](https://issues.qgis.org/attachments/download/14468/QGIS3-125k.qgz) (Massimiliano Moraca)

**Comment by jdugge** [comment]
I believe the problem here are the different ways the distances for the grid and for the scale bar are calculated.

Distances for the grid lines are calculated using Cartesian coordinates while those for the scale bar are calculated using ellipsoidal distances when the "Scalebar units" are set to "m" (as they are Massimiliano's example project).

In the case of EPSG:3857 Pseudo Mercator this means that at the equator the distance calculation for the grid line distance and the scale bar length would be equivalent. However, at the map latitude of 48° the ellipsoidal distance between two neighboring (Cartesian) grid lines is only approximately 67 % of the Cartesian distance, so the scale bar appears stretched compared to the distance between two grid lines:

![image](https://user-images.githubusercontent.com/2399255/81714238-24583100-9477-11ea-8461-b5d8fbaf4b92.png)

By setting the "Scalebar units" to "Map units" (which is the default) the same Cartesian distance calculation is used for the grid lines and the scale bar, and the length of the scale bar and the grid distance match:

![image](https://user-images.githubusercontent.com/2399255/81714584-7ef18d00-9477-11ea-83f6-afb6c22ef502.png)

I believe QGIS is doing the right thing here, but the difference between the distance calculation methods might need to be explained in the documentation.

In Massimiliano's case, the best approach would probably be to select a more appropriate CRS (such as EPSG:32631 WGS 84 / UTM Zone 31 N) where the different distance calculation methods do not lead to such different results.

**Comment by nyalldawson** [comment]
Closing as not an issue
