### ISSUE TITLE
QGIS Server does not show Map Tip in WMS GetFeatureInfo

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29235]
Author Name: **Bela Kutfej** (@kutfejbela)
Original Redmine Issue: [21418](https://issues.qgis.org/issues/21418)
Affected QGIS version: 3.4.5
Redmine category:qgis_server

---
I updated QGIS Server from "http://qgis.org/debian-ltr stretch" and after that the WMS:GetFeatureInfo does not show the maptip.

**Comment by zeusgonzalezfernandez** [comment]
Same with QGIS-server 3.8 under Linux, also there's no maptip field in the getfeatureinfo request (inside qgis client).
![bug_qgis](https://user-images.githubusercontent.com/44396000/61138451-cf9b0100-a4c7-11e9-9b99-3bd2f5767d65.png)

**Comment by andreasneumann** [comment]
This is not a bug, but a change in behavior (actually an improvement). You have to enable maptips if you want them in the GetFeatureInfo. Just add the WITH_MAPTIP in the GetFeatureInfo request.

Reason:
Maptips often contain redundant information to other attributes. Depending on the WMS client, you don't want to display the maptip attribute. In addition, for Desktop WMS clients (QGIS, ArcGIS, Geomedia, etc.) you don't want the maptip attribute. For this reason, because we can't influence most WMS clients, the maptip (and the geometry) was set to off by default.

WMS clients (mostly Web-GIS) who need them need to explicitly ask for them.

See also https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/services.html#getfeatureinfo

**Comment by andreasneumann** [comment]
See also https://github.com/qgis/QGIS/pull/5466/files

This issue should be closed.

**Comment by zeusgonzalezfernandez** [comment]
I don't think that qgis-server works as it should.

Check screenshot, the request it's ok but the WMS doesn't show the maptip field.

![bug_wms](https://user-images.githubusercontent.com/44396000/61139892-9c0da600-a4ca-11e9-8701-eeefc8bc58bb.png)
