### ISSUE TITLE
[Style] Allow partial loading/saving/copying/pasting of raster layer style 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29283]
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [21466](https://issues.qgis.org/issues/21466)

Redmine category:symbology

---
For vector layer, it's possible when interacting with styles, to only pick parts of it, either through the Style combobox in layer properties or Style submenu in the layer contextual menu.
None of these is possible with rasters; you always export/import the whole style.

**Comment by mblesius** [comment]
This would also be a good thing for the _Layer Notes_ which have been added in QGIS 3.20, so that you can copy the notes from one raster layer and paste it to multiple other raster layers or maybe even layers of mixed type (raster/vector). Currently, it is not possible to paste the _Notes_ copied from a _raster layer_ to a _vector layer_ (or vice versa).

**Comment by AlisterH** [comment]
Where this particularly annoys me is that when I copy a style onto a number of rasters the profile chart appearance is included i.e. they all turn the same colour on raster profiles.

**Comment by DelazJ** [comment]
Fixed in #58498
