### ISSUE TITLE
OPACITIES parameter is not handled with GetPrint

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29317]
Author Name: **Nicolas Boisteault** (@nboisteault)
Original Redmine Issue: [21500](https://issues.qgis.org/issues/21500)
Affected QGIS version: 3.4.5
Redmine category:qgis_server

---
Whatever value I put in OPACITIES parameter it doesn't change the opacity of my layers when I make a GetPrint request. With GETMAP it is ok.

**Comment by pblottiere** [comment]
Hi @nboisteault,

> Whatever value I put in OPACITIES parameter it doesn't change the opacity of my layers when I make a GetPrint request.

Can you give me your `GetPrint` request please? Because it seems to be working and already unit tested.

For example, the next request:

``` bash
http://qgisserver:
SERVICE=WMS &
REQUEST=GetPrint &
map0:LAYERS=Country,Hello &
OPACITIES=125,125 &
SELECTION=Country: 4 
```

returns layers with an opacity of `125` for each of the two layers:

![image](https://user-images.githubusercontent.com/9266424/67397216-288b3280-f5a9-11e9-81b3-09067fc65de6.png)

**Comment by Gustry** [comment]
Maybe @rldhont has some inputs?

**Comment by rldhont** [comment]
@pblottiere It has been fixed

I didn't found the PR or commit that fix it.

**Comment by pblottiere** [comment]
@rldhont ok, thanks for the feedback :+1:
