### ISSUE TITLE
Changing rendering behavior on zoom to prevent flashes 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29574]
Author Name: **Andrew Annex** (@AndrewAnnex)
Original Redmine Issue: [21759](https://issues.qgis.org/issues/21759)

Redmine category:map_canvas

---
On macOS with qgis 3.4.6 LTR. Unknown if this is on other systems

Zooming should disable rendering until the updated map view is completely rendered and then display. Currently with multiple raster and vector layers, with some wms layers, when a zoom event the canvas is cleared to white followed by various layers rendering and popping into view which causes eye strain and is visually distracting.

The behavior I want is closer to what happens when the render checkbox is deselected. The existing canvas should be in view until the new canvas has completely finished rendering and then it should replace the current canvas view on the screen. This behavior should probably be configurable

**Comment by kannes** [comment]
+100 from me. I think ArcGIS does it like this and it makes for a much more pleasant experience. Probably also feels more performant to users. ;)

**Comment by MeijeSibbel** [comment]
Giving a 1000+ to this one. This would seriously improve UX.

**Comment by PeterPetrik** [comment]
implemeted as smart updates (qgis 2020 grant)

**Comment by AndrewAnnex** [comment]
Yay thanks!

-Andrew Annex

**Comment by mkubantseva-art** [comment]
Subject: Persistent flickering and redrawing of basemaps and vector layers during navigation on macOS

QGIS Version: 3.44.11-Solothurn
OS: macOS (MacBook Pro with Retina display, "More Space" scaling mode)

Description:

When panning or zooming, basemaps (from QuickMapServices) and vector layers constantly redraw from scratch, causing severe flickering. This happens with every mouse movement, even during small displacement.

What I've tried:

Increased cache size to 1 GB (tried both Smart Cache and manual setting) — no improvement

Disabled geometry simplification — no improvement

Changed resampling method to Nearest Neighbor — no improvement

Created a completely fresh user profile (no plugins, no old settings) — issue persists

Disabled layer rendering cache — no improvement

Expected behavior:

Same as on Windows — basemaps and layers should use cache and not redraw with every tiny mouse movement. Smooth navigation without constant "flashes" and tile reloading.

Additional context:

This issue reproduces only on macOS. The same project with the same layers works smoothly on Windows. The problem is not specific to any particular project or dataset — it reproduces even on a fresh profile with just one basemap. Other users report similar behavior (e.g., bug report #21759).

Please investigate whether this can be fixed in future releases. It's especially frustrating that a clean profile doesn't help — this suggests a rendering/caching issue in QGIS on macOS at the system level, not a user config issue.

**Comment by kannes** [comment]
This issue is closed and not tracked. Please open a new issue so that your valuable report does not get lost.

FYI, I think you used automatic translation but the "Please investigate whether this can be fixed in future releases" line reads rather aggressively and i would recommended changing it. QGIS is a free and open source community where you have no reason to "demand" anything. ;)
