### ISSUE TITLE
when pasting features to postgresql layer, attributes that are a primary key do not have the values pasted

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29624]
Author Name: **Sebastian Brocks** (@beerockxs)
Original Redmine Issue: [21809](https://issues.qgis.org/issues/21809)
Affected QGIS version: 3.6.1
Redmine category:editing

---
I'm trying to paste a few features into a postgresql layer that has two attributes that together form the table's primary key. The values of the attributes are not pasted correctly, although both name and order and type match.

---

- [paste_error.png](https://issues.qgis.org/attachments/download/14778/paste_error.png) (Sebastian Brocks)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by beerockxs** [comment]
I just had this exact bug happen again, this time using QGIS 3.12

**Comment by andreasneumann** [comment]
Isn't that "by design"?

A primary key is normally generated by the database and not by QGIS. Thus, QGIS shouldn't attempt to provide data for primary key columns - especially not when pasting data - as the chance to violate pkey unicity is really high.

**Comment by andreasneumann** [comment]
What if you paste the same feature twice? Boom - you would get a violation of pkey unicity.

It would be really, really dangerous if QGIS would allow to paste data into pkey columns.

**Comment by beerockxs** [comment]
A primary key should uniquely identify a database entry.  It's perfectly fine to have it user defined, and then the database should and will throw an error when trying to save the layer, due to a violated constraint, just as it does now when a foreign key constraint is violated.

**Comment by andreasneumann** [comment]
> A primary key should uniquely identify a database entry. It's perfectly fine to have it user defined

Yes - ok. But how should QGIS magically find out if the pkey should be user defined or system generatated?

The current behavior covers the 99% use case where the pkey is generated by the DB. It is probably safe to say that this is the behavior that users normally want.

Your use case is an exception and you should open a feature request to allow handling this exception. It probably requires a configuration in order to allow pasting values into pkey columns.

Unless we find a way that QGIS does this distinction automagically? QGIS could f.e. find out if the column has a default value or serial/bigserial value (either on db or client-side in QGIS), if it has neither one, than it could allow pasting values into pkey columns.

**Comment by beerockxs** [comment]
How about if the user supplies a value, we use it and if he doesn't we let the database handle it?

**Comment by andreasneumann** [comment]
> How about if the user supplies a value, we use it and if he doesn't we let the database handle it?

As far as I know you can only copy / paste a feature with ALL attributes, not only selected attributes. So no - this wouldn't work.

**Comment by beerockxs** [comment]
Before copying and pasting, the user needs to thoroughly check the attribut list anyway to make sure that attribute names and types match up. how is it logical that just the primary key attributes are not pasted correctly?

**Comment by andreasneumann** [comment]
> how is it logical that just the primary key attributes are not pasted correctly?

If we would do that, we would get a ton of bug reports from people complaining that QGIS pastes values in a pkey column where they want it to be generated by the database.
