### ISSUE TITLE
GML_ATTRIBUTES_TO_OGR_FIELDS=YES by default when loading GML

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29641]
Author Name: **Alexander Kotsev** (Alexander Kotsev)
Original Redmine Issue: [21826](https://issues.qgis.org/issues/21826)

Redmine category:data_provider/ogr

---
We work in Europe for the Joint Research Centre (European Commission) as technical coordinator of the EU INSPIRE Directive implementation. Within the context of INSPIRE, an increasing number of datasets are made available by European Union Member States as GML [1]. Application schemas (*.xsd) for INSPIRE are available at [2]. Most, if not all of the GML instances that are made available use attributes of GML elements such as xlink:href pointing to a registry with persistent uri [3]. The default behaviour of QGIS ignores those attributes which is inherited from the default OGR/GDAL logic for creating a *.gfs on first load of a GML instance. As a consequence, a significant portion of the available attribute content is 'invisible' in QGIS. 

The issue is described in [4], and the solution is already available there. In a nutshell, when first loading the GML, the open option 'GML_ATTRIBUTES_TO_OGR_FIELDS' should be set to 'YES'. This would allow the generation of a fully-blown *.gfs correctly showing all GML attributes in QGIS (which would make the life of a lot of European data providers a lot easier). Sample GML instances are attached.

Addressing this issue would be very much appreciated. 

Marco Minghini and Alex Kotsev

[1] http://inspire-geoportal.ec.europa.eu/
[2] http://inspire.ec.europa.eu/schemas/
[3] http://inspire.ec.europa.eu/registry/
[4] https://github.com/INSPIRE-MIF/caniuse/issues/3

---

- [LandUseNL.gml](https://issues.qgis.org/attachments/download/14772/LandUseNL.gml) (Alexander Kotsev)

**Comment by timlinux** [comment]
@Samweli Here are the validation images:

![image](https://user-images.githubusercontent.com/178003/79232035-e7405500-7e5e-11ea-8f8b-8c62aff5fad3.png)

![Uploading image.png…]()

**Comment by timlinux** [comment]
vim src/core/providers/ogr/qgsogrprovider.cpp

```c++
3978 GDALDatasetH QgsOgrProviderUtils::GDALOpenWrapper( const char *pszPath, bool bUpdate, char **papszOpenOptionsIn, GDALDriverH *phDriver )
3979 {       
3980   CPLErrorReset();
3981       
3982   char **papszOpenOptions = CSLDuplicate( papszOpenOptionsIn );
3983 #if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(2,2,0)
3984   const char *apszAllowedDrivers[] = { "GML", nullptr };
3985   GDALDriverH hIdentifiedDriver =
3986     GDALIdentifyDriverEx( pszPath, GDAL_OF_VECTOR, apszAllowedDrivers, nullptr );
3987 #else
3988   GDALDriverH hIdentifiedDriver =
3989     GDALIdentifyDriver( pszPath, nullptr );
3990 #endif
3991   if ( hIdentifiedDriver &&
3992        strcmp( GDALGetDriverShortName( hIdentifiedDriver ), "GML" ) == 0 )
3993   {
3994     // There's currently a bug in the OGR GML driver. If a .gfs file exists
3995     // and FORCE_SRS_DETECTION is set, then OGR_L_GetFeatureCount() returns
3996     // twice the number of features. And as, the .gfs contains the SRS, there
3997     // is no need to turn this option on.
3998     // https://trac.osgeo.org/gdal/ticket/7046
3999     VSIStatBufL sStat;
4000     if ( VSIStatL( CPLResetExtension( pszPath, "gfs" ), &sStat ) != 0 )
4001     {
4002       papszOpenOptions = CSLSetNameValue( papszOpenOptions, "FORCE_SRS_DETECTION", "YES" );                                                                             
4003     }
4004   }
```

**Comment by alexbruy** [comment]
Probably duplicates #27888.

**Comment by heidivanparys** [comment]
> Probably duplicates #27888.

That issue is not a duplication, this issue is not about INSPIRE, it is about having GML attributes shown by default in QGIS, by requesting GML_ATTRIBUTES_TO_OGR_FIELDS=YES set as the default in QGIS.

Some examples of GML attributes (from test file [example_gml_attributes.txt](https://github.com/qgis/QGIS/files/5849014/example_gml_attributes.txt), which provides some dummy data that comply to the data model used in version 2.0 of [this register](https://eng.sdfe.dk/product-and-services/the-danish-register-of-underground-cable-owners-ler/)).

**xlink:href attribute for link:**

![image](https://user-images.githubusercontent.com/11427611/105346111-6bd9b400-5be5-11eb-872c-550343c5cf2a.png)

**indeterminatePosition attribute:**

saying that something happened in April 2019 is not the same as saying the something happened after April 2019

![image](https://user-images.githubusercontent.com/11427611/105346293-af342280-5be5-11eb-8afa-5ab86f58dc96.png)

**srsDimension attribute for elevation:**

the vertical coordinate reference system for an elevation is important to know

![image](https://user-images.githubusercontent.com/11427611/105346574-0f2ac900-5be6-11eb-95c7-fea6047fee58.png)
