### ISSUE TITLE
Browser cannot open Volumes under macOS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29702]
Author Name: **Chang Liao** (Chang Liao)
Original Redmine Issue: [21887](https://issues.qgis.org/issues/21887)
Affected QGIS version: 3.6.1
Redmine category:browser

---
I tried both QGIS 3.4 and 3.6, but none of them is working probably.
It cannot open the /Volumes directory on my Mac even though there are external driver connected.

P.S. I was able to open it ONLY in QGIS 3.2.

**Comment by gioman** [comment]
> Does the new single-click installer have the same behaviour?

@PeterPetrik yes, I just tested 3.14.0 on Catalina and inside the QGIS Browser "Volumes" shows nothing.

**Comment by PeterPetrik** [comment]
I removed the /Volumes from the Browser alltogether, since /Volumes are not displayed in any GUI application I have at hand for regular Users. Looks like Apple policy, e.g. Qt Creator

![Screenshot 2020-09-24 at 15 41 04](https://user-images.githubusercontent.com/804608/94153163-ba1bb800-fe7c-11ea-966a-d24dde6d68a4.png)

or Native Apple File Dialog or Finder
![Screenshot 2020-09-24 at 15 41 23](https://user-images.githubusercontent.com/804608/94153200-c56ee380-fe7c-11ea-9894-88b0e29bff72.png)
