### ISSUE TITLE
GRASS r.in.lidar fails in QGIS but works in native GRASS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29740]
Author Name: **Andreas Olsson** (Andreas Olsson)
Original Redmine Issue: [21925](https://issues.qgis.org/issues/21925)
Affected QGIS version: 3.6.2
Redmine category:processing/grass

---

File info pulled from LAS-file, using GRASS because that function doesn’t work in QGIS!

The data is in "SWEREF 99 18 00", a Swedish coordinatesystem.

>>
Using LAS Library Version 'libLAS 1.8.0 with GeoTIFF 1.4.0 GDAL 1.11.3 LASzip 2.2.0'
LAS File Version:                  1.2
System ID:                         'Trimble'
Generating Software:               'TRW 2.21.0 2.2 r0 (130917)'
File Creation Day/Year:            234/2018
Point Data Format:                 2
Number of Point Records:           126410605
Number of Points by Return:        126410605 0 0 0 0
Scale Factor X Y Z:                0.0001 0.0001 0.0001
Offset X Y Z:                      149520 6.56859e+006 20
Min X Y Z:                         148852 6.56773e+006 5.0197
Max X Y Z:                         149927 6.56905e+006 80.8466
Spatial Reference:                 None
Data Fields:
  'X'
  'Y'
  'Z'
  'Intensity'
  'Return Number'
  'Number of Returns'
  'Scan Direction'
  'Flighline Edge'
  'Classification'
  'Scan Angle Rank'
  'User Data'
  'Point Source ID'
  'Red'
  'Green'
  'Blue'

**Comment by neteler** [comment]
Could you try with the new GRASS GIS 7.8.1 (https://github.com/OSGeo/grass/releases/tag/7.8.1)? Also projection related issues where fixed and Python 3 is supported since 7.8.0. 

And since liblas is rather outdated, an addon we have https://grass.osgeo.org/grass7/manuals/addons/r.in.pdal.html and pending updates here: https://github.com/OSGeo/grass/pull/61 (PDAL-based version of r.in.lidar)

**Comment by alexbruy** [comment]
Closing for the lack of feedback. Please reopen if necessary.
