### ISSUE TITLE
layer properties panel hides labels

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29765]
Author Name: **Niccolo' Marchi** (Niccolo' Marchi)
Original Redmine Issue: [21950](https://issues.qgis.org/issues/21950)
Affected QGIS version: 3.4.7
Redmine category:gui

---
The "layer properties" panel shows only the icons by deafult. When the bar is dragged to the right in order to widen the box and let the icons' labels appear, it automatically hides everything, requiring the user to close and reopen the whole panel (see picture attached).
I freshly updated to 3.4.7 and the bug is still present.

---

- [gui_bug.png](https://issues.qgis.org/attachments/download/14856/gui_bug.png) (Niccolo' Marchi)

**Comment by alexbruy** [comment]
I can not confirm. By default all properties windows open with expanded sidebar and all labels are clearly visible. Tested on 3.4 and master with clean profiles.

**Comment by alexbruy** [comment]
Works fine in master. Please reopen if necessary.

**Comment by mercerraa** [comment]
Problem occurring in 3.34.3-Prizren but closing the window and even restarting doesnt solve the issue. Only small icons shown and any attempt at pulling the divider out to increase the available space causes the icon Layer Properties icon panel to collapse completely. The icon panel appears again if the whole Layer Properties window is resized. The only solution seems to be entering text in the search bar at the top of the panel.
Note that this problem is very intermittent. I can't always reproduce it.
