### ISSUE TITLE
Locked MapInfo tables when stored on a network share

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29885]
Author Name: **Phil Shevill** (Phil Shevill)
Original Redmine Issue: [22072](https://issues.qgis.org/issues/22072)
Affected QGIS version: 3.6.2
Redmine category:vectors

---
When a QGIS user has a MapInfo layer open in their QGIS project it is not possible for a MapInfo user to update that file on the network drive. It is also not possible to overwrite the MapInfo layer using windows file explorer. This appears to happen even when the map layer is not visible in QGIS and happens regardless of whether the file is in edit mode in QGIS. This is causing us real problems working in a mixed environment as our only solution at the moment is to ensure that all QGIS projects are closed while we update our MapInfo layers.

**Comment by paulwittle** [comment]
We are also experiencing this issue at Dorset Council. The issue is definitely impacting users of MapInfo v15 (32 bit) when trying to access TAB files stored on network drives. I should be able to test for v17 (64 bit) if required but at the moment I'm recommending that we avoid opening TAB files altogether. We are also using QGIS 3.4.7 (LTR).

**Comment by Pedro-Murteira** [comment]
@paulwittle Hello, I'm adressing you since the user that submitted this issue is no longer on github. Did you come across this issue on more recent versions?
