### ISSUE TITLE
When clearing a field, default value is not applied, instead QGIS attepts to insert the UI text hint

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29938]
Author Name: **Cory Albrecht** (@CoryAlbrecht)
Original Redmine Issue: [22127](https://issues.qgis.org/issues/22127)
Affected QGIS version: 3.6.2
Redmine category:data_provider/postgis

---
Instead of generating a new default value, QGIS tries to insert the hint used to show what will be generated.

```
2019-05-22T20:47:09     WARNING    Erroneous query: UPDATE "Balance of Power"."timeline-countries" SET "feature_uuid"='uuid_generate_v4()',"country_uuid"='uuid_generate_v4()',"alternate_name"=E'{}',"full_name"=E'{}' WHERE "feature_uuid"::text='59f16d38-2b77-4b3f-8cad-436026d3b5e7' returned 7 [ERROR: invalid input syntax for uuid: "uuid_generate_v4()"
             LINE 1: ...of Power"."timeline-countries" SET "feature_uuid"='uuid_gene...
              ^
             ]

```

Noosa 3.6.2-6f76857

---

- [Screenshot from 2019-05-22 20-48-26.png](https://issues.qgis.org/attachments/download/14974/Screenshot%20from%202019-05-22%2020-48-26.png) (Cory Albrecht)

**Comment by CoryAlbrecht** [comment]
Steps:
1. Copy a feature from another layer.
2. Modify some of the attribute values
3. Click on the layer save icon and hope it works this time.

**Comment by CoryAlbrecht** [comment]
```
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [78415ms] Checking field against: name
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: admin1_uuid
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: full_name
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: alternate_name
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: start_date
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: end_date
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: main_rgb
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: stripe_rgb
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: border_rgb
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: border_shade
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: sovereign
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: type
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: info_url
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: flag_url
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: predecessors
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: successors
../../src/providers/postgres/qgspostgresprovider.cpp:2167 : (addFeatures) [0ms] Checking field against: visible
../../src/providers/postgres/qgspostgresprovider.cpp:2280 : (addFeatures) [0ms] prepare addfeatures: INSERT INTO "Balance of Power"."timeline_level1"("geom","feature_uuid","name","admin1_uuid","full_name","alternate_name","start_date","end_date","main_rgb","stripe_rgb","border_rgb","border_shade","sovereign","type","info_url","flag_url","predecessors","successors","visible") VALUES (st_multi(st_geomfromwkb($1::bytea,4326)),$2,$3,uuid_generate_v4(),ARRAY[]::text[],ARRAY[]::text[],'1871-07-20','2099-12-31','F99F9F',NULL::character varying,'F67676',0.085,'Canada','province',$4,$5,$6,$7,true) RETURNING "feature_uuid"
../../src/core/qgsvectordataprovider.cpp:712 : (pushError) [62ms] PostGIS error while adding features: ERROR:  malformed array literal: ""
DETAIL:  Array value must start with "{" or dimension information.

../../src/core/qgsmessagelog.cpp:29 : (logMessage) [9ms] 2019-10-27T17:39:10 Messages[2] Layer timeline_level1 : PostGIS error while adding features: ERROR:  malformed array literal: ""
DETAIL:  Array value must start with "{" or dimension information.

../../src/core/qgsmessagelog.cpp:29 : (logMessage) [3ms] 2019-10-27T17:39:10 [1] Commit errors:
  ERROR: 2 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  malformed array literal: ""
    DETAIL:  Array value must start with "{" or dimension information.
    
../../src/gui/qgsmapcanvas.cpp:512 : (refresh) [4ms] CANVAS refresh scheduling
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [16ms] 2019-10-27T17:39:10 Messages[1] Commit errors : Could not commit changes to layer timeline_level1
../../src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
../../src/core/qgsmaprendererparalleljob.cpp:64 : (start) [166ms] QThreadPool max thread count is 8
../../src/providers/postgres/qgspostgresconn.cpp:219 : (QgsPostgresConn) [60ms] [thread:0x7f7fa80029d0] New PostgreSQL connection for dbname='Alternate History' host=pg1.db.cory.albrecht.name port=5432 sslmode=require authcfg=mkiyvty
../../src/auth/basic/qgsauthbasicmethod.cpp:347 : (getMethodConfig) [0ms] [thread:0x7f7fa80029d0] Retrieved config for authcfg: mkiyvty
../../src/core/qgsdatasourceuri.cpp:158 : (QgsDataSourceUri) [26ms] [thread:0x7f7fa80029d0] connection timeout ignored
../../src/providers/postgres/qgspostgresconn.cpp:319 : (QgsPostgresConn) [0ms] [thread:0x7f7fa80029d0] setting client encoding to UNICODE
../../src/providers/postgres/qgspostgresconn.cpp:323 : (QgsPostgresConn) [1ms] [thread:0x7f7fa80029d0] encoding successfully set
../../src/providers/postgres/qgspostgresconn.cpp:334 : (QgsPostgresConn) [0ms] [thread:0x7f7fa80029d0] Connection to the database was successful
../../src/providers/postgres/qgspostgresconn.cpp:1482 : (deduceEndian) [1ms] [thread:0x7f7fa80029d0] Creating binary cursor
../../src/providers/postgres/qgspostgresconn.cpp:1487 : (deduceEndian) [1ms] [thread:0x7f7fa80029d0] Fetching a record and attempting to get check endian-ness
../../src/providers/postgres/qgspostgresconn.cpp:1497 : (deduceEndian) [1ms] [thread:0x7f7fa80029d0] Got oid of 1259 from the binary cursor
../../src/providers/postgres/qgspostgresconn.cpp:1498 : (deduceEndian) [0ms] [thread:0x7f7fa80029d0] First oid is 1259
../../src/providers/postgres/qgspostgresconn.cpp:908 : (postgisVersion) [122ms] [thread:0x7f7fa80029d0] PostGIS version info: 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
../../src/providers/postgres/qgspostgresconn.cpp:933 : (postgisVersion) [1ms] [thread:0x7f7fa80029d0] geos:3.7.2-CAPI-1.11.2 b55d2125 proj:Rel. 6.1.1, July 1st, 2019
../../src/providers/postgres/qgspostgresconn.cpp:962 : (postgisVersion) [0ms] [thread:0x7f7fa80029d0] Checking for topology support
../../src/providers/postgres/qgspostgresconn.cpp:977 : (postgisVersion) [1ms] [thread:0x7f7fa80029d0] Checking for pointcloud support
../../src/providers/postgres/qgspostgresconn.cpp:343 : (QgsPostgresConn) [1ms] [thread:0x7f7fa80029d0] Checking for GEOS support
../../src/providers/postgres/qgspostgresconn.cpp:352 : (QgsPostgresConn) [0ms] [thread:0x7f7fa80029d0] Topology support available!
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [63ms] [thread:0x7f7fa80029d0] Finished after 5 features
../../src/core/qgsmaprendererparalleljob.cpp:210 : (renderLayersFinished) [204ms] PARALLEL layers finished
../../src/core/qgsmaprenderercustompainterjob.cpp:338 : (drawLabeling) [120ms] [thread:0x7f7fc4006080] Draw labeling took (seconds): 0.115
../../src/core/qgsmaprendererparalleljob.cpp:231 : (renderingFinished) [42ms] PARALLEL finished
../../src/core/qgsmaprendererjob.cpp:451 : (cleanupLabelJob) [1ms] caching label result image
../../src/gui/qgsmapcanvas.cpp:598 : (rendererJobFinished) [0ms] CANVAS finish! 1
../../src/providers/postgres/qgspostgresconn.cpp:219 : (QgsPostgresConn) [258ms] [thread:0x7f7fc40066a0] New PostgreSQL connection for dbname='physgeo' host=pg1.db.cory.albrecht.name port=5432 sslmode=require authcfg=mkiyvty
../../src/auth/basic/qgsauthbasicmethod.cpp:347 : (getMethodConfig) [0ms] [thread:0x7f7fc40066a0] Retrieved config for authcfg: mkiyvty
../../src/core/qgsdatasourceuri.cpp:158 : (QgsDataSourceUri) [25ms] [thread:0x7f7fc40066a0] connection timeout ignored
../../src/providers/postgres/qgspostgresconn.cpp:319 : (QgsPostgresConn) [0ms] [thread:0x7f7fc40066a0] setting client encoding to UNICODE
../../src/providers/postgres/qgspostgresconn.cpp:323 : (QgsPostgresConn) [1ms] [thread:0x7f7fc40066a0] encoding successfully set
../../src/providers/postgres/qgspostgresconn.cpp:334 : (QgsPostgresConn) [0ms] [thread:0x7f7fc40066a0] Connection to the database was successful
../../src/providers/postgres/qgspostgresconn.cpp:1482 : (deduceEndian) [1ms] [thread:0x7f7fc40066a0] Creating binary cursor
../../src/providers/postgres/qgspostgresconn.cpp:1487 : (deduceEndian) [1ms] [thread:0x7f7fc40066a0] Fetching a record and attempting to get check endian-ness
../../src/providers/postgres/qgspostgresconn.cpp:1497 : (deduceEndian) [1ms] [thread:0x7f7fc40066a0] Got oid of 1259 from the binary cursor
../../src/providers/postgres/qgspostgresconn.cpp:1498 : (deduceEndian) [0ms] [thread:0x7f7fc40066a0] First oid is 1259
../../src/providers/postgres/qgspostgresconn.cpp:908 : (postgisVersion) [124ms] [thread:0x7f7fc40066a0] PostGIS version info: 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
../../src/providers/postgres/qgspostgresconn.cpp:933 : (postgisVersion) [2ms] [thread:0x7f7fc40066a0] geos:3.7.2-CAPI-1.11.2 b55d2125 proj:Rel. 6.1.1, July 1st, 2019
../../src/providers/postgres/qgspostgresconn.cpp:962 : (postgisVersion) [0ms] [thread:0x7f7fc40066a0] Checking for topology support
../../src/providers/postgres/qgspostgresconn.cpp:977 : (postgisVersion) [2ms] [thread:0x7f7fc40066a0] Checking for pointcloud support
../../src/providers/postgres/qgspostgresconn.cpp:343 : (QgsPostgresConn) [1ms] [thread:0x7f7fc40066a0] Checking for GEOS support
../../src/providers/postgres/qgspostgresconn.cpp:352 : (QgsPostgresConn) [0ms] [thread:0x7f7fc40066a0] Topology support available!
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f7fc40066a0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [4ms] [thread:0x7f7fc40066a0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f7fc40066a0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [10ms] [thread:0x7f7fc4002290] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [3ms] [thread:0x7f7fc4002290] Finished after 1 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [102ms] [thread:0x7f7fc4002290] Finished after 65 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [21ms] [thread:0x7f7fc40067b0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f7fc40067b0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [41ms] [thread:0x7f7fc40067b0] Finished after 52 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [95ms] [thread:0x55791abd5940] Finished after 101 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [11ms] [thread:0x55791abd5940] Finished after 64 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [115ms] [thread:0x55791abd5940] Finished after 249 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [91ms] [thread:0x55791ad8bf40] Finished after 680 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [85ms] [thread:0x55791ad8bf40] Finished after 256 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [209ms] [thread:0x55791ad8bf40] Finished after 557 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [8ms] [thread:0x7f7fc40067e0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [2ms] [thread:0x7f7fc40067e0] Finished after 0 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [6ms] [thread:0x7f7fc40067e0] Finished after 51 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [183ms] [thread:0x7f7fa80029d0] Finished after 423 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [11ms] [thread:0x7f7fa80029d0] Finished after 55 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [119ms] [thread:0x7f7fa80029d0] Finished after 403 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [72ms] [thread:0x7f7fc4006080] Finished after 439 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [17ms] [thread:0x7f7fc4006080] Finished after 48 features
../../src/providers/postgres/qgspostgresfeatureiterator.cpp:313 : (fetchFeature) [51ms] [thread:0x7f7fc4006080] Finished after 104 features
```

**Comment by CoryAlbrecht** [comment]
Attribute table window 
![image](https://user-images.githubusercontent.com/8172909/67642405-d405f100-f8e1-11e9-9a5a-4c58e52f099d.png)

See how in the highlighted rows (the new features) there are several columns with SQL data type definitions? Those fields should be empty because the original items the features were copy-pasted from were empty.

Also see how the pencil icon is highlighted indicating that editing is toggled on? Those same fields are not editable except for the _NULL::character varying_ in the stripe_rgb field. The ones that are _ARRAY[]::text[]_ are not editable. Also, the empty fields in the rows above the uneditable _ARRAY[]::text[]_ in the same column are also not editable. You can click inn them and a text caret appears and blinks, but you cannot enter anything.

Feature attributes dialog
![image](https://user-images.githubusercontent.com/8172909/67642456-4ecf0c00-f8e2-11e9-814a-44c80b7a9573.png)

See the SQL data types in those same fields again? Even though the layer is editable, you cannot edit those fields.

**Comment by CoryAlbrecht** [comment]
The SQL table definition:
```
CREATE TABLE "Balance of Power".timeline_level1
(
    geom geometry(MultiPolygon,4326) NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    feature_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    admin1_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    full_name text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::text[],
    alternate_name text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::text[],
    start_date date,
    end_date date,
    main_rgb character varying(9) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    stripe_rgb character varying(9) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    border_rgb character varying(9) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    border_shade numeric DEFAULT 0.085,
    sovereign text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    info_url text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::text[],
    flag_url text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::text[],
    predecessors uuid[] DEFAULT ARRAY[]::uuid[],
    successors uuid[] DEFAULT ARRAY[]::uuid[],
    visible boolean DEFAULT true,
    CONSTRAINT timeline_level1_pkey PRIMARY KEY (feature_uuid)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

**Comment by gioman** [comment]
> The SQL table definition:

@CoryAlbrecht let's start from here because the previous comments/notes are unclear to me (again, sorry). After having created the table what we should do to replicate the issue?

**Comment by CoryAlbrecht** [comment]
Steps:

1. Copy a feature from another layer.
2. pasted into the layer in question.
3. Modify some of the attribute values of that new feature.
4. Click on the layer save icon.

You'll see the inability to edit the fields as I describe above.

../../src/providers/postgres/qgspostgresprovider.cpp:2280 : (addFeatures) [0ms] prepare addfeatures: INSERT INTO "Balance of Power"."timeline_level1"("geom","feature_uuid","name","admin1_uuid","full_name","alternate_name","start_date","end_date","main_rgb","stripe_rgb","border_rgb","border_shade","sovereign","type","info_url","flag_url","predecessors","successors","visible") VALUES (st_multi(st_geomfromwkb($1::bytea,4326)),$2,$3,uuid_generate_v4(),ARRAY[]::text[],ARRAY[]::text[],'1871-07-20','2099-12-31','F99F9F',NULL::character varying,'F67676',0.085,'Canada','province',$4,$5,$6,$7,true) RETURNING "feature_uuid"
../../src/core/qgsvectordataprovider.cpp:712 : (pushError) [62ms] PostGIS error while adding features: ERROR:  malformed array literal: ""
DETAIL:  Array value must start with "{" or dimension information.

QGIS is putting an inappropriate value when binding params to a prepared statement.

**Comment by CoryAlbrecht** [comment]
I would guess that it is related to this similar error when trying to update and QGIS tries to set a fiedl that is an array of UUIDs to an array containing a single empty string

```
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] 2019-11-02T15:14:29 PostGIS[1] Erroneous query: UPDATE "Balance of Power"."timeline_level1" SET "end_date"='1880-08-30',"info_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"successors"=E'{""}' WHERE "feature_uuid"::text='fbcbed89-0861-4e75-a4ae-0032f9a304ec' returned 7 [ERROR:  invalid input syntax for type uuid: ""
LINE 1: ...fo_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"s...
                                                             ^
]

```

**Comment by CoryAlbrecht** [comment]
Also see this, what the features in the layer look like in pgAdmin4:
![image](https://user-images.githubusercontent.com/8172909/68075928-e0c49200-fd84-11e9-980f-148b7fd7c567.png)

**Comment by CoryAlbrecht** [comment]
Compare that with the attributes table from QGIS:
![image](https://user-images.githubusercontent.com/8172909/68075951-2bdea500-fd85-11e9-8d7c-38243d27d7cf.png)

**Comment by CoryAlbrecht** [comment]
See those four fields - info_url, flag_url, predecessoors, and successors? In the QGIS view the empty fields correlate with the features where their value is an empty array ({} in PostgreSQL). The two rows that show NULL in QGIS show a faded out [null] in pgAdmin4.

In QGIS the fields with NULL are editable, but the ones that are blank and correlate to {} on the PostgreSQL side, all you can do is click and get the flashing caret, but you cannot add anything.

I suspect that this all comes down to the bad handling of arrays by QGIS that I have been reporting on for while now.

**Comment by CoryAlbrecht** [comment]
This is a cpy of the layer data that QGIS gas the problem with from a PostGIS layer. The command used to export was

`/usr/bin/psql --command "\\copy \"Balance of Power\".timeline_level1 (geom, name, feature_uuid, admin1_uuid, full_name, alternate_name, start_date, end_date, main_rgb, stripe_rgb, border_rgb, border_shade, sovereign, type, info_url, flag_url, predecessors, successors, visible) TO '/home/cory/Downloads/provinces4.txt' DELIMITER ',' ;"
`
[provinces3.txt](https://github.com/qgis/QGIS/files/3800881/provinces3.txt)

PostgreSQL 11.5 and PostGIS 2.5.3 on FreeBSD 11.2-RELEASE-p11

QGIS 3.8.3 and 3.10.0/92102bdec4

**Comment by gioman** [comment]
> * Copy a feature from another layer.
> 
> * pasted into the layer in question.
> 
> * Modify some of the attribute values of that new feature.
> 
> * Click on the layer save icon.

please attach dumps of the involved tables.

**Comment by CoryAlbrecht** [comment]
@gioman I gave you a dump of the table in that previous comment.

**Comment by gioman** [comment]
> @gioman I gave you a dump of the table in that previous comment.

that is not a dump (it was not made with pg_dump), I would have one (that contains both the table definition and the data) but I was able to manually recreate your table and in a second step import your data. Anyway I'm having a really hard time in understanding what is the issue here and how to replicate it.


From: https://github.com/qgis/QGIS/issues/29938#issuecomment-546737500
> Steps:
>     1. Copy a feature from another layer.

any other layer?
and then what? pasting into the table you provided?


>     2. Modify some of the attribute values

where, in the pasted feature?


>     3. Click on the layer save icon and hope it works this time.

"this time"? there was any other time before that?


I tried to follow the above steps (of they make any sense) and I got no error in the QGIS log or in the terminal and...

> See how in the highlighted rows (the new features) there are several columns with SQL data type definitions? Those fields should either be be empty because the original items the features were copy-pasted from were NULL in the database, or {} because the fields were an empty array in the database.

in the pasted feature those fields are empty.


I would really appreciate if you can give it another try to explain us (in a clear and concise way) what is the expected result vs the obtained result and what are the minimal set of steps necessary to replicate.

**Comment by CoryAlbrecht** [comment]
This can be replicated without the TimeManager plugin, but having it installed and active make it easier to describe as that is how I am working. Otherwise you'll have a large number of overlapping features (often with the same names). All descriptions here on in will assume you have it turning on with the layer in question added.

Set Time Manager to '1785-05-31 00:00:00.000', timeframe size 1 day and turn on.

Find the feature with name='East Florida', feature_uuid='e0598eec-597d-4d5c-b922-eed6307fe88a' in layer "Balance of Power"."timeline-countries"

Copy that feature.

Edit it's end_date from '1795/10/26' to '1785/05/31'

Save the layer, and toggle edit mode off

Advance Time Manager by 1 day to 1785-06-01.

Toggle edit mode on.

Paste the feature.

Edit its start_date to '1785/06/01'.

Try to save the layer.

You will get an error banner, and when clicking on 'Show more" it will display:

Could not commit changes to layer timeline-countries

```
Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  invalid input syntax for type uuid: "NULL"
    LINE 1: ...rying,'737318',0.085,'Spain','colony',E'{}',E'{}',E'{"NULL"}...
                                                                 ^
```    

To be able to save the layer you will have to use the Field Calculator to change the predecessors field for that feature to NULL.

The problem is that E'{"NULL"}. In the record it is '{NULL}', as per PostgreSQL's dialect for array values. '{NULL}' is different from '{"NULL"}'. 

In other cases as mentioned above it turns empty arrays, a  '{}', into a '{""}'. That might be fixed now, I don't know because honestly the problems with SQL arrays that QGIS 3.x introduced have been going on so long now that I have just become resigned to losing my data because of QGIS's screw up and just fix it with the field calculator and move on.

QGIS is turning the value NULL into the string "NULL". if the field were a varchar array, there would be no SQL error and insertion would happen just fine, though the value stored wouldn't be what was there originally and trying to search for NULLs as array members would not work becaus ethey've been replaced by the string "NULL". But because the field is a UUID array and "NULL" is not a valid UUID value, it cannot update the layer.

**Comment by CoryAlbrecht** [comment]
This is still happening

```
../../src/providers/postgres/qgspostgresprovider.cpp:3471 : (changeFeatures) [20751ms] Exception thrown due to PQprepare of this query returning != PGRES_COMMAND_OK (7 != expected 1): UPDATE "lawta"."timeline_level1" SET "name"='Antwerp',"feature_uuid"='uuid_generate_v4()',"realm_uuid"='uuid_generate_v4()',"type"='Margaviate',"geom"=st_multi(st_geomfromwkb($1::bytea,4326)) WHERE "id"=31 AND "feature_uuid"::text='a934011b-7208-4c48-a931-12c02a1cb0cd'
../../src/core/vector/qgsvectordataprovider.cpp:756 : (pushError) [0ms] PostGIS error while changing attributes: ERROR:  invalid input syntax for type uuid: "uuid_generate_v4()"
LINE 1: ...eline_level1" SET "name"='Antwerp',"feature_uuid"='uuid_gene...
                                                             ^

../../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2022-02-06T18:03:16 [1] Commit errors:
  
  Provider errors:
      PostGIS error while changing attributes: ERROR:  invalid input syntax for type uuid: "uuid_generate_v4()"
    LINE 1: ...eline_level1" SET "name"='Antwerp',"feature_uuid"='uuid_gene...
                                                                 ^
``` 
The problem is not with teh PostGIS data provider but with QGIS improperly stringifying things.

For example, the SQK statement:

```
UPDATE "lawta"."timeline_level1"
SET
    "name"='Antwerp',
    "feature_uuid"='uuid_generate_v4()',
    "realm_uuid"='uuid_generate_v4()',
    "type"='Margaviate',
    "geom"=st_multi(st_geomfromwkb($1::bytea,4326))
WHERE "id"=31 AND "feature_uuid"::text='a934011b-7208-4c48-a931-12c02a1cb0cd'
```

the data for the feature_uuid and realm_uuid should not be the string `'uuid_generate_v4()'` but the function `uuid_generate_v4()` for a correct SQL statement of

```
UPDATE "lawta"."timeline_level1"
SET
    "name"='Antwerp',
    "feature_uuid"=uuid_generate_v4(),
    "realm_uuid"=uuid_generate_v4(),
    "type"='Margaviate',
    "geom"=st_multi(st_geomfromwkb($1::bytea,4326))
WHERE "id"=31 AND "feature_uuid"::text='a934011b-7208-4c48-a931-12c02a1cb0cd'
```

QGIS is correctly picking up the default value from PostgreSQL's information_schema.columns table but erroneously thinks some things are strings. Here are the column defaults from one of my databases:

|table_catalog|table_schema|table_name|column_name|column_default|
:--|:--|:--|:--|--:|
|Alternate History|lawta|timeline_level1|border_rgb|NULL::character varying|
|Alternate History|lawta|timeline_level0|border_rgb|NULL::character varying|
|Alternate History|lawta|timeline_level1|border_shade|0.085|
|Alternate History|lawta|timeline_level0|border_shade|0.085|
|Alternate History|lawta|timeline_level0_borders|end_date|'2099-12-31'::date|
|Alternate History|lawta|timeline_level1_borders|end_date|'2099-12-31'::date|
|Alternate History|lawta|timeline_level1|feature_uuid|uuid_generate_v4()|
|Alternate History|lawta|timeline_level0|feature_uuid|uuid_generate_v4()|
|Alternate History|lawta|timeline_level1_borders|feature_uuid|uuid_generate_v4()|
|Alternate History|lawta|timeline_level0_borders|feature_uuid|uuid_generate_v4()|
|Alternate History|lawta|timeline_level1|flag_url|ARRAY[]::text[]|
|Alternate History|lawta|timeline_level0|flag_url|ARRAY[]::text[]|
|Alternate History|lawta|timeline_level1|id|nextval('lawta.timeline_level1_id_seq'::regclass)|
|Alternate History|lawta|timeline_level0|id|nextval('lawta.timeline_level0_id_seq'::regclass)|
|Alternate History|lawta|timeline_level0|info_url|ARRAY[]::text[]|
|Alternate History|lawta|timeline_level1|info_url|ARRAY[]::text[]|
|Alternate History|lawta|timeline_level1_borders|main_rgb|NULL::character varying|
|Alternate History|lawta|timeline_level0_borders|main_rgb|NULL::character varying|
|Alternate History|lawta|timeline_level1|predecessors|ARRAY[]::uuid[]|
|Alternate History|lawta|timeline_level0|predecessors|ARRAY[]::uuid[]|
|Alternate History|lawta|timeline_level1|realm_uuid|uuid_generate_v4()|
|Alternate History|lawta|timeline_level0|realm_uuid|uuid_generate_v4()|
|Alternate History|lawta|timeline_level1_borders|start_date|'0001-01-01'::date|
|Alternate History|lawta|timeline_level0_borders|start_date|'0001-01-01'::date|
|Alternate History|lawta|timeline_level1|stripe_rgb|NULL::character varying|
|Alternate History|lawta|timeline_level0|stripe_rgb|NULL::character varying|
|Alternate History|lawta|timeline_level1|successors|ARRAY[]::uuid[]|
|Alternate History|lawta|timeline_level0|successors|ARRAY[]::uuid[]|
|Alternate History|lawta|timeline_level0_borders|type|'settled'::character varying|
|Alternate History|lawta|timeline_level1_borders|type|'settled'::character varying|
|Alternate History|lawta|timeline_level1_borders|visible|TRUE|
|Alternate History|lawta|timeline_level0_borders|visible|TRUE|

```
SELECT table_catalog, table_schema, table_name, column_name, column_default FROM information_schema.columns WHERE column_default IS NOT NULL and table_schema='lawta'
order by table_schema, column_name;
```

As you can see, default is in the form `'text here'::character varying` as one would expect in PostgreSQL. QGIS is incorrectly surrounding the `uuid_generate_v4()` with single quotes when it should just be leaving it bare.

Oddly, QGIS does not add erroneous single quite for `nextval()` type defaults of columns that are sequences.

QGIS should **not** be adding quotes to the column_default values obtained from the catalog as those values are **already syntactically correct** for the table & column' default value.

**Comment by CoryAlbrecht** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.22.3-Białowieża | QGIS code revision | 926f9dad44
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
QGIS3-getWKT | 1.4
geometry_paster | 0.1.1
postgisQueryBuilder | 2.0.1
ClipMultipleLayers | 3.2.0
cartography_tools | 1.2.1
bettereditor | 1.5.0
quick_map_services | 0.19.27
db-style-manager | 0.8
splitmultipart | 1.0.0
pg_raster_import | 1.0.10
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[926f9dad44](https://github.com/qgis/QGIS/commit/926f9dad44)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.3 LTS




This copy of QGIS writes debugging output.




Active Python plugins
QGIS3-getWKT
1.4
geometry_paster
0.1.1
postgisQueryBuilder
2.0.1
ClipMultipleLayers
3.2.0
cartography_tools
1.2.1
bettereditor
1.5.0
quick_map_services
0.19.27
db-style-manager
0.8
splitmultipart
1.0.0
pg_raster_import
1.0.10
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

**Comment by CoryAlbrecht** [comment]
@gioman

**Comment by gioman** [comment]
@CoryAlbrecht same comments as already left in the past: provide a sample, self contained projetc (with all the necessary data) and a clear set of steps to replicate.
