### ISSUE TITLE
form not loaded properly from qml file

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29944]
Author Name: **Robin Rotsaert** (Robin Rotsaert)
Original Redmine Issue: [22133](https://issues.qgis.org/issues/22133)
Affected QGIS version: 3.6.2
Redmine category:forms

---
when saving the form-information from one geopackage-layer as a qml-file and trying to load it to another geopackage-layer (both have some entirely equal columns) only the "general" form setup is loaded. The widget type isn't, the defaults neither (haven't checked on the constraints).

**Comment by RobinRots** [comment]
Hi,
See geopackage and qml in attachment. I created the qml from the layer "PercelenInBeheer" and wanted to load it to the layer "Planeenheden".

[database_beheer_0.2 - kopie (2).zip](https://github.com/qgis/QGIS/files/3227539/database_beheer_0.2.-.kopie.2.zip)

**Comment by gioman** [comment]
@RobinRots I see several attributes with widgets like date, value map and also some expressions in the default values. Please try master (I used master to test).

**Comment by RobinRots** [comment]
@gioman I can't get the master version to work :s gives me an errormessage which directs me to a file that's not there (see attached printscreen). 

I tried recreating the problem however in a new geopackage in QGIS 3.6.3 (see attached files) and found out the issue is only there when trying to load from a qml in which only the category "form" was saved OR when only loading the "form"categorie from a qml in which all categories were saved.
This could mean at least one of the other style-categories has to be saved along the form-category to make the form-category work... it's not clear to me however which one this could be.

![error_starting_QGISmaster](https://user-images.githubusercontent.com/51113882/58543342-95b7b900-81ff-11e9-8e12-cd99af32db7a.png)
[test_for_qmlissue.zip](https://github.com/qgis/QGIS/files/3231613/test_for_qmlissue.zip)

**Comment by alexbruy** [comment]
@RobinRots try to reinstall master and make sure that grass7 also selected and installed

**Comment by alexbruy** [comment]
Closed for the lack of feedback
