### ISSUE TITLE
Label panel wording for combo/expression box.

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#30159]
We currently have "Label with" as the start label for the combo for the drop down.  The wording here feels a bit off to me (although I think I wrote it originally) 

![image](https://user-images.githubusercontent.com/381660/59234990-948c8000-8c32-11e9-9bbc-dfe162772bf5.png)

We also don't use wording like this for symbols so might be best to pick a standard name and run with that for both panels

![image](https://user-images.githubusercontent.com/381660/59235014-bbe34d00-8c32-11e9-8583-b511c8e16dae.png)

**Comment by NathanW2** [comment]
@nyalldawson @nirvn feels on this one?

**Comment by nyalldawson** [comment]
Standardising would definitely be good. 

This reminds me -- does anyone else think these two combo boxes should default to the first entry? I hate teaching people labeling and explaining that changing from "no labels" isn't enough to make labels appear. I'd much rather default to either the first attribute here, or the "display name" field so that changing from no labels gives an immediate effect on the map.

**Comment by NathanW2** [comment]
I agree, Change to display name would work for me here.

**Comment by andreasneumann** [comment]
Display name field makes more sense to me than first column. It is quite typical that the first column is an id column (primary key) in a table.
