### ISSUE TITLE
Add a field for GeoJSON's RFC7946 layer creation option

### ISSUE THREAD

**Issue by dericke** [qgis/QGIS#30257]
Many applications (Mapbox, among others) will only tolerate RFC7946-compliant GeoJSONs, which requires the file to omit a CRS definition and assume an EPSG:4326 projection. 

OGR supports the creation of compliant GeoJSONs with the layer creation option `RFC7946=YES`. Though the user can presently use this option by entering it in the Custom Options panel while saving a GeoJSON, it would be helpful if it had a field in the Layer Options panel, below the existing `COORDINATE_PRECISION` and `WRITE_BBOX` fields. Adding this option as a field there would also allow a tooltip to be added, explaining its relevance.

**Comment by dericke** [comment]
I wrote what I *think* is the necessary change on [my fork](https://github.com/dericke/QGIS/tree/dericke-patch-1), but I'm not setup to build QGIS myself or run unit tests right now. Not sure how I should proceed here: should I wait until I have the time to build and test myself? Submit a PR and ask for help there? Something else?

**Comment by elpaso** [comment]
@dericke I may state the obvious but it's much easier/better if you can run unit tests locally on your development machine. Otherwise you'll need to wait until somebody else has time and will to run build your branch and run the tests for you.
CI platform Travis will also run all the tests for you when you make a PR, but that's very slow and an endless source of frustration, I couldn't really recommend that.

**Comment by rduivenvoorde** [comment]
I'm interested in this, will test and do PR to run the automatic tests.

**Comment by dericke** [comment]
Thank you @rduivenvoorde !

**Comment by dericke** [comment]
Closed by https://github.com/qgis/QGIS/pull/30272
