### ISSUE TITLE
Have the "Make Permanent" option on layers imported as CSV with geometry 

### ISSUE THREAD

**Issue by ChalktyGeo** [qgis/QGIS#30449]
The "Make Permanent" option when you right click on a temporary layer is really useful and saves time. It would be great if you had this option when right clicking on a layer which has been imported as a delimited text layer with geometry.

**Comment by roya0045** [comment]
That's exactly the same as exporting/saving it to anything, like a shapefile. I'm already surprised that the 'Make Permanent' button exist it the first place for anything.

**Comment by nyalldawson** [comment]
Actually make permanent is a little different, because it's designed to save a memory layer as a file, and then replace it in place with the path pointing to this file.

But otherwise I agree with @roya0045 here -- couldn't the normal export function be used instead for your use case?

**Comment by ChalktyGeo** [comment]
I guess you are right - although I still don't really see why the "Make Permanent" function for memory layers would be useful but not for a CSV with geometry.

**Comment by ChalktyGeo** [comment]
Happy for the issue to be closed though.

**Comment by nyalldawson** [comment]
Actually, I'm just a bit behind. I CAN see what you're aiming for here - a layer added via delimited text with "virtual" geometries only, converting in place to a real spatial layer?

**Comment by ChalktyGeo** [comment]
@nyalldawson that is exactly it - apologies if I was not clear. I just want it to be as easy as possible to convert it to a real spatial layer. I constantly forget to do this and then go to edit the layer which is not possible until it is saved.

**Comment by datapolitan** [comment]
+1 on this issue. I'm a long time QGIS user and just made the upgrade to 3.4. I loaded a CSV and projected it onto a map, saved the project, and then went to open the project back up to show my work to colleagues and the CSV file had "lost" the projection and wouldn't display on the map. 

I understand that the normal behavior *should be* that a user would save this as a shapefile after projecting the coordinates from a delimited file, but I don't remember it being the case in QGIS 2.x where failing to do so means the coordinates are "lost" in the file and it exists in the Layers panel as just a text file without coordinates. 

Either way, having the projected data live in memory somewhere associated with the file or automatically generating a shapefile or other spatial format associated with the project would seem a better option than requiring users to perform an additional step they're likely to forget. 

Also as a side note, it also doesn't seem possible to re-run the Data Source Manager on imported delimited files to project a file from the available columns. Again, this seems different from 2.x behavior where we could reproject coordinates from a delimited file. Happy to be proven wrong, but again, if you're going to enforce this process of saving to shapefile, it makes sense to allow users to re-run the Data Source Manager on a loaded file to project data or otherwise correct data layer issues that can't be done from the Properties dialog.

**Comment by baswein** [comment]
I also like the make permanent feature but because QGIS only tags layers produced by native QGIS algorithms as valid for make permanent (as far as I have been able to tell) I find myself wanting a different feature. Perhaps there could be a Save As And Replace Current Layer option either in the layer right click menu or as a checkbox in the save as dialog. I could see many uses for that beyond temporary layers.
