### ISSUE TITLE
CRS changing coordinates systems even though default is set

### ISSUE THREAD

**Issue by ZacMcC** [qgis/QGIS#30460]
I have my default project, new project, current CRS settings set for gda94/utm zone 50 (EPSG:3850) as this is the area I am working on and need to work in this coordinate system. I am dragging and dropping a shapefile of Australia into QGIS (have tried 3.6 and 2.18 for mac) and then I change the CRS of that layer to the crs i want. Both version of QGIS seem to want to always display the coordinates in lat and long rather than eastings and nothings. I need to export coordinate data from polygons and points etc to use in other software which requires eastings and northings (should be what EPSG:28350 provides). 

I started using QGIS 3.6 and noticed the issue and couldn't solve it. From research I thought I needed the 'on the fly' function so i download 2.18 and tried in that, to no avail. I know 3.6 has 'on the fly' on by default.
[Aust Map.zip](https://github.com/qgis/QGIS/files/3338333/Aust.Map.zip)
i have attached the australia shape file

What am i doing wrong?

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
> current CRS settings set for gda94/utm zone 50 (EPSG:3850)

28350, not 3850

>  I am dragging and dropping a shapefile of Australia into QGIS (have tried 3.6 and 2.18 for mac) and then I change the CRS of that layer to the crs i want

I can't see anything wrong with the attached data, see attached image. If you are changing manually the CRS of a layer in order to re project it then you are doing it wrong. In the layer project you always must see/have the real CRS of the layer. If you want reproject it on the fly you change the CRS of the project. If you want to create a copy of the layer with a different CRS you do "save as..." (among the many options to achieve the same result).

![Screenshot_20190629_182621](https://user-images.githubusercontent.com/1951107/60387502-1c301680-9a9c-11e9-8355-9312ef41b64e.png)

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
