### ISSUE TITLE
QGIS 3.4 LTR don't create Integer field

### ISSUE THREAD

**Issue by SSGoveia** [qgis/QGIS#30493]
QGIS 3.4.9 does not allow you to create field in the table as Integer, only Integer64 which causes errors in the use of processing toolbox algorithms even by checking in Create New Field Type as Integer.

**Comment by jonnyforestGIS** [comment]
Hi @SSGoveia  what is the Operating System?

Please give an example with the steps to reproduce this error?

I teste the creation of new fields with the type integer in a shapefile, geopackage, temporary layer and i can't reproduce your error.

Do you have a project example or a sample data?

Regards.

**Comment by SSGoveia** [comment]
I created random points and extracted the pixel value from the elevation raster (I used as output shapefile, Gpkg and temporary layer). When I tried to use SAGA's Minimum Distance Analysis tool it gives an error because the fields (id, elevation) are like Integer64.
I tried to create a new Field by the Field Calculator and set the Type to Integer, but then in the Layer Properties this new field is like Integer64 and the OGR only accepts Integer.
Also when I interpolate using rscripts from R Provider gives error because Field is (by default) as Integer64
Use Windows 10 64bits and standalone QGIS 3.4.9.

**Comment by gioman** [comment]
> I created random points and extracted the pixel value from the elevation raster (I used as output shapefile, Gpkg and temporary layer)

@SSGoveia what is the name of the tool you used to do the above operation?

> I tried to create a new Field by the Field Calculator and set the Type to Integer, but then in the Layer Properties this new field is like Integer64 and the OGR only accepts Integer.

can't confirm here (at least on Linux).

**Comment by jonnyforestGIS** [comment]
@SSGoveia assuming that you had the error in  SAGA's Minimum Distance Analysis, the problem is not in the file but the output. So I try to run this SAGA algorithm with a temporary result and give me as well an error to produce de output.

Then I check in the SAGA this algorithm with the same point vector data and I realise that the output of this tool is a table.

Back to QGIS again I've done the same tool in processing with the same point vector data but change the type of output form shp to .dbf and works fine.

Note: With integer64 fields
Tested in Windows 7 64-bits with QGIS 3.4.9 64-bits.
SAGA LTR 2.3.2 (bundle in OSGeo4W64

Can you test again?

**Comment by SSGoveia** [comment]
@gioman I opened the points shapefile attribute table, and in Field Calculator I had a new field, Integer. I saved the edits and I go to the Layer Properties in the Source Fields tab and the new Field appears as Integer 64. I'm running R scripts, and the fields must be of type Numeric. Fields of type Integer 64 are automatically converted to string.

> OGR data source with driver: ESRI Shapefile
> Source: "C:\Users\Sidney\QGIS\Brasilia", layer: "sample_points"
> with 200 features
> It has 2 fields
> Integer64 fields read as strings: id cota
> Error in hist.default(Layer[[Field]], main = paste("Histogram of", Field), :
> 'x' deve ser numérico (must be numeric)
> Calls: hist -> hist -> hist.default
> Execução interrompida

@jonnyforestGIS  You're right. When running the SAGA tool Minimum Distance Analysis gives error if I leave the temporary layer option (Table.shp). I switched to save in DBF format and it worked correctly.

Windows 10 Pro 64 bits
QGIS 3.4.9 with GRASS 7.6.1
SAGA  2.3.2 (64 bit)

**Comment by jonnyforestGIS** [comment]
@SSGoveia  from my tests this is how processing R provider deals with integer64. I think this is a "bug" from R plugin processing provider. R can deal with integer64 but we need to tell him otherwise e use the field as a string. 
I think you need to open an issue in plugin r processing provider.
I found this package [bit64](https://cran.r-project.org/web/packages/bit64/bit64.pdf) please check if help

@gioman  please correct me if I'm wrong.

**Comment by SSGoveia** [comment]
@jonnyforestGIS many thanks, I'll open another issue in plugin r processing provider.
