### ISSUE TITLE
Value Relation multi with GPKG string broken

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#30557]
**Describe the bug**
When we use the `allowMulti` function in the value relation widget and as data source GPKG with a string field we cannot store any values. The list is stored empty.
It used to store the list like this `{1,2,3,4}` in case it's a string and not a JSON field. Now it stores it as `QVariantList` what is a good thing, but if it does not converts it in the end (on Widget code) it tries to store it as JSON, what does not work.

**How to Reproduce**
- Create a Value Relation Widget with GPKG string field.
- Check some values.
- Store it. 
- No values stored (empty list `{}`)

**QGIS and OS versions**
Ubuntu and QGIS Master (3.6/3.8)

**Additional context**
Already had a talk with @elpaso about it. He has the opinion, that it should make such conversion on provider side. I agree on that, but for this case it does not work. Because in other situations, this conversion should not be done. The format `{}` what comes from an `hstore` format but is not, is only used for the value relation widget, and should only be done, when the values come from it (what the provider does not know).
He agreed that I bring the else clause back, converting to this formatted string. I will make some tests for it. 

I'll have a look on it next week.

**Comment by signedav** [comment]
Someone could assign me, please? :man_factory_worker:

**Comment by elpaso** [comment]
Some more thoughts on this: I have the feeling that the whole concept in https://github.com/qgis/QGIS/blob/master/src/gui/editorwidgets/core/qgseditorwidgetwrapper.h#L74 should be revised.

The rationale is that each provider knows about how to format a data type (list, hash, string, blob etc.) in a way that is compatible with it's storage depending on the underlying field type, I think that marshalling to a provider compatible format does not belong to the widgets.

There is another advantage in doing so: depending on the provider and field type, some data structure may loose precision, for instance an hstore can only store string values, while a JSON serialization can distinguish between strings, floats and ints.

Summarizing:
1. choose and stick to a common QGIS internal format for lists and maps (I would recommend `QVariant` List and Map)
2. always pass values to widgets as `QVariant` without marshalling to a QVariant::String
3. always return values from widgets as `QVariant` 
4. let the providers take care of the conversion from QVariant to the underlying storage format (depending on the field type) and vice-versa.

@m-kuhn @nyalldawson  what's your advice here?

**Comment by m-kuhn** [comment]
I have thought about this too for formats that don't support data types natively (e.g. shp). There are two questions which always remained open

1. How would a user configure these columns?
2. Where would we save the type information?

Number 1. will probably lead to more effort required in project configuration. And widget configuration is already quite complicated. Number 2. has no clear answer (the information will probably end up in the QGIS project file which is not necessarily where it best belongs too for portability reasons).

On the other hand, it would certainly be nice to have the provider already take care of the conversion so all other parts of the system can just consume typed information.

But for what I see, this system is not in place yet and someone will need to go the extra mile to put that in place and do the work on provider side. Until then I think it's reasonable to have widgets that support both: fields with type information and fields with just string. It's not blocking any low level work if that turns out to be required and the effort is an order of magnitude smaller and the path to go there well defined.
