### ISSUE TITLE
QGIS crashed on connecting external monitor

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#30621]
h2. User Feedback

connected external monitor

h2. Report Details

*Crash ID*: 46f8f6b4e23feddc9c0839a81ea03cc22d807958

*Stack Trace*
<pre>
WacomExtHook :
WacomExtHook :
WacomExtHook :
WacomExtHook :
WacomExtHook :
WacomExtHook :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> connected external monitor

@Komzpa sounds weird to me... it happens all the time?

**Comment by nyalldawson** [comment]
Crash is coming from a Wacom driver or utility. Maybe try using that?

**Comment by SirChasm** [comment]
QGIS is consistently crashing for me if I run it on an external monitor. It doesn't appear to matter that the monitor is connected, just that the actual UI is on that monitor. Since moving QGIS to my laptop screen (and other apps to the external monitor) it is behaving as expected. Of course thiis is a pain since I like to leverage the largest display for the map.

**Comment by SirChasm** [comment]
Well I stand self-corrected.. it's still crashing but less frequently not running it on the external monitor. btw I am running my own scripts (using the provided template) from within the Processing Toolbox.

**Comment by gioman** [comment]
> Crash is coming from a Wacom driver or utility. Maybe try using that?

Closing for the lack of feedback.
