### ISSUE TITLE
Focus attribute table item

### ISSUE THREAD

**Issue by pedr0H** [qgis/QGIS#30755]
Upon object selection it would be useful to have a matching focus on the corresponding attribute table, so it would be easier to introduce alterations to the selected attribute without having select the field that is highlighted.

**Comment by andreasneumann** [comment]
Can you be more specific? In the map you can only select a whole feature, not individual attributes. Also you can select more than one feature. How would you focus on a specific attribute of a selected feature in the attribute table when you can't select attributes in the map?

**Comment by pedr0H** [comment]
Sorry, I didn't explain it well!
In the map you can select an object. If we have the attribute table opened it will show a yellow square on the selected object's id, but the object is not selected in the attribute table. We'll then have to select it in the table to manage its attributes.

**Comment by andreasneumann** [comment]
Ah - it sounds like you are in "form mode". The yellow box you mention is in the side column and is actually a checkbox which allows to select features in form mode.

At the bottom right you can switch to table mode. In table mode, selected features appear in blue, with white text instead of black text.

Of course selections in the table (both form and table mode) and in the map are synchronized. It has been like this since more than a decade or so.

Perhaps what you want is, that the selected feature is automatically scrolled into the visible area of the attribute table. For single features, this would probably work. But what happens if you select multiple features?

What you could do is filter the table to only selected features: bottom left of the attribute table allows you that. Just switch to "Show selected feature" then all other non-selected features are hidden.

**Comment by pedr0H** [comment]
All right! That functionality solves the workflow problem I was having, and really my suggestion would be just redundant.
Thank you!

This is outside of the topic, but is there a way to add a legend layer outside of the map creator?

**Comment by andreasneumann** [comment]
> This is outside of the topic, but is there a way to add a legend layer outside of the map creator (composer)?

Add a legend layer? Can you define "legend layer"? Where do you want to add it? In the layout component (former print composer) there is a legend item. But other than that I don't know any.

Of course the layer tree panel also contains a legend and allows to toggle visibility of individual categories or rules.

**Comment by pedr0H** [comment]
I meant as a single layer that displays on the work area map, but sticks to a fixed position. This way we could navigate the map while having the legend as reference (it could be a "fixed" raster image). 

Maybe it could make it easier to interpret some old raster maps with a lot of color-coded categories (like high definition soil maps)

**Comment by andreasneumann** [comment]
Ah I see. These are called "decorations" in the QGIS terminology. Examples are: Copyright, North-Arrow, Grid, Label, etc. See menu "View" --> "Decorations"

We don't have a decoration for legend images. You can open a feature request for that, but given that the legend can be easily shown and depicted in the layer panel, I am not sure how much pressure there is to implement a decoration for legends. But who knows ...

**Comment by pedr0H** [comment]
Yeah, it would only be useful to work along with raster maps, specially old ones...
I'll suggest it, maybe someone feels it would be useful.

Thank you!
