### ISSUE TITLE
Decorations for raster images

### ISSUE THREAD

**Issue by pedr0H** [qgis/QGIS#30769]
The idea would be to add another option for decorations that would be able to insert any raster file.

This would also enable the display of raster-based legends that can be used for readability of old digitalized maps, and improved Qgis for the vectorization and data organization of raster source material.

**Comment by AlisterH** [comment]
As a workaround it is possible to embed a raster in an svg and add it as a north arrow. 
I think it pads to make it fit in a square though.

**Comment by andreasneumann** [comment]
@pedr0H - are we talking about static raster files (e.g. png/jpeg) that are on the filesystem and should be displayed statically in some decoration?

**Comment by AlisterH** [comment]
> As a workaround...

Or of course just open it in another program.  Why do you particularly need it to display in QGIS itself?  Do you have lots of people working on lots of different maps, and you need anybody to be able to open a random project and see the legend?
Rather than displaying it as a map decoration it would make more sense to me to display it in a panel.  I guess it would be pretty easy to code a plugin to do that, too.

**Comment by pedr0H** [comment]
@AlisterH for the legend use a side panel would work well.

@andreasneumann yes, a static raster file displayed statically.

**Comment by nirvn** [comment]
This has been implemented and will be available in QGIS 3.10 (end of October 2019). In the meantime, it's already available in development weeklies.

**Comment by AlisterH** [comment]
> This has been implemented
For anyone looking for it, it was implemented as a decoration, as per the original suggestion.

A future improvement someone might want to look at would be allowing to specify size in a more intuitive way e.g. pixels or percentage.  With a raster I would say you typically want to display at 100%.

**Comment by AlisterH** [comment]
> > Anyway, rather than displaying it as a map decoration it would make more sense to me to display it in a panel. I guess it would be pretty easy to code a plugin to do that, too. What do you think?

> @AlisterH for a raster legend use a side panel would work well!

I've realised that the Qweb plugin is actually perfect for this.  You can just drag and drop images into it.  

If you need to look at more than one image at the same time I guess you'd need to put them in an html file, but otherwise you can switch between them with the back/forward buttons, or by using more than one tab.

I believe in theory it would work for PDFs and things too, using npapi plugins, at least if QTWEBKIT_PLUGIN_PATH is set properly.  But it didn't work for me using the foxit plugin.
