### ISSUE TITLE
Rasters inside a GPKG do not show in DB Manager

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#30932]
The subject says it all, it affects 3.4 and 3.8 and master (and probably also 2.18 from what I remember). Supporting them is really a necessary step to make GPKG the first class citizen we want GPKG to be in QGIS (also is not consistent with other supprted DBs in DB Manager, like PostGIS).

**Comment by AlsumDea** [comment]
tks!

**Comment by nyalldawson** [comment]
Is this necessary? They are shown in browser, and I can't see a compelling reason why they'd need to be exposed in db manager too..

**Comment by andreasneumann** [comment]
Strange - I can see rasters in the DB-Manager and preview them, but I can't delete or rename them.

**Comment by andreasneumann** [comment]
Also not in browser. Removing a raster layer in a geopackage in browser fails for me.

**Comment by gioman** [comment]
> Is this necessary? They are shown in browser, and I can't see a compelling reason why they'd need to be exposed in db manager too..

yes, is necessary. Is a matter of consistency, making gokg a full first classe citizien in QGIS and also because DB Manager is a proper work tool that allow you do more that just adding layers (i.e. running queriesI.

**Comment by nyalldawson** [comment]
> running queries

I might be mistaken, but I don't think gpkg has any support for querying on raster layers. 

And from browser rasters can be added, removed, and renamed. Not sure what else would be required...

**Comment by gioman** [comment]
Is there a clear path/plan to merge the browser and db manager in one unique tool (that aggregates all the functionalities of both)? if not I don't think is optional to not fix db manager: despite its several issues is a much richer tool compared to the browser. It allows preview the data, check the tables structures permissions, create tables from scratch, just to cite a few things.

Not showing data inside a GPKG datasource (by the way, also GPKG vector views are not shown in DB Manager) could lead to share data that is not supposed to be shared, which of course is not nice.

**Comment by nyalldawson** [comment]
> Is there a clear path/plan to merge the browser and db manager in one unique tool (that aggregates all the functionalities of both)?

Ultimately the goal is to move all db manager functionality into browser, and remove all the custom code which db manager is using to do the database operations and replace them with the standard QGIS c++ implementations (which @elpaso has made huge progress with recently!). Through this approach we gain:
- dropping lots of duplicate Python code, which isn't covered by unit tests and is frequently regressing, replacing it with c++ versions covered by unit tests, protected by c++ compile time errors, and subject to the same stable API contract which the rest of core QGIS is.
-  removal of duplicate UI which behaves differently and has different functionality depending on which part of QGIS you trigger the action from
- everything is inbuilt into the one dockable panel, instead of a separate window

So, yes, the ultimate goal IS a single unified tool which includes ALL the functionalities of both, and work is actively underway to make this a reality.

>despite its several issues is a much richer tool compared to the browser.

Agreed in some cases, but we've also got the awkward situation that browser exposes MUCH more functionality in general (e.g. drag and drop management of layers between different files and providers, management of file based databases without having to create connections to them, background population of tables and schemas, also management of non db sources like shapefiles, wms, wfs, etc...). Ouch!

> It allows preview the data

So does browser

> check the tables structures permissions

missing from browser, for non disk-based formats. 

> create tables from scratch

so does browser

**Comment by gioman** [comment]
> > It allows preview the data
> 
> So does browser

it "opens" always completely hidden on my working pc that I forgot about that, sorry

> > create tables from scratch
> 
> so does browser

not for PostGIS or Spatialite, it seems

**Comment by arne1921KF** [comment]
> Strange - I can see rasters in the DB-Manager and preview them, but I can't delete or rename them.

@nyalldawson , I think this is an issue. Users expect the data base manager to be able to show and manipulate all data. 
I, for one, expected the manager the better place to add and delete data (i.e., layers) to a geopackage and was very surprised I could not delete raster data there (without any prompt, BTW: delete, rename and add to canvas are given as options on right klick, but delete has no effect.

@andreasneumann, deleting rasters from the browser seems to work for me. Running 3.14.1 (code revision de08d6b71d) on W10,

**Comment by gioman** [comment]
@arne1921KF DB Manager is unfortunately riddled with more or less serious issues. At some point we (the users and/or the project) must do something to get rid of it and complete the porting to the data source manager while fixing all the main issues along the way.

**Comment by gioman** [comment]
Does not seems to be the case anymore on 3.16.2
