### ISSUE TITLE
Loading too many features in attribute table

### ISSUE THREAD

**Issue by plutoscarab** [qgis/QGIS#31253]
## User Feedback

Crashed while I was loading a ridiculous amount of rows in Attribute Table. It crapped out at around 900,000 features from the Geonames gazetteer dataset (http://download.geonames.org/export/dump/allCountries.zip).

## Report Details

*Crash ID*: ffc485992db59bda633a330389c3d8b52f05270c

*Stack Trace*
<pre>
VSICreateCachedFile :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment]
> Crashed while I was loading a ridiculous amount of rows in Attribute Table. It crapped out at around 900,000 features from the Geonames gazetteer dataset (http://download.geonames.org/export/dump/allCountries.zip).

It also brings a high end workstation to a complete freeze when opening the table after having imported the dataset into PostGIS.

900k is not a "ridiculous amount" in my opinion, nowadays is quite common to need to work with very large datasets and I think I will not offend anyone when I say that working with such amount of data in the QGIS table of attributes in QGIS has been historically very bad. Is also known that the developers say that the underlying code is not quite good. At some point I think that as project we should face this issue and define what are the necessary steps (and resources) needed to improve the situation.

**Comment by stelf** [comment]
QGIS is for some while in use at Sofia/Bulgaria/ Municipality's organization for planning and under my advice they are moving hundreds of layers in QGIS, some featuring 200-300-400k elements. While most smaller sets (less than 100k) are stale bigger ones tend to bring the system to a halt, or just crash/close QGIS. And yes, in 2019 it's not big data to have some million rows in a table. It's 10TB what people consider big data.

IMHO A much wider discussion is needed reg. how to offload as-many-as-possible operations to the DB when ST-enabled DB is the source for the layer, as this will greatly reduce CPU operations and backends are really optimized for large data-sets.

**Comment by elpaso** [comment]
The attribute table issue with big tables is a well know longstanding issue, a deep refactoring of the code is required.

**Comment by roya0045** [comment]
@elpaso for validation, [this is where the features are loaded](https://github.com/qgis/QGIS/blob/95073f9a1edbf94e774fdecdea12fd770eddc3e8/src/gui/attributetable/qgsattributetablemodel.cpp#L457)  after each column in populated by LoadAttributes() ?

**Comment by elpaso** [comment]
Yes, but there are a lot of other parts involved (the `QgsVectorLayerCache` cache is one of those).
Then there is the filter model and the dual view that makes it more complicated.

**Comment by roya0045** [comment]
@elpaso could it doable to simply show the first X row of the table and then add the next X row when the users scrolls lower down. And otherwise add a "Show all features" button.

That way we could drastically improve the time needed to populate and we don't need to bog down the whole app when someone wants to add a column ( there is often no need to repopulate the whole table since the user would most likely just validate the first few rows or outright close the table.)

I'm sure there is someway to fit all this in. I am assuming that in regards to the filtering it only alters the FeatureRequest (which could also be improved with the ability to stack filters in the request to speed up provided fetching on a subset of features ;) ;) )

I'm not too familiar with the dual view and the layerchache otherwise but I assume that this approach would be quite doable without major refactoring.

**Comment by roya0045** [comment]
@elpaso I can make a prototype if you want, but I'm not sure when I'll get around to test it.

**Comment by gioman** [comment]
> ould it doable to simply show the first X row of the table and then add the next X row when the users scrolls lower down

yes, that would be very welcome (and it is indeed the strategy used by another well-known GIS software).

semi-related: also in db manager table preview never show more than a few hundreds of rows, as it is a preview there is no need to show the whole thing.

**Comment by gioman** [comment]
> The attribute table issue with big tables is a well know longstanding issue, a deep refactoring of the code is required.

maybe the upcoming dev meeting is the right occasion to start discuss this long-standing issue? As we know it will need a lot of effort and so it would be needed the project to step in (i.e. skipping one or more rounds of grants and using that money to solve this problem).

**Comment by Pedro-Murteira** [comment]
I've tested this issue on QGIS 3.22.3 (Windows 10). I was able to load all 12 276 028 features, although it took a while, as it is expected. But I was unable to reproduce a crash.

**Comment by gjsa73** [comment]
This is a real issue.  And should not be closed.  It is an absolutely fundamental/basic requirement that QGIS can open an attribute table without the entire application freezing for minutes.

One of the frustrations with QGIS is the flurry of activity constantly releasing new versions and adding new features, but basic operational capability like this is ignored because it would take months of work.

I dearly wish dev priorities would equal a freeze on efforts to develop and release new features until basic issues like this are resolved.

There are a few questions I would pose to reopen this for further discussion:
1.  Large tables do open in postgres eventually, but they take longer to open than loading the entire dataset into the canvas. Surely loading ALL the geometries is more complex than loading all text attributes into memory, and yet it completes quicker AND it doesn't grab the entire UI while doing so?  This is strange and suggests that there is an optimization that may be possible without taking months of work.
2. Loading the attribute table of a large WFS layer is currently pointless.  It doesnt matter if you are zoomed in or out and have the option ticked in the WFS connection to only load features in the layer extent - QGIS freezes and the only current option is to kill the app and start again without trying to do something the application isn't capable of doing.

If there is no alternative but to refactor code in a major development effort to fix the issue, is there any possibility that loading an attribute table could be made a background process?  It may be tolerated if people can continue to work while the entire attribute table is loaded in the background.

**Comment by stelf** [comment]
I've been following this issue for years, even though I stopped doing work with GIS for some time, but now we are teaching GIS in Sofia University, so QGIS is again a tool we showcase. And one thing I tell my students (as information architect) and tell you here also:

stand back and think about this omnipresent bias which transcended into digital maps from the classical cartography - to want to have everything shown, all layers, all details, etc. this works for printed maps and people take years learning how to show and discern dozens of layers on top of each other. but in the digital age this is pointless for few reasons:

- you cannot tell the data is correct by just looking at it. the visual aid is just aid, our exact tools are algorithmical
- the data you see IS INCORRECT by definition, because it was rasterized and downgraded to fit 'that-many-pixels'.
- your mind cannot comprehend 100k polygons or 10k or...1000 and tell whether they are correctly rendered
- you only need correct view when you zoom to reasonable number of shapes. 
- you are not interested in looking at table with more than dozen columns and more than hundred records. you are going to use some kind of Search/Filter/Order if the data is big - never going to browse pages or want to see it all at once
-
even though QGIS has this option to skip stuff which renders to few pixels, it still moves all the data around.

why am I writing this - because the above bias, once and for all, has to be eliminated from the design of GIS tools. period. and QGIS can be a pioneer in doing so, because ESRI also has a lot of design decisions done as result of this bias.

and this bias, sorry guys, this comes from a lack of understanding how underlying systems work, where the data resides, etc. and I don't mean dev's lack of sight, but the community, the crowd of architects, landscapers, urban planners, etc - everyone in this crowd shares this bias, because they still get educated by ppl who were not savvy with digital maps at all.

as a sidenote - look at Google/Bing/whatever simplifying their maps before presenting them to the end-users. it is done to lower the cognitive load, and nobody cares or (can verify) the exactness of the data shown. because maps are this - maps of multi-tiered data into concrete domain of a 2D space. 

maps are not the data itself, we should stop trying to do them 1:1

**Comment by saberraz** [comment]
This is an ongoing issue and required substantial work which does not fit in QGIS bug fixing.

**Comment by theroggy** [comment]
> This is an ongoing issue and requires substantial work which does not fit in QGIS bug fixing.

I can understand that, but it is a pity that there doesn't seem to get a workaround implemented either, e.g. #37510
