### ISSUE TITLE
Counting feature slows down loading a project

### ISSUE THREAD

**Issue by MMR100** [qgis/QGIS#31570]
My project has around 40 shapefiles and takes time to load. 
I can see at every launch a blue banner stating that "Task failed: counting features in xxx.shp " and 11 more. 
For some of these layers, I previously counted the number of features, for others I never activated the counting. 
For any layer, I switch off the features counting before saving my project. 
Then it should not count the features at every start. I think this is slowing down the project loading.

**Comment by roya0045** [comment]
If you create a similar project with the same layers and nothing else done. And then reload the project, does it still behave the same?

Also what version are you using?

**Comment by MMR100** [comment]
I am using QGIS 3.8.2
Contrary to what I said in my first message, the blue sign now says " Task complete: conting feature in XXX .shp" (after I close QGIS and restarted my computer, it seems the "task failed" message has stopped). 
However it is still counting features. 
I made a copy of my project and saved / reopened it removing one by one the features and I realise the counting tasks is coming from composers and / or from the layers.
The project has been initially created with QGIS 2.18 and has been transformed into *.qgz. 
Maybe the feature counting is linked to this?

**Comment by roya0045** [comment]
I was also assuming that the counting was triggered by something that depended on it. Otherwise feature counting does not occur needlessly. If you have something like aggregate expressions, it is possible that feature counting need to be performed at each start in order to properly evaluate the expression.

Was I was asking about in my previous post was to start with an empty project and add the same layers that you have within your other project. No counting should occur as nothing depend on feature counting and this will prevent this issue.

I don't think transferring a project from 2.x to 3.x would add counting triggers in itself.

**Comment by Pedro-Murteira** [comment]
@MMR100 Hello, I've tested this issue but I can no longer replicate it on QGIS 3.22.3. Did you come across this issue in more recent versions of QGIS?

**Comment by MMR100** [comment]
@Pedro-Murteira I no longer faced this issue during the last months, I guess this has been solved with QGIS upgrades. 
Maybe we should close this thread.
