### ISSUE TITLE
QGIS Server - Download of capabilities failed: SSL handshake failed

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/QGIS#31675]
I have this problem with QGIS-SERVER 3.4.11 on a Ubuntu 18.04 linux server-

I use a https url for a WMS on my QGIS project. It works correctly and I can see all the layers of the WMS service

WMS URL (with https):
https://mappe.comune.genova.it/geoserver/wms?service=wms&version=1.3.0&request=GetCapabilities

Nevertheless when I use the project on QGIS Server it do not works and I see the following error:

QGIS SERVER LOG:

```
10:36:38 WARNING WMS[31162]: Download of capabilities failed: SSL handshake failed
10:36:38 CRITICAL Server[31162]: Layer(s) BACINI_IDROGRAFICI_a99b6847_544c_44f2_8d46_4f51fb97b650 not valid
```

I do not test directly on a QGIS 2.18 confiuration, but as you can see in this lizmap issue (https://github.com/3liz/lizmap-web-client/issues/1316) people do not encountered error using qgis server 2.18.

**Comment by elpaso** [comment]
I cannot reproduce this issue on Linux 18.04 with QGIS Server Master

I tested it on two different machines:
- my dev machine with Ubuntu 18.04.03
- a VM built from scratches with 18.04.03

 tested only layer "SFONDO CARTOGRAFICO COMUNALE (GRUPPO)" but I guess it does not matter which layer you test

Can you please test the latest QGIS master version and confirm that the issue is only with 3.4?

You can find deployment recipes here in case you need them:  https://github.com/elpaso/qgis3-server-vagrant/tree/master/provisioning

**Comment by groschialeux** [comment]
I run qgis-server 3.4.12 on a Ubuntu 18.04 server and also a Linux Mint 19.02  desktop.

After upgrading qgis-server from 2.18 to 3.4.12 on both machines I started having the same SSL issue on the server but not on the desktop.   I am not talking about qgis desktop here, I mean running qgis-server and apache2 on the desktop linux.

The fact that it worked on the desktop but not the server lead me to think it was nothing more than authentication issue and I just found out I was right.

The qgis-server fcgi program did not have write permissions to qgis-auth.db.  I must have done a chmod on it by mistake at some point.   After "chowning" it back to www-data:www-data (apache2 user) the problem was fixed.

So the bottom line is qgis-server 3.4.12 has no problem connecting to a WMS/WMTS that is served on https as long as it can update the qgis-auth.db file.

@rmarzocchi84, check what user:group owns this file on your server, maybe you have the same problem I had.

**Comment by rmarzocchi84** [comment]
Thanks for your answer @groschialeux 

I do not use the qgis-auth.db file because I never understood the usefulness of this file so I commented the line in apache configuration file

```
#FcgidInitialEnv QGIS_AUTH_DB_DIR_PATH "/home/qgis/qgisserverdb/"
#FcgidInitialEnv QGIS_AUTH_PASSWORD_FILE "/home/qgis/qgisserverdb/qgis-auth.db"

```

I can uncomment the lines (changing the path) anyway how can I create the qgis-auth.db file and what is the use of this file? If I understand it I can try to explain better in the qgis manual

**Comment by elpaso** [comment]
> Thanks for your answer @groschialeux
> 
> I do not use the qgis-auth.db file because I never understood the usefulness of this file so I commented the line in apache configuration file
> 
> ```
> #FcgidInitialEnv QGIS_AUTH_DB_DIR_PATH "/home/qgis/qgisserverdb/"
> #FcgidInitialEnv QGIS_AUTH_PASSWORD_FILE "/home/qgis/qgisserverdb/qgis-auth.db"
> ```
> 
> I can uncomment the lines (changing the path) anyway how can I create the qgis-auth.db file and what is the use of this file? If I understand it I can try to explain better in the qgis manual

https://docs.qgis.org/3.4/en/docs/user_manual/auth_system/auth_overview.html#authentication-database

**Comment by groschialeux** [comment]
@rmarzocchi84, you don't need to create the file, qgis-server will do it.

**Comment by rmarzocchi84** [comment]
done and effectively it works @groschialeux
