### ISSUE TITLE
[layout] Unexpected result when adding expression to legend items label

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31761]
The attached screenshot shows the same expression applied to a single symbol rendered "buildings" layer and a categorized "Restaurants" layer. I think something is no coherent in the result but  can't tell since I'm only trying to understand the logic behind the tool.
![image](https://user-images.githubusercontent.com/7983394/64904926-71f68100-d6d1-11e9-9901-3151565c8ea7.png)

Long story:
1. Add a legend item to a map layout
1. In the 'Legend items' section, select a layer (I tested with a single symbol rendered layer named "buildings") 
1. Click the "Add an expression to the vector layer and each child symbol's label" button
The expression dialog opens with a variable `@symbol_label` already entered. 
If I OK the expression dialog with the following expression in the field 
   ```
   'test ' || @symbol_label
   ```
I'd expect the legend to display `test buildings` and not `buildingstest buildings` (as shown in the item properties) nor `buildings` (as shown on the map). 

If the symbol_label has to be at the beginning (which is a bit restrictive imho), then I think the button label should use "Append" and not "Add" AND the expression dialog should not be prefilled with the variable.

Moreover, when applying the same expression to a categorized layer, the categories are correctly rendered, BUT the layer item keeps its original label. If the layer label is not supposed to change maybe should we review the button label (it currently implies it changes layer name AND symbol labels though it'd be only symbol labels)

master 3.9 cdd3a55e9e

**Comment by nyalldawson** [comment]
I agree - this logic needs to be rethought. @nirvn?

**Comment by roya0045** [comment]
Thanks for the feedback @DelazJ ! I agree that the single layer display seem to have some issues.
The symbol label can be anywhere. I'm just not sure what happened with the building layer.

And as far as the layer itself keeping it default name this is normal since the main layer doesn't have a symbol associated with it anymore, it has a group of symbols.

**Comment by roya0045** [comment]
As for the first layer the expression seem to have been appended to the current layer, and only the original string is displayed. 
The behaviour is caused by the fact that the label is empty, this causes a temporary label to be assigned. Since this temporary label doesn't replace the mlabel variable, is it not displayed in the legend.
If you change the default name of the  `building` layer in the legend, does it behave correctly?

the "issue" should come from there:
https://github.com/qgis/QGIS/blob/738ced64883b721138c749f0c18d099a5476a621/src/core/layertree/qgslayertreemodellegendnode.cpp#L695

This can be fixed easily but I implemented this check to be safe and not replace data needlessly.

**Comment by roya0045** [comment]
Also the logic was to be able to evaluate expression from a script, catch the result and not alter the layout. Though the label check might not be optimal.

**Comment by roya0045** [comment]
Ah and also, the label check was also instored in case users wanted to simply code an expression without the expression builder. Since Nyall implemented expression evaluation in the legend I made this bypass if a user had an expression, this was also meant to not replace the user defined expression.

And yes somehow [I decided to provide the layer name as a label here](https://github.com/qgis/QGIS/blob/248af94ba996ca80152b4e0556f2d07737c25f0c/src/core/layout/qgslayoutitemlegend.cpp#L944)

I assume that a fix on that line by simply removing the label input should be sufficient for a quick fix.

**Comment by roya0045** [comment]
The fix is pending approval and merging. This should make the evaluation on the layer than have only one symbology act like multi-symbology layer.

**Comment by roya0045** [comment]
@nyalldawson @DelazJ @nirvn are you guys ok with the proposed fix?

**Comment by nirvn** [comment]
I haven't followed the development of this feature too closely, can't offer useful opinion ATM.
