### ISSUE TITLE
Dialog windows are too tall for some screens, rendering them unusable

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#32021]
**Describe the bug**
An almost fatal UX problem just occurred in a QGIS workshop I was helping with.
The machines had a resolution of 1366x768.
This made several windows (I remember the Options and IIRC the CRS dialog) unusable for the participants as the "OK", "Cancel" control buttons were outside the visible display area.

The workaround was to resize the window from the top and then dragging it up until the buttons were visible. This is not what a user should have to do (and it took me a while to even think of as a workaround).

**How to Reproduce**

1. Set your monitor resolution to have a maximum of 768 pixels of height
2. Start QGIS with a clean profile
3. Enter the options
4. Notice that you cannot see the "OK" and "Cancel" buttons.

Please make sure that  by default no dialogs are set to a vertical height that is leading to this problem on a fresh start with a default QGIS installation.

**Additional context**
QGIS 3.8 on Windows

There was a report for the Layer Properties dialog at https://github.com/qgis/QGIS/issues/28153 but the user decided it was a non-issue. I disagree! >:)

A vertical resolution of 768 pixels is still very widespread. The Steam hardware survey (for gamers!) shows almost 12% of their users with 1366x768.

**Comment by kannes** [comment]
If you tell me what to grep for, I could try to compile a list of code changes and _maybe_ even manage to do a PR.

**Comment by andrekis** [comment]
this problem still hapens as today. New Qgis 3.16.16 instaled today. Resolution 1366x768. On new project, tried to set crs, but ok and cancel buttons down show. Had to move windows 10 taskbar to left (vertical) to see the buttons.
Thanks.

**Comment by mcingotti** [comment]
This problem happens today in ltr version 3.22.4 on a screen 1366x768

**Comment by kannes** [comment]
Please open new issues where you mention the exact dialogs were this occurs. My issue was titled a bit too broadly back then.

**Comment by kobus7z** [comment]
Don't know if it's related, but the project properties dialog window also opens too large / long for me on 3.22.1 & 3.28 (laptop1366x768 screen). You cannot view or use the save, cancel or ok buttons. You can grab and move it down, you can resize it horizontally but if you try to resize it vertically down, then the dialog box collapse to the bottom and you can not click on the QGIS user interface (bell ring), unless you press Escape. Otherwise QGIS become unresponsive. Anyway, it seems to only happen when I have the QField plugin installed. If QField uninstalled, QGIS project properties dialog box seems to be fine: size is in view, can be moved & resized, buttons used etc.

**Comment by elvilanova** [comment]
I confirm that if QField is uninstalled, QGIS project properties dialog box is fine, buttons can be used. But if QField plugin is installed QGIS project properties dialog box goes bellow the screen and the buttons are hidden away.
Currently I'm on a linux laptop machine and my screen resolution is 1600x900
