### ISSUE TITLE
[Expression]to_date function and example seems broken

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#32027]
The screenshot shows the example in the function help.

![image](https://user-images.githubusercontent.com/7983394/65707333-9d437d80-e08c-11e9-912e-51cbe3a3bcaa.png)

Trying without the format parameter does not help. Trying with a valid date and another type of date format neither helps 
master 3.9 ea7b27ef

**Comment by nirvn** [comment]
@DelazJ , is your OS locale English or French?

**Comment by DelazJ** [comment]
French

**Comment by nirvn** [comment]
Ah, voila ton probleme! :wink: 

The underlying Qt function used to convert a formatted string into a date relies on your system locale. 

I see one issue here, and one implementation gap:
- By default, the function should rely on the QGIS locale instead of the system locale (I assume you have manually set your QGIS locale to English)
- I wasn't sure it'd be needed, but evidently it does: the function needs another parameter to define the locale used to convert the formatted string. I.e. to_date('24 Janvier 2019','d MMMM, yyyy','fr')

**Comment by alexbruy** [comment]
Seems fixed with #32908

**Comment by Carolinah23** [comment]
Hello all, I just had the same problem, I tried to add the language and it does not work. Is there any other problem that I am not considering? I also tried en, EN, and ENG. I also changed the single quotes to double quotes in the field name ("Origin_dat") but nothing seems to work...
Any help is appreciated
![image](https://github.com/user-attachments/assets/f0f2f68b-297a-4c1a-a30b-bb81ddfe67d1)

**Comment by DelazJ** [comment]
> and it does not work.

Ideally you should explain how it doesn't work, what wrong output you get.
Anyway, based on your data preview, I think the correct expression would be `todate("origin_dat", 'M/d/yyyy', 'en')`. Your months and days do not have a leading zero,  please read about the formatting syntax in the format_date function help or the Qt doc mentioned in to_date function help.
