### ISSUE TITLE
Resurrect HTML formatted labels

### ISSUE THREAD

**Issue by nextstopsun** [qgis/QGIS#32098]
I'm sure a lot of people trying to format complex labels (multiline/bilingual/etc) would love to see [#2856](https://github.com/qgis/QGIS/pull/2856) merged. Any plans for giving it a try @NathanW2 @nyalldawson ?

**Comment by nyalldawson** [comment]
I've looked into this, and a different approach to #2856 is needed. It needs sponsorship to become reality though.

**Comment by huber-j** [comment]
HTML formatted labels are the top missing feature in QGIS for our work, so we would really like this to become available. Could you give a rough estimate on how much funding would be needed? Maybe this would be a good candidate for a crowdfunding campaign.

**Comment by nyalldawson** [comment]
@huber-j Can you please send me an email to nyall@north-road.com ? I've previously written up specifications and pricing for the approach we need to take to move this forward and can provide this to you.

**Comment by antoniolocandro** [comment]
I was looking into this today, I think it would be worth it to have a crowdfunding campaign as this is one needed feature  for many cartographic outputs

**Comment by huber-j** [comment]
@antoniolocandro I had a conversation with @nyalldawson about this with the result that there are basically two different use cases regarding HTML formatted labels:
- "Ordinary" text labels usually consisting of a single line of text. These will sometimes be curved and of course it would be nice to have the ability to use text formatting (HTML or some simple markup language) for this kind of labels. These could best be implemented in the QGIS labelling system step-by-step (Nyall suggested to start with color since it does not affect the shape of the text, then add others like bold, italic etc. as required).
- Labels with more complex formatting (multi-line, simple tables) which usually only apply to points or polygons, requiring no curved alignment like line labels. These could be implemented by a plugin which either directly renders the HTML data or which uses an external renderer and passes the resulting graphics object on to the labelling engine for placement.

I agree that a crowdfunding campaign would be a good approach here, but it would be important to decide beforehand what types of HTML-based labels should be implemented (or both types, requiring more funding).

**Comment by davidlgalt** [comment]
In my use case, I am labeling cities from a point layer. The two parts of the multi-line label come from 2 different fields: name and population, with name on top in bold and population underneath with the standard font and reduced size from the name. These label pairs are further split into 4 classes based on size with major cities having a larger font size and small towns being the smallest. If due to scale a larger city's label collides with a smaller city the label for the smaller city is removed. This is achieved using the z-index.

Since we don't yet have HTML rendering, my workaround has been to use rule-based labeling with two separate labels for each feature. Name is placed in a position above the point and population is positioned below. The problem that arises in this approach occurs when one part of the label pair collides with a heavier Z-score label and is removed while the other part is orphaned. This is really awkward when it shows populations with no matching city.

I just wanted to describe my use case because I worry that the example above that imagines a plugin may not work with the z-score and I still wouldn't have a working solution to my problem.

In any case, I love/need this feature and I would happily toss in some coin (or bills) to help get it built.

**Comment by nyalldawson** [comment]
@davidlgalt Send me an email to nyall@north-road.com. I've previously specced out the changes required here and can fill you in on funding requirements.

**Comment by axyzdile** [comment]
I interested in ressurection of HTML formatted labels. Have some code skills and have some time for it. @nyalldawson can you help with overwiew of problem.  I think it would be worth it to have a crowdfunding campaign as this is one needed feature.

**Comment by nyalldawson** [comment]
@axyzdile thanks for the offer! I'll be submitting handling of colors from html formatted labels for 3.14 shortly -- I'd suggest touching base after this is done as it will give a good example of what's needed and the path forwards...
