### ISSUE TITLE
Value map Widget: add copy & paste functionality

### ISSUE THREAD

**Issue by saemiw** [qgis/QGIS#32256]
**Allow copy'n'paste from value map widget**
Under "Layer properties" > "Attributes Form" there is the "value map" widget. Sometimes you take a lot of time to fill in a long list of value-descripton pairs in the value map widget. It would be cool if this list could be copied to Excel (or any spreadsheet programm) with copy'n'paste: select all entries in value map widget -> ctr.+c -> go to spreadsheet programm -> ctr.+v -> save the spreadsheet if you like

I use QGIS 3.4.12

**Comment by jgrocha** [comment]
Hi @saemiw 

Thank you for you contribution. That is already implemented on QGIS. When you upgrade your QGIS, you will get the copy and paste working (from the value map table to Excel/LibreOffice).

![copy and paste value map](https://user-images.githubusercontent.com/163681/67636903-36082b80-f8cd-11e9-882c-e8607e78e584.png)

I didn't check when this was implemented, but since 3.10 is out, i don't think it will be backported to 3.4.

**Comment by m-kuhn** [comment]
Unfortunately this works unreliably

**Comment by jgrocha** [comment]
My fault: I just tested it on Linux. Thank you @m-kuhn for reopen and fixing it.

**Comment by m-kuhn** [comment]
@jgrocha even if you test on Windows, it works 50% of the times (first time I tried it did 100%) and I'm not able to even guarantee that it always works on Linux ...
