### ISSUE TITLE
Not possible to save edits using MySQL

### ISSUE THREAD

**Issue by mgi1972** [qgis/QGIS#32275]
Made a setup with mysql and qgis.
Connecting to mysql is no problem and adding data (points) in qgis is no problem. But when I try to safe the data the following error occured.
![qgis_mysql](https://user-images.githubusercontent.com/56634195/66912132-489f7c80-f012-11e9-9c68-689736f56dbb.jpg)
and I can't safe the data.

**Comment by delolmo** [comment]
I am having the same issue with QGIS 3.10 A Coruña. Has this been solved?

![image](https://user-images.githubusercontent.com/659868/75802719-772db200-5d7d-11ea-9284-08289ad28305.png)

**Comment by gioman** [comment]
> I am having the same issue with QGIS 3.10 A Coruña. Has this been solved?

@delolmo I would not have much hopes that there will be any development about MySQL support (well... at least there haven't been any for long time). It is a **much** better choice to just use PostgreSQL instead.

**Comment by delolmo** [comment]
The problem is that we already have a MySQL database for other business logic and we wanted our spatial features to be linked to that data. After giving everything a thought, we are going to use the [MySQL foreign data wrapper](https://github.com/EnterpriseDB/mysql_fdw) to access the tables we need directly from PostgreSQL.

However, @gioman, I don't understand why QGIS offers DB connections to MySQL if support is so limited. Maybe it would be a good idea to show some kind of warning saying that MYSQL spatial data is read only. Or maybe this issue (SRID = -2) is directly linked to some versions of MySQL and not to others. In that case, maybe the warning should only pop up with the unsupported versions. At least as long as this issue remains unfixed.

I honestly don't know the inner workings of QGIS, but it seems to me that the only problem is that QGIS is not processing the query for retrieving the SRID's correctly (`SELECT * FROM INFORMATION_SCHEMA.ST_SPATIAL_REFERENCE_SYSTEMS`). To me, being QGIS all about geographical information systems, it seems weird that this would continue to be an issue in the future.

@gioman, if you could point me in the right direction, I may give it a try to fix it myself.

BTW, thank you very much for all the effort of the QGIS team. I cannot stress enough how invaluable this software is for me and my company.

**Comment by nyalldawson** [comment]
QGIS uses GDAL directly for mysql functionality, so if there's limitations in QGIS' handling of Mysql tables it's coming from the GDAL driver.

You can read some of the limitations here: https://gdal.org/drivers/vector/mysql.html

**Comment by gioman** [comment]
@delolmo to complete Nyall answer: in QGIS there native providers for PostGIS, Oracle Spatial and MSSQL Server, but not for MySQL. Not sure about the reason, but my impression is that there is really not much interest in spatial data into MySQL.

**Comment by Pedro-Murteira** [comment]
@mgi1972 Hello, is this still valid in more recent versions of QGIS?
