### ISSUE TITLE
DB Manager error: column adsrc doesn't exist any more in PostgreSQL 12

### ISSUE THREAD

**Issue by KoponenJ** [qgis/QGIS#32321]
When executing raster query for PostGIS error "column adef.adsrc does not exist" is generated. This is because PostgreSQL 12 doesn't have pg_attrdef.adsrc column any more (?). From version 8 documentation:
"The adsrc field is historical, and is best not used, because it does not track outside changes that might affect the representation of the default value. Reverse-compiling the adbin field (with pg_get_expr for example) is a better way to display the default value."
From version 12 release notes: "Remove obsolete pg_attrdef.adsrc column (Peter Eisentraut)."

**Comment by NyakudyaA** [comment]
I have also seen this by just clicking on a vector layer .
`column adef.adsrc does not exist
LINE 8: adef.adsrc AS default_value,
^
`

I do not think this is a QGIS issue because the logs from PostgreSQL are showing me the following


![logs](https://user-images.githubusercontent.com/2510900/67273641-251b7c80-f4bf-11e9-8bb0-50202032f3a8.png)

There has been various issues linked to it in postgresql
https://www.devexpress.com/Support/Center/Question/Details/T818996/column-d-adsrc-does-not-exist-postgresql-12
https://github.com/docker-library/postgres/issues/616

**Comment by blackgis** [comment]
Any solutions to that issue? I just transfaired all from postgres 11 to postgres 12 and facing now the issue that qgis can handle  this from the browser tab but not from the db manager. Any solutions on how to fix it on the postgres side or does it need a fix in QGIS?

![Postgres12_QGIS310_issue](https://user-images.githubusercontent.com/7139491/68071115-6fcaad80-fd77-11e9-9796-9e1de3110257.jpg)

**Comment by ra-mcinnes** [comment]
I'm also having the same issue. The rasters seem to be correct in the DB but QGIS views them as tables rather than a raster. Additionally QGIS doesnt recognize all of the columns in the Postgres raster tables. Genuinely have no idea what the work around would be here.

**Comment by pcav** [comment]
A pretty serious issue. The PostGIS provider has to be upgraded.

**Comment by pcav** [comment]
I think also the Data Browser is not capable of reading the layers.

**Comment by elpaso** [comment]
Fixed by https://github.com/qgis/QGIS/pull/32684
