### ISSUE TITLE
"Plugin installed successfully" when it actually crashed during installation

### ISSUE THREAD

**Issue by sickel** [qgis/QGIS#32376]
I am developing some plugins. A few times when I am testing, I have managed to make a package with illegal python code. When I try to install it, I will then first get a message informing me about the error, then I am told "The plugin is installed successfully" although it has not been installed.

To reproduce - in any package, modify the main python file so that it is not runnable, make the packaged zip file(pb_tools zip) and try to install it from the zip file.

**Comment by alexbruy** [comment]
Actually plugin **is installed** and message is correct in this case. It **can not be loaded** because of error and this is completely different.

To verify you can restart QGIS and you will see same error message saying that plugin can not be loaded because of error in the code.

IMHO this can be closed.

**Comment by gioman** [comment]
Closing for lack of feedback. Please reopen if necessary.
