### ISSUE TITLE
Raster calculator crashes QGIS 3.10 when using numerical values

### ISSUE THREAD

**Issue by giswgjs** [qgis/QGIS#32477]
**Describe the bug**
When using an expression containg numerical values of the form "raster@1" + 1.0 or "raster@1 * 2" QGIS 3.10.0 crashes with a

![grafik](https://user-images.githubusercontent.com/17158239/67753789-95814b00-fa35-11e9-818a-97ee624be9ac.png)

Expressions like "r1@1" + "r2@1" are processed. In the current LTR (3.4.13) these
expressions are processed as expected, cp. https://gis.stackexchange.com/questions/340043/qgsrastercalculator-fails-in-standalone-python-application

**How to Reproduce**
Can be reproduced with any raster dataset.

**QGIS and OS versions**
QGIS 3.10 on Win10, seems a regression.

**Additional context**

**Comment by FelisPimeja** [comment]
Same problem. QGIS 3.10 on Windows 10.
Silent crash with no logs on simple:
```
("1@1" < 0.5)*0 +
("1@1">=0.5)*50
```
No problems on QGIS 3.9.0 though

**Comment by elpaso** [comment]
Can you try to switch OpenCL off, just to check if that's related?
Settings -> Options -> Acceleration

**Comment by elpaso** [comment]
Found a bug with OpenCL `<` operator.

**Comment by elpaso** [comment]
@giswgjs to be clear, I'm not sure I fixed the `"raster@1" + 1.0` issue because I could not reproduce it, the ptch is about `("1@1" < 0.5)*0` (the `<` operator).
If the original is still an issue, please attach a sample test data and the exact procedure to reproduce, I will try to reproduce it again if new details and samples are provided.
