### ISSUE TITLE
Outdated "Check version" box

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#32683]
In QGIS 3.10.0, menu Help --> Check QGIS version shows an outdated information
![image](https://user-images.githubusercontent.com/7983394/68291661-9dbb3500-008a-11ea-8205-a428affa2fd8.png)

**Comment by jgrocha** [comment]
Hi @DelazJ,

Thank you for pointing out. This information is outside the code. It is fetched from: [https://version.qgis.org/version.txt](https://version.qgis.org/version.txt)

![Captura de ecrã de 2019-11-09 11-10-32](https://user-images.githubusercontent.com/163681/68527681-96419900-02e1-11ea-8eca-859b67bb0fe4.png)

Since the version.txt was already updated, you will see the new information on QGIS:

![Captura de ecrã de 2019-11-09 11-05-49](https://user-images.githubusercontent.com/163681/68527686-a2c5f180-02e1-11ea-89cc-1306054f7a1d.png)

**Comment by jgrocha** [comment]
This is probably one of the many tasks that @jef-n does whenever we release a new version.

**Comment by DelazJ** [comment]
Hi @jgrocha 
A late reply... sorry. This issue was closed but it still occurs, as confirmed in #33494

**Comment by DelazJ** [comment]
Closing again since #33494 is tagged as fixed.
