### ISSUE TITLE
Python script with probable infinite loop crashing QGIS

### ISSUE THREAD

**Issue by TechGus** [qgis/QGIS#32721]
## User Feedback

Running a python script that might be getting stuck in a loop. No way to break the process without crashing the software.

## Report Details

**Crash ID**: [25ac3ea55c9b2f1091bd387c6dc595b3b7090e6e]('https://github.com/qgis/QGIS/search?q=25ac3ea55c9b2f1091bd387c6dc595b3b7090e6e&type=Issues')

**Stack Trace**
<pre>
QgsProcessingToolboxModel::data qgsprocessingtoolboxmodel.cpp:435
QgsProcessingToolboxProxyModel::filterAcceptsRow qgsprocessingtoolboxmodel.cpp:693
QgsProcessingToolboxProxyModel::filterAcceptsRow qgsprocessingtoolboxmodel.cpp:769
QSortFilterProxyModel::flags :
QSortFilterProxyModel::filterRole :
QSortFilterProxyModel::invalidateFilter :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru?�a
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nyalldawson** [comment]
This doesn't look like a qgis issue, it looks like an issue with your script 🤔

**Comment by TechGus** [comment]
I know there is an issue with my script. My concern is that the only way to break the loop is by crashing QGIS. I don't know if there is a way to break the loop without crashing QGIS hence my question and I'm sure there are more important issues to fix in the software but since this happened to me, I thought of raising the issue.

**Comment by nyalldawson** [comment]
There's literal an infinite number of ways to write a Python script which can cause QGIS to lockup or crash :laughing:  By design, the PyQGIS API is made to expose all the functionality of the underlying C++ code. This gives huge flexibility in what you can do with Python in QGIS, but the trade off is that it pushes the responsibility for using this API correctly back to plugin authors. (The other alternative is the ESRI approach, where only "safe" functions are exposed to the Python API, but as a result only a tiny fraction of the software's functionality is available through the Python API).

If you've got a specific issue with the actual python api then you should open a bug report detailing this (along with an example script). (There's nothing we can do in general to change this situation)

**Comment by TechGus** [comment]
Ok. Thank you for clearing this up!
