### ISSUE TITLE
QGIS 3.10 Plugin install fails because of (hyphen in) folder name

### ISSUE THREAD

**Issue by Jannik-Schilling** [qgis/QGIS#32968]
I found this problem with the plugins "ESTIMAP Recreation" and "WaterNetAnalyzer". 

Both are available in the plugin repository. 
Both can be installed without any problem from a zip file.
Both work without any problems in QGIS 3.2, 3.4 ... 3.8. But installing these plugins **from the official plugin repository** fails in QGIS 3.10
When installed from the plugin repository you get an error: 
> Plugin has disappeared: The plugin seems to have been installed but I don't know where. Probably the plugin package contained a wrong named directory. Please search the list of installed plugins. I'm nearly sure you'll find the plugin there, but I just can't determine which of them it is. It also means that I won't be able to determine if this plugin is installed and inform you about available updates. However the plugin may work. Please contact the plugin author and submit this issue.

In the folder "...\QGIS3\profiles\default\python\plugins" they are correctly installed with the folder name "[pluginname]-master" e.g "waternetanalyzer-master"

It seems as the hyphen is a problem, because other plugins, which have "_" in the folder name, work fine.

I tried to fix this by uploading a new version to the official qgis plugin repository without the hyphen. I get: "Plugin name mismatch: the plugin main folder name in the compressed file (WaterNetAnalyzer_master) is different from the original plugin package name (WaterNetAnalyzer-master)

**Comment by elpaso** [comment]
Please report the issue to the plugin author.

**Comment by Jannik-Schilling** [comment]
> 
> 
> Please report the issue to the plugin author.

I am the author.

**Comment by elpaso** [comment]
This is the problem with your plugin: "Plugin name mismatch: the plugin main folder name in the compressed file (WaterNetAnalyzer_master) is different from the original plugin package name (WaterNetAnalyzer-master)"

The plugin package name cannot be changed after a plugin has been created.

**Comment by Jannik-Schilling** [comment]
> The plugin package name cannot be changed after a plugin has been created.
yes, I understand that. This was just my first attempt to fix the problem. 

But is there any reason, why a the version with the hyphen "WaterNetAnalyzer-master" , which is already located in the qgis plugin repostory cannot be installed?

**Comment by borysiasty** [comment]
It's because from the commit 5c1cc4a40d84, the hyphen is interpreted as a delimiter of a suffix in the zip file name. So WaterNetAnalyzer-master.zip is expected to contain a "WaterNetAnalyzer" directory.

It was never clearly expressed that hyphens are not allowed in the Python package names (it didn't occur to me that QGIS would be able to load them at all), so now we have 40 plugins with hyphens in the repository... I see three solutions:

1) Keep using hyphens as zip suffix delimiters and ask authors to rename all the 40 plugins (painful)... 

2) Authorise use of hyphens in the plugin names, revert that commit and announce widely that hyphens are again not allowed as zip suffix delimiter. It looks risky to me, so I guess authors should be warned that using hyphens in Python modules is clearly against the Python standard and they do it on their risk).

3) Just revert that commit and clearly forbid using hyphens in all new plugins.

In any case, we should work out an official naming convention and implement a validation in the repository.

**Comment by elpaso** [comment]
> It was never clearly expressed that hyphens are not allowed in the Python package names (it didn't occur to me that QGIS would be able to load them at all)

I think it was explicitly stated that they are allowed: https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/plugins/releasing.html#validation

**Comment by Jannik-Schilling** [comment]
> It's because from the commit [5c1cc4a](https://github.com/qgis/QGIS/commit/5c1cc4a40d84815061d41f1ff5cd4870093c531f), the hyphen is interpreted as a delimiter of a suffix in the zip file name. So WaterNetAnalyzer-master.zip is expected to contain a "WaterNetAnalyzer" directory.

I wrote a [comment for a potential fix to this](https://github.com/qgis/QGIS/commit/5c1cc4a40d84815061d41f1ff5cd4870093c531f#commitcomment-36049650)
