### ISSUE TITLE
"topological editing" only works if layer CRS and project CRS match

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#32977]
If the layer and project CRSs do not match, then topological editing does not work. Regression. Tested on 3.4 up to master.

**Comment by PedroVenancio** [comment]
Confirmed here with QGIS 3.10 nightly, from OSGeo4W64.

**Comment by gioman** [comment]
works as expected on 2.18.

**Comment by happydeb** [comment]
Okay, I thought I solved this with issue 33009 but now I can't snap to layers or do topological editing  or split features probably because of the same problem with the differing CRS since I had to change my project CRS to EPSG 3857 to render base maps now all my layers are off. There is a reason why we use projected layers instead of geographic, I can't just change all my layers to geographic?

**Comment by gioman** [comment]
> There is a reason why we use projected layers instead of geographic, I can't just change all my layers to geographic?

@happydeb this issue (not being able to snap if the project CRS <> layer CRS) is a very bad regression in QGIS 3, hopefully it will be fixed soon. In the meantime use as project CRS the same CRS of the layers you are editing. And stick to QGIS 3.4 LTR to not incur in the other problem (33009)

**Comment by lbartoletti** [comment]
@gioman is it a duplicate of https://github.com/qgis/QGIS/issues/29648 ?

**Comment by gioman** [comment]
> @gioman is it a duplicate of #29648 ?

it is indeed, thanks. I forgot about it. Still a very critical regression.
