### ISSUE TITLE
Data Source Manager | Browse | PostgreSQL page is blank

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [qgis/QGIS#32995]
1. Open a layer from postgres with the datasource manager.
2. Close the datasource manager
3. Open the datasource manager again. Now the page is all gray, no ui rendered. See image below:

![Capture2](https://user-images.githubusercontent.com/8887576/69335072-59b85a80-0c5c-11ea-837d-fa84f242c2e0.PNG)

Resizing the dialog will render the ui items ok, but not before.

Using Microsoft Windows 10 Enterprise 2016 LFSB and OSGEO QGIS 3.10.0

**Comment by elpaso** [comment]
Related to https://github.com/qgis/QGIS/issues/32615
Related to https://github.com/qgis/QGIS/issues/31449
Hopefully fixed by: https://github.com/qgis/QGIS/pull/32631

I'd really like someone to test current master, this behavior can vary from Qt version to another and to a platform to another, I'm not 100% sure it's fixed.

**Comment by alexbruy** [comment]
@Jakob-Lanstorp may I ask you to retest with latest master?

**Comment by gioman** [comment]
Assuming fixed.

**Comment by Jakob-Lanstorp** [comment]
Yes, fixed
