### ISSUE TITLE
intersection tool is very slow

### ISSUE THREAD

**Issue by bouyeijiang** [qgis/QGIS#33216]
*.shp file maybe have 9 millions features,*.mdb file maybe have two hundred thousand features.
intersect  finished ten percent but need  spend 1 day

**Comment by SrNetoChan** [comment]
Using Shapefies or mdb files to do the intersect may be one of the reasons why the intersect is slow, can you try convert the data to better format, like geopackage or even better PostGIS with some spatial indexes on top of it?

**Comment by nyalldawson** [comment]
It's likely because you're using a mdb file -- that format has no spatial index support

**Comment by bouyeijiang** [comment]
export shp file is still slow

**Comment by bouyeijiang** [comment]
using postgis is little bit better.but still slow

**Comment by lbartoletti** [comment]
@bouyeijiang did you create the spatial index on the layers (shapefile and postgis)?

**Comment by gioman** [comment]
@bouyeijiang also if possible link/attach your dataset.

**Comment by bouyeijiang** [comment]
as slow as

**Comment by gioman** [comment]
> as slow as

you are not giving use enough details to allow us understand of there is really a bug/performance issue. Without this details this ticket is likely that will be closed.

**Comment by mhugent** [comment]
@bouyeijiang : There is ongoing activity to improve the performance of the overlay tools. Do you have the possibility to make the data available to test it? If it is not public, could you send it to me privately?

**Comment by bouyeijiang** [comment]
arcgis tool is ok,it about spend thirty minutes

**Comment by gioman** [comment]
> arcgis tool is ok,it about spend thirty minutes

@bouyeijiang please attach a sample dataset we can test.

**Comment by bouyeijiang** [comment]
i can't attach file,secrect data

**Comment by gioman** [comment]
> i can't attach file,secrect data

@bouyeijiang can't you attach/link and open dataset that proves your point?

**Comment by bouyeijiang** [comment]
i mean that  i can't attach file on network,

**Comment by gioman** [comment]
> i mean that i can't attach file on network,

@bouyeijiang ?

**Comment by diddiman** [comment]
Just out of curiosity here, i am doing intersection for a very large dataset, not saying it's slow, but i want it to be as fast as possible. So i am stealing this thread, since it sounds related..

So i have a shapefile and running intersect with a grid (covers half of sweden, and each square being 5 km both sides), just to split the shape into smaller squares, then i output each grid as a new shape file. It should result in 15k-ish squares (so allot of data)
I have uploaded both the grid and the shape to my db, so i guess the format would be postgis, made sure to check the box to create spatial index.
Then i started the intesect tool and selected postgis grid and postgis shape and told it to loop through the grid (too get one shape per grid). Is that all i can do, or is there any more improvements i can do here? As it looks now, according to my calculations after doing the first 1k squares, it should take me 12 days-ish. Is that reasonable or is there something i can do?
