### ISSUE TITLE
WCS client stopped working on a specific service from 2.18 to 3.x

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS#33339]
http://sit.cittametropolitana.na.it/arcgis/services/lidar/MapServer/WCSServer?
works in qgis 2.18, it does not in 3.10.
tested both on Windows and Debian Sid.

**Comment by pigreco** [comment]
confirm
only works in 2.18

**Comment by pcav** [comment]
Layers are loaded, the info tool returns correct values, but nothing is displayed, even when adopting a proper colour scale (from 0 to 2000)

**Comment by gioman** [comment]
log:

2019-12-11T18:14:05     WARNING    No data received
2019-12-11T18:14:05     WARNING    Received coverage has wrong extent 399003.1521521521499380,4484495.1214244849979877 : 476198.8478478478500620,4529147.6187546495348215 (expected 399089.8888888888759539,4484582.3333333330228925 : 476112.1111111111240461,4529060.4068458015099168)

**Comment by pcav** [comment]
Thanks for checking. The points are:
* correct values are displayed when queried with the info tool
* 2.18 displays it correclty.
Have you zoomed to the correct area? It is around Naples.

**Comment by marisn** [comment]
> 2019-12-11T18:14:05 WARNING Received coverage has wrong extent 

I also got hit by such issue, but I managed to track down the issue to MapServer. Still in this case an ArcGIS server seems to be in use.
https://github.com/mapserver/mapserver/issues/5940

**Comment by troopa81** [comment]
> 2019-12-11T18:14:05 WARNING No data received

This message is no big deal and don't prevent the WCS layer to be displayed. I'll propose a PR to not display it.

> 2019-12-11T18:14:05 WARNING Received coverage has wrong extent

Like @marisn said, I wonder if this is not a problem on server side. QGIS checks that received extent is almost (10 significant digits) equals to requested extent. This not the case with this server (given BBOX and resulting bbox differs) : 

> curl -XGET "http://sit.cittametropolitana.na.it/arcgis/services/lidar/MapServer/WCSServer?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&FORMAT=GeoTIFF&COVERAGE=3&BBOX=13.83958719667134396,40.53155657495530306,14.67913815586193493,41.0219497441243135&CRS=EPSG:4326&RESPONSE_CRS=EPSG:4326&WIDTH=10&HEIGHT=10" -o notok.img
> gdalinfo notok.img
...
Upper Left  (  13.7929455,  41.0491938) ( 13d47'34.60"E, 41d 2'57.10"N)
Lower Left  (  13.7929455,  40.5043125) ( 13d47'34.60"E, 40d30'15.53"N)
Upper Right (  14.7257799,  41.0491938) ( 14d43'32.81"E, 41d 2'57.10"N)
Lower Right (  14.7257799,  40.5043125) ( 14d43'32.81"E, 40d30'15.53"N)
Center      (  14.2593627,  40.7767532) ( 14d15'33.71"E, 40d46'36.31"N)

Contratry to this one that works

> curl -XGET "http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&FORMAT=GTiff&COVERAGE=BGS_EMODNET_WesternMed-MCol&BBOX=-0.48958332999999998,35.21874233999999859,9.83125826000000025,44.78958332999999925&CRS=EPSG:4326&RESPONSE_CRS=EPSG:4326&WIDTH=418&HEIGHT=388" -o ok.img
> gdalinfo ok.img
...
Upper Left  (  -0.4895833,  44.7895833) 
Lower Left  (  -0.4895833,  35.2187423) 
Upper Right (   9.8312583,  44.7895833) 
Lower Right (   9.8312583,  35.2187423) 
Center      (   4.6708375,  40.0041628)

It was working before (QGIS 2.18) because of a side effect which lost precision when checking those extents, and the side effect is gone since this commit 4b009f96ecb92db0056c18285cb1b8375c239ed1

I take a look in OGC specifications and I don't see anything that said that result extent could be different from requested one (as long as pixel and bbox ratio are consistent).

@pcav @pigreco Any thoughts on that?

**Comment by pcav** [comment]
Why shouldn't qgis be more tolerant towards possible server (minor, apparently) misconfigs?
Thanks.

**Comment by troopa81** [comment]
> Why shouldn't qgis be more tolerant towards possible server (minor, apparently) misconfigs?
Thanks.

Why not. We could display the warning message but let the tile be displayed. I have not a strong opinion on this. I'll propose a PR and see what reviewers says about it.

**Comment by pcav** [comment]
Thanks Nyall!
