### ISSUE TITLE
Some GDAL Functions not working via QGIS interface 3.4.14 Win10

### ISSUE THREAD

**Issue by mattenvsys** [qgis/QGIS#33386]
Hi, certain GDAL tools are not working via QGIS Desktop 3.4.14 on Windows 10

For instance, GDAL Polygonise and GDAL Merge do not work

I receive the errors:

```
C:\PROGRA~1\QGIS3~1.4\bin\python3.exe: No module named gdal_merge
C:\PROGRA~1\QGIS3~1.4\bin\python3.exe: No module named gdal_polygonize
```

It is effecting all PCs in the office running this version and is reproducible on all raster datasets we have attempted to run.

* Click Raster on the top tool bar
* Select Conversion
* Click Polygonise (Raster to Vector)
* Set the parameters
* Click run

Tool fails instantly

Believe it is something to do with the way QGIS is trying to call/run the command. Here's the initial part of the console call QGIS creates:

```
python3 -m gdal_polygonize 
```

Other GDAL tools, susch as GDAL Raster Calculator, work with no issues. Here is and example of the console call for calc:
```
gdal_calc --calc
```

**QGIS and OS versions**

QGIS version 3.4.14-Madeira
QGIS code revision
QGIS code revision
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 2.4.3
Running against GDAL/OGR 2.4.3
Compiled against GEOS 3.8.0-CAPI-1.13.1
Running against GEOS 3.8.0-CAPI-1.13.1 
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 5.2.0
Running against PROJ Rel. 5.2.0, September 15th, 2018
Windows 10 Pro

**Comment by agiudiceandrea** [comment]
Same issue reported on the QGIS-User ML from another user
https://lists.osgeo.org/pipermail/qgis-user/2019-December/044443.html

and another one on StackExchange:
https://gis.stackexchange.com/questions/344713/qgis-3-python-doesnt-find-gdal-module

**Comment by agiudiceandrea** [comment]
It seems the PYTHONPATH environmental variable is not properly set.
It should be set to the path of the folder where there is gdal_polygonize.py (and the other gdal_*.py python scripts): on Windows with a standalone QGIS 3.4 installation it could be e.g. `C:\PROGRA~1\QGIS3~1.4\apps\Python37\Scripts`

**Comment by gioman** [comment]
There is something wrong with the most recent installers,
for example:

QGIS-OSGeo4W-3.4.13-2-Setup-x86_64.exe	11-Nov-2019 16:37 	455M
does not show any issue

while

QGIS-OSGeo4W-3.4.13-3-Setup-x86_64.exe	05-Dec-2019 22:06 	452M
(as also QGIS-OSGeo4W-3.4.14-1-Setup-x86_64.exe	07-Dec-2019 16:41 	452M)
shows the described problems.

@jef-n any idea?

**Comment by gioman** [comment]
> @jef-n any idea?

PS no issues on the latest 3.10

**Comment by 0verlord84** [comment]
I have just installed QGIS ver 3.10.1 but it spits out the same error when I try and run gdal_merge from the GUI.

I have set the PYTHONPATH as C:\Program Files\QGIS 3.10\apps\Python37
GDAL_DATA is at C:\PROGRA~1\QGIS3~1.10\share\gdal
GDAL_DRIVER_PATH is at C:\PROGRA~1\QGIS3~1.10\bin\gdalplugins
PYTHONHOME is the same as PYTHONPATH

The gdal_merge.py (among other gdal modules) are in this folder though (C:\Program Files\QGIS 3.10\apps\Python37\Scripts), which I have tried to point to that path from QGIS as the PYTHONPATH, but unsuccessfully because gdal_merge does not run properly.

I wonder whether it's because I should have installed it via OSGEO4W and point QGIS to those folders instead of the native QGIS ones

**Comment by agiudiceandrea** [comment]
@0verlord84
> The gdal_merge.py (among other gdal modules) are in this folder though (C:\Program Files\QGIS 3.10\apps\Python37\Scripts), which I have tried to point to that path from QGIS as the PYTHONPATH, but unsuccessfully because gdal_merge does not run properly.

This is strange... both the user on the QGIS-User ML and the user on StackExchange have solved the problem [[1](https://lists.osgeo.org/pipermail/qgis-user/2019-December/044510.html)][[2](https://gis.stackexchange.com/questions/344713/qgis-3-python-doesnt-find-gdal-module#comment563588_344713)] properly setting the PYTHONPATH environmental variable.

**Comment by harvey121** [comment]
I got the same error, and like a virus, it happened on all the computers in my office. I even installed 3.4 on a brand new computer and got the same error. I clearly remember that it worked well last week. It took me a whole day.

**Comment by jef-n** [comment]
Fixes in OSGeo4W

**Comment by agiudiceandrea** [comment]
Hi @jef-n, there are various similar report on some mailing lists and forums/groups regarding also QGIS 3.10.1 with GDAL 3, but it seems the fix only affected the OSGeo4W "python3-gdal2" and "gdal2-python" packages, isn'it?

**Comment by Bavarello** [comment]
The problem was solved by following this procedure:
- search, in the QGIS installation directory, for the folder where the gdal_merge.py, gdal_polygonize.py, etc. files are present. In your case it could be: G: \ QGIS3 ~ 1.10 \ apps \ Python37 \ Scripts
- in the QGIS window from the Settings / Options ... / System menu you must insert a new row in the "Environment" box, with the value "Overwrite" (or "Prepend") in the first column ("Apply"), the value " PYTHONPATH "in the second column (" Variable "), and in the third column (" Value ") the path of the above folder.

![Annotazione 2019-12-26 213901](https://user-images.githubusercontent.com/22433856/71491942-02497380-2834-11ea-90b9-4268ee1a3517.png)

**Comment by 0verlord84** [comment]
Hi Giovanni,
In my case I have tried to follow those instructions, however I have
noticed that it wouldn't prepend the string unless the semi-column was put
at the end (separator), which ultimately worked for me.

Cheers
Davide

**Comment by agiudiceandrea** [comment]
Now, after the latest fix, it should be sufficient to update python3-core to python3-core-3.7.0-4 via OSGeo4W setup to solve the issue.

**Comment by ThomasG77** [comment]
To avoid to set variables in QGIS or in the OS, you should better set the missing variables in the `qgis.bat` file in `C:\Program Files\QGIS 3.10` (path may change depending of the QGIS version)
When you click on the QGIS icon, it's this `qgis.bat` that is executed before running `qgis-bin.exe` (the real QGIS executable behind the scene on Windows).

The main advantage is to be able to patch all computers with the same issue by copying the file instead of setting the fix manually for each one. See selected part in the attached image below (PS: do not copy the other lines as they may be specific to my QGIS version

![Sélection_130](https://user-images.githubusercontent.com/642120/72434389-bedf8680-379b-11ea-9a26-9eb0b183ef8a.png)
