### ISSUE TITLE
MSSQL driver not found

### ISSUE THREAD

**Issue by stopyaks** [qgis/QGIS#33392]
MSSQL connections fail. 

Error = "Driver not found. Driver not found."
OS = Xubuntu 18.04 LTS

QGIS version
3.10.0-A Coruña
QGIS code revision
6c816b4204
Compiled against Qt
5.9.5
Running against Qt
5.9.5
Compiled against GDAL/OGR
2.2.3
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.6.2-CAPI-1.10.2
Running against GEOS
3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite
3.22.0
Running against SQLite
3.22.0
PostgreSQL Client Version
10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
QScintilla2 Version
2.10.2
PROJ.4 Version
493
OS Version
Ubuntu 18.04 LTS
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by jef-n** [comment]
Looks like you didn't install `libqt5sql5-tds`.

**Comment by stopyaks** [comment]
I installed it then removed, purged and reinstalled qgis. Same error trying
to connect to MS SQL server.

**Comment by wlorenzetti** [comment]
This bug is still present on QGIS 3.10.4. Do you have another indications?

**Comment by stopyaks** [comment]
There's no solution that I'm aware of. Sorry.

**Comment by gioman** [comment]
Same error message on Windows/OSGeo4W, unclear what libraries are needed to be installed.

**Comment by wlorenzetti** [comment]
Thanks to @elpaso I found the solution, other than Microsoft packages is necessary also libqt5sql5-odbc.

**Comment by wlorenzetti** [comment]
It'd be nice QGIS installation require libqt5sql5-odbc.

**Comment by jef-n** [comment]
@wlorenzetti Using freetds (via libqt5sql5-tds) didn't work?

**Comment by elpaso** [comment]
@jef-n FreeTDS works as well for me. I had to install `tdsodbc` and `libqt5sql5-tds`

**Comment by wlorenzetti** [comment]
@jef-n no only with  `libqt5sql5-tds` alone.

**Comment by MarvinMep** [comment]
I installed `tdsodbc` `libqt5sql5-tds` `libqt5sql5-odbc`
when I click on "test connection" in MSSQL "new connection" dialog, it shows "`Driver not loaded Driver not loaded`" error, and when I click on "List databases": "`[unixODBC] [Driver Manager] Unable to open 'FreeTDS' lib: file not found QODBC3: Unable to connect` " 
Debian Bullseye (11), QGIS 3.20.0-Odense (installed from QGIS repositories)

**Comment by jmkerloch** [comment]
I managed to remove this error message by following this gist https://gist.github.com/genio/7c7fc52fcb8be5d486aa#file-01_setup_ubuntu-md

But now I have a new error : 
`[FreeTDS][SQL Server]Unable to connect: Adaptive Server is unavailable or does not exist`

But this time it seems to be related to my FreeTDS configuration, not QGIS.

**Comment by alexbruy** [comment]
Is this still an issue? Seems that this is more about installing missing dependencies than a QGIS bug.

**Comment by OculiViridi** [comment]
I think the issue should be reopened since it is still present on latest version of QGIS (v3.36.1).

I found it when using **Vector - Data Management Tools - Reproject layer...** algorithm to save a SHP file to a new MS SQL Server Table.

This is the detail of the error

![image](https://github.com/qgis/QGIS/assets/42179710/8c877f8e-661b-4802-829a-eadd1642545d)

It seems to happen "randomly".
I was able to make a projection of one SHP file, but then, when trying to launch the algorithm on another layer, the error appeared.
Then I try to refresh the connection to the DB and also to close and reopen the project, but without any change. Closing and reopening QGIS seems to be the only way to make it work again, but only for 1 shot.
