### ISSUE TITLE
setFilterExpression and QGIS Filter output different results

### ISSUE THREAD

**Issue by Infiziert90** [qgis/QGIS#33454]
**Describe the bug**
setFilterExpression sorts out all NULL attributes, but the qgis internal filter function not.
So in pyqgis i get 8 rows and in qgis 4114 rows.

**How to Reproduce**
pyqgis:
```py
layer = iface.activeLayer()
request = QgsFeatureRequest()
request = request.setFilterExpression('"COM"  NOT LIKE \'muster\'')
t = 0
for x in layer.getFeatures(request):
    t += 1
print(t)
```
Result: 8

Qgis Filter:
`"COM"   NOT  LIKE  'muster'`
Result: The where clause returned 4114 row(s).

**QGIS and OS versions**

QGIS version: 3.10.0-A CoruÃ±a
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL/OGR: 2.4.1
Running against GDAL/OGR: 2.4.1
Compiled against GEOS: 3.8.0-CAPI-1.13.1
Running against GEOS: 3.8.0-CAPI-1.13.1 
Compiled against SQLite: 3.29.0
Running against SQLite: 3.29.0
PostgreSQL Client Version: 11.5
SpatiaLite Version: 4.3.0
QWT Version: 6.1.3
QScintilla2 Version: 2.10.8
Compiled against PROJ: 5.2.0
Running against PROJ: Rel. 5.2.0, September 15th, 2018
OS Version: Windows 10 (10.0)

**Comment by roya0045** [comment]
That's strange because the set filter expression should convert that to a where clause in the provider iterator.

**Comment by Infiziert90** [comment]
Is the behavior with sorting out NULL intended?

**Comment by troopa81** [comment]
@Infiziert90 I failed to reproduce with QGIS 3.10 and master. I have the same kind of filter with NULL values on a PostGres database and I get exactly the same number of feature with both ways. 

Could you provide data and project so I can reproduce?

**Comment by Infiziert90** [comment]
Sorry for the late response ...

i tested it again with QGIS 3.10.2 and nothing changed.

My steps:
1. Drag&Drop altlpar0.dbf into qgis
2. open python console
3. typed this in console ->
```python
>>>layer = iface.activeLayer()
>>>request = QgsFeatureRequest()
>>>request = request.setFilterExpression('"COM"  NOT LIKE \'muster\'')
>>>t = 0
>>>for x in layer.getFeatures(request):
...    t += 1
>>>print(t)
0


>>>layer = iface.activeLayer()
>>>request = QgsFeatureRequest()
>>>request = request.setFilterExpression('"COM"  NOT LIKE \'bru\'')
>>>t = 0
>>>for x in layer.getFeatures(request):
...    t += 1
>>>print(t)
8
``` 
4. right click altlpar0 and select the "Filter..." option
5. type in `"COM" NOT LIKE 'muster'`
6. Test: "The where clause returned 4132 row(s)."
7. type in `"COM" NOT LIKE 'bru'`
8. Test: "The where clause returned 4140 row(s)."

@troopa81 
[altlpar0.zip](https://github.com/qgis/QGIS/files/4179477/altlpar0.zip)

**Comment by Infiziert90** [comment]
Same behavior with 3.12.0

**Comment by troopa81** [comment]
@Infiziert90 IMHO, it's not a QGIS issue (or maybe not an issue at all). 

When you use `setFilterExpression`, the expression is evaluated by QGIS. When you use `Filter...` option, it delegates the filtering to the data provider, in your case OGR (gdal vector part), in my case the Postgres provider (that's why I failed to reproduce it the first place, we had different providers).

When QGIS evaluate expression `like`, it [returns false](https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpressionnodeimpl.cpp#L475) (filter feature) if either left part or right part of the expression is null. 

That's the same with Postgres
```sql
test_filterexpression=# select count(*) from altlpar0 limit1 where COM not like 'muster';
 count 
-------
     0
(1 row)
```

But that's different for OGR
```shell
$ ogrinfo -sql "select count(*) from altlpar0 where COM not like 'muster'" ~/work/tmp/bug_qgis_33454/altlpar0.dbf

INFO: Open of `/home/julien/work/tmp/bug_qgis_33454/altlpar0.dbf'
      using driver `ESRI Shapefile' successful.

Layer name: altlpar0
Geometry: None
Feature Count: 1
Layer SRS WKT:
(unknown)
COUNT_*: Integer (0.0)
OGRFeature(altlpar0):0
  COUNT_* (Integer) = 4132
```

My advice is to complete your filter to avoid ambiguity. For instance:
```shell
"COM" is not NULL and "COM" NOT LIKE 'muster
```

Or you can fill an issue in [gdal](https://github.com/OSGeo/gdal/issues) arguing that the subset filter behavior differs with the PostGres and QGIS one.
