### ISSUE TITLE
3.10.1 labels missing

### ISSUE THREAD

**Issue by danzig666** [qgis/QGIS#33659]
Some labels missing in 3.10.x, in 3.4.x they are fine.
Sample project: [qgis310_labels_missing.zip](https://github.com/qgis/QGIS/files/4034478/qgis310_labels_missing.zip)

**Comment by gioman** [comment]
Seems something related to label size and units used, but can't figure exactly what it is.

**Comment by nyalldawson** [comment]
It relates to the change in label overrun behavior in QGIS 3.10. QGIS 3.10 defaults to no overrun, so in order to get these labels to appear you'll need to increase the overrun distance in the placement tab:

![image](https://user-images.githubusercontent.com/1829991/72029284-29db1a00-32d1-11ea-8ab7-26c93c669daa.png)

![image](https://user-images.githubusercontent.com/1829991/72029292-2e073780-32d1-11ea-96b8-1ed4123ba092.png)

**Comment by roya0045** [comment]
> It relates to the change in label overrun behavior in QGIS 3.10. QGIS 3.10 defaults to no overrun, so in order to get these labels to appear you'll need to increase the overrun distance in the placement tab:
> 
> ![image](https://user-images.githubusercontent.com/1829991/72029284-29db1a00-32d1-11ea-8ab7-26c93c669daa.png)
> 
> ![image](https://user-images.githubusercontent.com/1829991/72029292-2e073780-32d1-11ea-96b8-1ed4123ba092.png)

Wait, you need to increase the distance to have labels that are close to display? Shouldn't that be the opposite?

Also would it be better to have this 'off' as a default and enabled/modifier by users if don't want any overlap?
