### ISSUE TITLE
Add option to increse the number of projects shown in 'recent projects'

### ISSUE THREAD

**Issue by calbhe** [qgis/QGIS#33720]
**Feature description.**
It would be really useful to be able to increase the number of projects shown in 'recent projects'. This could be a customisation feature, such as AutoCAD, with the ability to choose the number of recent projects shown.

**Comment by Gustry** [comment]
You can change the value in your QGIS config file:
https://github.com/qgis/QGIS/blob/master/resources/qgis_global_settings.ini#L50

**Comment by luipir** [comment]
@calbhe the answer by @Gustry shows that the feature already exist. Do you mind we can close this feature request? If so, please close it!

**Comment by calbhe** [comment]
Oh fantastic! I will close it. Apologies I am new to QGIS, where can I find the 'global settings' to change from the default value of 20?

**Comment by Gustry** [comment]
You can change in the `Advanced` section in your QGIS properties, in this screenshot:

![Capture d’écran de 2020-01-10 12-06-28](https://user-images.githubusercontent.com/1609292/72148669-ab01e200-33a1-11ea-86a4-f23826cf3864.png)

There are too many options in QGIS, it's difficult to have one proper field for each option. That's why some options can be changed in this dialog.

**Comment by calbhe** [comment]
Amazing! thanks @Gustry
