### ISSUE TITLE
Map Tips usability

### ISSUE THREAD

**Issue by Redoute** [qgis/QGIS#33981]
I thought @nyalldawson did solve #28337 last year, but I see the same problem in QGIS 3.10.1 on Windows. Here a screenshot:

![QGISMapTip](https://user-images.githubusercontent.com/1494624/72898986-696c2200-3d25-11ea-8576-739e6bc6a82d.jpg)

1. can't read first letters of the tooltip
1. can't click/select the feature

Thank you very much for all support.

**Comment by gioman** [comment]
@Redoute is this a regression?

**Comment by SrNetoChan** [comment]
With the help of Nyall, I have tried to address the problem of having the cursor blocking the map tip. but the solution caused even more problems because as soon as you moved the cursos the tooltip would disappear, making it impossible to, for example click in links inside of it. For that reason, we revert the change and now it is working as it always did.

IIRC, the workaround was to had some padding around the lable instead.

https://github.com/qgis/QGIS/issues/31311#issuecomment-523583849

**Comment by roya0045** [comment]
@SrNetoChan would it have been possible to set the box to anchor at the middle or the bottom of the left border instead of the top? With a little padding this might prevent the cursor from obstructing the text when it first appear.

**Comment by Redoute** [comment]
@gioman @SrNetoChan So it seems the fix I have seen never made it to a release version.

**Comment by SrNetoChan** [comment]
> @SrNetoChan would it have been possible to set the box to anchor at the middle or the bottom of the left border instead of the top? With a little padding, this might prevent the cursor from obstructing the text when it first appears.

No idea, what I did was to move the tooltip away from the cursor, but, because it was not below the cursor as soon as the mouse moved the map tip would disappear. At that time it did not seem oto have a simple solution. But I am a noobie developer :-)

**Comment by SrNetoChan** [comment]
> @gioman @SrNetoChan So it seems the fix I have seen never made it to a release version.

It kinda did, but it was reverted on the next patch release.

**Comment by roya0045** [comment]
@SrNetoChan since the map tip is a qwidget and the widget has size attributes, my guess would be that we could simply add half or the full height to the y value in the move() function to simply offset the map tip.

**Comment by SrNetoChan** [comment]
@roya0045 I think that's what I have tried, but go ahead and try.

**Comment by Saijin-Naib** [comment]
It should be doable, because the Advanced Digitizing Tooltip doesn't run under the cursor anymore.
How is that handling the offset?  
![image](https://user-images.githubusercontent.com/19295950/72926941-46407300-3d23-11ea-8f19-ab3da0fe9a4c.png)

However, the maptip WILL draw over the Advanced Digitizing Tooltip, which is frustrating.  
![image](https://user-images.githubusercontent.com/19295950/72926892-32950c80-3d23-11ea-9bec-9c81996e93bb.png)

**Comment by Redoute** [comment]
I think a tool tip (like the one in advanced digitizing) does not take mouse clicks by design. But we decided to allow clickable links in map tips (a design error IMO), so we have to deal with it.

For "1. can't read first letters of the tooltip" I can live with the workaround adding spaces to the text, but sure this is not pretty. Would it be reasonable to add blank space inside the tooltip left of the content?

For "2. can't click/select the feature" would it be possible to pass mouse events to the underlying window (the canvas?) - either all unhandled clicks or clicks in the "hot corner" of the tooltip widget?
