### ISSUE TITLE
QGIS freezing and crashing when I launch it /open projects

### ISSUE THREAD

**Issue by Caligraf21** [qgis/QGIS#33991]
Hello,

I'm new to github/qgis for information...

I have a big issue with the launching of any QGIS version since yesterday and I can't find a solution. Each time I'm trying to launch 3.4, 3.8 and even the newest 3.10 I've installed to fix the problem, QGIS keep freezing when I try to open a project. The launching itself take much more time than usual and it's freezing a lot. 
I have not tried to install new extensions recently or modified the QGIS files. I tried to restart PC obviously but I can't find the reason why QGIS became so slow that I'm unable to use it.

If you have tools to diagnostic the problem or any possible solutions I'd gladly take them please.

Thanks

**Comment by gioman** [comment]
> I have not tried to install new extensions recently or modified the QGIS files.

@Caligraf21 if you are able to start QGIS a good starting point to try figure where the problem can be is anyway try with a new QGIS profile (settings > user profiles > new profile).

**Comment by Caligraf21** [comment]
Hi @gioman I tried to set a new profile but it did'nt worked. QGIS is still super slow and keep freezing a lot.

**Comment by luipir** [comment]
I suspect you have some data source is freezing you or some remote mounted directory is parsed by the browser panel. 
I would check the project content... a way to do can be to duplicate the project and removing porting of the project to see if the problem is in some layer (or styling a layer).

Obviously would help a lot if you share the project and data  or to have a teswt project that replicate the issue

**Comment by Caligraf21** [comment]
Hi @luipir , I've been trying to delete the QGIS project files and I also removed all extensions in case it'd have caused the problem. QGIS still slow as a turtle. Is there any way to clear the 'recent project' or browser panel cache ? 
I've also been thinking to remove all the QGIS versions installed and do a fresh and clean QGIS installation not linked to any existing projects on the PC. I'm sorry for my low skills but if it's possible, how to do it please?

My recent data / project that may have caused the problem are not really heavy, and very usual. not sure if it'll help

**Comment by gioman** [comment]
@Caligraf21 if you have really created a new profile you should not see any trace of recent projects and also all your connections to databases, services, etc. would be reset to a clean state. If you did and still you see this issue is likely to be some kind of local issue, this is not of course a general one. You can of course uninstall QGIS, remove any trace of it by removing the QGIS folder within "AppData" (if you are on Windows) and also clean the registry.

**Comment by Caligraf21** [comment]
@gioman I followed your instructions then I re-installed QGIS 3.10 and the browser panel and the 'recent projects' disapeared BUT QGIS is still slow and freezing. My computer used to run it very fast like instant start and good processing performances so it's very strange...

**Comment by Caligraf21** [comment]
Problem found, it was an external source... a disfonctuntional burned cd caused the freezing ! I forgot about that cd and would never have though it d be the source of the problem. Once we removed the cd, QGIS worked like a charm like before. Many thanks to you guys for trying to help me

**Comment by luipir** [comment]
> Problem found, it was an external source

many problems comes from browser panel that trying to scan slow (for some reason) devices... this is another case!

**Comment by roya0045** [comment]
@luipir a timeout should be added for unresponsive/invalid drives on the browser scan, there is already a function to handle bad drive but it might be bjorked if so many users are having issues lately. :/
