### ISSUE TITLE
“QGIS3.10” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by mikenbrenda** [qgis/QGIS#34018]
This is on the latest Mac Catalina

**Comment by gioman** [comment]
@mikenbrenda don't believe in anything Apple throws at you:

![Screenshot 2020-01-24 at 15 46 41](https://user-images.githubusercontent.com/1951107/73082297-1f1fa800-3ec1-11ea-96bd-445de4ddc898.png)

![Screenshot 2020-01-24 at 15 46 50](https://user-images.githubusercontent.com/1951107/73082310-25ae1f80-3ec1-11ea-93dd-4521f5a2d104.png)

![Screenshot 2020-01-24 at 15 47 03](https://user-images.githubusercontent.com/1951107/73082322-2c3c9700-3ec1-11ea-85a4-e82ab849deb4.png)

**Comment by rouault** [comment]
@jef-n mentionned that the OSGeo certificate used for signing Windows builds had expired. Maybe this is the same root cause here ?

**Comment by andreasneumann** [comment]
I would also suspect that is the expired OSGeo certificates fault. As far as I know we use the same certificate also for MacOS.

**Comment by Temitaio** [comment]
Worked like a charm! Thanks @gioman

**Comment by dxander** [comment]
Thanks.   I got both versions QGIS and QGIS3.10 to open using the above tip.  System Preferences --> Security & Privacy --> Open Anyway.

**Comment by dmatranga-bayer** [comment]
Going to Security & Privacy > Open Anyway still didn't work for me. I had to run a command to remove QGIS from Apple's quarantine:

```xattr /path/to/MyApp.app```

then

```sudo xattr -r -d com.apple.quarantine /path/to/MyApp.app```

**Comment by gloriamacia** [comment]
I managed to download 3.22 but the app once installed on Mac will not open :(

**Comment by Gustry** [comment]
@elpaso and @nyalldawson, we pinned this issue, because it's a very common bug report, so we would expect that people can see this ticket before creating a new one. (even if I might change nothing)

It would be nice I think to update the website indeed when clicking on the link to download the mac package.

**Comment by loveEARs** [comment]
Go to Security & Privacy. Click the Open Anyway button in the General pane to confirm your intent to open or install the app.
This works for me. 
Mine is MacBook Pro with Catalina.

**Comment by gymate-1** [comment]
Why don't you update the OSGeo certificate instead? This issue is quite annoying.

**Comment by pgzmnk** [comment]
How is this still an issue?

**Comment by eapower** [comment]
The "Open Anyway" button in Security & Privacy doesn't resolve it for me -- results in the same alert. (Big Sur 11.7.6). Any suggestions?

**Comment by dgillis91** [comment]
It's an issue for people who have corporate devices with restrictions. I'm happy to make any changes and submit a PR, but I'd need some guidance. I don't really know what needs to be changed. 

If some one can point me in a direction to research, I can work on some changes over probably two weeks. 

Would really love to use this at work.

**Comment by gy-mate** [comment]
@dgillis91 Thank you for your work in advance!

I only referred to the [OSGeo certificate](https://wiki.osgeo.org/wiki/OGC_Certification_Services) because I saw [rouault's](https://github.com/qgis/QGIS/issues/34018#issuecomment-578198502) and [andreasneumann's](https://github.com/qgis/QGIS/issues/34018#issuecomment-578241053) comments above mentioning it. Unfortunately I'm not familiar with the repository, but @jef-n and @andreasneumann might be able to help you.

**Comment by estyrke** [comment]
Surely the solution to "the software is signed with an invalid certificate" can't be "just ignore the signature", which is the advice given here. Or am I missing something? I would prefer to not have to bypass security checks like this, but of course I understand if it's expensive and/or otherwise infeasible to provide a proper signature. In that case it's probably a good idea to mention this here.

**Comment by smsm1-ito** [comment]
With Sequoia the security has got stricter. This means that we can't use the ignore signature method within the corporate environment without it being correctly signed.

**Comment by newzealandpaul** [comment]
This is a real issue in corperate environments where users cannot, for good reason, ignore signing.

**Comment by dgillis91** [comment]
Been a while. I didn’t have notifications on. 

I’m missing something super easy here. I do mostly cli development and it’s internal. I understand what signing is generally, but don’t understand how it relates to macOS applications. I haven’t done desktop dev. 

I’m going to go talk to a robot but I welcome links as well.

**Comment by newzealandpaul** [comment]
> Been a while. I didn’t have notifications on.
> 
> I’m missing something super easy here. I do mostly cli development and it’s internal. I understand what signing is generally, but don’t understand how it relates to macOS applications. I haven’t done desktop dev.
> 
> I’m going to go talk to a robot but I welcome links as well.

It is something the core development team need to do. Signing provides proof the software was released by the org or person who claims to have released it. So the QGIS Development Team would need to sign the releases.

**Comment by dthuynguyen** [comment]
Hi 
I installed the QGis and got problem as attachment - I have MacOS 15.3.1. Please give guideline how to bypass

<img width="274" alt="Image" src="https://github.com/user-attachments/assets/04282f82-0e68-43be-a273-4b4620a52116" />

**Comment by jelmer3000** [comment]
You can find out how to open it in this thread higher up. 

However, QGIS should REALLY fix this?

**Comment by gmydda** [comment]
This really should be fixed, and probably shouldn't have been closed. The above solution is a *workaround,* not a solution

**Comment by Gustry** [comment]
Have a look to the recent work done in https://github.com/qgis/QGIS/pull/60039 ;-)
