### ISSUE TITLE
To_dms positive values only

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#34123]
**Feature description.**
Could there be an option to force the output to be between 0 and 360 instead of -90 and 90 or -180 and 180.

**Comment by jgrocha** [comment]
The `to_dms` output (in `x` axis) goes from -180 to 180, right?

Example: `to_dms(182.5432, 'x', 3) = -177°27′24.480″`

**Comment by roya0045** [comment]
Using y I get -90 to 270, in order to coerce it to 0-360 I must do some annoying things to check for a -, offset it by 90, parse the data, invert it from negative to positive and some other stuff. This is quite silly.

**Comment by agiudiceandrea** [comment]
@roya0045 The `to_dms` function is intended to be used for the formatting of geographic coordinates values, so it should _wrap around_ the values for x (longitude) in the range -180 to 180 and for y (latitude) in the range -90 to 90.

In QGIS 3.10.1 I didn't experience the  "-90 to 270" behaviour. Could you please provide an example?

A new function or the modification of the existing function is required in order to convert to dms without _wrapping around_ the value, for more general purpose.

In the meantime, it could be used something like this (for positive values, _wrapping around_ the output in the range 0 to 360):
`concat(floor(182.5432%360), substr(to_dms(182.5432%1, 'x', 3),2))` = '182°32′35.520″'
`concat(floor(382.5432%360), substr(to_dms(382.5432%1, 'x', 3),2))` = '22°32′35.520″'

**Comment by roya0045** [comment]
@agiudiceandrea I agree that the floor substring method is better, if values are don't get warped to -90.

I only tested on 3.4 for the -90 270, I'll try on master when I have the time.

**Comment by agiudiceandrea** [comment]
> I only tested on 3.4 for the -90 270, I'll try on master when I have the time.

That is strange. I've also tested on 3.4.5 and 3.4.9, but I cannot reproduce the reported behaviour.

**Comment by roya0045** [comment]
@agiudiceandrea no you're right, it's within -90 and 90.

**Comment by roya0045** [comment]
found a workaround similar to @agiudiceandrea 's proposal, should be good enough.
