### ISSUE TITLE
Concat function tolerant of null values

### ISSUE THREAD

**Issue by Geojim** [qgis/QGIS#34133]
When labeling with multiple fields, concat won't label if any field is null. Current workaround is to combine with coalesce function, but seems needless complcated.

**Comment by DelazJ** [comment]
I can't confirm on 3.10
@Geojim can you provide the version, OS you are using and probably expression and dataset you are using? Thanks.

**Comment by Geojim** [comment]
Using 3.10 on w10 x64.

Issue arises for multi-field labels, where one attribute is null meaning no other attributes are labelled. ie for a label 
concat("column1",'\n',"column2")won't work if any column is null, whereas 
coalesce("column1",'') || '\n'  ||  coalesce("column2",'') would.

Same thing here [https://gis.stackexchange.com/questions/122199/displaying-multiple-fields-as-labels-if-one-field-is-null-in-qgis](url)

Bit messy imho.

**Comment by DelazJ** [comment]
I Still can not reproduce on 3.10 windows 10: `concat("column1",'\n',"column2")` result is not null if any of the fields is null. 
The discussion you are linking to is 5 years old and five years are like decades in QGIS dev life 😄 . Meanwhile you got #2118 (and #1947) so I'm afraid your issue is local.
