### ISSUE TITLE
Scale bar defaulting to ellipsoid

### ISSUE THREAD

**Issue by mapman1980** [qgis/QGIS#34154]
**Describe the bug**
Version 3.10.2
Data layers are using EPSG:27700, project is set to EPSG:27700
When adding a scale bar to a layout, the scale is incorrect. It appears to match the ellipsoid distance measurements rather than the cartesian measurement. I can't make the scale bar switch to cartesian mode like I can the measurement tool. 

**How to Reproduce**

1) Open a data layer in EPSG:27700 (e.g. outline of Britain). 
2) create a new layout
3) add the map frame
4) add a scale bar and check accuracy

**QGIS and OS versions**
Version 3.10.2
Windows 10

**Comment by gioman** [comment]
@mapman1980 can you add a sample project (with sample data and the layout), thanks!

**Comment by mapman1980** [comment]
Hi - apologies, I've sorted the issue:

1) Downloaded and installed OSTN15_NTv2_OSGBtoETRS.gsb
2) Restarted **computer system**, not just QGIS and the issue resolved

Hope this helps anyone who comes across this issue with EPSG:27700 and the scale bar using Ordnance Survey data. Looks like it was an issue previously (https://forum.manjaro.org/t/latest-qgis-update-3-8-is-missing-has-error-with-datum-transformations/94400). 

Thank you!

**Comment by mapman1980** [comment]
I'm reopening this because it isn't resolved as I thought and is driving me crazy!!

Here is an example project:

[Example.zip](https://github.com/qgis/QGIS/files/4185842/Example.zip)

The scale bar is way off and I have gone through the settings and made sure all the CRS are EPSG:27700.

**Comment by mapman1980** [comment]
> @mapman1980 can you add a sample project (with sample data and the layout), thanks!

No problem - example attached above! This issue is making me feel very stupid - I'm sure I'm missing something...

**Comment by jdugge** [comment]
@mapman1980 In your example project, the scale bars are extremely long because they are set to a "Segment length" of "1000 units" with the "Scalebar units" set to "Kilometers". Either setting the "Scalebar units" to "Meters" or setting the "Segment length" to "10 units" makes the scale bar lengths more reasonable.

Since the original issue is about ellipsoidal versus Cartesian distances, I am assuming this is not actually the problem you are trying to solve. Could you describe the problem in a bit more detail (what would you expect the scale bars to look like, how did you notice that they are using the wrong distance calculation method)?

**Comment by Pedro-Murteira** [comment]
@mapman1980 Hello, I've tested this issue and tried to replicate it but to no avail. The scale added in the map layout match the measurements i've done on the map itself. Are you still having this issue or am I missing something in these tests? (QGIS 3.16.15 and 3.22.2.)
