### ISSUE TITLE
Cannot Create Printer Error on Export to GeoPDF when map is rotated

### ISSUE THREAD

**Issue by tveinot** [qgis/QGIS#34438]
**Describe the bug**
When exploring the GeoPDF options I created a number of PDF's using the GeoPDF options in the Print Composer in QGIS 3.10.0. When I applied a roation <0 the export to GeoPDF errors with "Could Not Create Printer"

**How to Reproduce**
Try and export any Print Composer to GeoPDF with a rotation value applied to the Map Layout.

**QGIS and OS versions**
QGIS 3.10.0
Windows 10

**Comment by gioman** [comment]
>  QGIS 3.10.0

@tveinot please update to 3.10.2 and see if the problem persist.

**Comment by roya0045** [comment]
@tveinot when you name the output, are you using the name of something that already exists or a new file?

**Comment by tveinot** [comment]
> @tveinot when you name the output, are you using the name of something that already exists or a new file?

I tried overwriting an existing file and creating a whole new one with a new name.

**Comment by roya0045** [comment]
And both failed?

**Comment by tveinot** [comment]
Yes, both returned the same error, I also restarted QGIS in between the attempts. Setting the roation of the map to 0 allowed the export to go through without error.

**Comment by NykoTera** [comment]
I'd like to complete this issue :

**Describe the bug**
I can't export (in pdf, picture or svg) large format (A0) with rotation between 0° and 90°. QGIS crash and then I've got to restart QGIS. It seems that I can print the map in A4 to A1 (A0 still crash) by using pdfcreator.

How to Reproduce
Try and export any Print Composer in large format (A0) with a rotation value applied to the Map Layout.

QGIS and OS versions
QGIS 3.10.2
Windows 10

**Comment by roya0045** [comment]
@nyalldawson I had a cursory glance at the geopdf code and it doesn't appear to be ways to handle rotation, though it might be doable in some annoying way, but I'm not sure. Or could there be something preventing thing?

**Comment by arno974** [comment]
I confirm also this issue 

**Describe the bug**
Exporting a GeoPDF with a rotation other than 0 or 360° (even 1° or 359°) generates the error "Could Not Create Printer". After changing the rotation to 0 or 360, the GeoPDF is correctly generated. I've also tried to set the rotation value using the field expression (variable) and the problem remains. 

**How to Reproduce**
In a Map Composer add a map object and apply a rotation to the map.
Then generate a GeoPDF. 
Error message => "Could Not Create Printer" 

**QGIS and OS versions**
QGIS 3.10.2 & QGIS 3.12
Windows 10

**Comment by nyalldawson** [comment]
This is not supported by GDAL -- I'll add an explicit warning to QGIS explaining the cause of the error

**Comment by archaeobotics** [comment]
@nyalldawson Might this problem be related to the one described here?

**Describe the bug**
Trying to export a GeoPDF including layers with a rotated custom CBS (Proj string: _+proj=omerc +lat_0=47.173836897 +lonc=8.4550705414 +alpha=29.3 +k=1 +x_0=750 +y_0=250 +gamma=0 +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs_) generates the error "Could Not Create Printer". The problem was not present before GeoPDF export was introduced. This seems to only occur with "old" layers digitized or imported prior to the release of QGIS 3.10, newly digitized data seem to work well.

**How to Reproduce**
In Map Composer add a map object with al layer in a rotated custom CBS, then try to export a GeoPDF.
Error message => "Could Not Create Printer"

**QGIS and OS versions**
QGIS 3.10 and 3.14.1 on Windows 10
