### ISSUE TITLE
[Oracle]Error on save geometries because wrong default values

### ISSUE THREAD

**Issue by j-lippmann** [qgis/QGIS#34482]
hello,
i think there is an issue with default values for attributes, if i use oracle provider and create or paste new geometries. details in the gif's. the behaivior depends on the datatype. in my cases varchar and number. create statements are in the txt file. 

the error occur with and without showing attribute form

affected versions: 3.4.15;3.10.2 actual master

hope someone can reproduce this issue.

thanks
jan

[create_gis_gruen_tables.txt](https://github.com/qgis/QGIS/files/4208409/create_gis_gruen_tables.txt)
![oracle_save_error_varchar](https://user-images.githubusercontent.com/32189541/74587134-149f8c80-4fef-11ea-8efc-e438efad16c2.gif)
![oracle_save_error_number](https://user-images.githubusercontent.com/32189541/74587135-16695000-4fef-11ea-8a4a-7fa2362549b7.gif)

**Comment by SebastienPeillet** [comment]
I reproduced the bug, it's not due to the dataset.

There is two bugs in one.

At first the obvious one from the failed SQL request : `SELECT 0   NULL FROM DUAL;`

Here Oracle provider tries to evaluate default value of NUMMER field and this value is "0  NULL" (we will we further why because it's the second bug). Because the string contains space, Oracle understand it as two distinct element, but there a missing coma.

This can be fix in [QgsOracleProvider::evaluateDefaultExpression](https://github.com/qgis/QGIS/blob/master/src/providers/oracle/qgsoracleprovider.cpp#L1292) by adding quote to the value.


The second bug is about the default value itself : '0  NULL'

Default values are retrieving from the `data_default` field in `all_tab_columns` table (see [here](https://github.com/qgis/QGIS/blob/master/src/providers/oracle/qgsoracleprovider.cpp#L604)).

And long story short : 
- `data_default` is a long type column
- long is a type that can contains a lot of data, so data is readed in a "piecewise" mode (see [qsql_ocispatial.cpp](https://github.com/qgis/QGIS/blob/master/src/providers/oracle/ocispatial/qsql_ocispatial.cpp#L1535) and [oracle documentation](https://docs.oracle.com/database/121/HETER/GUID-9F828F0D-60ED-4F7D-92D5-0F3DFE1C9AA7.htm#HETER4069))
- piecewise read mode concatenates the value piece by piece (for a single row), but after the first row the value is not cleared, so it concatenates the current default value with the previous one, etc

The solution is to clear values if piecewise mode is used.
