### ISSUE TITLE
Selective masking forces rasterisation of map

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS#34640]
Having spent some time recently on a heavily cartographic project, I've found it frustrating that I cannot utilise the new selective masking labeling capability due to the forced map rasterisation which occurs whenever this option is selected.

In my opinion this limitation severely restricts the usefulness of the feature. It's a feature specifically designed for high-quality cartographic production, yet is unable to be used for this purpose.

**Comment by andreasneumann** [comment]
@nyalldawson - do you see a way to implement selective masking without rasterization?

**Comment by nyalldawson** [comment]
I think a QPicture object could be used as the temporary render surface instead of an image -- that would losslessly keep all vector artwork as vectors

**Comment by mhugo** [comment]
@nyalldawson Back on this topic ...

If I understand correctly, the plan with QPictures could be:
- for the sequential rendering, rather than forcing to allocate QImage when selective masking is enabled, allocate QPictures for mask images
- compose QPictures rather than QImages with QPainter::drawPicture and QPainter::CompositionMode_xxx Do these composition modes work with qpictures ?

So, the decision to rasterize would be transfered to QPicture when the composition is done, right ? We should then have vectors everywhere it is possible and possibly some rasters when the painting device is not able to compose / apply effects in a "vector" way ?

**Comment by nyalldawson** [comment]
This was fixed in 3.26
