### ISSUE TITLE
Deir ez Zor / Levant Stereographic

### ISSUE THREAD

**Issue by mahmoud2728** [qgis/QGIS#34695]
Hello,
I am having a problem with the program,
It is not accurate to convert the coordinate system that we use in Lebanon with satellite maps !!

![Screenshot 2020-02-25 21 53 53](https://user-images.githubusercontent.com/61476338/75354476-b196db00-58b5-11ea-85d7-60eca07838a2.png)
![Screenshot 2020-02-25 21 53 43](https://user-images.githubusercontent.com/61476338/75354499-b78cbc00-58b5-11ea-957a-b460c906b994.png)
![Screenshot 2020-02-23 11 35 40](https://user-images.githubusercontent.com/61476338/75354525-be1b3380-58b5-11ea-8015-8a2955eb0add.png)

https://www.gulf-up.com/utde6pusjpu0

**Comment by gioman** [comment]
@mahmoud2728 what is the CRS of your data?

[KSY-896.zip](https://github.com/qgis/QGIS/files/4256941/KSY-896.zip)

**Comment by mahmoud2728** [comment]
![Screenshot 2020-02-26 18 41 14](https://user-images.githubusercontent.com/61476338/75366565-98972580-58c7-11ea-8ede-2e1a5e70d06a.png)

**Comment by gioman** [comment]
I tested on several QGIS releases (down to 2.18) so with several versions of GDAL and PROJ and that lines shows always in the same place. My gut feeling is that the vector is originally misplaced. You could check also in other software to have a better idea if the issue is really in QGIS or not.

I converted your sample to KML with https://mygeodata.cloud/converter/dxf-to-kml (it allows you to choose the CRS of your input data) and the result is the same also on google earth

![Screenshot_20200226_170451](https://user-images.githubusercontent.com/1951107/75368761-21a76000-58ba-11ea-9cd2-876aa499d8f9.png)
