### ISSUE TITLE
Close vertex for line when editing does not work on QGIS 3.10 and 3.12 win 10

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#34793]
TW: https://twitter.com/lo_bartoletti/status/1233824697080569858
PR: https://github.com/qgis/QGIS/pull/34217

@lbartoletti 

grazie

**Comment by uclaros** [comment]
Could this be that Close line does not work when Advanced Digitizing is enabled, since the C key is already hard-coded to *construction mode*?
Hard-coding keyboard shortcuts like that is not a good idea, it may lead to collisions like this one. Also leaves less keys available to the user to map actions. They should be customizable through *Keyboard Shortcuts...* and portable between profiles.
Close line would be better to be triggered with a modifier like ctrl+right click or shift+right click, since right click already ends digitizing.

**Comment by pigreco** [comment]
@lbartoletti 

still does not work on win 10
neither `C` nor `shift + c` works
I don't understand what I'm wrong.

**Comment by uclaros** [comment]
@pigreco The shortcut to close the line settled to `Shift+RightClick`, since `C` was occupied by advanced digitizing.

**Comment by pigreco** [comment]
@uclaros 

thank you very much,
I did not understand.

Shift + RightClick works well!

**Comment by uclaros** [comment]
You're welcome :)
