### ISSUE TITLE
QGIS Server: WMTS only in CRS 3857

### ISSUE THREAD

**Issue by Abelon38** [qgis/QGIS#34826]
Hi!

It seams that QGIS server can produce WMTS in CRS 3857 only. I am using QGIS server 3.10 with FastCGI and QGIS Desktop 3.10 on Windows server 2012.

I wonder if this is a known issue?

Best Regards.
Abel

**Comment by gioman** [comment]
@Abelon38 is this a question or a bug report?

**Comment by Abelon38** [comment]
Hi!

yes, I think this is a bug, Is there someone else having the same problem?

BR/Abel

**Comment by JeffGregg** [comment]
Hi!
I have the same issue on QGIS Server 3.10/Ubuntu 18.04. When I use other CRS (i.e. 2177) then generated data is empty, but when I invert x and y in "Advertised extent" (project properties/QGIS Server) then data is produced but in a wrong location (see attached picture). Is this problem of only 3.10 version? I`ve never used older versions.

![issue](https://user-images.githubusercontent.com/57112089/78010134-4de35000-7342-11ea-84c6-1fbc1c76898a.png)

**Comment by leojth** [comment]
Hi!
[tilesets.txt](https://github.com/qgis/QGIS/files/4456513/tilesets.txt)
I have the same issue with QGIS Server 3.12 on Windows. One clue might be that the TileMatrix calculation seems to go wrong. The built-in projections (EPSG:4326 and EPSG:3857) do work and shows correct min/max values in TileMatrixSet, but all other projections I have tried do not work probably because the min/max values are always set to the same value. See attached text-file that contains TileMatrix for EPSG:4326 (correct) and EPSG:32633 (wrong). When requesting a tile for other projections than the built-in, I always get "TileRow is unknown" error response.

Kind Regards
Joel

**Comment by gioman** [comment]
Work fine with the latest QGIS 3.10 server on Ubuntu 20.04.

**Comment by leojth** [comment]
Still doesn't work in QGIS 3.16 server on Windows

**Comment by Abelon38** [comment]
Nop! I just tried on windows server with QGIS server 3.16 and the problem still remains.  

Best regards! 
Abel

**Comment by tudorbarascu** [comment]
I also have this problem but as I am using mapproxy I didn't investigate further. However, it would be nice to have it fixed.

**Comment by rldhont** [comment]
QGIS Server WMTS is not only in 3857 CRS. In issue https://github.com/qgis/QGIS/issues/39040 the WMTS is in 28992 CRS.
