### ISSUE TITLE
CRS settings don't work properly

### ISSUE THREAD

**Issue by DG-85** [qgis/QGIS#34918]
I have seen CRS settings with respect to layers have been slightly revised in QGIS 3.10.x.
In this context I have observed some bugs:

1) Global CRS settings dont have any effect on "QSettings".
   "Projections/defaultBehavior" stays unchanged.
   (This has an impact on my plugin)

![error1](https://user-images.githubusercontent.com/61877347/76092761-3d002280-5fc0-11ea-912c-e6f94e54dd61.jpg)

2) When I work with QgsVectorLayer a wrong CRS is used as default.
   Same settings are used as in Figure 1)

![error2](https://user-images.githubusercontent.com/61877347/76093126-c31c6900-5fc0-11ea-9c8f-5440174fcf74.jpg)

If I change it to "Prompt for CRS", no prompt appears and still wrong CRS is used.

In QGIS 3.8.x and lower I didn't have these problems.

**Comment by stev-0** [comment]
Hi @DG-85 I copiled 3.8.3 for you (which is out of support) and I noticed the following differences.

- Firstly the `defaultBehaviour` setting which you refer to above has been renamed to `unknownCrsBehavior`, but it is saved, so probably you just have to change the name of the setting

- I think that there is a regression with this setting as it doesn't seem to make any difference to the CRS - I will try and have a look - it could be a case of someone forgetting that the setting name had changed

**Comment by DG-85** [comment]
I tried to use `unknownCrsBehavior` in QGIS 3.10.3. The return is always `None`.
Could it be that this setting is not jet writen to `QSettings()`?

```
s = QSettings()
def = s.value("Projections/unknownCrsBehavior")  
```

In Advanced Setting Editor I miss it too or did you place it on different category?

**Comment by stev-0** [comment]
try:

`behavior = s.value("projections/unknownCrsBehavior")`

projections has been changed to lower case

Still have to look into why it's not making a difference to CRS.

**Comment by nyalldawson** [comment]
Changing raw settings keys isn't considered stable API, so code like this will always be potentially fragile. As @stev-0 has pointed out, the setting was moved to 

    behavior = QgsSettings().enumValue( "/projections/unknownCrsBehavior", QgsOptions.UnknownLayerCrsBehavior.NoAction, QgsSettings.App )

using the values from the QgsOptions.UnknownLayerCrsBehavior enum.

**Comment by stev-0** [comment]
@nyalldawson there is definitely a difference of behaviour between 3.8.3 and master where in the former there is a CRS prompt for a new in-memory QgsVectorLayer without a specified coordinate system, and nothing in master. Is this expected behaviour? If so then the option `Prompt for CRS` doesn't seem to be obeyed by this option.

**Comment by nyalldawson** [comment]
@stev-0 memory layers have had an odd thing where no crs explicitly defined = assigned wgs84, since as long as they've been around. I think my changes fixed a bug whereby in earlier qgis versions you were being incorrectly asked for the crs, even though it was actually wgs84 for these memory layers!

(I want to change this in 4.0 - an undefined crs should remain undefined, not be silently converted to wgs84. Note that this impacts memory layers only)


What exactly are you trying to achieve? Do you want users to have to pick a crs manually?

**Comment by stev-0** [comment]
No, no axe to grind here - that sounds fine. I agree it's more sensible to directly set the projection in the code, and that shouldn't follow this particular option. Thanks for the explanation

**Comment by nyalldawson** [comment]
@stev-0 i'm still curious about your particular use case -- I might have some suggestions on how to address it

**Comment by DG-85** [comment]
If I use it in this way `vl = QgsVectorLayer("Point?crs=", "Test", "memory")` in all versions CRS settings behave like expected.
