### ISSUE TITLE
CRS not recognized when saving vector to SQlite or Spatialite

### ISSUE THREAD

**Issue by Tjeu** [qgis/QGIS#34992]
**Describe the bug**
QGIS 3.10 doesn't recognize CRS anymore from SQLite. Points end up in the wrong location.

**How to Reproduce**

1. Create a new shapefile (in EPSG:23031)
2. Convert it with ogr2ogr

        ogr2ogr -f SQLite -overwrite -s_srs EPSG:23031 -t_srs epsg1311-wkt.txt -a_srs EPSG:25831 -mapFieldType Real=Integer test.sqlite test.shp
[epsg1311-wkt.txt](https://github.com/qgis/QGIS/files/4317546/epsg1311-wkt.txt)

3. Add the result to QGIS 3.4
4. Look at the layer properties
![image](https://user-images.githubusercontent.com/11708371/76407642-f3328600-638b-11ea-9a08-cda7b692423b.png)
5. Add the result to QGIS 3.10
6. Look at the layer properties
![image](https://user-images.githubusercontent.com/11708371/76406988-f6794200-638a-11ea-95ad-8f2d650c0e55.png)
7. In QGIS 3.10 there is now also a 230 meter distance between the points.

**QGIS and OS versions**

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)

**Additional context**
When I don't do a transformation with ogr2ogr the CRS of the SQLite file is still unknown.

**Comment by gioman** [comment]
@Tjeu this is an odd one. I confirm it and no need to use ogr2ogr to do the transformation, is enough to use QGIS "save as..." functionality.

Saving a copy of a vector in 23031 to 25831 results in a vector with a CRS that is recognized fine if the output format is SHP or GPKG (haven't tested others) but not ok if the output format is SQlite or Spatialite. @rouault any idea?

Also seen on 3.12 and master.

**Comment by nyalldawson** [comment]
I think it's worth opening a corresponding ticket on the gdal tracker.

**Comment by rouault** [comment]
> I think it's worth opening a corresponding ticket on the gdal tracker.

eh, only when there's a bug ! :-)

> but not ok if the output format is SQlite or Spatialite

In pure SQLite output, ogr2ogr out.db poly.shp -a_srs EPSG:25831, ogrinfo on out.db reports a SRS that is EPSG:25831
In Spatialite output, ogr2ogr out.db poly.shp -a_srs EPSG:25831 -dsco spatialite=yes, ogrinfo on out.db reports a SRS  that is a bound CRS of EPSG:25831. The reason is that the spatial_ref_sys table is initalized by Spatialite itself, and it contains a WKT1 definition with a TOWGS84[] clause, thus interpreated on reading as a BoundCRS. Yet another issue with the transition between the old and the new world. Not sure if a software change is needed there (apart that an hypothetical future release of spatialite removes TOWGS84[] from its CRS definitions)

**Comment by rouault** [comment]
Submitted to spatialite upstream as https://www.gaia-gis.it/fossil/libspatialite/tktview/970ab8322e4995793b6b3acb872d1e6a100af60b

**Comment by nyalldawson** [comment]
Ok, closing as an upstream spatialite issue then! 😜

**Comment by Tjeu** [comment]
Thanks so far for looking into it!
