### ISSUE TITLE
Label position & rotation

### ISSUE THREAD

**Issue by XavierCalatrava** [qgis/QGIS#35082]
In QGIS 2.18 we placed the labels using 3 fields of our layers (label_x, label_y & label_rotation). When we copy the style from QGIS 2.18 to QGIS 3.10, the fields of the position (X,Y) are copied correctly but the rotation is transformed to the expression '360-label_rotation'. The problem comes when we want to rotate any label with the Label toolbar and a window appears to select the primary key of the layer for a new Auxiliary storage. When we select the ID for the layer, all the labels of the layer lose their angle of rotation. 

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@XavierCalatrava please add the QGIS version you are using now and operating system. Also a small sample dataset + style would help a lot. Thanks.

**Comment by roya0045** [comment]
Doesn't the data defined attributes get reset when the unique fid is demanded? Can't you just change from the auxiliary field back to your other field after the prop has appeared?

I would guess that adding a check for existing data driven position and rotation would be a good thing before generating and using the auxiliary fields.

**Comment by XavierCalatrava** [comment]
QGIS version 3.10.3 (A Coruña - LTR). Windows 10.

[EscLabels.zip](https://github.com/qgis/QGIS/files/4333234/EscLabels.zip)

**Comment by nyalldawson** [comment]
There's really nothing which can be done to change this -- rotation for labels in qgis 2 was incorrectly calculated using the opposite direction to symbols. This was fixed in 3, and the expression conversion automatically applied to avoid breaking existing projects.

Workaround is:
1. Use field calculator to update the stored rotation field values to the new direction
2. Change the data defined rotation back from the expression to the raw field value.
