### ISSUE TITLE
Deleting attributes should not cause repeated reload of features (Attribute Table)

### ISSUE THREAD

**Issue by arc12** [qgis/QGIS#35175]
**Describe the bug**
Features are re-loaded each time an attribute is deleted (Attribute Table). When a large number of attributes are being deleted from a layer with many features(e.g. from an OSM vector download), this gives an unacceptable delay (25 minutes and counting for my case now!).

Features should only be reloaded after all attributes have been deleted.

**How to Reproduce**
Observed with a geopackage but the behaviour is an application-level bug.

Given a layer with a large number of features (e.g 70,000) and a number of attributes which are to be deleted (demonstrable with a few but very troublesome with lots).

Select several attributes for deletion in the normal way, from the attribute table.

Trigger the deletion and watch the Attribute Table popup keep popping up to report nnnn features loaded. It seems to do this for each attribute.

**QGIS and OS versions**
3.6 on Windows

**Comment by gioman** [comment]
>  3.6 on Windows

@arc12 maybe it won't change anything, but you really must test with 3.10.3 or 3.12, because 3.6 is way (way) too old.

Anyway you are probably hitting a long known issue (please search for similar tickets): on large tables you basically can't remove columns when the same table is open. If you do the same from the vector properties, and with the table closed, performance is better.

**Comment by Pedro-Murteira** [comment]
@arc12 I've tested this issue on QGIS 3.22.3. with a layer containing around 50.000 features and I seem to not be able to replicate it anymore. Are you still having this issue?
