### ISSUE TITLE
qgis corrupt outputs with GRASS r.sun.insolation

### ISSUE THREAD

**Issue by aliasatp** [qgis/QGIS#35347]
Hi all, I realised that qgis 3.10/3.12 releases produce corrupt outputs while using r.sun (GRASS). I tested the same dataset with qgis 3.8 and outputs are ok. Have anybody experienced the same issue with r.sun?

**Comment by gioman** [comment]
@aliasatp not enough infos: add sample data and detail expected VS obtained results. Also you miss to say on what platform do you work.

**Comment by gioman** [comment]
@aliasatp also are you using GRASS plugin or GRASS Processing?

**Comment by gioman** [comment]
@aliasatp also have you tested on native GRASS using the same GRASS versions used in QGIS 3.8 and 3.10/2?

**Comment by aliasatp** [comment]
Hi simply have 2 standalone installations, 3.8 and 3.10/3.12 on WINDOWS 10. I run Qgis with GRASS and I use GRASS processing tools. Output rasters are ok with 3.8 and corrupted with 3.10/3.12. Simply the rasters have stripes on it

**Comment by gioman** [comment]
@aliasatp please have a look at my previous message: attach sample data and specify the parameters you are using. Also you must test the same tool in native GRASS, to allow us understand if the problem is in GRASS or QGIS.

**Comment by aliasatp** [comment]
3.10/3.12 version
![image](https://user-images.githubusercontent.com/62659943/77556813-3d9e2180-6eb9-11ea-81ab-e72cd89001e5.png)

**Comment by aliasatp** [comment]
qgis 3.8.3
![image](https://user-images.githubusercontent.com/62659943/77557100-a4233f80-6eb9-11ea-9356-673dc77019b9.png)

**Comment by aliasatp** [comment]
> @aliasatp please have a look at my previous message: attach sample data and specify the parameters you are using. Also you must test the same tool in native GRASS, to allow us understand if the problem is in GRASS or QGIS.

ok

**Comment by aliasatp** [comment]
dtm, esp (aspect), slo (slope)
I tested simply with one day elaboration. r.sun.insolation
[dati_qgis.zip](https://github.com/qgis/QGIS/files/4381958/dati_qgis.zip)

**Comment by gioman** [comment]
>  I tested simply with one day elaboration. r.sun.insolation

@aliasatp do you mean r.sun.insoltime?

the tool has **several** input parameters and several outputs, you must tell us what parameters are you using and what outputs are wrong.

**Comment by aliasatp** [comment]
the only inputs are the dataset I sent you. I set a day of the year as elaboration date. All optional inputs aren't set. All outputs are as I posted before

**Comment by gioman** [comment]
So far I haven't been able to pinpoint where the issue is. What I tested is the following:

1) I confirm that on QGIS 3.8/Windows (that uses GRASS 7.6) works as expected

2) Also work as expected on Ubuntu 18.04 with QGIS 3.10/12 and GRASS 7.4

3) On Windows using native GRASS 7.8 (the one used by QGIS 3.10/12) it also works ok

4) I can't see a difference in the GRASS command as issued by QGIS 3.8

`r.sun elevation=rast_5e7e27dce62fb2 aspect=rast_5e7e27dce62fb3 aspect_value=270 slope=rast_5e7e27dce67254 slope_value=0 albedo_value=0.2 day=1 step=0.5 distance_step=1 npartitions=1 insol_time=insol_timed0bb595f48c84a1e93d2d8b0b3504ba8 beam_rad=beam_radd0bb595f48c84a1e93d2d8b0b3504ba8 diff_rad=diff_radd0bb595f48c84a1e93d2d8b0b3504ba8 refl_rad=refl_radd0bb595f48c84a1e93d2d8b0b3504ba8 glob_rad=glob_radd0bb595f48c84a1e93d2d8b0b3504ba8 --overwrite`

and 3.10/12

`r.sun elevation=rast_5e7e1ab15a3a88 aspect=rast_5e7e1ab15a77f9 aspect_value=270 slope=rast_5e7e1ab15a77f10 slope_value=0 albedo_value=0.2 day=1 step=0.5 distance_step=1 npartitions=1 -p insol_time=insol_time1bc6b9f52a044846aab40b9e0bb914bf beam_rad=beam_rad1bc6b9f52a044846aab40b9e0bb914bf diff_rad=diff_rad1bc6b9f52a044846aab40b9e0bb914bf refl_rad=refl_rad1bc6b9f52a044846aab40b9e0bb914bf glob_rad=glob_rad1bc6b9f52a044846aab40b9e0bb914bf --overwrite`

5) in all the cases the input rasters are imported with r.external (but I also tested using r.in.gdal with native GRASS, and still results are ok).


@alexbruy any idea?

**Comment by roya0045** [comment]
Could it be a display issue or is it the values that are wrong?

**Comment by gioman** [comment]
7) it is also NOT ok on 3.10.4 on Linux and Ubuntu 20.04, so with GDAL 3 like on Windows.

The piece of software that is different where it works and where it does not, is GDAL so the issue could be there.

**Comment by gioman** [comment]
> The piece of software that is different where it works and where it does not, is GDAL so the issue could be there.

but still works as expected on native GRASS (the same GRASS installation used by QGIS).

**Comment by gioman** [comment]
> Could it be a display issue or is it the values that are wrong?

@roya0045 values are wrong.

**Comment by nyalldawson** [comment]
Does changing the GRASS "use external" options from the processing settings options fix this?

**Comment by aliasatp** [comment]
GRASS "use external" options doesn't fix the problem

**Comment by gioman** [comment]
> Does changing the GRASS "use external" options from the processing settings options fix this?

also using r.external instead of r.in.gdal in native GRASS makes this module outputs be as expected. So it really seems something on QGIS side, but I'm not really sure how that could be.

**Comment by gioman** [comment]
Works fine on 3.16 on Windows too.
