### ISSUE TITLE
Drag and drop of a grouped WMS

### ISSUE THREAD

**Issue by eurojam** [qgis/QGIS#35682]
Drag and drop of a grouped WMS with several layers from the browser into the layertree seems not be possible in QGIS (version 3.12.1, see picture 1 below). From the Data Source Manager it is possible to add the whole wms with all groups, but the grouping will be lost. The several layers will be loaded as one layer (see picture 2). In ArcGis it is possible to load a grouped wms and having the groups and layers in the layer tree (see picture 3).   

![wms1](https://user-images.githubusercontent.com/46351209/78872766-0cd9f280-7a4a-11ea-9556-a3ea0027d492.png)
![wms2](https://user-images.githubusercontent.com/46351209/78872773-0e0b1f80-7a4a-11ea-94a6-ba670e8f3923.png)
![wms3](https://user-images.githubusercontent.com/46351209/78872771-0d728900-7a4a-11ea-8418-9e3bb0f78fe2.png)

**Additional context**

**Comment by andreasneumann** [comment]
I think there are pros and cons for both ways:
- performance wise the QGIS way is much better because there is just a single request to the group vs. many requests for each layer
- flexibiltiy wise the ArcGIS way of loading each layer is better, but performance may suck

I think the user should have the choice to load the WMS as a single group layer or multiple layers with sub groups. If the user doesn't need to toggle the visibility of individual layers, the QGIS way of loading the whole group as a single WMS layer is preferable.

**Comment by Samweli** [comment]
Hi @eurojam, this is fixed here https://github.com/qgis/QGIS/pull/35148, should available in the next point release, thanks.

**Comment by cath222ou** [comment]
@Samweli There is the same problem with QGIS Desktop 3.16 and 3.20.

**Comment by Sven1403** [comment]
@Samweli this isnt working.. tried it on QGIS 3.32.0 and 3.36.2
