### ISSUE TITLE
Rasters with RPC georeferencing information are misaligned

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#35796]
Raster files with airborne imagery may use rational polynomial coefficients (RPC) with georeferencing information. See here for an introduction on the topic:
- https://fwarmerdam.blogspot.com/2013/09/exploring-rpcs.html
- https://gdal.org/development/rfc/rfc22_rpc.html

The problem is that in order to georeference the imagery correctly, one of the input parameters of the transformation is elevation of the terrain of the image. Without that, image will be scaled incorrectly. Right now, GDAL sets the assumed elevation to zero, so the images get misaligned.

We need a way to manually set the assumed elevation (it can be passed to GDAL using RPC_HEIGHT variable).

In addition to that, we should do a guess on the good initial value of RPC_HEIGHT. From what I understand, other pieces of software use HEIGHT_OFF parameter from image's RPC and it seems to be a better default than using zero elevation.

**Comment by rouault** [comment]
A good value for RPC_HEIGHT should be average elevation of the DEM under the raster, expressed as an ellipsoidal height to WGS84 (that is generally the DEM value since they are in orthometric height + the geoid undulation). For very precise orthorectification, using a DEM with RPC_DEM is the best choice.

The HEIGHT_OFF value might be a reasonable default indeed for well behaved RPCs (in which case you probably don't need to add the geoid undulation)
