### ISSUE TITLE
Random Points Along Lines Algorithm Behavior

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#35916]
With the attached line layer (roads) when using the algorithm `Random Points Along Lines` I noticed that with a great amount of points (10k) the point density is similar to a cluster:

![immagine](https://user-images.githubusercontent.com/2884884/79967227-d8752600-848e-11ea-8914-62ffa4944b7e.png)

![immagine](https://user-images.githubusercontent.com/2884884/79967272-e5921500-848e-11ea-9de8-6b15f2c97986.png)

So it seems that the algorithm is working as a distance between nodes and not as a function of the line. Isn't it?

[roads.zip](https://github.com/qgis/QGIS/files/4515304/roads.zip)

**Comment by gioman** [comment]
Is this a question?

**Comment by ghtmtt** [comment]
> Is this a question?

basically yes, but it can turn into a bug/feature request.

**Comment by gioman** [comment]
If is a question this should first be asked in the users/developers mailing lists, if it turns out that is a bug (or a feature request) then a ticket should be opened, with the appropriate wording.

**Comment by alexbruy** [comment]
Duplicates #33160.

**Comment by agiudiceandrea** [comment]
Hi @ghtmtt, the algorithm was designed to choose a random line feature and then a random segment of that line and then a random subsegment in order to generate a random point (with the minimum distance between points constraint).

The algorithm short help description was recently updated to make this behavior clear (see https://github.com/qgis/QGIS/pull/34605).

See also the updated doc https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorcreation.html#random-points-along-line

A new alg was added with a new behaviour: https://github.com/qgis/QGIS/pull/34631#issue-379314648 and https://github.com/qgis/QGIS/pull/35282

**Comment by gioman** [comment]
> A new alg was added with a new behaviour: [#34631 (comment)](https://github.com/qgis/QGIS/pull/34631#issue-379314648) and #35282

@ghtmtt closing?

**Comment by ghtmtt** [comment]
+1
