### ISSUE TITLE
Time field issue QGIS / Qfield

### ISSUE THREAD

**Issue by bakkerss** [qgis/QGIS#36345]
There is a problem proposing and storing the current time automatically if you would like to perform data entry using Qfield. The attached document describes a test which explains the problem in detail so it can be replicated. The main issue seems to originate in QGIS.

[Time field issue QGIS and Qfield.pdf](https://github.com/qgis/QGIS/files/4608907/Time.field.issue.QGIS.and.Qfield.pdf)

The requirement behind this test is to be able to store ecological information in the field. Date and time are important parameters for surveys and therefore it would be very useful to have this information proposed by default. However, due to different behavior of time in QGIS and Qfield this only seems to be possible with a workaround and manual interference.

**Comment by gioman** [comment]
@bakkerss here we should discuss only of QGIS issue, if you find a problem in Qfield this must be reported in its own tracker here: https://github.com/opengisch/QField/issues

A few notes:

The preview of the "now()" function is correct,  that function returns the data and time. So that is correct (as the preview is not defined by other settings of that specific field).

If you want to preview only the time you have to use "to_time(now())"

There is no time support in a date field in a shapefile:

https://en.wikipedia.org/wiki/Shapefile#Data_storage

"Supported field types are: floating point (13 character storage), integer (4 or 9 character storage), **date (no time storage**; 8 character storage), and text (maximum 254 character storage)"

so I guess that is expected that you are not getting the time saved in those (date) fields of your example. If you are using shapefile you really must use text fields.

Anyway I also moved my test project and data to Qfield and got results that are compatible with the notes above... so when you are digiting a point and Qfield show you the feature form it shows you the time for "date" field, but then anyway is not saved...

**Comment by gioman** [comment]
@bakkerss see also: https://github.com/qgis/QGIS/issues/36386#issuecomment-630044274

**Comment by gioman** [comment]
Closing for lack of feedback, please reopen if necessary.
