### ISSUE TITLE
Expression for default values not correctly evaluated if target field is read only

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#36360]
QGIS master.

Take the attached sample project:

[trees.zip](https://github.com/qgis/QGIS/files/4612352/trees.zip)

it has a layer with a column "scientific" that has an expression (based on another field called "common") for its default value:

```
CASE
WHEN
"common" = 'Cork Oak'
THEN
'Quercus suber'
WHEN
"common" = 'Eucalypt'
THEN
'Eucalyptus globulus'
ELSE
'no match'
END
```

if "scientific" editable option is checked, then it all work as expected, both on insert as also on update.

If the "editable" property is unchecked then strange things happen: the above expression is correctly evaluated until the feature form is open. When confirming the data entry in the feature form the computed value is lost and the result is always "no match".

**Comment by m-kuhn** [comment]
Confirmed

The reason is the fieldEditable check here:
https://github.com/qgis/QGIS/blob/master/src/gui/qgsattributeform.cpp#L359

Which was originally introduced (in a different form) in this commit, but unfortunately without any reasoning or pointer towards a pull request with reasoning.
https://github.com/qgis/QGIS/commit/b90dba4fd9c6631c8a63322b956facd4d621e8a7
