### ISSUE TITLE
rand() fail to generate negative values

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#36412]
**Describe the bug**
The function `rand()` available in the Expression Dialog for example is now unable to generate negative values. `randf()` however is unaffected by the bug. 

**How to Reproduce**
1. Open an Attribute Table of any vector file.
2. Select a field of type `Int` and in the expression line write `rand(-10,10)` then update field.
4. Only positive values have been generated and `NULL` is showing where I presume negative values should have been.

If the field is of type `double`, the value 18446744073709551616 is written where negative values should have been.

**QGIS and OS versions**
QGIS version 3.12.2-București
QGIS code revision 8a1fb33634
Windows 10 (10.0)

**Additional context**
I don't know exactly when the change happened, but the last time I used the function (and with negative values), I think I was running 3.4.x.

**Comment by ismailsunni** [comment]
I can replicate the bug.

I investigate the problem. It seems it is caused by the conversion of QVariant (the output/return from an expression). 

For example:
```
../src/app/qgsattributetabledialog.cpp:489 : (runFieldCalculation) [235983ms] new value as string 18446744073709551611
../src/app/qgsattributetabledialog.cpp:490 : (runFieldCalculation) [0ms] new value as int -5
```
Probably QGIS tries to convert to string if the field is int, but it will be more than the maximum int (arithmetic overflow?). But if you use int 64 bit, it will be converted properly.

But I am not sure in which part of the code the conversion happens. I am lost at this code (the undo stack)
```
L->undoStack()->push( new QgsVectorLayerUndoCommandChangeAttribute( this, fid, field, newValue, oldValue ) );
```
