### ISSUE TITLE
Interpolate Z when new vertex is added

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#36850]
**Feature description.**

While edition polygons and lines with Z values, it would be nice if, when a new vertex is added in the middle of already existing vertices, its Z got interpolated. Currently, all new vertex either in the middle of the line, or in its start or end gets the Z=0. It would be better if it could be interpolated.

This kind of rationale is already present in the cut tool. When you cut a 3D line, the Z values for the resulting Startpoint and Endpoint get interpolated.

For new vertex at the end of beginning of a line, The Z value could be kept equal to the nearest vertex.

**Additional context**

**Comment by SrNetoChan** [comment]
@lbartoletti what do you think of this?

**Comment by lbartoletti** [comment]
What is the situation today (tested on QGIS 3.12 and master, but IIRC works also on 3.10):
When a vertex is snapped, the Z value is inherited from the vertex of the snapped layer.
If you add a vertex on a segment, the Z value is the default value (Z=0 by default).

After my corrections, we thought about two additions:
- interpolating the Z on the segment
- add a tolerance to get the Z of the nearest vertex rather than the interpolated Z. However, this should not be an imposed behaviour. I think we need to add a modifier key to enable this "option".

So yes +1 with this proposal.

**Comment by SrNetoChan** [comment]
@lbartoletti  that would be even better and more flexible.

**Comment by lbartoletti** [comment]
@SrNetoChan The more I think about it, the more I think it's a bug. I'll add a new round about topological and Z issues after #39194

**Comment by SrNetoChan** [comment]
Thanks @lbartoletti for the great work. Not sure it's a bug, but it's definitely unexpected for the user.
