### ISSUE TITLE
QGIS crashing

### ISSUE THREAD

**Issue by KerenRaiter** [qgis/QGIS#36882]
Report: 
## User Feedback

Was just loading layers

## Report Details

**Crash ID**: [7fa06336fd36ee7382ad7dd7e9f819e60f0c71d0](https://github.com/qgis/QGIS/search?q=7fa06336fd36ee7382ad7dd7e9f819e60f0c71d0&type=Issues)

**Stack Trace**
<pre>
QtPrivate::QStringList_join :
QListSpecialMethods<QString>::join qstringlist.h:199
QgsWmsProvider::htmlMetadata qgswmsprovider.cpp:2255
QgsRasterLayer::htmlMetadata qgsrasterlayer.cpp:397
</pre>

**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@KerenRaiter ñot enough info here. Please describe what is being asked:

**Describe the bug

How to Reproduce

QGIS and OS versions

Additional context**

also please try with a new QGIS profile.

**Comment by Victor-mg1978** [comment]
I have the same problem. In my administrator user the program runs without problems, but in other user, that has a proxy to connect to internet, software no open at all. I don´t know if that detail may have a relation with that problem. In version 2.18 I configured the proxy after the software was open, but in this case I don´t know if the problem be that. Thanks.

**Comment by rduivenvoorde** [comment]
@Victor-mg1978 this does not seem related :-) 
But I wonder if QGIS does not open at all? Did you wait a couple of minutes (depending on your Network timeout settings)?
Because QGIS upon startup does some requests to the internet, to get some 'news'-items and the list of latest plugins. Could it be that the proxy is not configured (yet), and QGIS is trying to go to the internet but fails? And eventually should time out and start....?

**Comment by gioman** [comment]
Closing for lack of feedback.
