### ISSUE TITLE
QGIS3: DateTime incorrect from Excel import

### ISSUE THREAD

**Issue by robhubi** [qgis/QGIS#37178]
**Describe the bug**
An Excel file with 5772 lines of GPS data had 56 lines with timestamp 00:00:00 after import into QGIS. 
There is no data with this timestamp in the Excel file. Many other data have smaller timestamp variations in the order of 1 min.

A test file is included. Structure of "QB2_Test1.xlsx" (OS Country=German): 

| point_id | X          | Y          | ele   | time                |
| -------- | ---------- | ---------- | ----- | ------------------- |
| 375      | 676226,727 | 212399,93  | 486,6 | 07.04.2020 09:58:04 |
| 404      | 675895,496 | 212114,462 | 464,2 | 07.04.2020 09:58:05 |

**How to Reproduce**
1.  Launch QGIS, select "New Empty Project"
2. Drag and Drop File "QB2_Test1.xlsx"
3. Open Attribute Table of "QB2_Test1"
4. Sort field "point_id"
5. Compare "time" in QGIS with "time" in Excel

**Actual Result**
Table 1: Excel/QGIS differences emphasized
| point_id | time_Excel          | time_QGIS                   |
| -------- | ------------------- | --------------------------- |
| 371      | 07.04.2020 09:58:00 | 2020-04-07T09:58:00.000     |
| 372      | 07.04.2020 09:58:01 | 2020-04-07T09:58:01.000     |
| 373      | 07.04.2020 09:58:02 | 2020-04-07T09:58:0**1**.000 |
| 374      | 07.04.2020 09:58:03 | 2020-04-07T09:58:03.000     |
| 375      | 07.04.2020 09:58:04 | 2020-04-07T09:58:0**3**.000 |
| 404      | 07.04.2020 09:58:05 | 2020-04-07T09:58:0**6**.000 |
| 523      | 07.04.2020 10:03:00 | 2020-04-07T**00:00:00**.000 |
| 672      | 07.04.2020 10:10:00 | 2020-04-07T**00:00:00**.000 |
| 1078     | 07.04.2020 10:29:00 | 2020-04-07T**00:00:00**.000 |
| 1366     | 07.04.2020 10:42:00 | 2020-04-07T**00:00:00**.000 |

**Expected Result**
Identical time values in QGIS and EXCEL

**QGIS and OS versions**

Win 10 pro 64 bit German
QGIS 3.10.2

**Additional context**
[QB2_Test1.xlsx](https://github.com/qgis/QGIS/files/4772668/QB2_Test1.xlsx)

**Comment by agiudiceandrea** [comment]
Using the provided test file [QB2_Test1.xlsx](https://github.com/qgis/QGIS/files/4772668/QB2_Test1.xlsx) (MS Office Open XML 2007 XLSX format), I can reproduce the issue on:
Windows 7: QGIS 2.18.23 - GDAL/OGR 2.2.4, QGIS 3.4.5 - GDAL/OGR 2.4.0
Windows 10: QGIS 3.10.6, QGIS 3.12.3 - GDAL/OGR 3.0.4
GNU/Linux Ubuntu 20.04: QGIS 3.12.3 - GDAL/OGR 3.0.4

`ogrinfo QB2_Test1.xlsx QB2_Test1` also wrongly reads some date/time values:


point_id | time_Excel | time_QGIS | ogrinfo_2.2.4-3.0.4
-- | -- | -- | --
371 | 07.04.2020 09:58:00 | 2020-04-07T09:58:00.000 | 2020/04/07 09:58:00
372 | 07.04.2020 09:58:01 | 2020-04-07T09:58:01.000 | 2020/04/07 09:58:01
373 | 07.04.2020 09:58:02 | 2020-04-07T09:58:**01**.000 | 2020/04/07 09:58:02.**000**
374 | 07.04.2020 09:58:03 | 2020-04-07T09:58:03.000 | 2020/04/07 09:58:03
375 | 07.04.2020 09:58:04 | 2020-04-07T09:58:**03**.000 | 2020/04/07 09:58:04.**000**
404 | 07.04.2020 09:58:05 | 2020-04-07T09:58:**06**.000 | 2020/04/07 09:58:**06**
523 | 07.04.2020 10:03:00 | 2020-04-07T**00:00**:00.000 | 2020/04/07 10:**02:60**
672 | 07.04.2020 10:10:00 | 2020-04-07T**00:00**:00.000 | 2020/04/07 10:**09:60**
1078 | 07.04.2020 10:29:00 | 2020-04-07T**00:00**:00.000 | 2020/04/07 10:**28:60**
1366 | 07.04.2020 10:42:00 | 2020-04-07T**00:00**:00.000 | 2020/04/07 10:**41:60**

**If the provided file is converted in MS Excel 97-2003 XLS format** ([QB2_Test1.zip](https://github.com/qgis/QGIS/files/4777350/QB2_Test1.zip), zipped due to GitHub attachment formats limitation), **then both QGIS and ogrinfo can correctly read the date/time values**.

So it seems an issue in GDAL\OGR or in the libexpat parser library on which it relies for MS Office Open XML spreadsheet file parsing.

**Comment by nyalldawson** [comment]
Right, this needs filing on the GDAL bug tracker, not QGIS

**Comment by agiudiceandrea** [comment]
https://github.com/OSGeo/gdal/issues/2683

**Comment by agiudiceandrea** [comment]
Fixed in GDAL https://github.com/OSGeo/gdal/pull/2708
