### ISSUE TITLE
QGIS (3.10 & 3.12) Print Composer Atlas "Cannot write to C:\Work\****. This file may be open in another application or may be an invalid path.

### ISSUE THREAD

**Issue by NauticalNeil** [qgis/QGIS#37225]
**Describe the bug**
In both QGIS 3.10 & 3.12, in print composer Atlas, when creating the Output filename expression (under the Output tab in Atlas), i have found that if I use "/" in the filename expression, I get the following error message:

"Cannot write to C:\Work\******.pdf. This file may be open in another application or may be an invalid path."

I was using the  "/" to capture units (e.g. mg/L) in the map filename.

If I removed these "/" , the map exported ok.

QGIS version
3.12.1-București
QGIS code revision
121cc00ff0
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
quick_map_services; 
db_manager; 
MetaSearch; 
processing

**Comment by rduivenvoorde** [comment]
This is not a QGIS issue I think, googling 'valid filenames windows' for example I see:

https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3

Telling me that you should never use \ or / om filenames, because these are off course also path-separators.

I often replace such a character with an underscore '_'

Close this one?

**Comment by gioman** [comment]
I guess this could turn a feature request to handle such error in a more graceful way...

**Comment by rduivenvoorde** [comment]
Also in Linux I get an error (off course):

```
$ touch "This is a / test"
touch: cannot touch 'This is a / test': No such file or directory
```

Not sure if we want/can protect users from this. All other software will also fail. 
What would be a more gracefull way? Always check for invalid chars in file and path names?
Is that something we have seen in other software?

**Comment by nyalldawson** [comment]
Just to add -- we deliberately don't replace '/' '\' characters in the result with '_' or similar, because we want to allow users the ability to setup the atlas filename expression to put the pages in different folders if desired. I.e. the expression could be designed in such a way that the pages are split into multiple different output folders by some categorization field...

**Comment by rduivenvoorde** [comment]
@gioman I think we should close this then with a 'wontfix'?

**Comment by nyalldawson** [comment]
Yes

**Comment by NauticalNeil** [comment]
Thank you for your useful feedback
