### ISSUE TITLE
Hardcoded Limit for Relation Reference Widget Selection

### ISSUE THREAD

**Issue by Tugark** [qgis/QGIS#37269]
**Describe the bug**
When a lookup table consists of more than 100 elements, the Relation Reference Widget selection for this relation only shows the first 100 entries of this lookup table. Selection of relation elements not in the selection list can only be done by typing the identifier, which drills down the selection list and also shows the elements which are not within the first 100 elements.

Similarly, we also noticed that the elements in the list are not sorted numerically, even though the form is configured to sort the values (the ID field is an integer, but it's not sorted correctly; however, this might not be a bug):

![image](https://user-images.githubusercontent.com/16555423/84877084-4e110300-b088-11ea-9959-dd2253059875.png)

I discussed this with @andreasneumann and he mentioned that there _could_ be a hardcoded limit to 100 elements for better performance (imagine lookup tables with several 1000 elements). However, since we cannot find any documentation on this, I've labelled this as a bug.

If it is indeed intended behaviour, a possible feature could add the possibility to configure the limit (either globally in the project or for each Relation Reference Widget - the latter would be preferred, since you could allow for more elements only for specific attributes, without running into performance issues as mentioned above).

**How to Reproduce**

Use the attached ([qgis_issue_100_limit.zip](https://github.com/qgis/QGIS/files/4791356/qgis_issue_100_limit.zip)) minimal QGIS project as well as the attached geopackage. The layer "tree" has a relation to "tree_types", which can be selected in the form. "tree types" has roughly 200 entries, so the behaviour above can be reproduced as follows:

1. Open form on any of the two trees
2. Choose "id_baum_art" and assign it the value "165" - you can only do so by typing in "16...", but not by selecting it.

**QGIS and OS versions**

Tested in QGIS 3.10.5 and various Windows Builds.

I'll be happy to provide more information.

**Comment by andreasneumann** [comment]
We'd like to see this fixed by having an option to define the max nr of features to be included in the combobox - rather than the 100 entries. The 100 could still be the default, but it should be possible to define other values.

Often, there are only a few more entries than the 100 - and then it is really confusing to get access to the excess entries going beyond the 100, if users don't know that they'll have to type ...

**Comment by phidrho** [comment]
Hi,

I also stumbled upon this bug when trying a workaround for #50997.

@m-kuhn I think this should be labeled back as `Bug` because of following reasons:

1) there are no effective time savings in GUI creation time - in my [demo dataset](https://github.com/qgis/QGIS/files/10151334/relation_editor_bug_v2.zip) I have 77960 records in attribute table (stored in GPKG, on classical HDD, not SSD, i7 CPU from 2013), and it works instantly [see short video demo](https://youtu.be/zhroVO5FFos) (note: I had to create `Filter` to avoid 100 limitation)

2) we need to consider context of GPKG being a default file format for QGIS data since version 3
    - and it's based on SQLite which is more of a single-user database so there should be no problem with fetching data in this case
    - because of QField and Mergin Maps I think GPKG is even a lot more in use than before

3) if there is a slow DB while fetching data - it is a DB, server, connection speed or indexing problem, not a QGIS one

4) and last reason - maybe the most important one, `Relation Reference` widget doesn't make sense if not all options are shown, as @andreasneumann said

@signedav Since you've had recent presentation about relational data editing, did you run into this problem in practice, and do you maybe have good proposal for workaround?

**Comment by signedav** [comment]
Hm... Without having a deeper look at it, it sounds reasonable that the max size should not be hardcoded.

As a workaround (by config) maybe a chained filter would make sense anyway on such long lists. Of course not in any case.

**Comment by m-kuhn** [comment]
The proposal by @andreasneumann looks good to me.
Or a "load all" item at the bottom of the list.

For the record: postgres and other remote data sources are and stay first class citizens of QGIS and this means it has to deal with latencies in data loading.

**Comment by phidrho** [comment]
> Or a "load all" item at the bottom of the list.

I don't think that this is a good solution. It would make sense only in case when top 100 results would be ordered in some "most expected input on top" but it's impossible to predict this without some other logic

One more thing to consider is "lazy populating"/"lazy loading" of data - this might be useful: [notes on Qt ComboBox Widget](https://stackoverflow.com/questions/33447843/qcompleter-for-large-models/33454284#33454284)

**Comment by m-kuhn** [comment]
The base idea behind the combo box was, that it's scrollable for short lists.
And searchable (by typing text) for large lists where I expected scrolling to become cumbersome.

It seems that scrolling is not as cumbersome as I have expected it.
The easiest change would be to go with what @andreasneumann propoed (a "show all" or "limit" configuration option) which would be a couple of hours of work.
I'm sure there would also be possibilities with better UX if someone would like to go the long road.
