### ISSUE TITLE
No suggest/lock angle on final click when trying digitize square area

### ISSUE THREAD

**Issue by Doctor-Who** [qgis/QGIS#37312]
OS : openSUSE 15.1 / Windows 10
QGIS version : 3.12.3

When trying to digitize a rectangle/square area, there is no indicate/lock on the final line when trying to snap with starting point. See example : 

![Peek 19-06-2020 10-07](https://user-images.githubusercontent.com/5890416/85113923-5ef07e80-b218-11ea-85e3-78adfe7938a4.gif)

From my point of view, the last click should indicate/lock when it is perpendicular to the starting point.

Regards

**Comment by andreasneumann** [comment]
This is already implemented in QGIS 3.14: see https://changelog.qgis.org/en/qgis/version/3.14/#snapping-currently-digitized-feature

**Comment by saberraz** [comment]
Hi @andreasneumann 

I think the issue is related to a different use case than the one you age referring to.

I just tested on QGIS master (built this morning) and I can confirm the issue. To reproduce:

1- enable snapping and the Advanced digitising panel
2- Assuming you are capturing a rectangle/square, click for the first, second and the third
3- for the last point, there is no lock to indicate the 4th point is the shortest distance in reference to the first.

**Comment by andreasneumann** [comment]
Yes - it is just implemented slightly different in QGIS 3.14 / master - you have to move the cursor to the start point and then it will show the 4th point that users want to properly close a square. 

But the result is totally the same. You just have to be a little bit flexible.

**Comment by andreasneumann** [comment]
@saberraz and @Doctor-Who - I agree though that it would feel a bit "more natural" if it would snap to the 4th point when it the cursor is close to the position of the 4th point - instead of having to move the cursor to the start point to find the 4th point.

That is something to improve - but in general the functionality to properly close a rectangular polygon is now there in QGIS 3.14 and above. It hadn't been in the many releases before.

**Comment by andreasneumann** [comment]
cc @olivierdalang and @m-kuhn who worked on the improvement in QGIS 3.14

**Comment by olivierdalang** [comment]
As said by @andreasneumann, the current implementation already makes it possible to achieve the same shape. and it's really very efficient too if you're using keyboard shortcuts to lock angles. 

IMO we should avoid trying to be too smart with snapping, because this type hardcoded logic will get in the way when you're not drawing rectangles, and not work with other cases (non rectangular orthogonal shapes, moving nodes, splitting features, etc).

**Comment by m-kuhn** [comment]
I agree the current implementation allows for this use case and much more, but I also agree that it requires a certain knowledge level of the user.

Would it make sense to add this kind of behavior with a key modifier?
E.g. when holding down shift snap to some candidate points (e.g. intersections of the lines created from the current rubberband vertices combined with the advanced digitizing angles)?
