### ISSUE TITLE
Issue when trying to digitizing some rectangle/square area

### ISSUE THREAD

**Issue by Doctor-Who** [qgis/QGIS#37314]
OS : Linux / Windows 10
QGIS : 3.12.3

When tryting to digitize a square or rectangle polygon, there is no indication/lock/snap on the last segment. On the last click, it should indicate/lock when it is perpendicular to the starting point.

See example : 
![Peek 19-06-2020 10-07](https://user-images.githubusercontent.com/5890416/85120967-4ab27e80-b224-11ea-93b8-70d2e8b6b157.gif)

**Comment by andreasneumann** [comment]
@Doctor-Who - I am bit confused, why do you open a separate issue when I just closed the same issue in https://github.com/qgis/QGIS/issues/37312 with the remark that this is solved in QGIS 3.14

In any case - what you request here won't be fixed in QGIS 3.12 (no new features go into already released versions), but you will have to upgrade to QGIS 3.14 or higher in order to use this new feature.

**Comment by Doctor-Who** [comment]
My bad I was so focus on issue on actual version that I've missed new feature in the next release.
