### ISSUE TITLE
Add feature map tool only adds topological points to snapped layer

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#37824]
**Describe the bug**
When adding a new feature with *topological editing* enabled, topological points are added to the snapped layer. If there are identical geometries in other editable vector layers they do not receive the topological points. To correctly preserve topology, all editable vector layers should try to receive the topological points.

**QGIS and OS versions**
master on Debian testing

**Comment by lbartoletti** [comment]
> To correctly preserve topology, all editable vector layers should try to receive the topological points.

When I fixed topology tools last year, I asked myself this question... Finally, I let the in place the "adds topological points only on snapped layer" logic because, for some reasons, other editable vector layers may not have to receive the topological points.

However, I think it could be improved but with concrete use cases. I don't know what should be the best interaction with the user to select a topological mode? What are our options?

- as for now: adds topological points only to the snapped layer
- on all editable layer
- on all editable layer if the snapping on a segment is activated

**Comment by uclaros** [comment]
Thanks for the feedback!
Fixing topological editing is pretty high in my todo list.
- Adding points to the snapped layer, apart from being "selective topological editing", is also problematic when there are overlapping layers with identical features, in which case one cannot prioritize which layer will be chosen for snapping.
- Adding points to all editable layers should be, imho, the default and we should implement it to the tools that miss it.
- Enabling topological editing per layer might also make sense in some cases.

**Comment by JuhoErvasti** [comment]
@uclaros Should this be close as well after #57723?

**Comment by uclaros** [comment]
Yes, #57723 was a duplicate
