### ISSUE TITLE
Adding a new feature from attribute table fails, but works from digitizing toolbar

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#37846]
On tables with constraints, adding a new feature from the attribute table fails (with errors about violated constraints, the feature form does not open), but adding a new feature on the same table from the digitizing toolbar seems to work fine, opening the form and letting the user fill in some data in order to fulfill the constraints.

See this [video here](https://youtu.be/U6aSFfVU8OQ).

Tested on master and QGIS 3.10.

**Comment by andreasneumann** [comment]
Related issue with geometry tables:

see [video](https://youtu.be/yk5DCnjcib4)

The NOT NULL constraint is already violated before the user even has a chance to digitize the new feature on the map canvas.

**Comment by suricactus** [comment]
I looked into this and though a bit on the possible sollutions. I guess this issue is only present when transaction mode is enabled. Ther first solution is hard to implement and dangerous, but more UI coherent and real fix of the problem. The second one brings a new feature and relative easy to do, but feels more like a workaround:

1) When the add feature button is pressed, the newly added row is automatically selected and inserted in some kind of "single feature edit buffer" in the `QgsAttributeTable`, which is being actually written to the data source once the new row loses focus and/or a dedicated button on the row is pressed. This means the already complicated code of the attribute table needs to be changed as well as dealing with couple of edge cases - What if the user closes the attribute table? What happens if the row is not able to be written? What if you just want to copy a value from somewhere else/another row? I thinks it's not so fair price to pay just to keep the UI consistent when adding a new feature.

2) Make the current "Add feature" button to have a little arrow with two actions: "Add feature via attribute form" and "Add feature via attribute table". By default we have the latter, but when transaction mode is enabled, it is disabled and only the "Add feature via attribute form" is enabled. This will be minimal and backportable code and UI layout change which will overcome the attribute table limitations, as well as adding the convinience of using the attribute form when desired. As a bonus, the button may remember the last selection of action - add via form or via table.

![image](https://user-images.githubusercontent.com/2820439/89282474-45828500-d654-11ea-95e7-e24231612c6f.png)

**Comment by signedav** [comment]
Since the fragility of the attribute table I'm not sure if any risky things will be approved for back port. And the effort to ensure the safety is maybe to big. So I prefer to have the second one. This is an option that could be liked by the users anyway. But then I would suggest to make another type of tool buttons: instead long press - selecting action, having the small arrow to list the actions and select. After selection the default action is updated as well. So the user can get to the attribute form faster on the second time.

**Comment by suricactus** [comment]
To keep the changes as small as possible, let's keep the long press for now. AFAIK it is the only supported way for toolbar actions. Otherwise I have to change the button to `QToolButton`, which would be a bit more changes if planning to backport for 3.10.

**Comment by andreasneumann** [comment]
Seems like a good compromise, until we refactor the whole attribute table/form stuff ;-)
