### ISSUE TITLE
state of conda-forge repo

### ISSUE THREAD

**Issue by arimeyer** [qgis/QGIS#38017]
I am experimenting with various QGIS versions via conda, but have encountered several discrepancies with the versions in the conda-forge repo:

1)  The LTR (3.10.8) does not exist -- the closest is 3.10.7:
> conda search -c conda-forge qgis
qgis                          3.10.4  py38ha515ecd_0  conda-forge
qgis                          3.10.7  py37h76cbf2c_0  conda-forge
qgis                          3.12.0  py36h00e7516_0  conda-forge

2)  Dependency diffs versus the downloadable Windows desktop versions 3.14.0 and 3.14.1:
a)  gdal:
Windows desktop: 3.0.4
conda-forge: 3.1.1
b)  qt:
Windows desktop: 5.11.2
conda-forge: 5.12.5
c)  sqlite:
Windows desktop: 3.29.0
conda-forge: 3.32.3
d)  postgresql:
Windows desktop: 11.5
conda-forge: 12.3
e)  qwt:
Windows desktop: 6.3.2
conda-forge: 7.0.0

validation for the above:
> conda list

f)  pyqt:
Windows desktop: 5.11.3
conda-forge: 5.12.3
validation:
from PyQt5.Qt import PYQT_VERSION_STR
print("PyQt version:", PYQT_VERSION_STR)

![qgis-3 14 0-about](https://user-images.githubusercontent.com/15931433/88706875-12317a80-d0d7-11ea-962d-e7d892a55f87.PNG)
![qgis-3 14 1-about](https://user-images.githubusercontent.com/15931433/88706877-12ca1100-d0d7-11ea-9e54-b8beece0c168.PNG)

Please let me know if these version mismatches were intentional, and if so, why.  We are trying to develop for QGIS, and I'd prefer to use conda for dependency management, but we need to match the included library versions of the downloadable installers.  If this needs to be posted to another issue tracker, please point me to it.

**Comment by gioman** [comment]
@arimeyer we do not maintain the conda forge repo and do not officially support installed with conda.

**Comment by arimeyer** [comment]
Thanks for the quick response, @gioman .  Who does maintain the conda-forge repo?

**Comment by gioman** [comment]
>  Who does maintain the conda-forge repo?

@SrNetoChan do you know?

**Comment by SrNetoChan** [comment]
@arimeyer said:
> I am experimenting with various QGIS versions via conda, but have encountered several discrepancies with the versions in the conda-forge repo:
> The LTR (3.10.8) does not exist -- the closest is 3.10.7:

We are having some issues building 3.10.8 for OSX, and we delayed the release a bit until we get it figured out. Normally we try to release Windows, Linux and OSX at the same time.

> (...)
> Please let me know if these version mismatches were intentional, and if so, why. We are trying to develop for QGIS, and I'd prefer to use conda for dependency management, but we need to match the included library versions of the downloadable installers. If this needs to be posted to another issue tracker, please point me to it.

First, the dependencies used by QGIS, depend on the packaging system used. You will also find this kind fo differences between two Operating Systems (e.g. Linux and Windows) or even between the same OS in a different version (e.g. ubuntu 18.04 and ubuntu 20.04). This being said, as far as I understand, the conga-forge packaging system will always try to use the most recent stable version of each dependency, unless you force it to do otherwise.

Conda forge QGIS feedstock (the name given to the recipes) are here, any issues related to QGIS on conda-forge, can be reported there:

https://github.com/conda-forge/qgis-feedstock

> Thanks for the quick response, @gioman . Who does maintain the conda-forge repo?

QGIS recipe is maintained by the conda-forge community, and doesn't have any affiliation with the QGIS project. I am normally the one that triggers the recipes updates when there are new versions of QGIS, but then it's up to a few other guys to fix any problems that appear.

**Comment by nyalldawson** [comment]
I think we should close this (and any other conda specific reports) and direct it upstream

**Comment by arimeyer** [comment]
Thanks for responding, @SrNetoChan .  Before I move this to the other tracker, I did find that when I tried to match the 3.14.1 dependencies, conda errored out.  This was my attempt (fragment of yaml):

- qgis=3.14.1
- gdal=3.0.4
- qt=5.11.2
- pyqt=5.11.3
- sqlite=3.29.0
- postgresql=11.5
- qwt=6.1.3
- proj=6.3.2

I got:
ResolvePackageNotFound:
  - proj=6.3.2
  - pyqt=5.11.3
  - qt=5.11.2
  - qwt=6.1.3

That was surprising, but I did confirm that those versions are not available in channels default, anaconda, nor conda-forge.

I then tried commenting out the offenders, but then got tons of conflicts.  So now I just went with the conda 3.14.1 qgis dependencies and am hoping there aren't API conflicts, etc. compared with the installer dependency versions.

Is it possible for the Python QGIS development community to use conda rather than the convoluted environment configs I see?  This would make it seamless.  Is that something the main developers are considering?

**Comment by gioman** [comment]
>  Is that something the main developers are considering?

you should really ask this in the developers mailing list.

**Comment by arimeyer** [comment]
Done, thanks.
