### ISSUE TITLE
Print Layout Picture Box reverting to SVG

### ISSUE THREAD

**Issue by WobblyForester** [qgis/QGIS#38031]
Whenever I load a print layout in to QGIS my company logo picture box displays a big red X and the control has turned back to SVG image when had been saved as Raster Image:

![image](https://user-images.githubusercontent.com/45239511/88802427-f7c4d300-d1a2-11ea-80ff-2600344cc31b.png)

No matter how many times I revert the picture control back to raster image and save the template - every time it is loaded back from the layout manager the picture has reverted back to SVG.

I should mention that I'm using the latest release 3,14.1

**Comment by gioman** [comment]
Can't replicate on QGIS master on Linux.

**Comment by WobblyForester** [comment]
@gioman 

Hi Gioman,

I have the layouts saved to sharepoint via mapped drives using win 10- the problem is cropping up on all my colleagues projects who have updated to 3.14.

Thanks
Sam

**Comment by gioman** [comment]
> who have updated to 3.14.

@WobblyForester so this is not an issue if you if you use QGIS < 3.14? any chance you can test QGIS master?

**Comment by WobblyForester** [comment]
@gioman just installed 3.10.8 LTR and no issues - It seems the ability to switch between SVG and Raster in the picture control is causing it to default to SVG when the layout is loaded in.

**Comment by gioman** [comment]
> just installed 3.10.8 LTR and no issues

@WobblyForester thanks for testing. Can you please also test QGIS master?

**Comment by WobblyForester** [comment]
@giohappy 

I'm going to have to embarrassingly admit that I don't know how to install QGIS master :(

**Comment by gioman** [comment]
@WobblyForester is the development version of QGIS, at the moment the future QGIS 3.16.

You can install it using the osgeo4w installer (package "qgis-dev").

**Comment by WobblyForester** [comment]
@gioman I should have read a touch more before I commented! I am installing OSgeo4W now :)

**Comment by gioman** [comment]
> I am installing OSgeo4W now :) 

@WobblyForester follow the advanced install.

**Comment by WobblyForester** [comment]
@gioman - gosh that took ages to download...

The print layouts seem to be behaving - will report back tomorrow morning when I log back in for work!

**Comment by gioman** [comment]
> The print layouts seem to be behaving

@WobblyForester means that works fine on master for you?

**Comment by WobblyForester** [comment]
@gioman yes looks like it works fine on the master.

Thanks for your help - will have to fend off my colleagues until next release! :)

**Comment by nyalldawson** [comment]
Nothing related has changed since 3.14 release -- can you attach a sample project for debugging?

**Comment by gioman** [comment]
> Nothing related has changed since 3.14 release -- can you attach a sample project for debugging?

@nyalldawson should we leave this open?

**Comment by WobblyForester** [comment]
[sample project.zip](https://github.com/qgis/QGIS/files/5000311/sample.project.zip)
@gioman 
@nyalldawson 

I have attached a zip with the sample project from 3.14 

The north arrow in the layout is mapped to a http image and the logo image to a mapped drive - neither seem to want to work

**Comment by nyalldawson** [comment]
Yes - i suspect there's a real issue here, but we need steps to reproduce

**Comment by ygversil** [comment]
I have this exact same problem with 3.16.1 on Windows and 3.16.0 on Linux. It happens when path to picture is relative to the project folder in the template file.

Here is what I do to reproduce :
* start a new empty project and save it to a folder like `/tmp/test_layout_template_raster_image.qgz`,
* add any PNG picture to the same folder, eg. `/tmp/company_logo.png`,
* create a new print layout named `raster_image`,
* add a picture, change the type to Raster image and give the path `/tmp/company_logo.png`,
* save the project and save the print layout as a template, eg. `/tmp/raster_image.qpt`,
* open the `raster_image.qpt` file and ensure that path to picture is relative: `<LayoutItem ... file="./company_logo.png" ...>`,
* now start a new empty project and save it to the same folder: `/tmp/new_project.qgz`,
* open the Layout manager and in the New from template section, select Specific, give the path to the template, click Create, and accept the name `raster_image`,
* In the resulting template, there is a red cross instead of the picture.

On the other hand if, in the `.qpt` template, the path to the picture is absolute, then the image shows up correctly.

It looks like a bug to me: relative paths should work if the new project is saved in the same folder than the original project from which the template was created. But of course, if the new project is not saved yet or is saved in a different folder, it is OK for QGIS to not find the picture.

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.4 and 3.24.0.
