### ISSUE TITLE
Taskbar icon

### ISSUE THREAD

**Issue by EmHain8** [qgis/QGIS#38168]
**Describe the bug**

When I open QGIS 3.14 the Taskbar icon is a page icon rather than the QGIS. This happened in 3.10 as well. 
**How to Reproduce**
1. open qgis
2. look at your taskbar

**Additional context**

![image](https://user-images.githubusercontent.com/45258377/89483245-e9983780-d7de-11ea-83b4-49d5a6802d2b.png)

**Comment by gioman** [comment]
@EmHain8 can't confirm

![Screenshot_20200806_161212](https://user-images.githubusercontent.com/1951107/89548949-9da9ba80-d7ff-11ea-9bf0-0dabf594bdc0.png)

**Comment by phidrho** [comment]
It happens to me also sometimes, as I have figured out, it has something to do with installation method. When I use OSGEO 4W network installer > Advanced installation and then I check only QGIS without any other software (installer automatically asks for dependencies), then I get this bug without icon. But even then sometimes starts with normal icon, and sometimes without.

**Comment by gioman** [comment]
> QGIS without any other software (installer automatically asks for dependencies)

why you should not install any of the (necessary) dependencies tagged by the installer? On a "normal" osgeo4w install this issue/annoyance does not exist apparently.

**Comment by phidrho** [comment]
Maybe I have wrongly expressed myself. When I wanted minimal QGIS installation, I checked only qgis-desktop from setup wizard, and installer automatically also checked all other dependencies it needs, so I installed everything installer asked for together with qgis-desktop, but nothing other than that.
But as I said even then, icon sometimes appears, and sometimes not when application is started. If I remember well, it behaved differently on different computers in my company, so I believe it is very hard to trace the bug.
It never bothered me, because I knew I selected minimal installation so I though some dependencies are missing or not accessible.

We also have one other application in company which had similar problem, but it was created with totally different technologies (it had nothing with Qt), so maybe it's Windows related. One thing I could connect between this two is that both of them are installed in user's folder, not in traditional Windows way (inside Program Files).
