### ISSUE TITLE
DB Manager: PostgreSQL field comments are not displayed correctly

### ISSUE THREAD

**Issue by jguelat** [qgis/QGIS#38394]
DB Manager doesn't display the field comments of PostgreSQL tables. Sometimes you even see comments attributed to other tables in the same database. I guess there must be a wrong query somewhere... Table comments are however displayed correctly.

1. Create a new table (with DB Manager or pgAdmin) with a new field
2. Add a comment to the newly created field
3. Click on the table in DB Manager
4. The comment doesn't appear in the info tab of the table

QGIS 3.10.9 and 3.14.15
Windows 10
PostgreSQL 9.6.4

**Comment by elpaso** [comment]
I cannot reproduce on current master but while testing this issues I've found another possibly related issue: in step 1 from the table creation dialog I added a few fields inserting comments directly in the field creation dialog.

The comments were not added to the table, I checked with SQL and PG-Admin.

However, when I added a comment with PG-Admin it was correctly shown in DB-manager and if you create the table first (step 1) then edit the table later and add the comment (step 2) it works as expected (and the comment is also visible in DB-Manager.

I believe that the real bug here is that it is not possible to add a comment directly when creating the table in step 1.
