### ISSUE TITLE
Virtual field in virtual layer not found

### ISSUE THREAD

**Issue by dingausmwald** [qgis/QGIS#38523]
Qgis 3.14.15
Windows 10 x64

when inserting two layers with a virtual field with the same name in the same virtual layer, one of those fields cant be found. In my case i have a virtual field in two layers called 'laenge' as decimals. (sidenote: one of this fields is length 10 and precision 3, when creating a new virtual field as decimal, i cant even choose length, its greyed out and -1). Dependend if one or both layers are imported threw embedded layers dialog, qgis finds one field or the other. Never both.

"Query preparation error on PRAGMA table_info(_tview): no such column: t.laenge"

**Comment by gioman** [comment]
@dingausmwald it is not clear to me how to replicate, can you please attach a sample project/data and list the necessary steps? thanks.

**Comment by troopa81** [comment]
@dingausmwald I didn't manage to reproduce with an example of my own. Could you please attach a sample project/data with everything involved in your virtual layer query definition

**Comment by gioman** [comment]
Closing for lack of feedback.

**Comment by fraktal-sb** [comment]
because I have the same problem here some simple test Data.

[TEST.txt](https://github.com/qgis/QGIS/files/11581379/TEST.txt)

[TEST.xlsx](https://github.com/qgis/QGIS/files/11581381/TEST.xlsx)

the file TEST.txt contains the QGIS Project data; simply rename it to TEST.qgs
The EXCEL file contains 2 Records one with Coodinates, one with zero values

The QGIS Project is simple.

It contains a Table "Record" linked to the EXCEL file TEST

And a virtual Layer with the query working perfectly.

The query is

SELECT *, MakePoint("GK-R", "GK-H", 31466) as geometry FROM Record

But when I try to avoid displaying 0 value records with the where clause

"where Record.GK-H is not 0"

it shows the error message

Query preparation error on PRAGMA table_infoLtview): no such column: Record.GK

please note the difference: Record.GK and Record.GK-H
