### ISSUE TITLE
Geometry generator symbol not rendered if the feature itself is not on the map canvas

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#38579]
1. Select a point layer
1. In the symbology setting, use the geometry generator. Eg, generate a buffer around the points: buffer( $geometry, 100)
![image](https://user-images.githubusercontent.com/7983394/92106875-41798c80-ede5-11ea-92ba-8b707c2c560a.png)

1. Pan the canvas till one point feature is out (see the top right corner): you also lose the buffer
![image](https://user-images.githubusercontent.com/7983394/92107195-ad5bf500-ede5-11ea-8e06-5ff1295cc75b.png)

Tested on 3.14.15 but was originally reported on 3.10.6

**Comment by troopa81** [comment]
The issue here is that the expression evaluation is done at rendering time, no at filtering time. And it's fine this way. 

Imagine that you have a PG table with millions of points, the only way to know which point with buffer has to be drawn is to get all the points and evaluate the expression in QGIS, which will end up being really slow. 

You could argue that here the expression is simple and we could get a 100 meter larger extent but it would not be the case for all expression (expression with case/when for instance or `make_point` from given attribute, `rand`...)

The only way to fix that I think is to add an extent buffer for QGIS desktop, the same that exists for the server (see [tile buffer in pixel](https://docs.qgis.org/testing/en/docs/server_manual/getting_started.html#wms-capabilities)). The user would have to guess it according to its geometry generator expression. 

I can't see another way to deal with this.

**Comment by elpaso** [comment]
> I can't see another way to deal with this.

Neither do I, we should probably turn this into a feature request and expose an extent buffer to the project (or layer) settings.

**Comment by nyalldawson** [comment]
I'm +1 for a configurable buffer parameter, but it needs to be done at the symbol layer level.

**Comment by 3nids** [comment]
I have had several projects with several geometry columns and using geometry generator on the other columns depending on a rule.
The main geometry happened to be often NULL.
Rather than adding a buffer, I would recommend an option to force to evaluate the generated geometry to see if it is within the bounds of the canavs.

Does it make sense to you?
@nyalldawson does it fullfill the need of being done at symbol layer level?

**Comment by troopa81** [comment]
> Rather than adding a buffer, I would recommend an option to force to evaluate the generated geometry to see if it is within the bounds of the canavs.

But to evaluate the generated geometry, you'd have to get ALL the features (not only the one on the canvas) and then make the  evaluation on QGIS side. That could be very time consuming if there is a lot of database on your database.

**Comment by 3nids** [comment]
> But to evaluate the generated geometry, you'd have to get ALL the features (not only the one on the canvas) and then make the evaluation on QGIS side. That could be very time consuming if there is a lot of rows in your database.

Yes, that's why it needs to be optional.

More generally, this comes to the issue that we should be able to use a geometry generator on a geometry-less layer.
It is not efficient at all, but this comes very handy.

One use case I had recently: raod-signs.

The signs are a geometry less table containing the sign type.
The pole contains the point geometry.
You want to render the signs on the map: you need to join the pole layer which has virtual fields of the position (x and y columns) and then use a geometry generator.
In order to have this working, I had to make the signs a polygon layer having a default geometry being a polygon of the whole country (to be sure it intersects with map canvas).

Of course you can achieve this on server side.
But sometimes you just don't have a server side (on the field).

**Comment by nyalldawson** [comment]
@3nids I think that's abusing the geometry generator. Ultimately the geometry generator is for rendering only, but what you're wanting is a way to effectively create a virtual geometry for a non spatial table. Theres a definite need for this, but I don't think it should be handled as a geometry generator but rather an equivalent to virtual fields which is handled in the iterator instead.

**Comment by antoniolocandro** [comment]
I have a use case, I flipped the coordinates due to the lat,lon thing for display. I would think an option to render the geometry generated feature even if the original feature is outside the map canvas would be possible, maybe an option like

[x] Render even if original feature outside canvas extent

![flip_coordinates](https://user-images.githubusercontent.com/4627073/161323799-71b8f5a0-69bb-419f-9b51-ca186ec0cc4c.gif)

I think in this case no test would be done to check if it is within the map canvas and just force render as per the geometry generator
