### ISSUE TITLE
Add support for SIP 6

### ISSUE THREAD

**Issue by sebastic** [qgis/QGIS#38911]
Followup to #37542 as reported by Dmitry Shachnev in [Debian Bug #964132](https://bugs.debian.org/964132):
> I have an update on PyQt5 vs. SIP 5 status.
>
> Unfortunately, things got a bit more complicated recently. Upstream is
> going to release SIP 6 in the beginning of next year, which will be not
> co-installable together with SIP 5, and which will not have /usr/bin/sip5
> “legacy” script:
>
> https://www.riverbankcomputing.com/pipermail/pyqt/2020-September/043201.html
> https://www.riverbankcomputing.com/pipermail/pyqt/2020-September/043162.html
>
> sip5 was a script to ease upgrades from SIP 4, and it has a set of options
> similar to SIP 4's /usr/bin/sip. Upstream now recommends using their new
> tools, sip-build and similar ones. See the documentation:
>
> https://www.riverbankcomputing.com/static/Docs/sip/
>
> This means that next year we will have SIP 4 and SIP 6 in Debian, but not
> SIP 5. My upstream work on QGIS made use of /usr/bin/sip5, so it will need to
> be ported to the new tools in order to support SIP 6 (and PyQt6).
>
> At the same time, upstream says that it will remain possible to compile
> applications with SIP 4 even when PyQt5 uses newer SIP. So now I think the
> best plan is:
>
> - Please keep using SIP 4 for QGIS for now.
> - Please test that it still works fine with PyQt5 in experimental.
> - Ask upstream to migrate to the new tools to be prepared for SIP 6 / PyQt6.

**Comment by mitya57** [comment]
To add some more clarifications: SIP 6 will be the same of SIP 5 but without any deprecated tools/methods. The `sip5` tool that I used in #37901 is deprecated, so it will not be present in SIP 6.

Basically this bug is about migrating to the new buildsystem, that will work with both SIP 5 and 6.

PyQt5 itself and related projects (PyQtWebEngine, QScintilla2) are examples of projects that are using the new build system. kovidgoyal/calibre@7a4b3f61ff24f8c3 is an example of third-party project ported to the new build system.

**Comment by lbartoletti** [comment]
QGIS works fine with PyQt5.15 and sip5 (tested on my pyqt5 WIP branch) or sip4.

But as a packager, I have seen problems with other software (calibre, frescobaldi, etc.) so +1 to keep using sip4.

**Comment by kikislater** [comment]
We now have SIP 6 in Archlinux (and other based distribution like Manjaro or Endeavour) and SIP4 + python-sip4 packages available. 


SIP 6 contains sip-module in /usr/bin whereas SIP4 package doesn't have it ... 
- When building QGIS without SIP 6 package installed (cmake find sip4), cmake build is looking for sip-module (I think it comes from https://github.com/qgis/QGIS/blob/master/cmake/FindSIP.cmake#L47 because FindSIP.py fails to find sip4)
- When building QGIS with SIP 6 package installed (cmake find sip6), cmake build generate an error. 


sip4 contains only `usr/bin/sip`, `usr/include/sip.h`. 

python-sip4 contains 
```
usr/lib/python3.9/site-packages/sip.pyi
usr/lib/python3.9/site-packages/sip.so
usr/lib/python3.9/site-packages/sipconfig.py
usr/lib/python3.9/site-packages/sipdistutils.py
```

Is it sufficient to build Qgis ?

**Comment by kikislater** [comment]
Ok successfully build with latest FindSIP.cmake and FindSIP.py
help(sip) in qgis return me : 

```
DATA
    SIP_VERSION = 328704
    SIP_VERSION_STR = '5.4.0'

FILE
    /usr/lib/python3.9/site-packages/PyQt5/sip.cpython-39-x86_64-linux-gnu.so
```

So it relies on `python-pyqt5-sip` package
```
$ pacman -Qo /usr/lib/python3.9/site-packages/PyQt5/sip.cpython-39-x86_64-linux-gnu.so
/usr/lib/python3.9/site-packages/PyQt5/sip.cpython-39-x86_64-linux-gnu.so owned by python-pyqt5-sip 12.8.1-3
```

Sorry for the noise ...

**Comment by landryb** [comment]
+1 for sip6 support, i think in our packaging system qgis is one of the last SIP users not using the sip-build command and preventing us to update SIP port to v6 (still new, i agree, but sip-build has been here since SIP v5)

**Comment by stoecker** [comment]
On openSUSE Tumbleweed the package is now failing because of missing SIP6 support. Would be fine when this is fixed soon.

**Comment by ar-jan** [comment]
I hope this can be prioritized. On Void Linux the absence of SIP6 is preventing addition of QGIS to the package repository.

**Comment by manisandro** [comment]
https://github.com/qgis/QGIS/pull/45128

**Comment by manisandro** [comment]
#45128 is merged.
