### ISSUE TITLE
Wrong assignments of raster values to symbology Paletted/Unique values or Singleband Pseudocolor

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39058]
I'm seeing some inconsistencies when styling raster layers.

Here is a sample raster (Float32) that has pixels with 4 different values:

[prob0115_sample.zip](https://github.com/qgis/QGIS/files/5289216/prob0115_sample.zip)

```
 - 0;
 - 3.450000047683716;
 - 6.900000095367432;
 - 10.350000381469727.
```
 
Loading it to QGIS, the default Singleband Gray render type shows the 4 values with different levels of gray.

- If I try to apply a Paletted/Unique Values render style, to get different colours for each value, canvas shows these different colours, but legend on TOC display wrong values for each one:

```
 - 0;
 - 3.78333;
 - 6.62083;
 - 10.4042.
```

![imagem](https://user-images.githubusercontent.com/1331581/94377515-5ca49700-011a-11eb-87f4-f3f11a91ade1.png)

As you can see, value in Symbology dialogue only show 0, 3, 6 and 10, and labels are different from raster values (not even rounded).

- If I try to use Singleband Pseudocolor as render type, with Exact interpolation, to get 4 particular colours to each one of the 4 raster values, I get some classes not rendered in canvas (just transparent):

![imagem](https://user-images.githubusercontent.com/1331581/94377720-b0fc4680-011b-11eb-95b9-e6a93ee8aec2.png)

However, if I assign the exact raster values manually, with full precision (all decimal places), they are already rendered:

![imagem](https://user-images.githubusercontent.com/1331581/94377812-33850600-011c-11eb-9b40-92cab22cd7e4.png)

Here is a screencast that shows this behaviour: https://cld.pt/dl/download/02852983-9f11-439d-bc81-33b58ade21bc/raster_symbology.mp4 

So, I believe that all these problems come from the raster precision that is not captured or is rounded by symbology engine. Anyone confirm?

Tested with 

QGIS version | 3.14.16-Pi | QGIS code revision | 2b2f966720
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.

**Comment by elpaso** [comment]
@PedroVenancio the problem comes from a combination of facts:
1. the paletted raster renderer works on integers, the values of the classes use integer precision so I guess it won't work on floats by design
2. the paletted raster renderer uses the histogram to determine its values and (since it assumes integers) the histogram uses a bin count calculated by `std::ceil( max - min ) + 1`, so in this test raster you get a bins size of 12
3. the interval for the breaks is then calculated by dividing `double interval = ( histogram.maximum - histogram.minimum + 1 ) / histogram.binCount;` so you will never get the exact class values.

I honestly don't know what to do here. It seems that the renderer is not designed to work with floats in the first place.

I'll spend some more time to determine if we can use a different approach for floats but I believe that this qualifies as a feature request because it requires API changes to support float values for classes. 

I'm also worried about the performances: imagine the case of a huge float raster with many continuous values, the exact calculation of the classes would require scanning the whole raster to determine the unique values with a potentially large memory consumption and a very slow processing that would freeze the GUI.

Any idea?


I'll check for the second issue now (single band pseudocolor) that appears to be a completely different issue.

**Comment by gioman** [comment]
>  honestly don't know what to do here. It seems that the renderer is not designed to work with floats in the first place.

should we raise this on the developers mailing list and see what others think?

**Comment by elpaso** [comment]
@gioman it seems a good idea, but given the low answer/question rate on that list I wouldn't count too much on that.

**Comment by elpaso** [comment]
@PedroVenancio for the pseudocolor, there are different issues, again related to precision and rounding, for now I identified the problem in the min/max rounded values.

But, in this particular case there is something that I don't get: the raster is `Float32` which has room for maximum seven decimal significant digits but GDAL reports max `10.35000038147` which has far more precision than what a `Float32` can handle, so the rounding to `10.35` in this case is correct (besides that the current QGIS implementation does an arbitrary rounding without considering the underlying data type, but this is something I can try to fix).

Break values as well as min/max for this renderer are internally stored by QGIS as double precision (which has room for 17 significant digits).

Still digging ...

**Comment by elpaso** [comment]
@PedroVenancio I would like to create some tests for this kind of issue, would you be able to help by providing the smallest possible raster that I can use to reproduce the issue and create a test with?

**Comment by PedroVenancio** [comment]
> @PedroVenancio I would like to create some tests for this kind of issue, would you be able to help by providing the smallest possible raster that I can use to reproduce the issue and create a test with?

@elpaso Do you think this one with 63KB is small enough?

[sample_raster.zip](https://github.com/qgis/QGIS/files/5291853/sample_raster.zip)

**Comment by elpaso** [comment]
@PedroVenancio yes, thank you.

**Comment by elpaso** [comment]
@PedroVenancio regarding the issue 

> If I try to use Singleband Pseudocolor as render type, with Exact interpolation, to get 4 particular colours to each one of the 4 raster values, I get some classes not rendered in canvas (just transparent):

that is the expected behavior: you selected `Exact` interpolation, that means "match the raster values with the ramp break exactly", but the color ramp has `Equal interval` (I deduce from the next screenshot because the first one does not show the mode combo) so you won't get the exact values of the raster and only one (0) matches exactly.

**Comment by PedroVenancio** [comment]
Hi @elpaso 

> that is the expected behavior: you selected `Exact` interpolation, that means "match the raster values with the ramp break exactly", but the color ramp has `Equal interval` (I deduce from the next screenshot because the first one does not show the mode combo) so you won't get the exact values of the raster and only one (0) matches exactly.

So, if I understand well, it only use the `Exact` interpolation to find the breaks, that should be the exact raster values. 
But what mode should be choosed, to apply some colors to each raster value? `Equal interval` is the unique that permit to change the number of classes (quantile does not fit here), and in this case, choosing 4 classes it put the correct pixel values in each class, but without the precision it needs. In fact, 3.45 is different from 3.450000047683716, using `Exact` interpolation. But isn't this, again, a problem with the precision of the input raster vs. the precision used by symbology?

I think I understand that to apply different colors to exact raster values, Paletted/Unique Values render style would be the correct approach. 

But if that 'rounding' were not being applied to Singleband Pseudocolor, the breaks shouldn't be, with that 4 classes, the original pixel values, with full precision?

**Comment by elpaso** [comment]
> Hi @elpaso
> 
> > that is the expected behavior: you selected `Exact` interpolation, that means "match the raster values with the ramp break exactly", but the color ramp has `Equal interval` (I deduce from the next screenshot because the first one does not show the mode combo) so you won't get the exact values of the raster and only one (0) matches exactly.
> 
> So, if I understand well, it only use the `Exact` interpolation to find the breaks, that should be the exact raster values.

No, it uses "Exact" to match the raster values against the calculated breaks (and it fails to do so because the breaks are approximated).

> But what mode should be choosed, to apply some colors to each raster value?

I'm sorry to say that applying precise colors to distinct values on a continuous variable (like a float) makes little sense to me. You should really use integers here (where "Paletted/unique" should work).

The only option you have is to manually set the values.

> `Equal interval` is the unique that permit to change the number of classes (quantile does not fit here), and in this case, choosing 4 classes it put the correct pixel values in each class, but without the precision it needs. In fact, 3.45 is different from 3.450000047683716, using `Exact` interpolation. But isn't this, again, a problem with the precision of the input raster vs. the precision used by symbology?

Yes, I have an incoming PR  that sets the number of digits according to the underlying data type. This should at least show the right number of decimals.

> 
> I think I understand that to apply different colors to exact raster values, Paletted/Unique Values render style would be the correct approach.

Yes, but that one is designed for integers, not for floats where you are supposed to have continuously varying observations and not discrete unique values so all values are casted to integers which does mean it is completely unsuitable for floats (it may accidentally work for some datasets if the breaks are larger than 1, but it will completely fail for most datasets).

> 
> But if that 'rounding' were not being applied to Singleband Pseudocolor, the breaks shouldn't be, with that 4 classes, the original pixel values, with full precision?

Not necessarily: that depends on how they are calculated. QGIS raster approach is different from "exact" approaches like grass or the vectors, where the algorithm goes through all the values and does not make any sampling approximation. For performances reasons (I guess) the current QGIS raster classification implementation is based on the histogram and the histogram is based on two "approximations/guesses", one is the sample size and the other is the bin size, for https://github.com/qgis/QGIS/pull/35718 I  doubled the bin size to increase the "resolution" of the histogram, but that was reverted recently https://github.com/qgis/QGIS/pull/38769 so we are back to square 1.

I don't really see any (easy) solution here, we can make sample and bin size user-defined but the calculation should then be moved into a thread to avoid the risk of blocking the GUI. 

In any event, please open two different issues because maybe it's just me but I feel we are mixing two or more different things here.

**Comment by PedroVenancio** [comment]
@elpaso It seems that raster need some kind of revamp. Do you think that would be feasible still in QGIS 3.x series, or that it is something to QGIS 4.x? 

I will split this issue. The Paletted/Unique Values is not really an issue and can be leave behind , right? Where do you think I should split the issue? The one for Singleband Pseudocolor that you're already working on and should be fixed.

**Comment by elpaso** [comment]
Yes, I think the paletted/unique for floats is not a huge priority, but it isn't hard to fix and I know how to fix it so we could maybe do it right now while it's fresh in my mind.

The hardest/biggest issue is probably the quantile/histogram. But there is already a ticket for it.
