### ISSUE TITLE
Edited Vector layers are not loading after reopening the project

### ISSUE THREAD

**Issue by mithileshk87** [qgis/QGIS#39497]
Hi,

I have created custom countries and regions map using Natural Earth vector data. Once the project is closed. It's doesn't load the edited vector (refactored, dissolved and merged) maps.

I am attaching my project file.

[Armenia-Azerbaizan.zip](https://github.com/qgis/QGIS/files/5407446/Armenia-Azerbaizan.zip)

Thanks.

**Comment by gioman** [comment]
>  It's doesn't load the edited vector (refactored, dissolved and merged) maps.

@mithileshk87 have you created them outputting to temporary layers or telling QGIS to actually save the results to "real" datasources?

**Comment by mithileshk87** [comment]
I simply save the project as qgis file.

**Comment by rduivenvoorde** [comment]
Using the processing algorithms (like merge, dissolve etc), the algoritms creates *temporary layers* and shows them to you. The data is saved in some temporary dir on your pc. Upon a restart, this data is probably removed by your OS.
It works like this, because processing data often creates a lot of intermediary files, mostly not interesting to save.
BUT you can Qgis instruct to NOT create a temporary file, but a real file, just point it to your datadir and give it a name..
See https://docs.qgis.org/3.10/en/docs/training_manual/processing/first_alg.html

**Comment by mithileshk87** [comment]
Thanks a lot. That helped!
