### ISSUE TITLE
[Labeling] Data defined placement override default value sporadically 

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#39637]
When moving points or simply modifying settings of a label category (in ruled-based symbology), the values set in the data defined position are overriden by the default value. This occurs seemingly at random, somtimes also when moving labels.

I suspect this is related to https://github.com/qgis/QGIS/blob/0d3984632b87838ee2b97def2636a7ee60cb20fd/src/app/labeling/qgsmaptoolmovelabel.cpp#L244 or any code behaving similarly that blindingly set the field.

Or at least something similare relying on https://github.com/qgis/QGIS/blob/1c7b5833204bd1d6183f42cee5855d16b47cbc33/src/app/labeling/qgsmaptoollabel.cpp#L484

Occured on everything up to master 3.15 on Windows.

This may also be related to #39432

**Comment by roya0045** [comment]
Use case:

I have a set of points, I have a label that must have its position set relative to the geometry. I have another label that has its position defined by the auxiliary positions. My third label has its position relative to the second label (auxiliary position) but with an offset. This way the label is outside of the background of the second label and is always in the same quadran. Though from time to time the data defined positions are all set to the same value for no apparent reason. Needing me to copy paste the symbol in order to get back the good state of my label.

This is done in a rule-defined symbology.

**Comment by roya0045** [comment]
@nyalldawson does this https://github.com/qgis/QGIS/blob/0d3984632b87838ee2b97def2636a7ee60cb20fd/src/app/labeling/qgsmaptoolmovelabel.cpp#L31 sets the datadefined position value to the default auxiliary fields?
I'm trying to find when those are initially set when moving for the first time and this seems to be the closest thing.

**Comment by nyalldawson** [comment]
@roya0045 the logic starts from about here: https://github.com/qgis/QGIS/blob/0d3984632b87838ee2b97def2636a7ee60cb20fd/src/app/labeling/qgsmaptoolmovelabel.cpp#L81

**Comment by roya0045** [comment]
@nyalldawson Thanks, I looked at that part multiple times and I guess I must have missed something. I guess its because the code is designed to rely on the columns usually used rather than the provided expression. Or I'm just missing things. Thanks for confirming! I'll just look harder at this part.

**Comment by roya0045** [comment]
@nyalldawson Ah THIS IS THE CULPRIT! https://github.com/qgis/QGIS/blob/0d3984632b87838ee2b97def2636a7ee60cb20fd/src/app/labeling/qgsmaptoolmovelabel.cpp#L85 Is there any reason as to why the overwrite expression is set to True by default rather than False??

**Comment by nyalldawson** [comment]
@roya0045 I'm not sure -- that wasn't my code. Maybe check the git blame for clues?

**Comment by roya0045** [comment]
@nyalldawson Yeah I was confused by the fact that github only listed you as the contributor but indeed gitblame showed another history. I'm confused as to why github didn't display all contributors.

**Comment by nirvn** [comment]
@roya0045 , if you mean 'culprit' by this is the line that would have caused a regression, I'm afraid that's not the case :) prior to the commit you're raising, values would be overwritten all the time. As for why the added parameter to prohibit property overwrite is set to `true` by default, it was to insure that the function would continue to behave as it did prior to the commit for code paths I had not tested to avoid regressions.

Also, specifically on the move label tool, it was a choice to _allow_ overwriting property as I had assumed that if a user clicks on a label, he/she wants to move that label. Whereas we avoid overwriting properties when opening the label properties dialog because someone might just want to change the color and not have a dozen properties overwritten.

I assume that your issue has to do with a bunch of labels close to each other and you end up clicking on the wrong one?

**Comment by roya0045** [comment]
@nirvn Actually not at all. The good label is displaced. The issue is that I have multiple labels per feature and the properties of those label are overwritten from time to time when displacing the label that I want to displace.

Also I mean culprit as the part/function that has the capacities to overwrite that setting as I have overlooked such an innocuous function.

I am joining an example. The geopacage contains a sample layer, a project with the style applied to the layer and the geopacage also contains the reference style. Now one points has its auxiliary variables defined, the fields should be created and the other points don't have yet values. If you move one of the unset layer the style will bjork. There are also some more strange cause for the reset that I could not test reliably. This is simply to show that those functions replace all the data defined variablles for each label regardless. 

The only way to solve this is to keep a 'backup' of the symbology to apply again.
[multilabels.zip](https://github.com/qgis/QGIS/files/5457740/multilabels.zip)

**Comment by nirvn** [comment]
@roya0045 , looked into this a bit -- long story short, you should have all of your rules use the same data defined X Y auxiliary field, and use offsets to relocate individual labels relative to that main X Y coordinate.

The data defined X Y property is applied to all rules in `QgsAuxiliaryLayer::createProperty`.

**Comment by roya0045** [comment]
@nirvn Thanks, would it cause breakage if the create property only updated the fields of the moved label? This is what I was mostly looking into, or simply not replacing anything once the function has been run properly once. 

I'm still unsure as to why the current process must be so contraining. And using any offset gets overruled once the x y fields are define as they are the sole element controling position and gets overwritten, so no offset can be used there. :/

**Comment by roya0045** [comment]
And I'm also confused as to why https://github.com/qgis/QGIS/blob/1c7b5833204bd1d6183f42cee5855d16b47cbc33/src/app/labeling/qgsmaptoollabel.cpp#L811 is an OR instead of AND, especially since the default is true.

**Comment by dtutic** [comment]
I have noticed strange bahavior of expression and field based label placing. When done manually by setting all fields, it works OK, but if you copy&paste symbol (even only symbol part) the labels start to appear automatically on places which are not defined by expression/field. 
![labels1](https://user-images.githubusercontent.com/16665784/100282795-8805ff80-2f6c-11eb-9992-6d5ed5dee76b.png)
On this image the upper labels are done without copy/paste, all set manually. The labels on left are also done manually, but line style was prior to that copied from other layer. When the position where label should be is visible is on canvas, all is ok, but if moved then labels start to appear by automatic placement.
![labels2](https://user-images.githubusercontent.com/16665784/100282954-db784d80-2f6c-11eb-947c-7938d7318442.png)
Here you can see the behavior of labels eventhough they should be fixed. 

So, for now only way to have them fixed in place is to avoid copy&paste of symbology.

**Comment by roya0045** [comment]
@dtutic Please see #39432

**Comment by roya0045** [comment]
@nirvn You may be right, I think the label bounding box overlap would change wich label is set as the default and override the expressions of all the others, otherwise custom placement expressions are maintained, I'll close this one.
