### ISSUE TITLE
Add Row and Remove Row(s) of Batch Processing does not work

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39838]
Add Row and Remove Row(s) buttons of Batch Processing interface does not work in 3.16, both on Windows and Linux

![imagem](https://user-images.githubusercontent.com/1331581/98369085-4e5a6c80-2030-11eb-80ed-27668cafeacc.png)

**Comment by gioman** [comment]
@PedroVenancio already reported and fixed.

**Comment by AlisterH** [comment]
Just commenting for the benefit of anyone else who reads this ticket:

In current versions of QGIS you may think that the _"Remove Row(s)"_ button does not work.  It actually does work, but the batch processing interface has a "focus follows mouse" rather than "click to focus" focus model, so if you select a row but then move your mouse up to the button the row loses focus.  After you select the row you need to move the mouse sideways out of the window, then reenter the window from the top so that the row is still selected when you click the button.
