### ISSUE TITLE
Cell Statistics - Median giving wrong results

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#39843]
The new Cell Statistics algorithm is giving wrong median results. 

By default, functions like Mean, Standard deviation and Variance will always generate Float32/Float64 data types, depending on input float type. Count and Variety will always generate Int32 data types.

In the case of Median, "If the number of input layers is even, the median will be calculated as the arithmetic mean of the two middle values of the ordered cell input values."
However, I've tested with 10 layers and Median creates an Integer raster (Int16), with wrong results. Take a look for instance for this pixel:

![imagem](https://user-images.githubusercontent.com/1331581/98364417-adb47e80-2028-11eb-9f4a-2760a6dd4704.png)

Median should be 14.5.

Here is a sample dataset (simply 10 rasters with 1000m spatial resolution and random values between 0 and 25):
Cell_Statistics.zip

So, it seems that when the number of input layers is odd, the output is correct. When the number of input layers is even, the output is wrong. 

And the output data type seems to be the same of input data type, which will lead to wrong or rounded/truncated results when arithmetic mean of the two middle values is a decimal number.

https://github.com/qgis/QGIS/pull/36835#issuecomment-722560187

**Comment by root676** [comment]
I already identified the issue here - Bugfix-PR is on the way. 😄

**Comment by PedroVenancio** [comment]
Hi @root676 

Sorry for the delay in this feedback, but I'm seeing that the output of Median with an even number of input layers is still an Integer raster (Int16). For the pixel of the example above, the output is 14, instead of 14.5, because, I believe, the raster type truncates the output. 

Maybe when the stackSize be even, Median should generate Float32/Float64 data types just like Mean, since that is exactly what is done (arithmetic mean of the middle values).

What do you think?

**Comment by root676** [comment]
You are totally right here - thank you for the report, I didn't take that into account when I fixed the median. PR is on the way!

**Comment by root676** [comment]
After reviewing the code, I have to correct myself. In this case I would prefer data type consistency over result precision. Currently the algorithm scans the input raster stack and assigns the output data type according to the input raster with the most potent input data type: For example a stack of 4 rasters, with one of those rasters being float32, will set the output data type to float32 - in this case median will be calculated without truncating the output value. If all 4 input rasters where integer, the output of the median function would be written to an integer output raster as a truncated value. In my opinion this is the correct functionality because it favors data type consistency over calculation results. This is the same behaviour as the [Arc pendant tool](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/how-cell-statistics-works.htm) features. 

@PedroVenancio what do you think?

**Comment by SrNetoChan** [comment]
I agree with @PedroVenancio the result should be accurate and honor the median formula. So, if needed, the output should be moved from integer to float.

I don't think ArcGIS is doing it correctly.

Moving the result back to integer is not a problem, but recovering the truncated values is impossible.

How about an option to "keep input format" with a warning that it might truncate the result?

**Comment by PedroVenancio** [comment]
Yeah, I tend to agree with @SrNetoChan . For a user that does not know a floor or a ceil, the output can be confusing. 14.5 rounded for an integer is 15, 14 can be confusing in their minds.

@root676  However, if you think it is better to keep the same behaviour than arcgis, or if it can be side effects in other metrics, at least the help at the right of the tool needs to be something like:

Calculation details - Median: If the number of input layers is even, the median will be calculated as the arithmetic mean of the two middle values of the ordered cell input values. 
**This output will be truncated to an integer if all the input layers are of integer type. If any of those input layers be floating point, the output will be floating point, without truncating the output value.**

What you think @root676 ?

**Comment by root676** [comment]
@SrNetoChan @PedroVenancio Thanks for your thoughts - this is very convincing. But I think that a parameter `keep input format` is a little confusing because it would be only related to the median function. I'll update the algorithm to the new behavior and describe it in the algorithm help string/documentation.
