### ISSUE TITLE
QGIS no longer loads styles from PostGIS

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#39850]
QGIS no longer loads styles from PostGIS due to SQL requesting nonexistent column. 

With a PostGIS 2.5 set up that has previous had styles saved to it by QGIS, open the properties dialog for a layer, go to the "Symbology" tab, open the "Style" dropdown, select "Load Style…" and then change to "From Database (postgres)". It will be empty.

![image](https://user-images.githubusercontent.com/8172909/98395685-9d9d9e80-202a-11eb-83b9-1d651d349a1e.png)

The following error appears on the console

```
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [6ms] 2020-11-06T12:13:37 PostGIS[1] Erroneous query: SELECT id,styleName,description FROM layer_styles WHERE f_table_catalog='Alternate History' AND f_table_schema='Balance of Power' AND f_table_name='timeline_level0' AND f_geometry_column='geom' AND (type='Polygon' OR type IS NULL) ORDER BY useasdefault DESC, update_time DESC returned 7 [ERROR:  column "type" does not exist
LINE 1: ...imeline_level0' AND f_geometry_column='geom' AND (type='Poly...
                                                             ^
]
../../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2020-11-06T12:13:37 [1] Error executing query: SELECT id,styleName,description FROM layer_styles WHERE f_table_catalog='Alternate History' AND f_table_schema='Balance of Power' AND f_table_name='timeline_level0' AND f_geometry_column='geom' AND (type='Polygon' OR type IS NULL) ORDER BY useasdefault DESC, update_time DESC
```

QGIS version | 3.16.0-Hannover | QGIS code revision | fd9b11d8df
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | processing; db_manager; MetaSearch

**Comment by gioman** [comment]
Confirmed on Windows too, 3.10.11 is OK.

**Comment by jgrocha** [comment]
Thank you for reporting this @CoryAlbrecht 

The code (since #32138 ) will try to create the column `type`, if it doesn't exist. 
From you report, we can assume that QGIS failed to add the column to the `layer_styles` table. It should have added the column before querying the table.

Can you help us to find the problem? 

- If you manage the postgresql instance, can you check the logs and see why QGIS fails to add the column?
- Are you using the same role to access the database? The current role has permission to change the table?
- Can you login to the database with the same credentials as you use in QGIS and try to create the column manually with:
```sql
ALTER TABLE layer_styles ADD COLUMN type varchar NULL
```

Thank you for this additional effort.

**Comment by gioman** [comment]
> Are you using the same role to access the database? The current role has permission to change the table?

@jgrocha same user, same db backend, different QGIS version, different outcome > on QGIS 3.16 the GUI does not show the styles.

**Comment by jgrocha** [comment]
Thanks @gioman 

I was able to reproduce the problem.  Accessing the `layer_styles` table before any writing operation will cause this issue.

QGIS will update the table on the first write operation to `layer_styles`.

Workaround

If you save another style to the database, the `layer_styles` table will be updated and then you can recover the existing styles.

It is a workaround, but not solves the problem.

**Comment by CoryAlbrecht** [comment]
> Thank you for reporting this @CoryAlbrecht
> 
> The code (since #32138 ) will try to create the column `type`, if it doesn't exist.
> From you report, we can assume that QGIS failed to add the column to the `layer_styles` table. It should have added the column before querying the table.
> 
> Can you help us to find the problem?
> 
> * If you manage the postgresql instance, can you check the logs and see why QGIS fails to add the column?
> * Are you using the same role to access the database? The current role has permission to change the table?
> * Can you login to the database with the same credentials as you use in QGIS and try to create the column manually with:


The PG login I use in QGIS is my personal one for the PG cluster, which is my own. The account is a superuser on the cluster and is the same one I use with PGAdmin4. Logs for the past  few days show no attempt to run an ALTER command on the layer_styles table, only the SELECT. Is the ALTER statement something I should expect to see each time I try to load styles from the database, or does QGIS cache that attempt to upgrade and never try again?

> 
> ```sql
> ALTER TABLE layer_styles ADD COLUMN type varchar NULL
> ```

This seems to have reenabled scanning for the database styles.

**Comment by jgrocha** [comment]
> This seems to have reenabled scanning for the database styles.

Hi @CoryAlbrecht 

With the above `ALTER TABLE` you solve the problem manually. You should be able to work with styles without issues.

I've already identified the problem. Soon as possible, I will submit a fix.

**Comment by mixedbredie** [comment]
Apologies if this is already fixed. Running 3.16.2 and trying to load styles from my PostGIS database this is the query in the log message window:

`SELECT id,styleName,description FROM layer_styles WHERE f_table_catalog='database' AND f_table_schema='schema' AND f_table_name='tablename' AND f_geometry_column='polygon' AND (type='Polygon' OR type IS NULL) ORDER BY useasdefault DESC, update_time DESC`

My PostgreSQL login roles have search paths set so they write to specific schema in order. Should the table name be schema qualified with **public** so that it reads **public.layer_styles** as the table is created in the public schema by default? I have adjusted my **search_path** parameter to put public first in the list which has fixed the problem. However, I'll need to remember this when loading new data and set the schema explicitly.

**Comment by elpaso** [comment]
@jgrocha any progress on this one?

@mixedbredie mabe we should check the schema of the layer and search the styles in the same schema? Would it make more sense?

**Comment by gioman** [comment]
@elpaso @jgrocha related issue/request: https://github.com/qgis/QGIS/issues/38617

**Comment by gioman** [comment]
> @elpaso @jgrocha related issue/request: #38617

https://lists.osgeo.org/pipermail/qgis-developer/2020-September/062149.html

**Comment by mixedbredie** [comment]
> 
> 
> @jgrocha any progress on this one?
> 
> @mixedbredie maybe we should check the schema of the layer and search the styles in the same schema? Would it make more sense?

Some databases have the public schema deleted - where would the table be created then? Depends on the user saving the style where, for example, the user could be reading the table from SchemaA but having search_path/write permissions in SchemaB.

Having a layer_styles table in each schema would mean the tables and the styles are kept together. Additionally, the option to choose where to look for the layer_styles table would be useful as per the email to the list. Could QGIS check to see if a layer_styles table exists in the same schema as the layer and use it if it does and create it if it doesn't? At the moment we have 25 schemata in our database and 1 layer_styles table in the public schema. Changing the behaviour would mean 25 layer_styles tables, one in each schema.

**Comment by jgrocha** [comment]
QGIS right now only supports `layer_styles` in the public schema. This schema must be present in the role path. 

This issue can be closed (since it is not a bug, but a design decision limitation). The discussion should continue on #38617. We are all welcome to suggest the best way to improve the current implementation.
