### ISSUE TITLE
3.16 Windows install slows down all QGIS version 

### ISSUE THREAD

**Issue by QuentinStrappazzon** [qgis/QGIS#39930]
Hello Qgis folks! I have dealt with issues to open QGIS on my laptop since I install the last 3.16. Opening QGIS is very slow (up to 20 min) no response and all. Never had this pb before. Seems to begin with 3.16 (confirmed on 3 laptops in my company) . Is it the same for you ? It put mess in all QGIS versions opening.
Window install by the way

**Comment by SrNetoChan** [comment]
@QuentinStrappazzon can you try creating a new profile and see how it goes? 

If it fixes, the next step would be to run QGIS with NOPLUGINS option.

**Comment by gioman** [comment]
@QuentinStrappazzon as @SrNetoChan said, please try with a new QGIS profile. Anyway your report sounds more like a question. Questions must be addressed to the users or developers mailing lists. If you are making a bug report this must be done using the template that is presented here https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=


**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by i-s-o** [comment]
A shot in the dark: have you tried uninstalling 3.16 and installing 3.14 [again]? I am suggesting this to rule out any changes that might have occurred outside of QGIS (i.e. Windows or other software updates or network configuration at your company).

I am suggesting this because my situation is the exact opposite: until 3.16 came out, QGIS startup would take very long time. The culprit in my case was the Browser Panel if my laptop was not connected to the company network. In that situation the Browser  would try to connect to network shares, which were no longer available. My solution was to not use the Browser, or hide those drives in the Browser.

Note that before 3.16 was released, I had the same problem with all release channels (3.10.10, 3.14.16, and 3.15-master). Right after 3.16 was released, all of a sudden this problem disappeared from all release channels. This made me think that it might have been a "fix" outside of QGIS. I am still planning on testing the older version to check this theory.

**Comment by QuentinStrappazzon** [comment]
Thank you all for your answers !

A clean un-install and reinstall of QGIS 3.10 fixed it.

Strange that version 3.16 created these problems though. I will wait for later point release of 3.16 before installing it again.

Cheers



Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : i-s-o <notifications@github.com>
Envoyé : Tuesday, November 10, 2020 1:41:17 PM
À : qgis/QGIS <QGIS@noreply.github.com>
Cc : Quentin STRAPPAZZON <qs@sepia-conseils.fr>; Mention <mention@noreply.github.com>
Objet : Re: [qgis/QGIS] 3.16 Windows install slows down all QGIS version (#39930)


A shot in the dark: have you tried uninstalling 3.16 and installing 3.14 [again]? I am suggesting this to rule out any changes that might have occurred outside of QGIS (i.e. Windows or other software updates or network configuration at your company).

I am suggesting this because my situation is the exact opposite: until 3.16 came out, QGIS startup would take very long time. The culprit in my case was the Browser Panel if my laptop was not connected to the company network. In that situation the Browser would try to connect to network shares, which were no longer available. My solution was to not use the Browser, or hide those drives in the Browser.

Note that before 3.16 was released, I had the same problem with all release channels (3.10.10, 3.14.16, and 3.15-master). Right after 3.16 was released, all of a sudden this problem disappeared from all release channels. This made me think that it might have been a "fix" outside of QGIS. I am still planning on testing the older version to check this theory.
