### ISSUE TITLE
Crash when selecting Font after adding a label in a layout on macOS 10.13

### ISSUE THREAD

**Issue by e42mercury** [qgis/QGIS#40278]
QGIS crashes when selecting "font" after adding a label in a layout.
This issue was [also reported for QGIS 3.0](https://github.com/qgis/QGIS/issues/26416).

1. Go to Layout Manager
2. Click on Add Item > Add Label
3. Go to Item Properties and left-click on "Font"
    3a. Right-click "Font" (or left-click the arrow) and a contextual menu appears (Font size, recent fonts, etc.)
    3b. Left-click "Configure Font" (size can be changed)
4. Program exits

The attached file is a ZIP (can't upload QGZs) – it is an empty project with one layout, "test", and a single label.

QGIS version | 3.16.0-Hannover | QGIS code revision | 4af1cbfb97
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS High Sierra (10.13)
Active python plugins | AutomaticBackup-master; Coordtransform; DigitizingTools; latlontools; layer2kmz; leastcostpath; mapswipetool_plugin; mmqgis; oneatlas-qgis-plugin-1_0_1; quick_map_services; SpreadsheetLayers; xyToPoint; db_manager; MetaSearch; processing

[Label bug and crash.qgz.zip](https://github.com/qgis/QGIS/files/5598309/Label.bug.and.crash.qgz.zip)

**Comment by gioman** [comment]
@e42mercury please attach a sample project (with the necessary data).

**Comment by e42mercury** [comment]
I attached a QGZ to the original post – will that work or do you need other data?

**Comment by gioman** [comment]
> I attached a QGZ to the original post – will that work or do you need other data?

@e42mercury no crash on Linux with that empty project. I will test on macOS.

**Comment by gioman** [comment]
>     1. Go to Layout Manager
> 
>     2. Click on Add Item > Add Label
> 
>     3. Go to Item Properties and left-click on "Font"
>        3a. Right-click "Font" (or left-click the arrow) and a contextual menu appears (Font size, recent fonts, etc.)
>        3b. Left-click "Configure Font" (size can be changed)
> 
>     4. Program exits
> 
> 
> The attached file is a ZIP (can't upload QGZs) – it is an empty project with one layout, "test", and a single label.
> 
> QGIS version | 3.16.0-Hannover | QGIS code revision | [4af1cbf](https://github.com/qgis/QGIS/commit/4af1cbfb97600affea798b0c2114c244d8b61767)

@e42mercury no crash here with QGIS 3.16 on macOS Catalina.

**Comment by e42mercury** [comment]
Strange. Thanks for checking. Perhaps the bug is limited to macOS 10.13? That seems odd, though. I would guess it's not related to the plugins I have installed. I just tried it with QGIS 3.16.1 and the same thing happened.

**Comment by gioman** [comment]
> I would guess it's not related to the plugins I have installed.

@e42mercury try with a new QGIS profile anyway.

**Comment by roya0045** [comment]
@gioman could this just be the style crash that was fixed? I suggest trying in 3.16.1

**Comment by gioman** [comment]
> @gioman could this just be the style crash that was fixed? I suggest trying in 3.16.1

I tested with 3.16 on Catalina, so maybe it is not the same issue.

**Comment by e42mercury** [comment]
I tried with a new profile in 13.16.0. Same result. The 3.16.1 mac build is not available from the main download page; the link is for the 3.16.0 build ([I created a separate issue for this](https://github.com/qgis/QGIS-Mac-Packager/issues/103)).
I installed the nightly build (3.17.0) and used a new profile. Same result. My macOS version is older than Catalina; that is the only difference I can see, but again, I don't think that would explain the crash or why you can't replicate it.

**Comment by roya0045** [comment]
@e42mercury No stack traces and its only font specific? Is it any font selector, is it the font dialog or the font list, both?

**Comment by e42mercury** [comment]
it's both - anything that calls the window for text style

**Comment by roya0045** [comment]
Do you have particular fonts installed in your machine that could cause the crash?

**Comment by e42mercury** [comment]
I don't think so, since they haven't caused any problems in any other applications. Also, the fonts and the QGIS font dialogue work fine in other parts of the application. Even within the layout, I have no problems changing the font of the scale bar, for example, and other elements. The crash only happens when I try to change the font of a label within a layout.

**Comment by DelazJ** [comment]
> I have no problems changing the font of the scale bar, for example, and other elements. The crash only happens when I try to change the font of a label within a layout.

Maybe because these are not the same; the scale bar font (like most of the other font features in QGIS) uses the custom QGIS [text format widget](https://docs.qgis.org/testing/en/docs/user_manual/style_library/label_settings.html#formatting-the-label-text) while the label font in layout still relies on the OS font dialog. I couldn't find (a quick check so feel free to double-check!) if there is any other part of QGIS using this OS-related font dialog, otherwise it'd be interesting to test if the crash occurs there also.

**Comment by e42mercury** [comment]
@DelazJ this very much sounds like it could be the problem. I was not able to find other parts of QGIS that rely on the OS font dialogue, so I couldn't test this further. Not sure what to try next. Generally speaking, it might be time to change QGIS so it only uses its own font dialogue throughout (should this be a separate feature request?). This might prevent any future conflicts with the OS dialogue, which could vary by operating system. This might explain why @gioman was unable to reproduce the error on Linux or macOS 10.15 while it is quite consistent for me on 10.13.

**Comment by roya0045** [comment]
@e42mercury can you update your os to 10.15 and see if the issue is still present?

**Comment by e42mercury** [comment]
No, my mac is too old to update (it's from early 2011).

**Comment by PeterPetrik** [comment]
related to 2yo fix https://github.com/qgis/QGIS/commit/930c56f5b85db0c452263225fb51f8bf9f2e003c for Qt 5.11.x series. We are on 5.14.x now, so let me remove the workaround and see if it helps?

**Comment by roya0045** [comment]
I'm trying to implement the full font renderer widget for labels, if my works succeed it should also solve this. Alignment is behaving strangely but the font itself renders fine in my minimal tests.

**Comment by PeterPetrik** [comment]
I leave it with you then... good luck

**Comment by roya0045** [comment]
@PeterPetrik TY!

**Comment by roya0045** [comment]
@PeterPetrik PR is up, do you know anyone with this issue that could test the PR?

**Comment by PeterPetrik** [comment]
@roya0045 which PR?

**Comment by roya0045** [comment]
@PeterPetrik #41392 sorry for not specifying.

**Comment by PeterPetrik** [comment]
@roya0045 is this fixed? At the moment LTR will be on qt 5.14.2 and nightly on 5.15.2...

**Comment by e42mercury** [comment]
I opened this ticket In November 2020; I have since upgrade my mac, macOS, and QGIS to 3.18. This bug is gone! I see that this dialogue is now the QGIS version, not the OS font dialogue. I can't can't pinpoint the problem or what the fix was, but it is not happening anymore. Thanks!

**Comment by kbjshop** [comment]
I understand this ticket has been marked as closed, but I have been seeing the symptoms of the Font button crashing QGIS.

Today I found a clue as to why it is happening on my system.. I used a program a while back called "**Font Menu Cleaner**" which allows you to remove the "Supplemental Fonts", so that you don't see a lot of superfluous fonts in the menu lists.

Today, on a hunch, I had Font Menu Cleaner "Restore Defaults", after which, QGIS 3.16.13 **no longer crashes when hitting the Font button** as described below.

So, I am guessing that some vital font had been disabled by Font Menu Cleaner.  It disables a lot of them, so I have not filtered through to see which one(s) were vital to QGIS.

To verify, I then had Font Menu Cleaner do its "Clean Up".   
The QGIS that was still running was not adversely affected (Font button did not crash it.)

However, quitting QGIS and doing the steps below (after the "Clean Up" by Font Menu Cleaner ) caused the crash to return.

Clearly, QGIS is not able to handle something about the disabled fonts.


Here are the steps that would crash QGIS
New Project,
Create a New Report, edit header, draw in a text box, in Item Properties of text box, hit "Font" button... crash.
Same thing for a new Layout: text box... Font button of Item Properties crashes QGIS.

Versions of QGIS that I have tested and found this problem:
3.22.0
3.22.3

LTR
3.16.13
3.16.11
3.16.8

I deleted the QGIS3 default profile before each test

macOS  Big Sur 11.6.1

As always, I hope this helps someone who may be in the same quandry.
Keith
