### ISSUE TITLE
QGIS sorting problem in Mac

### ISSUE THREAD

**Issue by YenihayatN** [qgis/QGIS#40307]
Hello All!

I am using QGIS 3.14 for both Windows and Mac. Even though it works perfectly in Windows, I had sorting problem in Mac. QGIS sorts as 1 10 100 instead of 1 2 3.

To fix this, I have updated to 3.16 version, and nothing changed.

Thanks for all help.

**Comment by andreasneumann** [comment]
I assume you are trying to sort in the attribute table?

What data type does your column have?

**Comment by YenihayatN** [comment]
I am trying to use Properties => Symbology => Categorized according to 3rd column which is PGA as given in below, and the first two columns are Lat Long. I have also tried to replace dot with comma, does not affected.
<img width="253" alt="Screen Shot 2020-11-26 at 23 40 43" src="https://user-images.githubusercontent.com/75095606/100390279-d8e72800-3040-11eb-86c8-b5b34b78a6ba.png">

**Comment by andreasneumann** [comment]
To me it seems like your column is of string data type (see the "abc" icon next to the PGA column.

You could use an expression instead of the column, something like "to_int(PGA)" to convert the string into a number.

And then you would use the "Graduated" renderer - which is for numbers between min/max values.

I don't think this is a bug if your data column is a string - it is expected behavior - but converting it to numbers and switching the renderer would fix your issue.

**Comment by YenihayatN** [comment]
Dear Adreas Neumann;
It works perfectly now. Thanks a lot!

Best wishes.

**Comment by YenihayatN** [comment]
Dear Andreas Neumann;
It works perfectly now. Thanks a lot!

Best wishes.
