### ISSUE TITLE
The WMS request from the QGIS server was used normally, but the WFS request cannot be used.

### ISSUE THREAD

**Issue by Stealth1202** [qgis/QGIS#40439]
WFS request url.

http://localhost/cgi-bin/qgis_mapserv.fcgi.exe?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities&map=c:\OSGeo4W64\apps\qgis\bin\sd_L05.qgs

![image](https://user-images.githubusercontent.com/61223540/101125490-bbb3ea00-363c-11eb-8385-f149068cd6f1.png)

WFS service cannot be registered in qgis3.14 version.

![image](https://user-images.githubusercontent.com/61223540/101125621-059cd000-363d-11eb-81c2-1b8a9f22ac6f.png)

No layer information in Capabilities document.

WMS connects normally, but WFS cannot find layer information. What's wrong with me?

**Comment by gioman** [comment]
@Stealth1202 this report is largely incomplete (you must add all the requested infos asked here https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title= ) anyway I'm guessing if your problem is just because you have not added any vector layer to the WFS capabilities in your project properties.
