### ISSUE TITLE
GRASS Shell Crash on MacOS

### ISSUE THREAD

**Issue by dkav** [qgis/QGIS#40534]
In QGIS 3.16.1 the GRASS shell console crashes on leaving and reentering 

Crash log - [QGIS_2020-12-08-233907_Arbutus.txt](https://github.com/qgis/QGIS/files/5664326/QGIS_2020-12-08-233907_Arbutus.txt)

_Originally posted by @dkav in https://github.com/qgis/QGIS/issues/38961#issuecomment-741601518_

**Comment by gioman** [comment]
@dkav the GRASS plugin is abandoned as it hasn't received any attention since long. It is probably even on the kill list of some main developer. Not sure if it is worth at all to put any effort on it. As a QGIS user that does a lot of geoprocessing and analysis, since we have GRASS in the Processing toolbox the GRASS plugin has become basically irrelevant. For anything GRASS in the Processing toolbox can't do, power uses can just use native GRASS.

How this is different from https://github.com/qgis/QGIS/issues/40533 ?

**Comment by drf5n** [comment]
I think this issue is about the crash, as in the closed https://github.com/qgis/QGIS/issues/38961#issuecomment-742012154 , rather than the merely non-functional GRASS terminal in https://github.com/qgis/QGIS/issues/40533

**Comment by dkav** [comment]
@drf5n is correct in is response.

**Comment by dkav** [comment]
Grass console has been removed. See https://github.com/qgis/QGIS/pull/53597.
