### ISSUE TITLE
Advanced Digitizing tool "Rashape features" not work when reshape inside polygon (polygon, multipolygon)

### ISSUE THREAD

**Issue by giedrioks26** [qgis/QGIS#40607]
"Rashape features" not work when reshape inside polygon (polygon, mutipolygon). Outsite work fine. 
This occurs on a single polygon (attachment [reshape_feature_not_work.zip](https://github.com/qgis/QGIS/files/5695560/reshape_feature_not_work.zip)). Works well with other polygons. I applied Fix geometry but it doesn't help. There are no topological errors. It was only possible to fix it by applying the minus and plus Buffer. Maybe you know why that is?
QGIS versions 3.4 and 3.10

**Comment by uclaros** [comment]
Can you clarify what you mean by *inside* and *outside*?

**Comment by giedrioks26** [comment]
inside when the area inside the edge of the polygon is removed
[inside](https://user-images.githubusercontent.com/6436791/102247396-95c5f980-3f08-11eb-93b1-fb2eecc966df.png)
but does not remove

outside when an area is added to an existing area
[ouside](https://user-images.githubusercontent.com/6436791/102247479-aeceaa80-3f08-11eb-8342-51b9dc281d3a.png)

outside work fine:
[outside_work](https://user-images.githubusercontent.com/6436791/102247771-0d942400-3f09-11eb-8611-a33b9ca5a406.png)

**Comment by gioman** [comment]
@giedrioks26 your geom has definitely something weird that I cannot understand (but I haven't investigated much).

If you use as input for the "multipart to singlepart" tool you get a layer that when trying use the reshape tool you get a

`IllegalArgumentException: Points of LinearRing do not form a closed linestring`


message. Whatever the problem is, doing the buffer thing (even a tiny one) fixes it (in fact in PostGIS doing a 0 buffer was a common way to fix geometries before st_makevalid).

I guess that QGIS should handle better this case, especially considered that "fix geometries" seems to do nothing.

Also interesting that the reshape tool used to remove works after it has been used to enlarge de polygon.

**Comment by uclaros** [comment]
It works fine both ways for me on master.
No issue with *multipart to singlepart* and then reshape either.
It is built against geos 3.9.0dev with overlayNG though, so maybe it is a geos issue.

**Comment by uclaros** [comment]
Do you use snap for the reshape? If yes you could be hitting one of the following:
- Snap to segment works 25% of the times for split and reshape (#29270)
- Snap to vertex with a project crs different than the layer crs is unreliable (possibly related to #29648)

**Comment by gioman** [comment]
> It is built against geos 3.9.0dev with overlayNG though

then you are cheating ;)

**Comment by lbartoletti** [comment]
> so maybe it is a geos issue.

Yes, QGIS uses geos for this feature, there are other bugs in this kind. 
It'a precision problem and overlayNG will fix it.
You still can fix your data using snap to grid algorithm and reduce the precision of your coordinates to what you really need to have (only 2 or 3 digits). This should work in most cases.

**Comment by agiudiceandrea** [comment]
Hi @lbartoletti, I don't think the issue is triggered by a great number of decimal digits in the coordinates values.

On Windows 7 64 bit, latest available QGIS 3.17.0-master build (GEOS 3.8.1-CAPI-1.13.3), I can replicate the reported issue with a 4 vertex (actually 5, with first=last) singlepart polygon stored in a geojson (just to be sure about the number of decimal digits) layer in which the coordinates values of the vertexes have only 3 decimal digits: [test_reshape_3_digits.zip](https://github.com/qgis/QGIS/files/5715349/test_reshape_3_digits.zip)

Conversely, the issue doesn't happen using the same polygon in a geojson layer with 15 decimal digits coordinates values, from which the previous one was created: [test_reshape_15_digits.zip](https://github.com/qgis/QGIS/files/5715357/test_reshape_15_digits.zip)

**Comment by Pedro-Murteira** [comment]
@giedrioks26 I've tested this on QGIS 3.22.3. with a new profile, no plugins installed, and both ways are working alright. Did you come across this issue more recently?

**Comment by agiudiceandrea** [comment]
> @giedrioks26 I've tested this on QGIS 3.22.3. with a new profile, no plugins installed, and both ways are working alright. Did you come across this issue more recently?

The issue depends on the GEOS version installed in the system and used by QGIS:

- with QGIS 3.16.16 on Windows from OSGeo4W v1 with GEOS 3.8.1-CAPI-1.13.3: the issue does occur

- with QGIS 3.16.16 on Windows from OSGeo4W v2 with GEOS 3.10.0-CAPI-1.16.0: the issue does not occur

**Comment by gioman** [comment]
> * with QGIS 3.16.16 on Windows from OSGeo4W v2 with GEOS 3.10.0-CAPI-1.16.0: the issue does not occur

@agiudiceandrea @uclaros 3.22.3 ship with GEOS 3.10 and there won't be a new 3.16 release, can we close this?

**Comment by agiudiceandrea** [comment]
What about other operative systems?
On Linux Ubuntu 20.04 Focal Fossa has GEOS 3.8.0.

**Comment by gioman** [comment]
> On Linux Ubuntu 20.04 Focal Fossa has GEOS 3.8.0.

@agiudiceandrea I'm a Linux user, and I learnt to live with old dependencies, if I don't want to compile myself code. Also: there will be any fix to workaround the old GEOS dependency? If not then it still does not make sense keep this open.

**Comment by agiudiceandrea** [comment]
> If not then it still does not make sense keep this open.

Yes, it's a GEOS upstream issue.
