### ISSUE TITLE
Erro ao utilizar google maps

### ISSUE THREAD

**Issue by Emeli21** [qgis/QGIS#40925]
Bom dia,
Estou tendo um erro ao tentar utilizar o google maps dentro do Qgis, com as novas atualizações ele começo a dar um erro no código phyton. Simplesmente ele não me permite usar o google maps sem quelas pequenas letras na imagem e dizendo que a mesma foi mal carregada. 
Haveria alguma solução?
Agradeço a atenção.

Emeli Susane

**Comment by roya0045** [comment]
1) english 2) is this a question? If so please post on the mailing list and not in the issues/feature requests.

**Comment by gioman** [comment]
@Emeli21 as stated here

https://github.com/qgis/QGIS/issues/new/choose

this facility is not for questions. 

Issues reports must be written in English and add all the requested info as per

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

 Your issue is anyway likely a local issue or an issue with a 3rd party plugin (if is the latter you must report to the plugin author, again as stated here https://github.com/qgis/QGIS/issues/new/choose).

Cumprimentos
