### ISSUE TITLE
World_times Projection does not woerk

### ISSUE THREAD

**Issue by Algarius** [qgis/QGIS#40927]
Hello

Im new on QGIS, and i have a question. I downloaded the Natural Earth TIFF
https://www.naturalearthdata.com/downloads/10m-raster-data/
I import this Tiff in Qgis Version 3.16.2
Then i change the KBS ( I think in english its the name CRS) to
World_times (ESRI: 54048) or to Sphere_times (ESRI: 53048)
but when i do this, the Map disappear and i have a white blank screen instead of the Map.

Have you an idea what i doing wrong? This still works not.

Thank you very much for your Help
Best regards
Thomas

**Comment by gioman** [comment]
@Algarius Hi,

this is not the place for questions, as stated clearly here https://github.com/qgis/QGIS/issues/new/choose

If you want to reproject on the fly a layer in another CRS you must change the CRS of the project, not the one of the layer. The CRS that shows in a layer properties must be the one of the datasource. It is possible to manually change the layer CRS because there are cases where a layer was givena wrong CRS when loaded in QGIS or because has been given a wrong CRS when created, but are edge cases.

**Comment by nyalldawson** [comment]
For reference: this is fixed in newer versions of the proj library, so it will work in qgis as soon as the proj library version is updated
