### ISSUE TITLE
Duplicate parameter coordinates registered for alg v.net.visibility

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#41030]
**Describe the bug**

The Log Messages panel shows the following warning:

`WARNING    Duplicate parameter coordinates registered for alg v.net.visibility`

**QGIS and OS versions**

QGIS 3.10.13 - QGIS 3.16.2

**Additional context**

This issue was fixed in 3.2 with 5436ce9a3583fa77e335931dd69828ca950c0894 (https://github.com/qgis/QGIS/pull/6649) and then reintroduced since 3.10.11 and 3.16.0 with 3119eb7de2f2d1bf27001d6b5160af9295b3b355 (https://github.com/qgis/QGIS/pull/38966)

**Comment by gioman** [comment]
@agiudiceandrea I can take care of this.

**Comment by bkgrantham** [comment]
I am having this same issue when trying to use the Line Smoothing Tool. Not sure if it is something on my end. I input a line shapefile and getting this error

**Comment by agiudiceandrea** [comment]
Hi @bkgrantham , does the Line Smoothing tool works as espected? What kind of issue do you experience?
The error reported in this bug report regards only the GRASS v.net.visibility, although the error message is always displayed in the Log Messages panel.

**Comment by gioman** [comment]
>  Line Smoothing Tool

@bkgrantham you can use also GRASS's v.generalize with the "Chaiken" algorithm.

**Comment by bkgrantham** [comment]
Im sorry, the error message was from a previous tool. Im experimenting with QGIS. Im getting an error " First Derivative is singulair! Probably the shape containes consectutive identical points." Im getting this error from running the line smoothing tool in SAGA. I am trying to smooth out a plotted floodplain and this tool looks like it will do a better job with smoothing out the floodplain. Sorry about highjacking this thread

![image](https://user-images.githubusercontent.com/70763516/105395111-01744400-5be4-11eb-81eb-812bf1edae5f.png)

![image](https://user-images.githubusercontent.com/70763516/105395124-0638f800-5be4-11eb-843b-ff5863b0615a.png)

**Comment by gioman** [comment]
> Im getting this error from running the line smoothing tool in SAGA.

@bkgrantham this is unrelated to this ticket, please do not mix up issues. Anyway please attach you dataset, I can test if it works under SAGA or not.

**Comment by bkgrantham** [comment]
Ok thanks. Feel free to remove my comment as it does not pertain to this task. SMH
[Floodplain.zip](https://github.com/qgis/QGIS/files/5851391/Floodplain.zip)

**Comment by bkgrantham** [comment]
Ok thanks!

**Comment by agiudiceandrea** [comment]
Will this be fixed in time for QGIS 3.16.4 LTR?

**Comment by gioman** [comment]
@agiudiceandrea i'll have a look later today.

**Comment by gioman** [comment]
@agiudiceandrea here the PR https://github.com/qgis/QGIS/pull/41515

I have removed the duplicate parameter, leaving the one that make use the widget to pick a coordinate from the map. Anyway I'm not sure about it because the parameter can accept multiple coordinates (and in this case we should change from the coord picker widget to an open string parameter).

Moreover the parameter "visibility" was set to accept only points layers, but in my opinion that was wrong as reading the examples in the GRASS manual seems clear to me that it should be lines layers (despite the description for the parameter reading "Name of input vector map containing visible points").

**Comment by BotDoubt** [comment]
Hi all,

I think I'm getting the same error, but under different circumstances. Please let me know if I'm posting this in the wrong place (I'm pretty new to GitHub and _very_ new to QGIS).

I tried to change the canvas background color to something other than white. The background color doesn't change, and I get the following Processing Log Message: 'WARNING Duplicate parameter coordinates registered for alg v.net.visibility'

I'm on Windows 10 64 bit

QGIS and System info:
```
QGIS version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
OS Version: Windows 10 (10.0)
Active python plugins: FreehandRasterGeoreferencer; qgis_resource_sharing; QuickOSM; ViewshedAnalysis; db_manager; MetaSearch; processing
```
I also had the Least-Cost Path plugin active, but I uninstalled it earlier this evening because it threw a different error when I tried to change my background color - `RuntimeError: wrapped C/C++ object of type LeastCostPathAlgorithm has been deleted`

Again, let me know if this is the wrong place to put this comment, and thanks!

**Comment by agiudiceandrea** [comment]
Hi @BotDoubt, your issue is unrelated to the "Duplicate parameter coordinates registered for alg v.net.visibility" warning. That warning appears in the Log Messages Panel since QGIS is started.
