### ISSUE TITLE
Label placement is broken in QGIS 3.16

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#41043]
Text placement is set to "Curved" along a line. When label is moved to the edge of the screen, then it's placement switches to horizontal, an sometimes label even overruns. But overrun is set to none. 

See the attached video.
There is a comparison between 3.12 and 3.16.

v3.12 behavior
https://user-images.githubusercontent.com/11345848/104806985-6ac31400-57ec-11eb-9ac0-cc350a0bcec9.mp4

v3.16 vehavior
https://user-images.githubusercontent.com/11345848/104806996-7adaf380-57ec-11eb-8b57-07af02d9bc6d.mp4

This breaks tiled export and exprort to partial map sheets.
I expect the label to be clipped to the edge of the screen (preferrable) or disappear.

**Comment by nyalldawson** [comment]
Can you share a sample project please?

**Comment by Xeenych** [comment]
[temp.zip](https://github.com/qgis/QGIS/files/5828350/temp.zip)
Here it is.
Thre are two layers: with GOOD and BAD label placement

**Comment by nyalldawson** [comment]
The difference between the layers is that the one which falls back to the horizontal placement has the option "Show all labels for this layer" enabled. 

I'm not entirely convinced this is a bug. When the "show all labels" option is enabled then the user is indicating that showing labels is more important than the actual placement /appearance of these. But I'm open for second opinions. @nirvn what do you think?

**Comment by Xeenych** [comment]
When "show all labels" is enabled I expect the label to be shown on its original place along the curve, not somewhere else, the labels should have the same font and orientation, spacing, the same size, color etc. Other settings should be preserved. 
Just the collissions should be ignored.

**Comment by roya0045** [comment]
To most user 'show all labels' mean 'find the optimal place and display it', rather then not caring about the overlap.

**Comment by Xeenych** [comment]
I don't agree.
find the optimal place and display it - is the default expected behavior. That what placement engine is for. Tp find optimal place (with some constraints, size, spacing, orientation, collisions) and place label. 
"Show all labels" should remove collision constraint leaving all other constraints intact. That is how this setting behaved in 3.12 and older versions. Even in 2.x

**Comment by Xeenych** [comment]
The same behaviour in 3.18.1.
Label jumps out of its place.

**Comment by apicella2** [comment]
3.18.3
I agree with Xeenych, the behaviour in 3.12 was right.
Will it ever be set as it was before?

**Comment by stadt-koeln-tillmann** [comment]
3.22 This issue is still a big problem. Is there any chance to change this behavior. It was not like this in the past QGIS-versions and ist does not make any sense. Actually there isn't any recogniseable rule, which this behavior is following. If I want the label to follow a path, it should do it in any way, otherwise it appears as a mistake when suddenly horizontal labels are shown.

I do need a change urgently. Is there a workaround or has this to be changed in the QGIS code? If neccessary I would like to discuss it with developers. How can I get in touch?

I am glad for any help! 

Robert

**Comment by JuliaLev** [comment]
This Problem is also annoying me. Would love to see a solution

**Comment by Xeenych** [comment]
@nyalldawson reopen this please!

**Comment by elpaso** [comment]
> 3.22 This issue is still a big problem. Is there any chance to change this behavior. It was not like this in the past QGIS-versions and ist does not make any sense. Actually there isn't any recogniseable rule, which this behavior is following. If I want the label to follow a path, it should do it in any way, otherwise it appears as a mistake when suddenly horizontal labels are shown.
> 
> I do need a change urgently. Is there a workaround or has this to be changed in the QGIS code? If neccessary I would like to discuss it with developers. How can I get in touch?
> 
> I am glad for any help!
> 
> Robert

@nyalldawson and myself are working on some bugfixing and enhancements for the label along path manual placement, I'm not sure if that will fix this issue though. Feel free to contact us in private (contacts are in the QGIS professional support list https://www.qgis.org/en/site/forusers/commercial_support.html#qgis-commercial-support).

**Comment by stadt-koeln-tillmann** [comment]
@elpaso Thank you for your immidiate reply. Actually I can not find your contact informations in the supporter list. I am working on a city-map in qgis which needs reliable labeling. I am sure to have tested any kind of labeling from the menus now. I could supply test-data and qgis-styling.

**Comment by stadt-koeln-tillmann** [comment]
We are still searching for any solution on this issue very intense. I would like to keep this issue open, How can I reopen it? How can I get in contact with the one who built this labeling features?

**Comment by elpaso** [comment]
> We are still searching for any solution on this issue very intense. I would like to keep this issue open, How can I reopen it? 

This issue is already open.

Can you test https://github.com/qgis/QGIS/pull/47872 ?

**Comment by stadt-koeln-tillmann** [comment]
Thank you for the hint, but #47872 does not properly work for us. Ourstreet-data ist in a postgresql-database and viewed from different QGIS-Projects. Moving the labels is a feature, that changes the placement within the presentation of the labels inside of a QGIS-Project. What we do ist putting the labeling information into the dataset, even the chosen size. At the end we exchange the dataset with our neighbour communes, so they can include it into their city map. Furthermore we tryed this feature experimentally, but with thousends of text and a complicate map-styling working with it is much to slow and far off from being efficient. What we need is a relyable labeling engine. All labels must be shown, and if they are defined to be shown alongside a path, especially this must be done relyable. There is no reason at all to show them horizontal, and they do even if the path is long enough! A collision with other labels can not be the reason for this behavior - per definition. In a former contribution is told, this would be consequent. I think it is not, it is a mistake, and I hope this is going to be repaired soon.

**Comment by IBW-Peter-Markus** [comment]
Hello everyone, we're having similar issues in QGis 3.22.5 ltr 64 bit and think it's the same fundamental problem. We also store the labeling information in a postgres-database. Since QGis 3.16, the labels change their position on the labeled object and change their orientation to horizontal when zooming or navigating the map. This happens when the stored coordinates for the label leave the displayed map.
Examples of the issue:
![incorrect_example_1](https://user-images.githubusercontent.com/104503096/165525553-e42b47ff-dd30-43c6-94c9-8695356ca5e0.png)
![incorrect_example_2](https://user-images.githubusercontent.com/104503096/165525557-7c5fd545-ade9-4c1c-9be8-ff63f843c5c1.png)
Same area from a wider Scale (all coordinates within the displayed map):
![correct_example_1](https://user-images.githubusercontent.com/104503096/165526581-fdebb564-5aa7-45da-9961-1d8365a0bb7e.png)
In previous Qgis-versions the labels with stored coordinates outside the displayed area where not displayed, now the labels move to the labeled object.

**Comment by stadt-koeln-tillmann** [comment]
If the label is forced to be shown but does not fit to the line however, would it be a possibility in those cases to increaase the overun automatically instead of switching the label off the linestring? Actually it is no problem, if labels are colliding. The problem for me is, that I do not even know, who worked out the labeling engine and created this behavior of QGIS and who is able to solve the problem. Probably for this person it would be easy to solve this issue.

**Comment by jef-n** [comment]
> This happens when the stored coordinates for the label leave the displayed map. 

That could be worked around by setting a "Show label" expression to only display labels with positions (here x and y) inside of the canvas: ``within(make_point(x,y), @map_extent)``

**Comment by stadt-koeln-tillmann** [comment]
Yes, this ist true, but not only and not not always! Sometimes ist appears without any recogniseable reason offside the edge of the canvas. BTW probably I do not want the label omitting at the edge instead of beeing cut?!

**Comment by IBW-Peter-Markus** [comment]
@jef-n Thank's for the workaround. On first sight does this solve our Problem (moving labels onto the object when the stored coordinates for the label leave the displayed map).

Unfortunately, this reduces performance a bit. This was not the case in previous QGIS versions and it makes no sense to move labels onto the object if a position for the label is given.

**Comment by stadt-koeln-tillmann** [comment]
I still would be very, very happy to see this problem to be solved.

**Comment by nyalldawson** [comment]
Just a heads-up that I'm working on a fix for this for the 3.26 bug fixing round :+1:

**Comment by stadt-koeln-tillmann** [comment]
This sounds very good! Is it probably an option to increase the line overrun automatically, if the lines are to short to show any label. Anyway: I would be very happy with the solution mentioned above. If I can help with any data for testing, then please let me know.

**Comment by stadt-koeln-tillmann** [comment]
Hello Nyall Dawson, I do not want to forget to send a big thank you for your help and enggement in this topic. It was a very big help and we solved our problem with this. It took us some tests to work out, which combination of choosen options lead to an maximum of labeled roads in our city map, but at the end we got 99,9% of the recommended labels. Greetings from Cologne.
