### ISSUE TITLE
Relation reference for default styles stored in PostgreSQL are not populated in QGIS

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#41131]
# Problem

* Spin up a database i.e running on port 25433 i.e 
```
docker run --name "postgis" -p 25433:5432 -d -t kartoza/postgis:11.0-2.5
```
* Restore the database dump attached below.
```
pg_restore -d gis -p 25433 - U docker -h localhost -f data.sql
```
* Open the QGIS project from the PostgreSQL database.

* Look at the attribute form for the Parcel_Lookup layer. Notice the form layout inherits the style from the database but the
relation references in the project properties are empty.
![form-layout](https://user-images.githubusercontent.com/2510900/105458323-017e4d80-5c91-11eb-92ac-4439c78a128c.png)

*  Apply the qml style attached to the Parcel_Lookup layer. Notice that the Relation references are now applied to the project
![ref-rel](https://user-images.githubusercontent.com/2510900/105458746-cdeff300-5c91-11eb-91e8-fbecea929f40.png)

* Save the style into the database and make it the default style
* Close the QGIS project and reopen it. Notice the default style still doesn't have the relation references populated

**NB:** Use the docker image to test others if you need to use your local database make sure you have a user called `docker` with a password `docker` and the database is running on port `25433` because the relation references stores all these credentials in the XML file. 

[parcel.zip](https://github.com/qgis/QGIS/files/5854182/parcel.zip)

Tested with QGIS
![Qgis-ret](https://user-images.githubusercontent.com/2510900/105460515-92a2f380-5c94-11eb-9481-14765149bbe8.png)

**Comment by SebastienPeillet** [comment]
@NyakudyaA I'm not sure the bug is well identified here. I tested the project that you provided.

From what I see the default style is saved with the relation references. If I remove and add again the parcel_lookup layer, relations will be considered in the project, it can be saved and relations will be still there when I re-open the project.

Default styles are used when you're adding a new layer in the project, but then it's the project that stores the layer style. When you re-open the project, only the project style is used and not the default style (otherwise it would be impossible to store a particular style if a default style is defined).

Here, you applied a default style but you didn't save the project, so the layer keeps the same style in the project. I think the mistake came from : 

> Look at the attribute form for the Parcel_Lookup layer. Notice the form layout inherits the style from the database but the
relation references in the project properties are empty.

Actually the form properties are defined in your project, so you thought it came from the default style, but it's not.

**Comment by gioman** [comment]
Closing for lack of feedback.
