### ISSUE TITLE
Project loading fails to properly restore temporal range of fixed range temporal settings

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#41225]
Most likely culprit: https://github.com/qgis/QGIS/commit/9da580cb3d4e58f530486ffbf6ec77ec4d3601d9

When a project is being restored / loaded, the temporal range fails to restore properly whe it's set to fixed range. Instead, the actual temporal range used to render the canvas is the fixed range's start date and instead of using its end date uses the the start range + animated temporal mode's step.

@dminor , ping. Needs fixing prior to 3.18 release.

**Comment by nirvn** [comment]
@dminor , I might have wrongly pointed the finger at you :wink: -- you or @Samweli 's work on the temporal nav. object led to this regression.

**Comment by dminor** [comment]
Sorry about that! I started some work on temporal navigation, but I didn't have a chance to finish it and @Samweli picked it up for me. I apologize for any bugs in the code I wrote, but since I didn't actually finish the work, I haven't followed it closely, and I'm not really in a good position to make a fix.

**Comment by nirvn** [comment]
No worries, fixed now. Thanks for your efforts here, happy spatiotemporal mapping! ;)
