### ISSUE TITLE
Zoom to Layer(s) action does nothing when no layer is selected in layer panel

### ISSUE THREAD

**Issue by TurboGraphxBeige** [qgis/QGIS#41288]
A layer absolutely needs to be selected in the layer panel for the Zoom to Layer(s) action to do something. 

Steps to reproduce:

1. Select a spatial layer in the layer panel
2. Deselect it with ctrl+left click on the layer
3. With the layer being deselected but still the "active layer", click on Zoom to Layer(s) (View menu or Map Navigation toolbar)
4. The action should do nothing

![Peek 2021-01-31 21-07](https://user-images.githubusercontent.com/59714546/106407448-0d44df00-640a-11eb-9ac1-9cd91fcdf655.gif)

**Comment by rduivenvoorde** [comment]
@TurboGraphxBeige I think this is related to the not so sharp defined use of terms like 'selected', 'current' and 'active' in our legend....
Can you elaborate a little on you screencast? Because to me it looks like to behave as you want/describe it to behave?
You first make poly 'selected' (green background), zoom to it: OK?
Then you make the test 'selected' (green background) zoom to it: OK?
Then you deselect 'test', the green background is removed, but it is still 'current' I think because it still has some opaque background compared to the others. Then you try to zoom to it, and nothing happens... OK?

(OR do you propose to rename the action: "zoom to SELECTED layer(s)"?

**Comment by TurboGraphxBeige** [comment]
By selected, I really mean "with green background" (returned by selectedLayers()) and by active/current, I mean when the layer name is "underlined" in the layer panel (and returned by activeLayer()). 

To elaborate on my screencast:

>  You first make poly 'selected' (green background), zoom to it: OK?

Yes

>  Then you make the test 'selected' (green background) zoom to it: OK?

Yes

> Then you deselect 'test', the green background is removed, but it is still 'current' I think because it still has some opaque background compared to the others. Then you try to zoom to it, and nothing happens... OK?

Yes. The layer is deselected and selectedLayers() returns an empty list. 'test' is still the active layer and activeLayer() returns this layer. However nothing happens when clicking "Zoom to Layer(s)".

I only propose the action to actually do something if no layer is selected in the layer panel (green background). To compare, "Zoom to Selection" has this behavior. I think it is the appropriate behavior because if zooming and panning to layers or selection is done using the selected layers in layer panel, it could also happen that a user deselect everything, then tries to zoom to a layer (I did it myself to discover this behavior). So if nothing is selected, defaulting to the active layer feels kind of natural.
