### ISSUE TITLE
regexp_match function in advanced Filter/Select in attribute table ignores UTF diacritics when matching word boundary

### ISSUE THREAD

**Issue by pavaos** [qgis/QGIS#41453]
**Describe the bug**

Regular expression **\\\\b** should match a word boundary before or after a string of word-characters, but it seems that it doesn't see UTF diacritics (single character, not combined) such as ą ę ł ń ó ż ź š ć ž etc. and ignores it (as well as characters after it).

**How to Reproduce**

1. Add Delimited Text Layer ([buda_test.txt](https://github.com/qgis/QGIS/files/5952386/buda_test.txt)) with encoding set to UTF-8, and no geometry
2. Right-click on "buda_test" layer -> Open Attribute table -> Select features by expression
3. In "Expression" field type 

> regexp_match\("name", '[Bb]ud[ay]\\\\b'\)

 and click Select features.

4. This expression should match only words Buda, Budy, Kolbudy, Babuda, Buda Something, Buda-everywhere (objects with id 1, 2, 3, 4, 5, 6), where **a** or **y** is at the end of the string of word characters, but it appears that when diacritics follow these letters QGIS just ignores it and treats as... I don't even know how to call it - word boudary itself (?), so the selection covers also objects with names Bud**yń**, Bud**aś**, Bud**yš**, Bud**aą**, Bud**ać**, Pobud**yż**, Bud**ażo** and so on.
5. I tried a look-ahead option as well but it behaves the same way: 

> regexp_match("name", '[Bb]ud[ay]\(?=\\\\b\)'\)

**QGIS and OS versions**
This happens also in earlier 3.10 La Coruna version. In 2.18 Las Palmas everything is ok.

QGIS version: 3.16.1-Hannover
Compiled against Qt: 05.11.2002
Compiled against GDAL/OGR: 03.01.2004
Compiled against GEOS: 3.8.1-CAPI-1.13.3
Compiled against SQLite: 3.29.0
PostgreSQL Client Version: 11.maj
QWT Version: 06.01.2003
Compiled against PROJ: 06.03.2002
QGIS code revision: b381a90dca
Running against Qt: 05.11.2002
Running against GDAL/OGR: 03.01.2004
Running against GEOS: 3.8.1-CAPI-1.13.3
Running against SQLite: 3.29.0
SpatiaLite Version: 04.03.2000
QScintilla2 Version: 02.10.2008
Running against PROJ: Rel. 6.3.2, May 1st, 2020
OS Version: Windows 10 (10.0)
Active python plugins: db_manager; MetaSearch; processing

**Comment by rduivenvoorde** [comment]
Confirmed here on current master. Also with real utf-8 file I created here based on the same texts.

I'm not a regexp guru, but  FYI: work is done here:
https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpressionfunction.cpp#L1433-L1445

(I tried to replay this in the Python console, but fail there because QString is not defined there, so indexOf is unknown to a string)

**Comment by rduivenvoorde** [comment]
Ah, I think I found it... 

First I tried it in Python, as I read somewhere (cannot find it now) that 
regexp_match would follow python rules:

```
#!/usr/bin/env python3

import re

exp = re.compile('[Bb]ud[ay]\\b')

with open('buda_test.txt', 'r') as f:
    f.readline() # just to skip first line
    lines = f.readlines()
    # just to sort them on id
    lines = sorted(lines, key=lambda x: (int(x.split(',')[0])) )
    for line in lines:
        if len(line)>0:
            print(f'{line.split(",")[0]} {line.split(",")[1][:-2]} {exp.search(line.split(",")[1])}')
```
returns
```
01 Bud <re.Match object; span=(0, 4), match='Buda'>
02 Bud <re.Match object; span=(0, 4), match='Budy'>
03 Kolbud <re.Match object; span=(3, 7), match='budy'>
04 Babud <re.Match object; span=(2, 6), match='buda'>
05 Buda Somethin <re.Match object; span=(0, 4), match='Buda'>
06 Buda-everywher <re.Match object; span=(0, 4), match='Buda'>
07 Budal None
08 Budyr None
09 Budy None
10 Buda None
11 Budy None
12 Buda None
13 Buda None
14 Pobudy None
15 Buda None
16 Buda None
17 Buda None
18 Budy None
19 Budač None
20 Budał None
21 Budaż None
22 Budyś None
```
(I noted that there is always a \n after the words....)

which seems OK... BUT then looking into the QGIS code, it looks like it is (maybe later) ported to C++ so actually using:
https://doc.qt.io/qt-5/qregularexpression.html
Some fiddling and debugging I found the option `QRegularExpression::UseUnicodePropertiesOption` in
https://doc.qt.io/qt-5/qregularexpression.html#PatternOption-enum

If I add that to the line:
```
QRegularExpression re( regexp, QRegularExpression::UseUnicodePropertiesOption );
```
instead of
```
  QRegularExpression re( regexp );
```
it give this result: 

![Screenshot-20210211115415-865x801](https://user-images.githubusercontent.com/731673/107627651-e5524880-6c5f-11eb-96ae-1c5cdcf5cf48.png)

So if OK, I think I will try to create a pull request, just hope that this does not break a lot of tests....

There is indeed an  ASCII bias in the western world....  :-)

**Comment by rduivenvoorde** [comment]
@pavaos ^^

**Comment by pavaos** [comment]
@rduivenvoorde thank you very much, it looks good. I'll try it.
