### ISSUE TITLE
QGIS 3.16.4 LTR splashscreen without long term release red lettering

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#41785]
QGIS 3.16.4 HANNOVER is the new LTR, I noticed that what in object is missing

## OSGeo4W64 win 10

![image](https://user-images.githubusercontent.com/7631137/108985441-5860b380-7691-11eb-9e7c-93f6a12d0ec5.png)

**Comment by pigreco** [comment]
I just saw that in the source file (* .xcf), the layers are disabled:

![image](https://user-images.githubusercontent.com/7631137/108987086-2d775f00-7693-11eb-9942-78909e9e42a3.png)

**Comment by jef-n** [comment]
BTW we can enabled that when the new branch is released.   LTR starts with 0 not 4.  That we have two lines of repos and keep the previous LTR in the ltr repo and the new LTR in the regular repo is just because there's no point in having the same in both - so the new LTR takes the place of the old one, once there is a new release to takes it place in the regular repo.

**Comment by agiudiceandrea** [comment]
It seems fixed in 3.16.5

![image](https://user-images.githubusercontent.com/16253859/113473884-9c9f5a80-946c-11eb-97f9-aa19c337501e.png)
