### ISSUE TITLE
Value map widget: "value"/"description" inconsistency when table added to print layouts

### ISSUE THREAD

**Issue by Cucumerlu** [qgis/QGIS#41798]
Hi, 
I created a QGIS project using value map widget. When I open attribute table in the "main" project I see the "description" BUT when I create an attribute table in the layout I see the "value"

Example
1 - build
2 - river
3 - tree

In the attribute table of the project I see "build", "river" and "tree"
In the attribute table in tha layout I see 1, 2, 3

Can you help me?

Thanks

**Comment by gioman** [comment]
@Cucumerlu show "description" instead of "value" in the attribute table is by design, so here there should not be any bug. I guess that one could argue that then also in print layouts the table should behave the same. Anyway there are probably many workarounds, you can for example create a virtual column that is filled with the "description" and this will show as such in the layouts.

**Comment by Cucumerlu** [comment]
@gioman I know that I could _"create a virtual column that is filled with the "description" and this will show as such in the layouts"_ but I have a lot of columns and I don't think that the incosistency _"is by design"_. And, as you understand, I argue that _"also in print layouts the table should behave the same"._

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3. (Windows 10)
