### ISSUE TITLE
Activating Processing plugin crashes QGIS

### ISSUE THREAD

**Issue by rmarkRCS** [qgis/QGIS#41973]
Mac OS 10.15.7

Application Specific Information:
/usr/lib/libssl.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libssl dylib as it does not have a stable ABI.

**Comment by gioman** [comment]
@rmarkRCS  QGIS version?

Have you tried on a new QGIS profile?

**Comment by rmarkRCS** [comment]
QGIS 3.18
What do you mean new profile?

**Comment by gioman** [comment]
>  What do you mean new profile?

@rmarkRCS settings > user profiles > new profile

**Comment by rmarkRCS** [comment]
New profile did not fix the crash.
Perhaps an Apple security problem?

**Comment by gioman** [comment]
> New profile did not fix the crash.

@rmarkRCS I will try on my mac mini shortly.

**Comment by rmarkRCS** [comment]
Look at https://developer.apple.com/forums/thread/119429

**Comment by gioman** [comment]
@rmarkRCS Can't confirm on a clean 3.16.4 installation on macOS Catalina.

**Comment by rmarkRCS** [comment]
I can try reinstalling, I guess...

**Comment by Sergegang** [comment]
Hi everyone, I have the same problem on my macmini with Catalina 10.15.7. The processing plugin is blocked because it crashes the Qgis. The version I have installed is the QGIS version 3.16.4-Hannover.

Someone has solved the problem, can you help me?

Thank you.
![Schermata 2021-03-06 alle 21 43 07](https://user-images.githubusercontent.com/80176146/110220588-e117f480-7ec6-11eb-8107-0e7d80930bbe.png)

![Schermata 2021-03-06 alle 21 43 21](https://user-images.githubusercontent.com/80176146/110220584-dc534080-7ec6-11eb-9f74-060b5fedaef3.png)

**Comment by gioman** [comment]
> Someone has solved the problem, can you help me?

@Sergegang try a new QGIS profile.

**Comment by Sergegang** [comment]
@gioman I had already tried.Unfortunately it doesn't work the same, at least in my case. Also even if I start the python console it crashes.

**Comment by gioman** [comment]
> Also even if I start the python console it crashes.

@Sergegang so it seems you clearly have a local issue.

**Comment by Sergegang** [comment]
@gioman what kind of issue in your opinion?

**Comment by gioman** [comment]
> @gioman what kind of issue in your opinion?

@Sergegang hard to say, maybe a multiple python installations mix-up.

**Comment by Sergegang** [comment]
@gioman To avoid this problem I have completely formatted the Mac and then reinstalled only version 3.16.4 and the Path seems to me the right one.

![Schermata 2021-03-07 alle 12 18 42](https://user-images.githubusercontent.com/80176146/110238011-6212d280-7f3f-11eb-84ea-598b375f944f.png)

**Comment by gioman** [comment]
> To avoid this problem I have completely formatted the Mac and then reinstalled only version 3.16.4

@Sergegang then there may be something else at play. I test on clean macOS systems in English and QGIS set to work in English locale settings. Maybe you may want to try run a macOS VM and see if there it makes any difference.

**Comment by Sergegang** [comment]
@gioman I solved it! I did this: first I installed python 3.9 and then gdal. I installed them from here.  https://www.kyngchaos.com/software/qgis/
            
![Schermata 2021-03-07 alle 15 04 44](https://user-images.githubusercontent.com/80176146/110242649-4a474880-7f57-11eb-93c5-a4086ca068b3.png)

Then I installed it all in one versione QGIS_LTR from here.    
https://www.qgis.org/it/site/forusers/download.html#                                                                                                             
      
![Schermata 2021-03-07 alle 15 12 34](https://user-images.githubusercontent.com/80176146/110242718-9abea600-7f57-11eb-80b1-7fd42c0e4f39.png)

Everything works.

**Comment by gioman** [comment]
> @gioman I solved it! I did this: first I installed python 3.9 and then gdal. I installed them from here. https://www.kyngchaos.com/software/qgis/

@Sergegang this should not really be necessary (and if fact it isn't).

**Comment by kyngchaos** [comment]
What I could figure out about this problem is something in python seems to be loading libssl dynamically.  I could find no direct library loading links to the system libssl for anything in QGIS or python.  I could also not find any meaningful references to "ssl" that might be used to load the ssl library from python.  I would need a python trace to see where it comes from, but since QGIS crashes we get no trace. 

To summarize the background for this problem from the Apple link above and what I found - macOS Catalina (10.15) added a security measure to lock out loading libssl without a version in the library name.  The proper solution would be to load the versioned library, but we don't know where it's coming from, and may not have control of the source of that call.

One solution mentioned using DYLD_FALLBACK_LIBRARY_PATH environment var to point python dyld to a libssl that doesn't have this restriction.  The Mac Python framework does have its own libssl and libcrypto, but it's not in the default library path, so it's not found.  I suggested to someone (was that you @Sergegang ?) to add this to QGIS system vars, pointing to the Python lib folder, but it didn't work.

When I see the screenshot from @Sergegang with the python lib path, I wonder now if it's something to do with the system language.  The top level there uses "Libreria" instead of "Library" that I suggested.  If you "ls /" in a terminal, are those really the top level folder names on your system?  Or maybe the Finder is renaming them on the fly? (I suspect dynamic renaming, otherwise the GDAL and Python installers would not work, unless the Apple installer also redirects paths based on locale)

You could try adding DYLD_FALLBACK_LIBRARY_PATH set to 

/Libreria/Frameworks/Python.framework/Versions/3.9/lib

**Comment by Sergegang** [comment]
Hi @kyngchaos Yes , I am. I uninstalled everything as you suggested, without installing python and gdal separately, because "this should not really be necessary". Now i installed the all in one version, only. It seems that everything works but gives me an error for matplotlib :   CRITICAL    Semi-Automatic Classification Plugin : Error. Check Python Matplotlib installation for the Semi-Automatic Classification Plugin. 

While typing ls / this is the report:
Applications	Volumes		etc		sbin
Library		bin		home		tmp
System		cores		opt		usr
Users		dev		private		var

**Comment by SebSilva** [comment]
Hi, reporting similar issue with Processing Plugin on QGIS 3.16.7 Hannover, on a new Mac running on Catalina 10.15.7. 

This is the first software I installed on my Mac following Kyngchaos links/instructions: 1) Python, 2) GDAL and 3) QGIS.

So QGIS automatically deactivated the plugin the next time I opened it. And QGIS crashes as soon as I activate the Plugin.

**Comment by kyngchaos** [comment]
Sorry, I forgot to report back to this bug report (I've also been receiving reports of this problem directly).  The solution I recently found is to symlink Python's libssl and libcrypto into /usr/local/lib, this is one of Pyhon's default search paths for dynamically loading libraries.  For some reason the DYLD_FALLBACK_LIBRARY_PATH wasn't working, like Python was ignoring it.  

@SebSilva I've incorporated this symlink into my installer, but maybe it's not setting up the symlinks as it's supposed to do.  Do you have a /usr/local/lib/libssl.dylib and /usr/local/lib/libcrypto.dylib?  And do they link into the Python framework? (Get Info in the Finder, or ls -l /usr/local/lib/libssl.dylib in a Terminal)

@rmarkRCS did you install the all-in-one QGIS or my package?
