### ISSUE TITLE
Double-clicking a .qgz file on macOS doesn't open QGIS

### ISSUE THREAD

**Issue by grischard** [qgis/QGIS#42033]
**Describe the bug**

Spin-off from #39204. Double-clicking a .qgz file on macOS doesn't open the project in QGIS.

**How to Reproduce**

1. In the finder, navigate to a .qgz file
2. Double-click it

Expected behaviour:

Project opens in QGIS

Actual behaviour:

macOS doesn't know it can open the .qgz file in QGIS. Finder shows a dialog that says:

> There is no application set to open the document “foo.qgz”.

Workaround:

Right-click on the qgz file, choose 'Open with', choose 'Other', change "Enable: Recommended Applications" to "Enable: All Applications", navigate to QGIS, check 'Always Open With', and finally choose "Open".

**QGIS and OS versions**

3.18, macOS 11.2.2 (both latest)

**Additional context**

PR at #42032

**Comment by grischard** [comment]
Solved in ec3fbaa

**Comment by MattF-NSIDC** [comment]
Is this fix available in a 3.16.x LTR version?

**Comment by MattF-NSIDC** [comment]
Our OSX user tested with `3.16.15`, the latest LTR build, and did experience this issue. They did not experience this issue with 3.22.2. It appears the fix is applied to 3.22.x but not 3.16.x.

@grischard Can this fix please also be applied to the LTR version of QGIS? Our project (qgreenland.org) is directing users towards the LTR release, and we'd like to provide those users with a `.qgz` file instead of the larger `.qgs`.

**Comment by grischard** [comment]
I'm just the guy reporting the bug but there's no reason the fix can't be backported; the changes are minimal.

**Comment by MattF-NSIDC** [comment]
Ah, my apologies! I saw you posted "Solved" and jumped to "I should pester that person". Looks like I should open a new "Bug/crash report" type issue to request that this fix be backported?
