### ISSUE TITLE
missing osgeo4w shell shortcut when installing using the osgeo4w-ng installer

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#42039]
Subject says almost everything.

There is no osgeo4w shell shortcut in the "ogseo4w" menu entry.

The shortcut created within the folder "OSgeo4W" on the Desktop do not open the shell, but it just open a Windows explorer dialog.

The user is left to go dig the shell .bat file inside "C:\OSGeo4W64".

**Comment by jef-n** [comment]
Not an qgis issue

**Comment by gioman** [comment]
> Not an qgis issue

@jef-n should I report it in the psgeo4w tracker?

**Comment by gioman** [comment]
> @jef-n should I report it in the psgeo4w tracker?

@jef-n I'm now even sure if the issues regarding the "new" osgeo4w installer must be reported on the osgeo4w trac. Can you clarify please?

**Comment by jef-n** [comment]
> @jef-n I'm now even sure if the issues regarding the "new" osgeo4w installer must be reported on the osgeo4w trac. Can you clarify please?

Well, it's not always easy to say whether a issues is a qgis issue (file here), packaging issue (downstream in OSGeo4W; file on trac) or maybe just an issue from a newer version in OSGeo4W than we use to have (upstream; file somewhere else).   For packaging issues with the new installer I said:

On Tue, 23. Feb 2021 at 17:36:48 +0100, Jürgen E. Fischer wrote:
> You can install them using the osgeo4w installer on
> http://download.osgeo.org/osgeo4w/testing/osgeo4w-setup.exe (note the testing -
> the old installer will also work, if you point it to the new site, but it will
> default to the old).
[…]
> The package recipes currently reside at https://github.com/jef-n/OSGeo4W.
>
> Please test and report packaging issues to the OSGeo4W TRAC at
> https://trac.osgeo.org/osgeo4w.

Packaging issues with the (now a bit outdated) MSI standalone should probably be fixes there too - although it's "our" installer and not "their" "pure" OSGeo4W ;)  And I'm hijacking GRASS a bit because I've built that for the new installer too - mainly to harvest the QGIS dependencies and not carying about itself to much (ie. the GUI didn't work at all and I didn't even notice).

**Comment by gioman** [comment]
> Please test and report packaging issues to the OSGeo4W TRAC at
> https://trac.osgeo.org/osgeo4w.

@jef-n thanks. Done.

**Comment by jef-n** [comment]
See also https://trac.osgeo.org/osgeo4w/ticket/666
