### ISSUE TITLE
Every time that I try and install the processing plug in on GIS 3.16 and 3.18 the whole QGIS program crashes. As a result I cannot access geoprocessing tools etc.

### ISSUE THREAD

**Issue by newmanm1** [qgis/QGIS#42085]
Every time that I try and install the processing plug in on GIS 3.16 and 3.18 the whole QGIS program crashes. As a result I cannot access geoprocessing tools etc.

**Comment by gioman** [comment]
@newmanm1 if you want to report a bug you must use

https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.md&title=

and use a maningful title (and reasonably short, in your case could be something like "issue activating with Processing") and then adding all the requested infos (see below). 

Please note: you don't have to install the Processing toolbox, it comes with any installation of QGIS since long ago.




**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**
