### ISSUE TITLE
plugin repositories unavailable

### ISSUE THREAD

**Issue by kmw2221** [qgis/QGIS#42153]
i am having an issue where on the plugin manager, under "settings", the QGIS Official Plugin Repository is listed but its status is "unavailable".  i am able to install plugins via from zip, but then they don't seem to work.  For example i am able to download the QuickMapServices plugin via zip, but then when i load the OSM Standard layer as a basemap, nothing shows up on my QGIS console.  

i am using qgis 3.16

can anyone please help? :) thank you!!

**Comment by gioman** [comment]
@kmw2221 works with no issues here.

**Comment by Gustry** [comment]
Since 1/2 days, the plugin manager in QGIS takes a long time to open. The request to plugins.qgis.org seems very very slow. I'm connected to other QGIS plugin repository on the internet, they are answering quite fast, I can only read "connected" for them.

![Capture d’écran de 2021-03-10 20-35-33](https://user-images.githubusercontent.com/1609292/110637709-ff733e00-81ad-11eb-91f9-42e040cb43fe.png)

@kmw2221 maybe your timeout in QGIS Settings -> Network is too low ?

**Comment by kmw2221** [comment]
Thank you all so much for taking a look at this and for your replies.  No
luck here, I tried increasing the network time size 10x as well as
uninstalling/reinstalling the software.  I am on my simple home network
here with a macbook pro, i am pretty sure the plug ins were working when i
looked at this for the first time 3 weeks ago.  Maybe my computer/network
is just acting up, so I will try again next week.

Kris

**Comment by mabesa** [comment]
Similar issue here. Also working on macbook pro,  QGIS 3.16.4 on Windows 10 installed. Plugins Settings says "unavailable QGIS Official Plugin Repository". The repository is available & plugin installations are possible from the mac installation of QGIS 3.16 LTS (some plugins try to access my local python instead of QGIS's version but that's another matter...). Can this be a network problem?

**Comment by gioman** [comment]
> Since 1/2 days, the plugin manager in QGIS takes a long time to open.

@Gustry still the case?

**Comment by dbrizuela** [comment]
Same issue here, any workarounds?

**Comment by dafitt** [comment]
Increasing the QGIS Settings > Network > Timeout Limit to 360000 was the solution for me. Thanks @Gustry. Though it really needs a very long time to connect. The website plugins.qgis.org is also extremely slow (about 1 or 2 minutes). A ping reveals a time of around 105ms.

**Comment by shawndegroot** [comment]
Same issue here. Tried changing timeout limit but no luck.

**Comment by agiudiceandrea** [comment]
@shawndegroot please report the issue adding a comment at https://github.com/qgis/QGIS-Website/issues/1246
