### ISSUE TITLE
Picture layout element does not handle properly a non-existing filepath when provided with an expression

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#42280]
**Describe the bug**

I think it's a regression for layout.

When I define a expression for a raster picture in an atlas layout, it falls back to SVG picture.
![layout](https://user-images.githubusercontent.com/39594821/111357649-ca715a80-8689-11eb-9898-60c59f07d72e.gif)

[bug_report.zip](https://github.com/qgis/QGIS/files/6151253/bug_report.zip)

@gioman I don't have idea for a better title... feels free to modify it.

**How to Reproduce**

1. Open project
2. Open the only print layout
3. Try to switch from SVG to raster (you can't)
4. Delete expression
5. Switch to raster
6. Try to use a field as an expression (it switch to SVG)
7. See warnings in logs

**QGIS and OS versions**
Tested on both 3.18.0 and 3.16.4 new OSgeo4W

**Additional context**
It worked fine on 3.16.3 as I used an expression to display picture based on attributs on a previous project.

**Comment by agiudiceandrea** [comment]
@nicogodet it seems to me that the described behavior also occurs with QGIS 3.16.3.

**Comment by nicogodet** [comment]
@agiudiceandrea 
Maybe 3.16.2 then...
The point is that I'm 100% sure I managed to set an expression for a raster image to display a picture on a previous version.
I remember also that was unstable : after closing/reopening the project it was back to SVG, I had to set the expression again.

**Comment by agiudiceandrea** [comment]
Anyway I see the same behavior with 3.16.2 and 3.16.0

https://user-images.githubusercontent.com/16253859/111587050-f859ba80-87c1-11eb-8b45-cde561b80db1.mp4

**Comment by nicogodet** [comment]
At least the bug is confirmed.

Now I need to find a working version until this is fixed as I have 100 features in my atlas

Thank you for your investigations @agiudiceandrea as always !

**Comment by nicogodet** [comment]
Ok I narrowed the issue.

The issue described above happens when the evaluated expression does not correspond to an existing picture/file.
Everything is fine when the evaluated expression corresponds to an existing files.

So the issue is less critical as it works as excepted when I'm not dumb. It's just more difficult to troubleshoot as the behavior when the evaluated filepath does not exist is not handle properly.

@gioman you can remove the regression label, it was an error in my filepath...

@agiudiceandrea do you want me to update the zipped project or the above description is enough ?

**Comment by M-Rick** [comment]
I do have exactly the same bug under MacOS with 3.16.1, 3.16.3, 3.16.5 and 3.18.1.
I am using Qfield and Input instances and it impact those applications as well, since they are using the QGIS core application code.

**Comment by nicogodet** [comment]
Linked/duplicates #37804 #38031 ?

**Comment by walking-the-talk** [comment]
I have just downloaded 3.20.0.2 as I saw that this issue was marked as fixed (I raised a duplicate as https://github.com/qgis/QGIS/issues/43589)

I am unable to confirm that it is fixed. When selecting the image type as Raster with the source as a data override expression it does not preview correctly and the layout returns and error on print (even though the override resolves to a real file path).

If I deactivate the expression and 'select file' as the source, the item does not preview and returns and error on print. The Item also reverts to SVG when it loses focus. 

When I return to the item and change it back to Raster, the image previews correctly, but does not show the file path (it prints the image). Changing 'select file' source resets the behaviour... so I need to change the focus to an other item, return to the image and change image type back to Raster.

Have I misinterpreted the fix?

Many thanks
