### ISSUE TITLE
QGIS 3.18.1 Windows installer fails to add start menu folder and items on Win 10 x64 20H2

### ISSUE THREAD

**Issue by sxwebster** [qgis/QGIS#42473]
**Describe the bug**
When installing on Windows 10 Pro x64 with the latest patch (March 2020), patch level 20H2, the installer fails to add start menu folder, and shortcuts. This make it difficult to start QGIS, particularly to start QGIS with GRASS or OS4W etc. 

**How to Reproduce**

Perform a clean install of QGIS on Win10 with patch level 20H2. 

Optionally, uninstall the old version, ensure current patches are applied, install 3.18.1

**QGIS and OS versions**

Windows 10, patch level 20H2.
QGIS 3.18.1 (installer: QGIS-OSGeo4W-3.18.1-1-Setup-x86_64.exe)

**Additional context**

The first time attempting to install, the installer hangs at "creating start menu folder" for over half an hour. Further installs succeed, but no start menu folder is created. 

Attempting to run qgis-bin.exe results in "Could not load qgis_app.dll", so it appears final configuration steps of the installer are not working. 

Same results if running the installer as Administrator.

**Comment by teknowledgist** [comment]
This is still an problem in the 3.20.0 release.  

Other issues for very similar symptoms (though not identical) have been closed (which I optimistically assume is because they are considered duplicates of this first-reported issue):

* https://github.com/qgis/QGIS/issues/43850
* https://github.com/qgis/QGIS/issues/43819
* https://github.com/qgis/QGIS/issues/43852
* https://github.com/qgis/QGIS/issues/42574
* https://github.com/qgis/QGIS/issues/43819

Hopefully, this issue won't be closed and will be assigned and resolved.

**Comment by agiudiceandrea** [comment]
@teknowledgist have you tried the new -4 version of the installer https://qgis.org/downloads/QGIS-OSGeo4W-3.20.0-4.msi (24-Jun-2021 01:28 CEST)?

**Comment by teknowledgist** [comment]
I didn't notice that there was a newer installer available!  I suppose that's why the tickets were being closed.  It would be nice if there were a short note indicating why.  🙄 

The -4 version one does appear to work properly.  Thanks!
