### ISSUE TITLE
Project DXF export does not allow to use attribute as DXF layer name

### ISSUE THREAD

**Issue by dr1542** [qgis/QGIS#42575]
This error began from version 3.18.0
In project DXF export dialog the drop down list of attributes for exported layers is frozen

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Comment by dr1542** [comment]
@gioman yes, it is in "Project->Import/Export->Export Project to DXF..."

**Comment by agiudiceandrea** [comment]
I can confirm the issue on Windows with QGIS 3.18.1, while the issue doesn't occur with QGIS 3.16.5.

**Comment by dr1542** [comment]
@agiudiceandrea 

> are you sure the issue also occurs with QGIS 3.18.0?

sorry. i can't check it now. When i trying open this dialog qgsi3.18.0 crashes.

**Comment by agiudiceandrea** [comment]
Indeed, with QGIS 3.18.0 opening the Project to DXF export dialog make QGIS crash.

It seems the crash in QGIS 3.18.0 was a side effect of https://github.com/qgis/QGIS/pull/39577 (see https://github.com/qgis/QGIS/pull/41900#issue-581360624)

The Project to DXF dialog crashing issue was then fixed in 3.18.1 with https://github.com/qgis/QGIS/pull/41918 (https://github.com/qgis/QGIS/pull/41925) by @elpaso but apparently he didn't noticed that the functionality was not completely restored.
