### ISSUE TITLE
Is it necessary to build 3D modules to use the QGIS Console

### ISSUE THREAD

**Issue by erzhanhongxingjiao** [qgis/QGIS#42606]
Hello, I built QGIS from source without WITH_3D checked, and then when I ran the Python console in QGIS Desktop Edition, there was an error where I couldn't find the 'QGIS._3d' module.
Do I have to build a 3D module to use the console
QGSI Version：3.16.3
![捕获](https://user-images.githubusercontent.com/30744116/113233668-56ae8f00-92d2-11eb-831b-a7380a0774da.PNG)

**Comment by agiudiceandrea** [comment]
For more details and workaround see my previous report https://github.com/qgis/QGIS/issues/41855

**Comment by gioman** [comment]
> For more details and workaround see my previous report #41855

@agiudiceandrea so this a duplicate, correct?

**Comment by agiudiceandrea** [comment]
@gioman I think so. I spotted the issue in 3.19-master MingW build, but it supposedly occurs with any build of QGIS >= 3.14.0 compiled without 3d support: this seems due to the import of the 3d python library by default in the console (https://github.com/qgis/QGIS/commit/601a71717407af3a1f6a544c65a9244074824662).
