### ISSUE TITLE
Geopackage: Parts can be added to a fetaure even if layer is not "MULTI"

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#42632]
QGIS 3.18.1 on Ubuntu 20.04

1) create a GPKG and a POLYGON layer (not MULTI)

2) create a new feature, save it

3) select the feature, use the "add part" tool to add a part > QGIS show a warning "Add part: Add part: Feature geom is single part and you've added more than one"

4) save edits > NO ERROR

If the same steps are done using a Spatialite (or PostGIS of course) layer instead of a GPKG the user gets an error while trying save edits.

**Comment by nyalldawson** [comment]
I think this was fixed on master this week - are you able to test? (https://github.com/qgis/QGIS/pull/41391)

**Comment by gioman** [comment]
> I think this was fixed on master this week - are you able to test? (#41391)

@nyalldawson thanks for the heads up! I will test as soon the nightly build for Ubuntu will contain that commit

**Comment by uclaros** [comment]
#41391 handles this on the add part tool level. We still need to handle saving (or should I say not saving) on the provider level, since there are many other ways that multi geometries can be created like merging or the dangerous avoid overlaps. INSERTing a multipart on a single type layer correctly fails, but UPDATEing an existing feature to a multipart is wrongly accepted.

**Comment by gioman** [comment]
> but UPDATEing an existing feature to a multipart is wrongly accepted.

As far as I can see on the latest master the case I reported is now fixed > selecting the "add part" tool will result in a "Add part: Could not add part. This layer does not support multipart geometries." and drawing a geometry will not even work.
