### ISSUE TITLE
Layer rendering opacity is not taken into account when exporting a layout to PDF

### ISSUE THREAD

**Issue by Benb73** [qgis/QGIS#42698]
With QGIS 3.16.5, cannot export a PDF with transparency on vector polygons. For this to work, the transparency must be applied to the syombology of the elements and not to the layer rendering 

QGIS 3.16.5 and windows 10

**Comment by gioman** [comment]
@Benb73 please add the requested info:



**Describe the bug**


**How to Reproduce**



1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment]
> It's simple bug, no need for a precise description.

@Benb73 no I'm sorry, it is always needed a precise description (it does not need to be very verbose).

For instance: you are not saying if you are exporting the PDF from the main QGIS window or from the QGIS print composer.

**Comment by gioman** [comment]
> i export from QGIS Print composer and I tried the different PDF export options

@Benb73 did it worked as expected in a previous QGIS release?

**Comment by Benb73** [comment]
yes of course, QGIS 3.4 in particular for me

**Comment by cesarcorreo** [comment]
Tested for me in 3.16.5 and 3.18.1. in W10
Exporting as a PDF and it's working properly.
![image](https://user-images.githubusercontent.com/25932761/113877390-f2e80280-97b8-11eb-9568-08dd58b65712.png)

**Comment by Benb73** [comment]
@cesarcorreo where is your transparency managed?

**Comment by cesarcorreo** [comment]
![image](https://user-images.githubusercontent.com/25932761/113885101-d9968480-97bf-11eb-852d-f1c087fa2f96.png)

**Comment by Benb73** [comment]
@cesarcorreo test here please  :

![113872365-19f00580-97b4-11eb-8a54-d88087efb88c](https://user-images.githubusercontent.com/65361648/113885436-1ebab680-97c0-11eb-9204-6a4f9df0b53b.PNG)

**Comment by gioman** [comment]
> @cesarcorreo test here please : 

@Benb73 works fine here on master, could you give it a try?

**Comment by agiudiceandrea** [comment]
@gioman I can confirm the issue on Windows 7 64 bit using QGIS 3.18.1 from OSGeo4W old repository (with Qt 5.11.2) while the issue doesn't occur using the same QGIS version 3.18.1 from the new OSGeo4W testing repository (with Qt 5.15.2).
Maybe it's a Qt (or some other library) issue.
Anyway the issue doesn't occur exporting as GeoPDF, so maybe is there room to fix the code to also work with old Qt version?

**Comment by agiudiceandrea** [comment]
I can also confirm that the issue doesn't occur using QGIS 3.10.14 (Qt 5.11.2) and QGIS 3.14.16 (Qt 5.11.2).
The issue occurs since QGIS 3.16.0 (Qt 5.11.2) and QGIS 3.18.0 (Qt 5.11.2).
So it seem a regression.

**Comment by jgruszka93** [comment]
I also confirm this issue. I've described it [here](https://gis.stackexchange.com/questions/396805/qgis-3-16-transparency-layer-export-to-pdf-not-working)

I've got problem with transparency when exporting my layout to PDF file. I have layer with transparency defined in Symbology -> Layer Rendering -> Opacity. 

[![enter image description here][1]][1]

In map view and in layout i can see transparency in my layout:

[![layer is transparent in map and layout view][2]][2]

However, adter exporting to PDF transparency is gone and edge of polygon looks weird:

[![no transparency after exporting to PDF][3]][3]

My PDF export settings are:

[![PDF export settings][4]][4]

What **solve** this issue, but I can't use it because of other reasons:

 - Checking "Print as raster" in Layout Settings 

[![enter image description here][5]][5]

 - Define transparency right in the color of symbol, not in "Opacity" of layer.
 - Exporting as image
 - using older varsion of QGIS (works in 3.2)

As I've mentioned, i can't use any of this solution.

What I've tried:

 - Enabling/Disabling "simplify geometry"
 - Enabling/Disabling "Always export as vector"
 - Enabling/Disabling "Export RDF metadata"
 - messing up with other layer-, layout- and export settings. All things that works I've mentioned above. 

Someone has [this exact problem earlier][6], but no satisfying answer was provided

Do you have any ideas how to fix that issue? Am I doing something wrong? 


  [1]: https://i.stack.imgur.com/hRHHF.png
  [2]: https://i.stack.imgur.com/AeMno.png
  [3]: https://i.stack.imgur.com/OOM3b.png
  [4]: https://i.stack.imgur.com/JxJL6.png
  [5]: https://i.stack.imgur.com/EXL11.png
  [6]: https://gis.stackexchange.com/questions/390254/qgis-transparency-layer-export-to-pdf-not-working

**Comment by agiudiceandrea** [comment]
Since it seems to me that:

- this regression was introduced in 3.15 and not backported to 3.10 and 3.14 and is Qt version dependant
- QGIS 3.16.0 is the first version with which the issue occurs
- the issue occurs with QGIS 3.16 and 3.18 using Qt 5.11.2, while it doesn't occur using Qt 5.15.2

so, it cold be that the PR https://github.com/qgis/QGIS/pull/37594 (merged in 3.15, not backported to 3.10 and 3.14, Qt version dependant) may have triggered this regression.

**Comment by jgruszka93** [comment]
I confirm that using build with Qt 5.15.2 the issue does not occur.

**Comment by agiudiceandrea** [comment]
In master branch at commit https://github.com/qgis/QGIS/commit/2626ad6130 the issue doesn't occur.

I narrowed down the search to the commits https://github.com/qgis/QGIS/compare/2626ad6130...7257456 and it seems to me a really related commit among them could be https://github.com/qgis/QGIS/commit/2d15a4cfad6c732cf640fbb0eabd625856b643ca PR https://github.com/qgis/QGIS/pull/39461 "Don't force a whole layout map to be rasterised just because one vector layer has non 100% opacity".

**Comment by nyalldawson** [comment]
@agiudiceandrea I strongly suspect this is some odd Qt issue in the older Qt release.

What we could potentially do is restore the forced rasterization of the whole map on Qt versions < 5.12 as a workaround.

**Comment by agiudiceandrea** [comment]
@nyalldawson just to sum up the findings:

Map with two polygon layers; layer B "over" layer A; layer A and B symbology is Single Symbol; layer B with 50% opacity

Setting the **Symbol opacity** or the **Color opacity** of layer B always lead to the same results:
- **layer A NOT RASTERIZED, layer B NOT RASTERIZED and 50% opaque**

Setting the **Layer opacity** of layer B lead to different results:

- QGIS with **Qt 5.11.2**
  - BEFORE the opacity rendering behaviour change:
    - exporting as regular PDF: **Layer opacity: layer A RASTERIZED, layer B RASTERIZED and 50% opaque**
    - exporting as GeoPDF: **Layer opacity: layer A RASTERIZED, layer B RASTERIZED and 50% opaque**

  - AFTER the opacity rendering behaviour change:
    - exporting as regular PDF: **Layer opacity: layer A NOT RASTERIZED, layer B RASTERIZED and <ins>TOTALLY OPAQUE</ins>**
    - exporting as GeoPDF: **Layer opacity: layer A NOT RASTERIZED, layer B NOT RASTERIZED and 50% opaque**

- QGIS with **Qt 5.15.2**
  - AFTER the opacity rendering behaviour change:
    - exporting as regular PDF: **Layer opacity: layer A NOT RASTERIZED, layer B RASTERIZED and 50% opaque**
    - exporting as GeoPDF: **Layer opacity: layer A NOT RASTERIZED, layer B NOT RASTERIZED and 50% opaque**

**Comment by jasonbcox** [comment]
This bug seems to have returned. Setting symbol fill opacity DOES render correctly when exported to PDF, but symbol layer opacity DOES NOT render correctly (100% opaque) when exported. This is happening in the latest release version 3.44.4.

**Comment by agiudiceandrea** [comment]
@jasonbcox I cannot reproduce the issue described in this issue report running QGIS LTR 3.40.13.
Please create a new issue report providing all the info requested in the issue report form with a detailed description and step-by-step detailed instructions possibly also providing a minimal QGIS project file and layers files.
