### ISSUE TITLE
Project saved with custom CRS shows as "unknown"

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#43197]
I created a project with a custom SR and saved.

When you load the project, Qgis 3.16.6 reports as "Unknown" and you have to reset it in the project properties each time.

**Comment by gioman** [comment]
>  a custom SR and saved.

@Forna73 can you add there the SR definition? thanks!

**Comment by Forna73** [comment]
(+proj=lcc +lat_1=37 +lat_2=45 +lat_0=41 +lon_0=12 +x_0=4000000 +y_0=2800000 +ellps=GRS80 +units=m +no_defs)

**Comment by elpaso** [comment]
> I created a project with a custom SR and saved.
> 
> When you load the project, Qgis 3.16.6 reports as "Unknown" and you have to reset it in the project properties each time.

What do you mean with "reports as 'Unknown'"? Reports how, where?

Because if it's in the bottom right projection widget this behavior is kind of expected, you should see the custom projection when hovering over the widget:

![immagine](https://user-images.githubusercontent.com/142164/119822583-19dacf00-bef4-11eb-9f15-23ab5ea30019.png)

"Unknown" here means that the projection has no authority ID `QgsCoordinateReferenceSystem::authid()` not that QGIS is not using any projection.

... and I agree that this is confusing but I've no idea about how to make it clearer.

**Comment by FelisPimeja** [comment]
I've made a gif demonstrating the issue
![user_projection_bug](https://user-images.githubusercontent.com/874261/119842976-cd04f180-bf0f-11eb-8f16-420ca6006eb1.gif)

1. Project CRS is 3857
2. Go to projection settings -> add custom projection "МСК-51" in proj format.
3. Change project CRS to "МСК-51".
4. Save project
5. Reopen project -> **Project CRS labeled "Unknown CRS"**
6. Go to projection settings -> resave custom projection "МСК-51" in wkt format.
7. Change project CRS to "МСК-51".
8. Save project
9. Reopen project -> **Project CRS labeled "USER:6335001"**

**Comment by Forna73** [comment]
Thank you for yours replies. Yes I mean in the bottom right corner.
So no bug and works as you described.

Il Gio 27 Mag 2021, 16:24 Felis Pimeja ***@***.***> ha
scritto:
