### ISSUE TITLE
import photos with geotag problems from android 10

### ISSUE THREAD

**Issue by albertograva** [qgis/QGIS#43226]
Hi all!

I noticed a problem with the tool import photos with geotag
I don't think tha the problem is QGIS, but maybe it will be simple to solve.
Using a smatphone with Android 10 in the details of the photos there are no coordinates but the address [1], using android 9 there are the coordinates [2].

When I use the tool import photos with geotag if I use the picture catched with android 9 smarthphone [3] it work, if I use the android 10 picture [4] it doesn't.

thank you

qgis version 3.16 on ubuntu 18.04

[1] ![android10](https://user-images.githubusercontent.com/47315786/118294282-d9825680-b4da-11eb-8b35-f02076f794c7.jpg)
[2] ![android9](https://user-images.githubusercontent.com/47315786/118294538-1c442e80-b4db-11eb-901d-cad49798d403.jpg)
[3] ![pic_android9](https://user-images.githubusercontent.com/47315786/118298453-c4f48d00-b4df-11eb-84e9-3b57983e817c.jpg)
[4] ![pic_android10](https://user-images.githubusercontent.com/47315786/118298524-d9d12080-b4df-11eb-811a-ce5f84b4d711.jpg)

**Comment by gioman** [comment]
@albertograva you are right, is not a QGIS issue. If the photos has no coordinate it can't be imported correctly. It depends on your camera App on Android: there are many (even the ones that comes by default) that do not save the location or do not save it unless activating the location service AND the proper setting in the App.

**Comment by saberraz** [comment]
This is very likely due to the way the recent Android (and iOS for that matter), strips the exif data from the photos when exported. For example, you need to select an option in iTunes to include the exif data for iOS. Or in Android, if you email the photo, it removes all the exif data.

If you are interested in taking photos with proper geotagging information, I suggest having a look at https://inputapp.io which is based on QGIS and read the blog post how to set it up:
https://www.lutraconsulting.co.uk/blog/2021/04/20/photo-exif-input/

**Comment by roya0045** [comment]
@saberraz I love Input, but I'm not sure if taking them with Input is a good Idea. I am aware that this helps you get funds for infrastructure when proposing subscriptions, but this also encourages people to used up the base allocated space. I think minimizing the footprint on your infrastructure is a good thing. Curious what are your thoughts on this. I don't want you to cut it off eventually because of this burden.

**Comment by mbernasocchi** [comment]
@albertograva I agree with @saberraz first part of the answer, most likely you're hitting an android behaviour.
As for the solution, could you please make sure you've enabled location in the camera app settings? Also at our company, we've had very good experiences with OpenCamera. You could probably give that a try and see if it solves your issue. 
Since this is not a QGIS issue I'll close this.

**Comment by albertograva** [comment]
> @albertograva I agree with @saberraz first part of the answer, most likely you're hitting an android behaviour.
> As for the solution, could you please make sure you've enabled location in the camera app settings? Also at our company, we've had very good experiences with OpenCamera (here some info from a quick google search: http://www.50northspatial.org/using-open-camera-geotagging-photos/). You could probably give that a try and see if it solves your issue.
> Since this is not a QGIS issue I'll close this. You could also install an Exif tool to analyse the EXIF information in the various photos.

Hi,
thanks for your replies.
I've installed an exif reader and also it doesn't see the coordinates.
I bypass th problem using gps map camera app to take picture. 

But, I only wanted to highlight the difference in behavior (pre and post android 10) as I believe that the workflow was faster and smarter before using the smartphone native camera app than using a dedicated one. 

I was wondering if there was a way for the tool to still read the coordinates even from the photos taken with the native camera of android 10, i'm not a devoloper, so I ask to the comunity...

thank you all
