### ISSUE TITLE
Layer Properties: "Cancel" button to reset layer and undo changes made by "Apply" button

### ISSUE THREAD

**Issue by beyhh** [qgis/QGIS#43274]
It would be a cool feature if the "Cancel" button actually resets the entire layer to it's state it had when the properties dialogue was opened. 
Currently, I try out different styling options for a layer by pressing "Apply" while the properties window is still open, which is very convenient. But undoing these changes and going back to the original state is not possible if the original state was not saved as a style.

Therefore:
I would suggest to keep the changes done by the "Apply" action on the properties dialogue by pressing "OK" as a confirmation and to drop all the changes when pressing the "Cancel" button.

**Comment by uclaros** [comment]
This would be counter intuitive, since this is how pretty much all programs treat the apply/ok/cancel triplet.

For trying out styling options you should be using the *Layer Styling Panel* instead of the layer properties, since it offers live previewing and a styling history undo/redo stack without being a modal dialog!
