### ISSUE TITLE
Confusing why some methods allow x,y,z and QgsPoint

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#43692]
I find it confusing why sometimes both x,y,z and QgsPoint or both are allowed, specially how the docs are written highlighting in grey what I would expect to be the way to use. This is just one example but this happens for several instances on where one, the other or both options are possible. It also seemed repetitive text and I suppose new in version 3.0 is when the change was introduced but it this really necessary?

![image](https://user-images.githubusercontent.com/4627073/121631651-b6e15000-ca3c-11eb-9581-c6b3341488f3.png)

I would also move the see also to the end not in the middle

**Comment by gioman** [comment]
@antoniolocandro shouldn't this be filed under documentation ?

**Comment by DelazJ** [comment]
> @antoniolocandro shouldn't this be filed under documentation ?

@gioman if you mean [QGIS-Documentation repository](https://www.github.com/qgis/QGIS-Documentation), then definitely NO! The content of [pyQGIS API documentation](https://www.qgis.org/pyqgis) is generated from this repository so anything related to that should IMO be reported here, in this repository and in some cases in [pyqgis repo](https://www.github.com/qgis/pyqgis), but never in docs repo. But it probably should be labeled with "Documentation" or pyqgis

Back to @antoniolocandro request, may I suggest you to share direct link to pages you are referring to? It's quite more convenient for someone willing to check the issue. Here we are at https://qgis.org/pyqgis/master/core/QgsPoint.html#qgis.core.QgsPoint.distance3D

> I find it confusing why sometimes both x,y,z and QgsPoint or both are allowed, specially how the docs are written highlighting in grey what I would expect to be the way to use. 

Not sure I fully understand the issue(s):
- if you mean they should have a color other than grey, hmm why not?
- if you mean `distance3D(self, other: QgsPoint)` should be in the same color as `distance3D(self, x: float, y: float, z: float)`, yes they should but there is (was?) a limitation in sphinx to handle this (see https://github.com/qgis/pyqgis/issues/18)
- About the `see also`, if you look at the other methods, you'll notice that each variant has its own see also. Should be fixed in #43697
- About `new in version xxx` I think it's still good to know in which version a function is introduced, hence the versions of the software the code you are writing can support.
