### ISSUE TITLE
Layout Attribute Table sorting does not work in Print Layouts when column name has spaces

### ISSUE THREAD

**Issue by IvanEfremov-GitHub** [qgis/QGIS#43744]
**Describe the bug**

**How to Reproduce**

1. Go to 'print layout'
2. Click on 'add table'
3. Click on 'atributes'
4. Click on 'sorting (ascending / descending)' and select an attribute with integer format
5. See error --> sorting does not apply

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment]
@IvanEfremov-GitHub QGIS version? Operating system?

**Comment by eemilhaa** [comment]
Could not reproduce this on QGIS 3.19 nightly build or on 3.16 LTR. OS is linux/ubuntu. Following the steps provided in the issue results in a properly sorted table for me.

**Comment by FelisPimeja** [comment]
Can not replicate on 3.18/3.19 on Windows either.
Sample dataset needed.

**Comment by FelisPimeja** [comment]
Ok. After conversation with @IvanEfremov-GitHub I've managed to reproduce the bug.

It's actually caused by white spaces and dots in column name (maybe some other symbols).
When a column name of a table contains white spaces and/or dots it can't be sorted in layout attribute table for some reason.
But I've also found sort of a workaround - you can manually add double quotes around column name in sorting form for sorting to work properly. 

Sample dataset and gif demo included:

[sorting_bug.zip](https://github.com/qgis/QGIS/files/6676616/sorting_bug.zip)

![qgis_sorting bug](https://user-images.githubusercontent.com/874261/122552243-ba796600-d03e-11eb-868f-788ce9db7aaf.gif)

**Comment by FelisPimeja** [comment]
@gioman , maybe rename issue to "Layout Attribute Table sorting bug when column name has spaces"?

**Comment by Pedro-Murteira** [comment]
Still valid on QGIS 3.22.3. (Windows 10)
