### ISSUE TITLE
Execution speed problem on windows 21H1

### ISSUE THREAD

**Issue by AliceSRDCBS** [qgis/QGIS#43778]
Hello;

We just buy a new laptop whithout graphic card. Its exploitation system is the new windows 21H1. Our problem is when we open a layer or when we want to see a layer, Qgis don't answer few minut before doing the task.  We don't have problems with other laptop without graphic card or other windows version. Do you know if there is compatibilty problems with this new version of windows and Qgis 3.16 7 LTR. 
Before writing here, we test to uninstall and install again. It was the same problem. 
Thank you for your answer
ps :I'm french
AliceSRDCBS  

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by tjukanovt** [comment]
I have the same Windows version and I've tested with 3.16 and 3.18 and encountered nothing out of the ordinary. I would say that the problem is somewhere else than your Windows version.

I guess by "no graphics card" you mean that your graphics card is integrated in your laptop? Because I doubt that you would be using QGIS completely without a graphics card 😙

My initial guess is simply that your new machine just doesn't have enough performance to run as fast as the other machine. Hard to help more without any further details (machine specs, what data are you using etc.)

**Comment by gioman** [comment]
> your new machine just doesn't have enough performance to run as fast as the other machine.

probably not, QGIS works just fine even on very old machines (I personally run it on 10+ years old laptops with integrated video cards).

**Comment by andreasneumann** [comment]
One potential issue might the "browser panel" with network drives attached. (just a wild guess).

There are known issues where the browser panel can terribly slow down QGIS when slow network drives are scanned for data sets.

Try closing the browser panel and see if it fixes the issue?

Antivirus scanners can also slow down QGIS substantially.

**Comment by jonnyforestGIS** [comment]
I notice that these last win10 updates also increase the security and sometimes make some applications run slower than usual because we try to check everything first then allow it to execute.

Try to add the QGIS installation folder as an exception in Windows Defender if helps in this problem.

https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/how-to-add-an-exception-to-windows-defender/8a096ae3-5ee5-4eac-9dc7-ab4d8628b035
