### ISSUE TITLE
QGIS creating silvers in reproject layer algorithm

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#43798]
**Describe the bug**
QGIS creating silvers between features when I reproject layer from EPSG:5070 to 2240 using reproject layer algorithm.

**How to Reproduce**

In the attached project. Reproject layer Curve Number to 2240. The reprojected layer will have silvers. (The attached project contains a Silvers layer to highlight these areas)

**QGIS and OS versions**

Checked in 3.6 and 3.18
[AWA.zip](https://github.com/qgis/QGIS/files/6683457/AWA.zip)

**Comment by gioman** [comment]
It happens also when reprojecting with ogr2ogr, so maybe is something in some upstream library.

**Comment by agiudiceandrea** [comment]
@ar-siddiqui I think this is expected.
A polygon layer actually contains only the vertices (points) of the polygons perimeter. Reprojecting a polygon only means reprojecting the vertices of the polygon.
The path between two points in a CRS is not always the same in another CRS.
So you need to ensure that adjacent polygons in a layer have corresponding vertices along the perimeters in order to avoid the creation of slivers or gaps after reprojecting the layer.
The polygons in your original layer don't have corresponding vertices along the perimeters:
![image](https://user-images.githubusercontent.com/16253859/122744325-2b5f8e80-d288-11eb-9ddb-49a219b8da00.png)

so you will find slivers and gaps in the reprojected layer
![image](https://user-images.githubusercontent.com/16253859/122744360-31556f80-d288-11eb-9c0a-99c3d314303f.png)

The GRASS processing tool v.clean with the "break" tool https://grass.osgeo.org/grass78/manuals/v.clean.html will create appropriate vertices along the perimeter at intersections with adjacent polygons.

![image](https://user-images.githubusercontent.com/16253859/122745531-61e9d900-d289-11eb-82b5-d53617a9c569.png)

**Comment by ar-siddiqui** [comment]
@agiudiceandrea Thanks for the investigation and a great explanation. I am developing a plugin and need to reproject layers in the logic of the algorithm, if I use grass tools, all the users will need to have QGIS with grass. Is there a native QGIS solution to this (even if it involves multiple steps)?

**Comment by agiudiceandrea** [comment]
@ar-siddiqui a QGIS native processing tool similar to "v.clean break" is "Snap geometries to layer" (native:snapgeometries).

**Comment by gioman** [comment]
@agiudiceandrea thanks for catching this, I missed it when I looked at the data. I think this should be closed.
