### ISSUE TITLE
qgis_process need .bat file

### ISSUE THREAD

**Issue by Gaetanbrl** [qgis/QGIS#43847]
Hi,

I try to to execute some model created with windows first, into a debian OS ensure (Qgis standalone without UI - cron execution).

To to that, i think i could use the `qgis_process` command line tool (wonderfull !).

The [doc](https://docs.qgis.org/3.16/en/docs/user_manual/processing/standalone.html) said : 
> QGIS comes with a tool called qgis_process which allows you to call processing algorithms and models directly from the command line without starting QGIS desktop itself.

Firstable, i need to try qgis_process command in windows env (as well to validate process with windows). Next, i will[ install QGIS 3.18 standalone in Debian 10](https://www.qgis.org/fr/site/forusers/alldownloads.html#debian-ubuntu) to reproduce the same.

So, if i read the doc correctly i thing that we just need to install and use `qgis_process` with Windows / Debian terminal.

**Describe the bug**

* Windows env

After Qgis 3.18 install (fresh env - no old version), `qgis_process`  command return :

```
+ qgis_process
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (qgis_process:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

To use qgis_process, i have to execute `qgis_process-qgis.bat` file :

`C:\Program Files\QGIS 3.18\bin> .\qgis_process-qgis.bat list`

Well, now from .bat file i could execute a model and all works fine with this command : 

`PS C:\Program Files\QGIS 3.18\bin> .\qgis_process-qgis.bat run ("path\model1.model3")`

* Debian env

`qgis_process` command return `X display error` after install (no graphic env - full command line as server).

```
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

I had found `/usr/bin/qgis_process.bin` to directly execute command and i get the same `X display error`. 

Here, `qgis_process` seems to use screen...but i only use command line.

If i create a var env like that, `qgis_process `exists (thanks @agiudiceandrea) : 

`$ export QT_QPA_PLATFORM='offscreen'`

**QGIS and OS versions**

QGIS 3.18
Windows 10 / Debian 10

**Comment by agiudiceandrea** [comment]
@Gaetanbrl your description is not clear to me. Are you trying to execute qgis_process on GNU/Linux Debian headless (without UI / display / X system) or are you trying to execute qgis_process on Windows (the bat file and the path reported are available on Windows only)?

If you want avoid the reported error on a GNU/Linux headless system:

> qt.qpa.screen: QXcbConnection: Could not connect to display
> Could not connect to any X display.

you could use: `env QT_QPA_PLATFORM='offscreen' qgis_process list`

**Comment by Gaetanbrl** [comment]
Hi @agiudiceandrea , thanks for reply.

I got same error with windows and Debian.

- With Windows, i need to user .bat file directly
Question : how directly user qgis_process (CommandNotFoundException) and not qgis_process.bat file to use qgis_process ?

- With Debian, this command (thanks) resolve the error : 
```
$ export QT_QPA_PLATFORM='offscreen'
```

But why i open issue instead of user mail list ?

* So, the doc about qgis_process could be improve (i can contrib)
The doc talk about simple qgis_process command, but this tool needs some config (windows / linux) and seems not work natively.

* In my case, windows need to use .bat file and qgis_process not work (maybe i need a specif var env ?)

**Comment by agiudiceandrea** [comment]
> * With Windows, i need to use .bat file directly
> Question : `how directly use qgis_process (CommandNotFoundException) and not qgis_process.bat file to use qgis_process ? `

You need to use the .bat file to properly set environmental variables on Windows.
This is expected, although not documented (as for all the other OSGeo4W Shell commands).

QGIS for Windows is shipped via [OSGeo4W](https://trac.osgeo.org/osgeo4w/) installer/package system.

OSGeo4W uses a bunch of .bat file to temporary properly set environmental variables for QGIS, Python, GDAL, GRASS, dlls, libraries, ecc. avoiding to permanently set those environmental variables system wide.
Command line applications are available in the OSGeo4W Shell command window (you cold see a list of available OSGeo4W Shell commands using `o-help` in the OSGeo4W Shell.

So qgis_process-qgis.bat (or qgis_process-qgis-ltr.bat or qgis_process-qgis-dev.bat) contains the needed instruction to properly set those environmental variables (notably the PATH variable, otherwise you will encounter CommandNotFoundException: this is a basic knowledge for Windows command line usage).

After the environmental variables are properly set, then you can directly use qgis_process, instead of qgis_process-qgis.bat, in the same Windows/OSGeo4W command line shell instance.

> * With Debian, this command (thanks) resolve the error :
> 
> ```
> $ export QT_QPA_PLATFORM='offscreen'
> ```

This is an issue not specifically related to qgis_process but to applications developed with Qt libraries and executed on a Debian/GNU/Linux headless system. So this is related with the system. You will probably encounter the same issue with other applications.
You could permanently set that environmental variable in your bash shell profile or in your shell script.

**Comment by gioman** [comment]
I guess we can close this, right?

**Comment by Gaetanbrl** [comment]
I close, @agiudiceandrea give many info usefull for next users ;)
