### ISSUE TITLE
QGIS GUI not properly scaling when using an external monitor with a different resolution

### ISSUE THREAD

**Issue by mapperfr** [qgis/QGIS#43924]
**QGIS and OS versions**

Version de QGIS | 3.20.0-Odense | Révision du code | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.0
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | GeometryShapesshapetoolsdb_managerMetaSearch

</body></html>

**Additional context**

Using QGIS on a HP Spectre X360 laptop under Windows 10, with a screen resolution of 3840x2160 and a 300% zoom (the advised zoom level). 

QGIS is using the default theme, icons size is 64, font size is 8.

The GUI appears properly scaled on the laptop monitor:

![Capture d’écran 2021-06-25 125534](https://user-images.githubusercontent.com/3398608/123415802-0d5e9a80-d5b6-11eb-8f27-28919c63bee4.png)

However, when I move the software on my external 1920x1080 21'' monitor, the icons appears way too big and there are some other GUI issues that make it really hard to use:

![Capture d’écran 2021-06-25 125444](https://user-images.githubusercontent.com/3398608/123416188-88c04c00-d5b6-11eb-8fc0-adabffda28b9.png)

Not sure if there's a setting I missed or if it's a bug. Using an external monitor is kind of mandatory with a 13'' laptop. I know that HiDPI monitors cause a number of issues, especially under Windows, but it would be an amazing progress to be able to seamlessly use both screens.

**Comment by gioman** [comment]
> Not sure if there's a setting I missed or if it's a bug. Using an external monitor is kind of mandatory with a 13'' laptop. I know that HiDPI monitors cause a number of issues, especially under Windows, but it would be an amazing progress to be able to seamlessly use both screens.

@mapperfr have you checked if this is not duplicate of one of the several tickets about hidpi on QGIS?

**Comment by mapperfr** [comment]
> @mapperfr have you checked if this is not duplicate of one of the several tickets about hidpi on QGIS?

Yes I checked and didn't find anything yet with "hidpi", "second monitor" or "external monitor"! Maybe I missed the right keyword?

**Comment by Houska1** [comment]
While not 100% the same, see my previous issue at https://github.com/qgis/QGIS/issues/41248

In particular, using `iface.mapCanvas().setMagnificationFactor(...)` to set the magnification factor for the canvas (using PyQGIS) might be a workaround for you, either manually from the Python console or as a startup script. Though not clear to me if the specific ratio there using physical and logical DPI will work for this instance.

**Comment by elpaso** [comment]
Did you have a look to https://doc.qt.io/qt-5/highdpi.html ?
I am using `QT_SCREEN_SCALE_FACTORS` (on linux) and it works well.

**Comment by m-kuhn** [comment]
It looks like this could be fixed by https://github.com/qgis/QGIS/pull/44132
Can I ask you to test https://github.com/qgis/QGIS/suites/3219192054/artifacts/74539265 (and enable the switch "respect screen DPI" switch in the options and let us know if this works?

**Comment by mapperfr** [comment]
> Did you have a look to https://doc.qt.io/qt-5/highdpi.html ?
> I am using `QT_SCREEN_SCALE_FACTORS` (on linux) and it works well.

Thanks for your input @elpaso, My answer is a bit late, partly because I'm not sure where/how to set the Qt parameter setting `QT_SCREEN_SCALE_FACTORS`. I started looking into C:\OSGeo4W\bin\qt.conf but I'm a bit lost. Should I set it in QGIS system options? Any other indication? Thanks.

> It looks like this could be fixed by #44132
> Can I ask you to test https://github.com/qgis/QGIS/suites/3219192054/artifacts/74539265 (and enable the switch "respect screen DPI" switch in the options and let us know if this works?

Doesn't seem to work as expected @m-kuhn. Here is what it looks like:

- On the laptop screen

![Capture d’écran 2021-07-13 111530](https://user-images.githubusercontent.com/3398608/125426315-33dc8103-e073-48a7-ba6e-abd7d89be114.png)

- On the external monitor

![Capture d’écran 2021-07-13 111730](https://user-images.githubusercontent.com/3398608/125426558-3908036d-ffc8-420a-90a2-5ae808359341.png)

**Comment by m-kuhn** [comment]
Thanks for the feedback

1. Did you enable the "respect screen dpi" option (and restart qgis I think ...)
2. This only concerns the representation on the canvas (symbology size etc) not the buttons, so just focus on that for now

**Comment by mapperfr** [comment]
> Thanks for the feedback
> 
>     1. Did you enable the "respect screen dpi" option (and restart qgis I think ...)

Yes

> 
>     2. This only concerns the representation on the canvas (symbology size etc) not the buttons, so just focus on that for now

Here are two other screenshots:

- laptop monitor

![Capture d’écran 2021-07-13 115443](https://user-images.githubusercontent.com/3398608/125432174-709babcd-589b-41c8-a9d9-322cb5fc763e.png)

- external monitor

![Capture d’écran 2021-07-13 115516](https://user-images.githubusercontent.com/3398608/125432919-16ddf84f-4588-40ab-b24a-45f7ef8bca82.png)

Canvas objects appear bigger on the external screen.

The white area at the top right is because the window doesn't suceed to properly maximize/adapt to the external screen.

**Comment by m-kuhn** [comment]
Thank you for testing and sorry, there was still an issue.
Can you retry https://github.com/qgis/QGIS/suites/3230212708/artifacts/74885572?

**Comment by mapperfr** [comment]
Thanks for taking care of the issue!

Symbology and sizes on the canvas seem to be better preserved now:

- laptop

![Capture d’écran 2021-07-15 104501](https://user-images.githubusercontent.com/3398608/125758507-081dfc40-c909-487d-a2f3-26a3b8c8970f.png)

- external

![Capture d’écran 2021-07-15 104601](https://user-images.githubusercontent.com/3398608/125758956-a805de78-a72a-4f9a-8069-bd01079444a2.png)

Other glitches and visual imperfections remain.

**Comment by mapperfr** [comment]
Version de QGIS | 3.20.2-Odense | Révision du code | 9f59a156
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.3.1
Version de Proj | 8.1.0
Version de la base de données du registre EPSG | v10.027 (2021-06-17)
Version de GEOS | 3.9.1-CAPI-1.14.2
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 13.0
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.3
Version de QScintilla2 | 2.11.5
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives | GeometryShapesopenlayers_pluginqgis-maptiler-pluginshapetoolsdb_managerMetaSearch

Re-opening the issue as it is not totally solved with QGIS version of 3.20.2. It looks better but there are still some imperfections, like the size of symbols in the legend and the thickness of certain elements of the GUI (tabs, toolbars...). 

![Capture d’écran 2021-09-08 094840](https://user-images.githubusercontent.com/3398608/132469377-2fb9f2ca-81da-45a7-a1aa-fb3a2feb6b31.png)

**Comment by mapperfr** [comment]
![Capture d’écran 2021-09-08 100319](https://user-images.githubusercontent.com/3398608/132470669-aa6bc507-a12f-4aa4-bd41-7dc6507bed7b.png)

**Comment by Houska1** [comment]
@mapperfr , m-kuhn's solution uses the system's "physical DPI" (DPI as reported by the screen itself) for the map canvas itself, and the system's "logical DPI" (as reported by the operating system, on Windows affected by the "display scaling" parameter in system settings) for elements of QGIS' UI, to be consistent with other applications running on your system. I think the latter includes the layer list (including symbols inside it as on-screen legend).

Could you clarify whether the "imperfections" you've noticed are:
a) Inconsistencies where the above rule is not followed
b) Visual artifacts in some window/dialog from using this rule
c) Behaviour "as designed" surprising to you since you weren't aware of this distinction

I don't see a) or b) in your screenshot, but I could be missing something. (I do find the copyright line bizarrely large...)

If it is c), then of course a design change could be considered, but it is a balancing act. In an ideal world, 12 pts actual screen distance (=4.2 mm with a ruler), a 12 pt label in the map canvas, a 12 pt symbol in the canvas, 12 pt text in the QGIS UI, a 12 pt symbol in the legend/layer list, and 12 pt text in another application open on your monitor would all be precisely the same size.  But as long as operating systems allow display scaling to set so-called logical DPI different from monitor physical DPI, there will be mismatches somewhere.

I could see it desirable to "flip the switch" which DPI certain windows/dialogues use, so e.g. also the layer list/on-screen legend and the symbology setting dialog use physical DPI. But I'm not 100% sure what's feasible (how granularly this can be done due to Qt limitations) and there might be enough side effects to not make it worth it.

**Comment by mapperfr** [comment]
Thanks for these detailed explanations @Houska1!

It's clearly c). 

I understand that the issue comes from the Windows and its display rules behaviour. As the laptop screen has a resolution of 3840x2160 px, for the screen elements to be readable and not too small, I need to apply a display scaling of at least 250 %. if I use my external screen, the display scaling is still applied on QGIS GUI elements, causing an unconvenient UX, where the scaled elements are sometimes unaccessible (e.g. in pop-up windows like the layer properties window). 

As a workaround, If I set the resolution of the laptop screen exactly as the external screen (1920x1080 px), and deactivate the display scaling, then indeed everything displays the same way on both screens. But doing this every time I open QGIS would be inconvenient and quite time-consuming. 

Most other softwares/applications seem to auto-detect the change but QGIS doesn't, under Windows at least. From my end-user point of view, it would be a useful design change if it were to happen. Would it be a problem to use the system's physical DPI on the whole UI? But I don't clearly understand yet how it would break the "point equivalence" that you describe. 

Maybe a "Windows HDPI" special version could exist? Half-joking here, I know it's a lot of work. I'm just surprised I never saw this issue popping up here and there.

**Comment by Houska1** [comment]
First, you write about 3.20.2, but my recollection is the fix is only in Master, i.e. 3.21 and up; not backported to 3.20.2. I may be wrong. Can you check if the problem persists for you in the latest development master (and with the `Respect screen DPI` setting on, of course)?

If it's not just a version issue, I think it will take a bit of digging to find a way forward here. I'm not a "real" developer, though I've been involved in this issue, and I only have one monitor (my interest was to have physical map canvas scale, and also symbols, accurate on my one display, i.e. reflect physical DPI not logical DPI - https://github.com/qgis/QGIS/issues/41248 now closed). @m-kuhn did the fix for both, and his interest is symbol size accuracy, but he doesn't use Windows. 

Could you do the following to help:

a) With QGIS running on your laptop window, open up a Python console (`Ctrl Alt P`) and execute `iface.mainWindow().logicalDpiX(), iface.mainWindow().physicalDpiX()`. I get `(120,158)`. I expect you'll get something like 240 (=250% of Windows' base dpi of 96) and 314+- (if your 3840 laptop screen is 14"). Then do the same with QGIS running on your external monitor. Your physical dpi will then be something like 100-150 (depending on size of your screen); and will be interesting what the logical dpi is. I hope it is *not* also 240, which would indicate that somewhere between Windows, Qt (the library QGIS uses for UI), and QGIS the monitor change is not being recognized.

b) Can you also try to figure out what DPI other applications are using on each monitors? I do this with Microsoft Word: open a (new) document and display it in layout view in 100% zoom on that screen. Screen clip the page width and use a paint program to see the size of the clip in pixels. For me it is 1018 pixels for a letter size (8 1/2 inch) page, so 1018/8.5=120 dpi, which matches the logical DPI QGIS sees. If you don't have Word, another application that allows you to display stuff at "100%" should do the trick.

c) Finally, can you play around with Windows properties for the QGIS executable (right click on the executable itself, `Properties`, then `Compatibility` and `Change high DPI settings`) and see if a different setting for `High DPI scaling override` helps or makes things worse.

**Comment by munjalsavla** [comment]
I had the same problem, external monitor with a lower resolution resulted in problems scaling the toolbars, fonts, etc. The solution lies in changing the Qt.conf file. 
[See my comment here for the solutions](http://disq.us/p/2l8kr1h)

**Comment by m-kuhn** [comment]
Thanks a lot @munjalsavla could you open a new issue with a screenshot of before and after?
Maybe we can integrate this in QGIS itself to avoid the need for manual intervention.

**Comment by mapperfr** [comment]
I'll try @munjalsavla's fix as soon as possible on my home config (Windows hidpi laptop + external screen with lower resolution) and will report here.

**Comment by jbp35** [comment]
I have been facing a similar scaling issue on a dual screen setup :
- 15" laptop with 4K display
- External 27" screen QHD
- QGIS 3.22.2 & Windows 11

Editing  C:\OSGeo4W\bin\qt.conf as @munjalsavla mentioned to set dpiawareness=0 greatly improves the UI scaling but causes artifacts such as blurry icons especially on my 4K screen.

I don't know if this is of any help, but I figured that the scaling of Qgis UI is influenced by the choice of the primary monitor (under windows settings) which seems a bit counter intuitive to me.

Here is a screenshot of my external display when I launch QGIS with my 27" external screen as primary monitor:
![main display external screen 27inch](https://user-images.githubusercontent.com/19955142/151833522-714ba1e5-b0de-40c6-93b5-e84d36cd0662.jpg)
 
And here is a screenshot of my external display when I launch QGIS with my 15" internal screen as primary monitor:
![main display Laptop 15inch](https://user-images.githubusercontent.com/19955142/151833850-cf160250-679c-4441-90ff-9f427ae3db29.jpg)
