### ISSUE TITLE
Geopackage m:n relation still broken

### ISSUE THREAD

**Issue by dingausmwald** [qgis/QGIS#43959]
[42952](https://github.com/qgis/QGIS/issues/42952) didnt solve the problem for me. Since nobody replied after update i believe this is geopackage related so i open a new one

in 3.16.8 adding relations does work. Still less than 100 entries show. More than 100 make the entries in relation widget disapear

and i get

`WARNING Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()`

in 3.20 i get
`Layer testmn: OGR error creating feature -24: failed to prepare SQL: INSERT INTO "testmn" ( "fid", "geometry", "id") VALUES (?, ?, ?)`
when trying to add a geometry to the point layer or add a relation to a non geometry layer 

When added with 3.16.8 and opened with 3.20 same bug, over 100 entries wont show.

**Comment by gioman** [comment]
> in 3.16.8 adding relations does work. Still less than 100 entries show. More than 100 make the entries in relation widget disapear

@dingausmwald is there somewhere a project + data we can test?

**Comment by dingausmwald** [comment]
[testmn.zip](https://github.com/qgis/QGIS/files/6726875/testmn.zip)

**Comment by elpaso** [comment]
@gioman looks like a regression to me. @gioman can you confirm?

**Comment by gioman** [comment]
@elpaso checking...

**Comment by elpaso** [comment]
@gioman I checked on 3.16 and it worked as expected.

For clarity, the bug I am talking about is the error `OGR error creating feature -24: failed to prepare SQL: INSERT INTO "testmn" ...`

**Comment by elpaso** [comment]
Master:

![Peek master](https://user-images.githubusercontent.com/142164/123756729-82371a80-d8bd-11eb-8613-7aa1f92a0184.gif)

3.16:

![Peek 3 16](https://user-images.githubusercontent.com/142164/123757039-d8a45900-d8bd-11eb-8d5f-70777e61d223.gif)

**Comment by gioman** [comment]
@elpaso thanks for having checked this, yesterday I was out of time.

**Comment by gioman** [comment]
@elpaso I tested on 3.18.3 on Windows and with this specific project it crashes as soon I try to add a new feature or identify an existing one.

**Comment by elpaso** [comment]
@gioman yeah, I think you hit #42952

**Comment by elpaso** [comment]
@gioman I discovered why it works in 3.16:

The problem comes from the fact that for a newly created feature, when the user links the feature to the parent the relation is created **before** the child actually exists, which obviously violates the FK constraint.

Before  https://github.com/qgis/QGIS/pull/43330, foreign key checks were disabled so there was no problem (so to say, because you could end up with corrupted data quite easily).

There is no easy solution that I can think of, I'm curious to see if that only affects GPKG or also postgis.

@m-kuhn @rouault brainstorming for possible patches here: 

1. wrap the main form into an edit command (we are inside a transaction) and create the main feature immediately, rollback if the form is not saved on exit
2. temporarily disable the FK check and restore it on exit (I can't really think of a way of implement this though, maybe a RIIA restorer)

**Comment by rouault** [comment]
Perhaps the solution would be to use deferred foreign keys: see §4.2 of https://www.sqlite.org/foreignkeys.html

**Comment by elpaso** [comment]
> Perhaps the solution would be to use deferred foreign keys: see §4.2 of https://www.sqlite.org/foreignkeys.html

Yeah, I though about that but that would mean to alter the DB, or is there a pragma to enable deferred globally?

**Comment by rouault** [comment]
>  or is there a pragma to enable deferred globally?

it seems so: https://www.sqlite.org/pragma.html#pragma_defer_foreign_keys

**Comment by elpaso** [comment]
After a deeper look, it turns out that the test database is ill formed: `foreign key mismatch` SQLite error comes from a wrongly defined FK (the FK colum the constraint points to is not a PK nor unique).

Also, the definition was `DEFERRABLE INITIALLY DEFERRED` so there was not really a FK check issue.

I could still add the pragma but I don't really see the point.

**Comment by dingausmwald** [comment]
I'm very sorry for the wrong test project. The documentation says to create a table with the DB Manager with a id field which is a bit confusing since primary key for geopackage is fid and there is no possibility to create a (second) unique key with the db manager. So i sticked tightly to the docs, trying to link with a id field.

With a new project, linked with fid, `Layer testmn: OGR error creating feature -24: failed to prepare SQL: INSERT INTO "testmn" ( "fid", "geometry", "id") VALUES (?, ?, ?)` in logs is gone.

But my main problem persists (apologies again for the bad choosen title of this / mainly tested with 3.20 from here, but surely true for 3.16). 
Over 89 entries wont show in relation widget. Yes, i checked. Its 89. 90 wont show. 89 do.

In addition, i played a bit and i cant unlink more than 86 entries. 87 wont delete in the relation table nor in the relation widget. 86 works.

when i delete manually from relation table (while projects relation widget is open) i get `WARNING    Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()`, what might be unrelated to the main problem.

I created another project to test, with 2 entries in project table. 1 with 89 entries, 2 with 90.
Thank you for your fast response

**Comment by gioman** [comment]
> I created another project to test, with 2 entries in project table. 1 with 89 entries, 2 with 90.
> Thank you for your fast response
> [test2.zip](https://github.com/qgis/QGIS/files/6740523/test2.zip)

@dingausmwald maybe is better to file a new ticket, with a title that reflects this specific issue
