### ISSUE TITLE
>89 m:n relations in widget wont show/update

### ISSUE THREAD

**Issue by dingausmwald** [qgis/QGIS#43992]
reopened with clearer title and data [43959](https://github.com/qgis/QGIS/issues/43959)

Windows 10 64x
qgis 3.16 and 3.20
geopackage

More than 89 relations in a m:n relation test geopackage wont show in relation widget. They are created in the relation table though.
In addition, more than 86 entries cant be deleted from the relation widget. The relation widget nor the relation table update when pressing the unlink button in relation widget.

Deleting manually from relation table does work, but brings `WARNING Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()` (when related widgets are open, maybe even without). Maybe not related.

I created a project to test, with 2 entries in "projekte" table. 1 with 89 entries, 2 with 90.
[test2.zip](https://github.com/qgis/QGIS/files/6740631/test2.zip)

**Comment by domi4484** [comment]
I have found the place where the bug happens but I don't know how to solve it.
The QGIS filter expression is translated by `QgsSQLiteExpressionCompiler` in a `WHERE`statement:
```
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((("fid" = 194) OR ("fid" = 195)) OR ("fid" = 196)) OR ("fid" = 197)) OR ("fid" = 198)) OR ("fid" = 199)) OR ("fid" = 200)) OR ("fid" = 201)) OR ("fid" = 202)) OR ("fid" = 203)) OR ("fid" = 204)) OR ("fid" = 205)) OR ("fid" = 206)) OR ("fid" = 207)) OR ("fid" = 208)) OR ("fid" = 209)) OR ("fid" = 210)) OR ("fid" = 211)) OR ("fid" = 212)) OR ("fid" = 213)) OR ("fid" = 214)) OR ("fid" = 215)) OR ("fid" = 216)) OR ("fid" = 217)) OR ("fid" = 218)) OR ("fid" = 219)) OR ("fid" = 220)) OR ("fid" = 221)) OR ("fid" = 222)) OR ("fid" = 223)) OR ("fid" = 224)) OR ("fid" = 225)) OR ("fid" = 226)) OR ("fid" = 227)) OR ("fid" = 228)) OR ("fid" = 229)) OR ("fid" = 230)) OR ("fid" = 231)) OR ("fid" = 232)) OR ("fid" = 233)) OR ("fid" = 234)) OR ("fid" = 235)) OR ("fid" = 236)) OR ("fid" = 237)) OR ("fid" = 238)) OR ("fid" = 239)) OR ("fid" = 240)) OR ("fid" = 241)) OR ("fid" = 242)) OR ("fid" = 243)) OR ("fid" = 244)) OR ("fid" = 245)) OR ("fid" = 246)) OR ("fid" = 247)) OR ("fid" = 248)) OR ("fid" = 249)) OR ("fid" = 250)) OR ("fid" = 251)) OR ("fid" = 252)) OR ("fid" = 253)) OR ("fid" = 254)) OR ("fid" = 255)) OR ("fid" = 256)) OR ("fid" = 257)) OR ("fid" = 258)) OR ("fid" = 259)) OR ("fid" = 260)) OR ("fid" = 261)) OR ("fid" = 262)) OR ("fid" = 263)) OR ("fid" = 264)) OR ("fid" = 265)) OR ("fid" = 266)) OR ("fid" = 267)) OR ("fid" = 268)) OR ("fid" = 269)) OR ("fid" = 270)) OR ("fid" = 271)) OR ("fid" = 272)) OR ("fid" = 273)) OR ("fid" = 274)) OR ("fid" = 275)) OR ("fid" = 276)) OR ("fid" = 277)) OR ("fid" = 278)) OR ("fid" = 279)) OR ("fid" = 280)) OR ("fid" = 281)) OR ("fid" = 282)) OR ("fid" = 283))
```

The statement is SQL correct but apparently SQL Lite does not support opening more than 89 brackets. If I execute the query whit an SQL Lite client I get this error:
`SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (parser stack overflow)`

For a solution I think there are more options:

1. The expression could be better translated avoiding unnecessary brackets
2. The whole N:M thing could probably use a join query instead of two separate on middle and end table. But this would require some more work
3. `OGR_L_SetAttributeFilter`should return an error so the fallback with expression filtering could be used at this place: https://github.com/qgis/QGIS/blob/f0838764b87568e4c3f7968e51ee2960c82df314/src/core/providers/ogr/qgsogrfeatureiterator.cpp#L231

**Comment by elpaso** [comment]
@domi4484 this reminds me of https://github.com/qgis/QGIS/pull/43502/files any chance you can use the same logic to turn  `OR`s into `IN` ?

**Comment by domi4484** [comment]
@elpaso thank you for the suggestion, i ll look at it

**Comment by andreasneumann** [comment]
> @domi4484 this reminds me of https://github.com/qgis/QGIS/pull/43502/files any chance you can use the same logic to turn `OR`s into `IN` ?

This is how a "human" would do it. The many nested brackets and OR statements look really, really strange.

**Comment by dingausmwald** [comment]
Any news on this?

**Comment by ghtmtt** [comment]
this bug seems still valid also with the same project attached (https://github.com/qgis/QGIS/files/6740631/test2.zip)
