### ISSUE TITLE
QGIS 3.20 Cannot pip install due to missing ssl library on Windows

### ISSUE THREAD

**Issue by letmaik** [qgis/QGIS#44185]
**Describe the bug**
In the OSGeo4W Shell, PyPI packages cannot be installed with `pip install` anymore.

**How to Reproduce**

1. Launch OSGeo4W Shell
2. Run `pip install f90nml`

>C:\Program Files\QGIS 3.20.0>pip install f90nml
Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/f90nml/
Could not fetch URL https://pypi.org/simple/f90nml/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/f90nml/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement f90nml (from versions: none)
ERROR: No matching distribution found for f90nml
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**QGIS and OS versions**

QGIS 3.20, Windows 10

**Additional context**

This worked fine in earlier versions of QGIS, last tested in QGIS 3.16.

**Comment by uclaros** [comment]
I've had the same issue with at least 3.18 and 3.16, using the standalone installers
http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-ssl-module-in-Python-is-not-available-td5451520.html

**Comment by letmaik** [comment]
> 
> 
> I've had the same issue with at least 3.18 and 3.16, using the standalone installers
> http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-ssl-module-in-Python-is-not-available-td5451520.html

Interesting, I never had issues. I just downloaded 3.16 from https://qgis.org/downloads/QGIS-OSGeo4W-3.16.8-1-Setup-x86_64.exe and it works. The new 3.20 uses MSI but probably it's caused by some OSGeo4W issue. The website notes say it uses v2 as repository now, so probably bigger changes were made.

**Comment by gioman** [comment]
> Run `pip install f90nml`

@letmaik works here, win 10, qgis 3.20

**Comment by cartoinddigo** [comment]
Hello,
I have the same issue (QGis 3.20 installed with OSGEO4W installer) :
This code 
`try:
    import openpyxl
except ModuleNotFoundError:
    print('installing openpyxl')
    if platform.system() == 'Windows':
        subprocess.check_call([sys.executable, "-m", 'pip', 'install', 'openpyxl'])
    else:
        subprocess.check_call(['python3', '-m', 'pip', 'install', 'openpyxl'])
    import openpyxl
    try:
        import openpyxl
        print('installation completed')
    except ModuleNotFoundError:
        QMessageBox.information(None, 'ERROR', "Oops ! L'installation du module openpyxl à échouée. Désolé de ne pas pouvoir aller plus loin...")`
give me this error : 
`pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/openpyxl/`

**Comment by cartoinddigo** [comment]
Re,

I've foud a solution : 

`subprocess.call(['pip3', 'install', 'openpyxl', '--user'])`

work for me ;-)

**Comment by jef-n** [comment]
Odd that is gets that far.  Python console:

```
>>> import sys
>>> sys.executable
'…\\bin\\qgis-bin.exe'
```

**Comment by Joonalai** [comment]
The same ssl library problem occurs when using python trough `bin/python-qgis-ltr.bat`:

```bat
$ python-qgis-ltr.bat
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
```

Due to this problem, it is not possible to install packages from internet trough pip.

With the normal `bin/python.exe` this error does not occur, but the environment is not properly set.

**Comment by LKajan** [comment]
I think this is due how dll lookup changed in Python 3.8. Dlls are looked up only from system directories and the ones added with add_dll_directory(). PATH directories are not looked up anymore for dlls. The right dll directories are set in `qgis.__init__.py` but pip is not aware that it should first `import qgis`. Osgeo4w has custom directory structure so python doesn't recognize its dll directories automatically.

This causes problems also with other command line tools like `pre-commit`.

**Comment by komima** [comment]
It seems in a "normal" Windows Python 3.8 install the `ssl` package is found in `install-dir/Lib/ssl.py`, that will in turn import the binary `_ssl` package found in `install-dir/DLLs/_ssl.pyd`, together with the DLLs `libcrypto-1_1.dll` and `libssl1_1.dll`, so the resolving works as expected (searched in "the loaded extension module's directory").

For QGIS with Python 3.7 plain `python-qgis.bat -m pip` call works, the wrapper bat setups the PATH, so the ssl dlls are found in PATH. To use virtual environments for development/testing (using --system-site-packages and PYTHONPATH/.pth-file to provide the `qgis` package to sys.path), some extra directories are necessary in PATH (osgeo/bin, osgeo/apps/qt5/bin, osgeo/apps/qgis/bin) to find the necessary DLLs. For example, using `pytest-cov` in the venv will use `coverage` from the osgeo install site-packages and `sqlite3` from the stdlib, but the sqlite dll is not in the `osgeo/apps/python/dlls` directory, but instead in the `osgeo/bin` directory (since its the same shared dll for both python and qgis, I assume?), and adding that directory to PATH fixes the resolving for Python 3.7.

But for Python 3.9 both the venvs and pip break since PATH is no longer enough. It seems for a fresh "normal" Python 3.8 install there are only ssl and sqlite dlls in the `python/dlls` directory.

Is it sufficient for QGIS packaging to duplicate the ssl and sqlite DLLs also to the stdlib binary module location, for at least the stdlib to be somewhat functional?

That will only leave a problem with some bundled packages that also share the DLLs with QGIS, and for that reason the DLLs are not in the module directory, but instead somewhere else in the osgeo install tree (eg. gdal dll in osgeo/bin, pyqt dlls in osgeo/apps/qt5/bin), and those modules will not work without importing qgis first (since that call add_dll_directory with the osgeo install tree paths).

Another option could be if there is there a way to somehow package the python.exe in such a way that it would setup the DLL directories using system calls (`AddDllDirectory()` ?) or run some python code to use add_dll_directory always when starting any session, similar to what `PYTHONSTARTUP` does for interactive mode?

**Comment by agiudiceandrea** [comment]
@komima have you tried to make this change? https://github.com/jef-n/OSGeo4W/commit/6f17d96ce12e8f7d47bc5f909a07278fb151c3d5

**Comment by komima** [comment]
@agiudiceandrea that is interesting, I tried that and it seems to help but just a little.

I did a fresh install with the v2 network installer for 3.16.10, and using that bat fix by pointing to the python.exe in the osgeo/bin directory (instead of osgeo/apps/python39) an interactive console imports successfully both ssl and sqlite3 modules. I assume that is because the dependencies are then also searched next to the executable (new dll search rules include "the application directory (e.g. that of python.exe)").

However, that will actually fail in mysterious ways with venv module, since even when the PYTHONHOME is properly setup when creating the venv (using the bat), that information is not baked into the venv (pyvenv.cfg sets home = osgeo/bin) and it will try to find stdlib modules relative to the executable, as would be the structure in osgeo/apps/python39 with lib/dlls directories next to the exe. Dirty magic trick test was to paste the DLLs and lib directory to osgeo/bin, and the venv works.

Also the fresh install actually now includes the libcrypto-1_1.dll and libssl-1_1.dll in the osgeo/apps/python39/dlls directory next to the _ssl.pyd module (and also in osgeo/bin directory). Checking the dependencies of the pyd module, it actually seems to fail due to libssl-1_1.dll having a dependency on another dll found only in osgeo/bin, libcrypto-1_1_x64.dll. Copying that to osgeo/apps/python39/dlls, using the original bat and starting an interactive console `import ssl` actually now succeeds. Same thing with the sqlite3 module, copying sqlite3.dll from osgeo/bin to osgeo/apps/python39/dlls imports sqlite3 fine.

Extra note for normal Python 3.8 the _ssl.pyd actually depends on libcrypto-1_1.dll and libssl-1_1.dll, which again depends on libcrypto-1_1.dll, so its a bit different and does not need the extra x64 labeled dll.

With those two dlls copied I cant find any other dll directory pyd that has unresolved dll imports, so could this be a valid fix to make the stdlib functional? And is something that can be fixed in this repo, or somewhere else regarding how the osgeo4w installers work?

Only problem that would probably remain are the included python modules that have dll dependencies only in the osgeo/bin directory, for which using the python.exe in that directory definitely helps. PyQt5 has this solved (it searches the path for what it needs), osgeo.gdal informs the user to set an environment variable to use the PATH if dll cant be found in default search locations. Importing qgis first would also help, but I'll test this more how installing only gdal+python with the osgeo4w installer compares and how the exes and dlls are placed in that case, since there would be no qgis to import to set the paths for gdal use only.

**Comment by agiudiceandrea** [comment]
> And is something that can be fixed in this repo, or somewhere else regarding how the osgeo4w installers work?

The specific issue report system for OSGeo4W installers is at https://trac.osgeo.org/osgeo4w/ and the new OSGeo4W installer scripts repository is at https://github.com/jef-n/OSGeo4W

**Comment by komima** [comment]
I made a [ticket on this issue](https://trac.osgeo.org/osgeo4w/ticket/692) to osgeo4w issue tracker, it seems the problem can be fixed by the packaging (and already is with [this fix](https://github.com/jef-n/OSGeo4W/commit/6f17d96ce12e8f7d47bc5f909a07278fb151c3d5) if the python environment is only used with the .bat wrapper).
