### ISSUE TITLE
Searches with Metasearch are broken on installations based on OSGeo4W v2 (missing python3-lxml dependency)

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#44225]
Searching with metasearch returns (any service) always a message

`Connection error: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'`

No other errors in the QGIS log. No issues under Linux.

**Comment by agiudiceandrea** [comment]
I cannot confirm.
I've just made a fresh installation of QGIS Standalone Installer Version 3.20 QGIS-OSGeo4W-3.20.0-4.msi on Windows 10 Home 1903 64 bit and I can use the searching functionality of the MetaSearch core plugin without issues.

**Comment by gioman** [comment]
@agiudiceandrea I didn't use the standalone installer, but as stated in the title I used the osgeo4w one. So it may be just a matter of a package/dependency that is not automatically installed, but is added in the standalone one. Anyway this not something that a final user should be worried about.

**Comment by agiudiceandrea** [comment]
Anyway your issue may be caused by the missing or incorrectly installed Python package "lxml" and by a not updated owslib Python package.

Could you test if the following commands are executed without errors in the Python console?:

```python
from lxml import etree
from lxml.etree import ParseError
```

and that the output of the last following commands outputs the string `lxml.etree`?:

```python
from owslib.etree import etree, ParseError
print(etree.__name__)
```

**Comment by gioman** [comment]
> ```python
> lxml

@agiudiceandrea I confirm that the problem is the missing dependency python3-lxml after installng it manually Metasearch works.

**Comment by agiudiceandrea** [comment]
The OSGeo4W package `python3-lxml` is not a dependency of the `qgis` and the `qgis-ltr` packages, so it is not automatically installed following the instructions ("use the Advanced Install and choose qgis and/or qgis-ltr").

Instead, it is a dependency of qgis-full and qgis-ltr-full, which are the meta packages used to create the standalone installer, so it is automatically installed with the standalone installer.

Anyway, the MetaSearch plugin could work also without the `lxml` module: in fact it is not installed by default also using the OSGeo4W old repository, but the MetaSearch plugin doesn't have the reported issue using the OSGeo4W old repository network installer.

The real cause of the issue is the version 0.20 of the `owslib` Python package in the OSGeo4W v2 repository, which doesn't properly work with Python 3.9 (which is used in the OSGeo4W v2 repository).

The `owslib` Python package in OSGeo4W v2 repository should be updated at least to the 0.21 version to properly work with Python 3.9.

**Comment by agiudiceandrea** [comment]
OSGeo4W v2: python3-owslib-0.20.0 doesn't support Python 3.9
https://trac.osgeo.org/osgeo4w/ticket/684

**Comment by agiudiceandrea** [comment]
Confirmed fixed for QGIS installed via OSGeo4W v2 Network Installer updating python3-owslib package to version 0.24.1 (python3-owslib-0.24.1).

**Comment by gioman** [comment]
Many thanks @jef-n and @agiudiceandrea
