### ISSUE TITLE
saga version 7.8.2

### ISSUE THREAD

**Issue by ezraile** [qgis/QGIS#44611]
### What is the bug or the crash?

Hello,
When I want to use any function in SAGA, on Top of the window of function was written: "saga version 7.8.2 is not officially supported - algorithms may encounter issues".  What's wrong? What should I do to fix it?
my QGIS version is 3.16.9.
Thanks

### Steps to reproduce the issue

any function in SAGA 7.8.2 

### Versions

3.16.9

**Comment by nyalldawson** [comment]
>What's wrong? What should I do to fix it?

As the warning shows, we don't officially support the SAGA algorithms in QGIS. We offer a way to run them, but you'll run into issues which won't be addressed here. Wherever possible you should use alternative algorithms from the QGIS/GDAL/GRASS providers instead.

That said, the SAGA algorithms MAY still work fine, we just don't make any claims that they will 🙃

**Comment by gioman** [comment]
> Hello,
> When I want to use any function in SAGA, on Top of the window of function was written: "saga version 7.8.2 is not officially supported - algorithms may encounter issues". What's wrong? What should I do to fix it?
> my QGIS version is 3.16.9.
> Thanks

@ezraile The warning was added because for long time we shipped description files for SAGA tools that were based on SAGA 2.* (we were stuck with that old SAGA version because some mainstream Linux distribution, that we officially support, didn't shipped with a more recent SAGA). Now at least on recent Windows installers we ship SAGA 7.* and the description files are also generally fine for it, anyway the warning remained, possibly (not sure 100%) because on Linux we still have old description files.
