### ISSUE TITLE
Unable to retreive version information with command line options on Windows

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#44694]
### What is the bug or the crash?

I'm unable to retrieve version information with command line option `--version` even though the option exists. Nothing is printed. Other commands like `--help` (image below that display what `--version` should do), `--profile` or `--profiles-path` work as intended.

![QGIS_options](https://user-images.githubusercontent.com/32580398/129451507-84f9df28-49a6-4c74-b778-01c454f94e33.png)

### Steps to reproduce the issue

Call `qgis-ltr-bin --version` or `qgis-bin --version` and see that nothing is printed.

### Versions

QGIS 3.20.0 and QGIS 3.16.9, both via OSGeo4W install
Windows 10 Version 1809

**Comment by gioman** [comment]
Also it should print that infos in the terminal/console, and not open that dialog, I think.

**Comment by agiudiceandrea** [comment]
> I'm unable to retrieve version information with command line option `--version`

It's an issue that occurs on Windows platforms. Also reported in https://github.com/qgis/QGIS/issues/37465#issuecomment-654894052.


> Also it should print that infos in the terminal/console, and not open that dialog, I think.

It seems this is by design, introduced with https://github.com/qgis/QGIS/commit/bd23bf1a2368fa68fe692d451f61bfe3095619bd and https://github.com/qgis/QGIS/commit/f61c993e1355cd8ded491e48bdeb3b0aea939c34 by @jef-n probably just to workaround  the same issue that occurs with "--version".
https://github.com/qgis/QGIS/blob/3e28304ad3dbe8a501dca770f61e3678ead79889/src/app/main.cpp#L180-L187

**Comment by jfbourdon** [comment]
>Also it should print that infos in the terminal/console, and not open that dialog, I think.

Sorry for the confusion, I now edited my description to make it clear that `--help` works but not `--version`.

The argument `--version` or  `-v` should be read...
https://github.com/qgis/QGIS/blob/f14ddac702cd74a1e79dd5638ebc24edb7a918e9/src/app/main.cpp#L641-L645

Is it that `version()` function doesn't produce a valid string on Windows?
https://github.com/qgis/QGIS/blob/f14ddac702cd74a1e79dd5638ebc24edb7a918e9/src/app/main.cpp#L121-L125

[Elsewhere](https://github.com/qgis/QGIS/blob/f14ddac702cd74a1e79dd5638ebc24edb7a918e9/src/app/main.cpp#L182) strings seem to be printed with `msg.toLocal8Bit().constData();` instead of `msg.toStdString();` . I must say that I don't know much about C++.

**Comment by agiudiceandrea** [comment]
> Is it that `version()` function doesn't produce a valid string on Windows?

AFAIK the issue is due to the fact that, normally, std::cout cannot display the text string in the console when a WIN32 GUI application is executed in the CLI.
In fact, you can redirect the output of `qgis-bin --version` to a file using  `qgis-bin --version > version.txt` and see a valid version text string successfully written in the file.

> I now edited my description to make it clear that `--help` works

Do you mean it's OK for you that the `--version` output would be displayed in a message window like for the `--help` output?
In this case it should be simple to fix the issue.

**Comment by jfbourdon** [comment]
>Do you mean it's OK for you that the --version output would be displayed in a MessageBox window like for the --help output?
No, I was just trying to say that all arguments were doing what we are expecting them to do. Maybe I should have remove my last sentence altogether.

Thanks for the trick `qgis-bin --version > version.txt`, I didn't thought about trying that. For my intended usage, it will do the job just fine.
