### ISSUE TITLE
Freehand raster georeferencer plugin creates a border around every image

### ISSUE THREAD

**Issue by IAmHereAtGithub** [qgis/QGIS#45004]
### What is the bug or the crash?

Sorry if this is an obvious configuration settings somewhere, but I spend hours and can´t solve it.

I installed latest ubuntu and qgis.
Every time I add a image with the "Freehand raster georeferencer" plugin I get a border around the image, and I see no possibility to remove this border.

![qgis](https://user-images.githubusercontent.com/89143144/132677892-85a5af83-b060-4262-ab3f-30ec4c5f28cb.png)

### Steps to reproduce the issue

1. Install "Freehand raster georeferencer" plugin.
2. Create new project.
3. Click on Layer > Add Layer > Add raster for inactive georeferencing.
4. Select any image (.png) you want and click on "Add New".

### Versions

QGIS version
3.20.2-Odense
QGIS code revision
9f59a15664
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.3 LTS

Active Python plugins
FreehandRasterGeoreferencer
processing
db_manager
MetaSearch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I have the same behavior on windows and with different qgis version (3.16.4) too.

**Comment by roya0045** [comment]
Ask the plugin author, qgis is not responsible for the plugins.

**Comment by magau** [comment]
I was facing the same issue. So, I also ended up here while searching for a solution...
Despite it's already _Closed_, because it's not a QGIS issue (as mentioned by @roya0045), I've decided to share how I've workaround with it. 

The frame thickness is actually hardcoded in the [FreehandRasterGeoreferencer](https://github.com/gvellut/FreehandRasterGeoreferencer) plugin scripts.
After finding the QGIS plugins install location, I've edited the following script: _plugins/FreehandRasterGeoreferencer/freehandrastergeoreferencer_layer.py_

And modified the current value (3) according to what it fits better to my project, by changing the following line:
From:
`
pen.setWidth(3)
`
To:
`
pen.setWidth(1)
`

Note that since the width value is set in pixels, 1 is the thinner you will get.
If you set it to any value lower than 1, the frame will disappear (which was not my intention, but it can be a solution for those who are trying to get rid of it...).

Hope it helps someone that is getting annoyed with it, like I was...

**Comment by Aporiac** [comment]
Changing:
pen.setWidth(3)
To:
pen.setWidth(0)

doesn't remove the black border - it just makes it thin (QGIS 3.40.5-Bratislava, Freehand raster georeferencer v0.8.3)

To remove the border entirely, comment out the drawRect() line a few lines after setWidth():

Change:
painter.drawRect(rect)
To:
\# painter.drawRect(rect)

On my Mac, the freehandrastergeoreferencer_layer.py Python file is in:
~/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
