### ISSUE TITLE
v.clean doesnt work when type name for fid is int8

### ISSUE THREAD

**Issue by dingausmwald** [qgis/QGIS#45707]
### What is the bug or the crash?

as [#43437](https://github.com/qgis/QGIS/issues/43437) stated already, refactor fields, and join attributes by location (summary) and surely others produce int8 type name for the fid.

After that, v.clean cant create fid

![grafik](https://user-images.githubusercontent.com/30699246/139309329-538544d5-fd12-4762-bac0-b1d0257a24fd.png)

### Steps to reproduce the issue

refactor fields,
use v.clean

### Versions

3.16.11
3.20.3

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by dpiercy8** [comment]
This issue is "Closed",  but have also encountered this bug. I'm not sure of the proper process to reopen an issue. If I need to create a new issue let me know. I have attached a sample as requested to allow the issue to be reproduced.

QGIS 3.28.14 on a 2022 MacBook Air with Apple's M2 processor running MacOS Ventura 13.6

Recreating the problem using the attached sample bug-45707.gpkg
1. load the bug45707 layer into QGIS
1. run v.clean from the processing toolbox on the Bug-45707 layer (parameters listed below)
    - output should be a "clean" temporary layer with good output (line)
1. run "refactor fields from the processing toolbox (using default parameters)
   - generates a "Refactored" temporary layer with an identical line to the Bug-45707 layer
1. run v.clean from the processing toolbox on the "Refactored" layer (parameters listed below)
   - ERROR 1: Wrong field type for fid
   - ERROR: Unable to create column <fid>
   - _note: the input is lineZ and you also get warnings about this for both layers. I could not find out what the output type for a temporary layer is, and thus what ico to pass to get 3D output. {perhaps a separate documentation bug?}_
1. Saving the "Refactored" temporary layer to a gpkg, and then running v.clean will work (no errors)

In a Geopackage layer, the fid field's "Type" is 'Integer (64 bit)', and "Type name" is 'Integer64'
In a temporary layer the fid field's "Type" is 'Integer (64 bit)', and "Type name" is 'int8'

settings for v.clean: 
* Input type= line
* cleaning tool= snap,rmdupl,prune
* Threshold= 0.00055,0,0
* advanced parms= default.

[bug-45707.gpkg.zip](https://github.com/qgis/QGIS/files/13854886/bug-45707.gpkg.zip)

**Comment by rtdietrich** [comment]
It's a real shame that this has been closed even though the problem still exists (for me too).

**Comment by Horizen89** [comment]
Issue still exists in 4.0.2
