### ISSUE TITLE
QGIS Crashing

### ISSUE THREAD

**Issue by MeganWoodCalibre** [qgis/QGIS#45761]
### What is the bug or the crash?

Crash ID: 714cdebb4294d246220d704f0aa9214c11d910ad

Stack Trace

QgsGeometryValidator::checkRingIntersections :
QgsGeometryValidator::run :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

### Steps to reproduce the issue

Reopening QGIS is not helping

### Versions

3.16.11-1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Can you confirm the actual QGIS version used? is it 3.16.0 or 3.16.11?

**Comment by MeganWoodCalibre** [comment]
Hi Nyall,

I'm using this one  https://qgis.org/downloads/QGIS-OSGeo4W-3.16.11-1.msi

**Comment by Gustry** [comment]
Clicking the link provided for the code revision, it leads to the 3.16.0 commit from October 2020, it's not 3.16.11

Please upgrade following the roadmap : https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

Duplicate crash ID : https://github.com/qgis/QGIS/issues/39770
It's already fixed in latest 3.16.X

Reopen another ticket if necessary
