### ISSUE TITLE
Crash ID: 53c326f8381be00e27f895b68a8609a04554d418

### ISSUE THREAD

**Issue by beilic** [qgis/QGIS#46014]
### What is the bug or the crash?

Crash ID: 53c326f8381be00e27f895b68a8609a04554d418

Stack Trace

operatoroperatorQMetaType::save :
QVariant::save :
operatorQSettings::value :
QSettings::value :
QSettings::sync :
QThreadPool::maxThreadCount :
QSettings::~QSettings :
QgsSettings::~QgsSettings :
QgsSettings::~QgsSettings :
QgsNewsFeedParser::onFetch :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Just openning QGIS

### Versions

3.10.4

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Can't open QGIS and change the profile

**Comment by gioman** [comment]
>  QGIS Version: 3.10.4-A Coru�a

@beilic too old and unsupported. Update to 3.16.13 or 3.22.0, use a new QGIS profile and try again.

**Comment by agiudiceandrea** [comment]
@beilic you can add `--profile `, followed by the name of a new profile you want create, in the Windows Shortcut link you use to launch QGIS. See https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#command-line-and-environment-variables
Otherwise you could rename the user profile folder so QGIS will create a new one. See https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#command-line-and-environment-variables

**Comment by beilic** [comment]
I had to delete the log folder in "AppData\Local\QGIS\QGIS3\crashes". After, qgis started normally.
Thanks for help
