### ISSUE TITLE
WMS: Identify Feature cannot be switched back to "HTML" or "text"

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#46436]
### What is the bug or the crash?

Identify Feature cannot be switched back to "HTML" or "text" when once switched to "Feature" and if there is an error receiving the data (like a Java exception)

![grafik](https://user-images.githubusercontent.com/67278094/145548750-bfb322fe-bd64-4f6b-a598-ac09195e316a.png)

I consider this a very minor bug though

### Steps to reproduce the issue

1. Connect to a WMS that causes a Java exception when getting feature contents, currently e.g. https://geoservice.dlr.de/eoc/basemap/wfs (Source: https://geoservice.dlr.de/web/services)
2. Switch format to feature
![grafik](https://user-images.githubusercontent.com/67278094/145546658-0fe42e7b-ea4e-48f5-8bf1-8bd811eef1d4.png)
3. Try to identify a feature and observe the identify result panel stays empty. 

### Versions

3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
I'd say this is a won't fix: you can switch back to HTML/TEXT if the identify does not return an error because in feature mode you have no features in case of errors while in HTML/TEXT mode you have an error response (QGIS cannot really tell if it's an error or a valid HTML/TEXT response).

IMO this issue is really a corner case from a faulty server.
