### ISSUE TITLE
Georeferencer is broken

### ISSUE THREAD

**Issue by CEDGIS** [qgis/QGIS#46901]
### What is the bug or the crash?

The Georeferencer tool is not working on 3.22.2, however visible under Raster tab

### Steps to reproduce the issue

Click Raster
Click Georeferencer...

### Versions

3.22.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Grgsj** [comment]
I have been also having an issue trying to georeference in QGIS 3.22:

I am working with a TIFF image that is already in my UTM Zone 10 projection (EPSG: 26910 - NAD83 / UTM zone 10N) and trying to improve its registration.  The map coordinates from QGIS match those on the map but when you run Georeferencing it shows a massive error that is the size of the UTM coordinates themselves.  This is visible as the red offset lines in the Georeferencer window (see image).

I am not sure how to troubleshoot this.  Suggestions would be appreciated.

![image](https://user-images.githubusercontent.com/96092842/150228895-d6fed307-fcb5-4e5d-8f55-c974cbd12601.png)

**Comment by CEDGIS** [comment]
I should have probably mentioned in the ticket initially, but my georeferencer wont open at all, I select it in the Raster tab and it does nothing.

**Comment by gioman** [comment]
> I should have probably mentioned in the ticket initially, but my georeferencer wont open at all, I select it in the Raster tab and it does nothing.

@CEDGIS please try with a new QGIS profile.

**Comment by gioman** [comment]
> I am not sure how to troubleshoot this. Suggestions would be appreciated.

@Grgsj you may want to attach/link your image, the gcp table and the georef configs you are using.

**Comment by Grgsj** [comment]
Here is the GCP and image file:

https://www.dropbox.com/s/phxe4aug9dakc69/SS_ORTHOPHOTO_UAV_5CM.tif.points?dl=0
https://www.dropbox.com/s/l0ywi6ujwb4wwqv/SS_ORTHOPHOTO_UAV_5CM.tif?dl=0

Below are my config settings:
![image](https://user-images.githubusercontent.com/96092842/150233364-3e21ea8d-3c61-4134-a064-cb2c2e0a3245.png)

**Comment by CEDGIS** [comment]
> > I should have probably mentioned in the ticket initially, but my georeferencer wont open at all, I select it in the Raster tab and it does nothing.
> 
> @CEDGIS please try with a new QGIS profile.

I have now and it works - is there a way can open my old docs in this new profile now? or do I have to set up all my connections and data all over again?

**Comment by gioman** [comment]
> is there a way can open my old docs in this new profile now? or do I have to set up all my connections and data all over again?

@CEDGIS you can switch back to your old profile, save/export your connections and then import them in the new one.

**Comment by gioman** [comment]
> I have now and it works

@CEDGIS weird, it didn't helped me. I'll reopen this because georef seems really broken in 3.22 while seems to still work ok on 3.16.

**Comment by ramotswa** [comment]
This is happening for me too. It seems to be a problem with trying to georeference an image that already has georef information in it. As per @Grgsj's screeshot - mine does the same.

After having created some gcp's - I can see the gdal command that QGIS wants to run is ;
`gdal_translate -of GTiff -gcp 520289 -180839 520341 180933 -gcp 520273 -180579 520274 180467 -gcp 520576 -180888 520768 180933 "image1.tif" "tempimage1.tif"` 
(My projection is EPSG: 27700).

As you can see the first two parts of the -gcp command are quite strange - i.e there is a big negative jump  which is wrong - there is nothing under 0,0 in EPSG:27700. I bet you @Grgsj has the same sort of issue.

If I remove the georef information from the tiff file (gdal_translate to tiff + tfw file and then delete the tfw file) -and then try and georef that the obvious difference is that the gdal_translate command from the georeferencer now has pixel location (column / row) in the -gcp flag (as expected) rather than some strange coordinates. 

I've set up a new profile. No difference.
Am using 3.22.1 on MacOS X 11.3.1 (Intel)

**Comment by roya0045** [comment]
@gioman Can we file this as solved?

**Comment by gioman** [comment]
Fixed recently.
