### ISSUE TITLE
No (more) warning when trying to run tool with inputs  with different CRSs

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#46964]
### What is the bug or the crash?

According to the option "Warn before before executing if parameter CRS's do not match" a warning should be displayed if different CRSs are processed in external tools.

 ![image](https://user-images.githubusercontent.com/1951107/150530808-892bcd28-ca80-4f8d-8959-66cfe7575391.png)

![image](https://user-images.githubusercontent.com/67278094/150768829-49ca8714-d521-4e9f-a7c4-f8a90c83cc4c.png)

**Yet no warning is displayed!**

### Steps to reproduce the issue

Load two different layers and execute tool v.what.vect

For an actual example and detailed steps see https://github.com/qgis/QGIS/issues/46916

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.18
GroupStats
2.2.5
HCMGIS
21.8.28
mmqgis
2021.9.10
Qgis2threejs
2.6
QuickOSM
2.0.0
quick_map_services
0.19.27
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@tschmetzer this is probably a general issue (of non QGIS tools, as QGIS native tools do reproject layers in case the inputs have different CRSs), and not one specific to this tool. Please give it a try and edit the title and description accordingly, if is the case.

**Comment by tschmetzer** [comment]
Cannot do the test before 11 Feb 2022

**Comment by alexbruy** [comment]
Warning is shown only algorithm advertises that its inputs should have matching CRS. This is not the case for most of non-native tools.

**Comment by gioman** [comment]
> Warning is shown only algorithm advertises that its inputs should have matching CRS. This is not the case for most of non-native tools.

@alexbruy so I guess we can close.

**Comment by tschmetzer** [comment]
From a usability perspective I would expect a warning that the CRSs differ and that extern tools are not expected to issue a corresponding warning.

**Comment by DelazJ** [comment]
@alexbruy Trying to understand the scenarios here. If I check this option and I'm running:

*  a QGIS c++ native alg: nothing happens since a native tool is expected to transparently reproject the layers before running. Right?
* a QGIS non native alg: I get a warning and the process would stop, so that I reproject the layers and rerun the alg
* a thrid-party alg: nothing happens, because we don't (have to) check what is the protocol for other providers

**Comment by tschmetzer** [comment]
Isn't this an upstream topic then?

**Comment by gioman** [comment]
> Isn't this an upstream topic then?

@tschmetzer I believe that the check was implemented at a QGIS level.

**Comment by tschmetzer** [comment]
Depends on whether the message doesn't show up anymore because the check on QGIS level has been removed (maybe accidentally) or because the underlying upstream function doesn't provide the required information anymore.

**Comment by gioman** [comment]
I believe is the former.

**Comment by alexbruy** [comment]
@DelazJ it does not matter whether algorithm is native or 3rd-party. It just should advertise that it needs inputs in the same CRS. So in your scenarios:

-  a QGIS c++ native alg:  if algorithm has corresponding flag, you will get a warning, otherwise it will run and produce some results. As in this case we have full control on the implementation, right now almost all native algorithms handle reprojection transparently.
-  a QGIS non native alg: if algorithm has corresponding flag, you will get a warning, otherwise it will run and produce some results
-  a thrid-party alg:  if algorithm has corresponding flag, you will get a warning, otherwise it will run and produce some results

**Comment by alexbruy** [comment]
> Depends on whether the message doesn't show up anymore because the check on QGIS level has been removed (maybe accidentally) or because the underlying upstream function doesn't provide the required information anymore.

As I have said in the comment above, all required logic is here. Algorithms should advertise that they require inputs with the same CRS. This is not the case for majority of 3rd party providers.

**Comment by tschmetzer** [comment]
> As I have said in the comment above, all required logic is here. Algorithms should advertise that they require inputs with the same CRS. This is not the case for majority of 3rd party providers.

Will most 3rd party provider need the same CRS? What about inverting the logic for 3rd party providers so they need to advertise algorithms are allowed to be in different CRS? Or just issue a general warning for 3rd party providers as suggested in https://github.com/qgis/QGIS/issues/46964#issuecomment-1039298869 that as the CRSs differ extern tools are not safe to issue a corresponding warning.

**Comment by gioman** [comment]
> Will most 3rd party provider need to be fed the same input CRS?

@tschmetzer yes. PostGIS, GRASS, SAGA, GDAL they all expect same CRS for the inputs.
