### ISSUE TITLE
QGIS 3.22 wrongly displays raster

### ISSUE THREAD

**Issue by k-rns** [qgis/QGIS#47158]
### What is the bug or the crash?

A raster file that was correctly displayed in qgis 3.14 is not correctly displayed in qgis 3.22. When adding the reference system WGS84, the raster does not get put on the map in the right spot, while in 3.14 it is being visualized correctly. 

### Steps to reproduce the issue

import grid file with WGS84 into the data layer manager. When adding projection to that layer, it will wrongly project it on the map.

Same sort of issue described can be found here: https://gis.stackexchange.com/questions/421861/qgis-3-22-incorrectly-displaying-raster-layers 

### Versions

3.14 (works)
3.22 (works not)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> he raster does not get put on the map in the right spot

@k-rns attach/link the data.

**Comment by bartbatt** [comment]
I'm having the same issue.  Rasters that projected properly in 3.16 no longer do.  Also, I have the same problem when I rebuild the project using a different profile.

**Comment by gioman** [comment]
@k-rns @bartbatt on what operating system you are? please attach/link sample data.

**Comment by gioman** [comment]
I have also tested on macOS Monterey (M1), no issues.

**Comment by k-rns** [comment]
Thanks @gioman, any idea where I should raise this issue with them?

**Comment by agiudiceandrea** [comment]
It seems to me this is a GDAL issue:
- QGIS version 3.16.16 (Windows 10 - OSGeo4W v2) / GDAL 3.4.1 / NetCDF 4.7.4-7: the issue occurs
- QGIS version 3.16.16 (Windows 10 - OSGeo4W v1) / GDAL 3.1.4 / NetCDF 4.7.3-2: the issue does not occur

**Comment by gioman** [comment]
> Thanks @gioman, any idea where I should raise this issue with them?

@k-rns https://github.com/OSGeo/gdal/issues

**Comment by roya0045** [comment]
Maybe this issue could be already fixed upstream also, @rouault would know best.

**Comment by rouault** [comment]
The fact that this file is no longer detected as georeferenced is actually a feature. GDAL 3.4 (per commit https://github.com/OSGeo/gdal/commit/295cc128cf825aa0a66762dcade905b62d46a4e0) got much more restrictive on how it inspects netCDF dimensions and indexing variables, due to false positives, which led to gdalwarp producing wrong results in the presence of geolocation arrays for example. So GDAL now requires that the variables indexing the x/y dimensions have the long_name and/or standard_name attributes mandated by the netCDF CF conventions. Which the file in that ticket lack. It is possible to define the GDAL_NETCDF_IGNORE_XY_AXIS_NAME_CHECKS=YES environment variables to restore the laxer past behavior. Per https://github.com/OSGeo/gdal/pull/5233, I'm also adding an open option which will make it easier to define it on a file-per-file basis from QGIS GUI (using the "Add raster layer" command)

**Comment by gioman** [comment]
@rouault thanks!

**Comment by jarrettinho** [comment]
Please see this question I posted that I think is linked to this issue with QGIS 3.22 https://gis.stackexchange.com/q/443874/96729. I'm not sure how to resolve this in 3.22 so had to go back to 3.18
