### ISSUE TITLE
Postgres views load very slow 

### ISSUE THREAD

**Issue by savillstdv** [qgis/QGIS#47675]
### What is the bug or the crash?

Loading a postgres view object from the browser panel into the layer list takes a really long time compared to tables or matviews.
We have tested using multiple versions of Qgis and multiple versions of Postgres, all with the same behaviour. We also tested with both our Postgres test environment (Postgres 12.9) and production environment (Postgres 9.6) and took into account various tables.

### Steps to reproduce the issue

See the above. This should be easy to reproduce with any postgres database

### Versions

QGIS version
3.22.1-Białowieża
QGIS code revision
663dcf8fb9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
pdokservicesplugin
3.6.0
qgis-maptiler-plugin
1.1.4
Qgis2threejs
2.6
qgis2web
3.16.0
vector_tiles_reader
3.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> See the above. This should be easy to reproduce with any postgres database

@savillstdv well... I guess it can depend on how much info the view pushes and/or if the underlying query does complex stuff. Without a concrete example hard to troubleshoot. I suggest you to post a dump with the necessary tables and the view, so we can test locally.

**Comment by savillstdv** [comment]
Thank you @gioman 
I agree I need to provide better repro steps including a PGdump.
I will do so, but this may take a while due to lack of time currently. I will try to provide you with this as soon as possible.

**Comment by FestplattenSchnitzel** [comment]
This issue is still present 3.44.11-Solothurn.  There is a significant difference in performance between working with views compared to materialized views.

Edit: I can provide a database dump if desired.

<details>
<summary>Version information</summary>
<table width='100%' align='center'><tr><td>QGIS version</td><td>3.44.11-Solothurn</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_44">Release 3.44</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.19</td></tr><tr><td>Python version</td><td>3.14.6 (Compiled)<br/> (Running)</td></tr><tr><td>GDAL version</td><td>3.13.1 — <i>Iowa City</i></td></tr><tr><td>PROJ version</td><td>9.8.1</td></tr><tr><td>EPSG Registry database version</td><td>v12.029 (2025-10-02)</td></tr><tr><td>GEOS version</td><td>3.14.1-CAPI-1.20.5</td></tr><tr><td>SQLite version</td><td>3.53.3</td></tr><tr><td>PostgreSQL client version</td><td>18.4</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Debian GNU/Linux forky/sid</td></tr><tr></tr></table>
</details>
