### ISSUE TITLE
Add support for OAUTH PKCE authorized code flow

### ISSUE THREAD

**Issue by lucwillems** [qgis/QGIS#47760]
### Feature description

current authorized code flow is based on RFC6749. it requires a client_id and client_secret for requesting oauth tokens.

the current best praktisch for authentication of native apps , see [https://auth0.com/blog/oauth-2-best-practices-for-native-apps](https://auth0.com/blog/oauth-2-best-practices-for-native-apps) ,
to use PKCE based authorization code flow.

this will improve the overall security of this flow and as additional "extra", we do not need to distribute client secrets as there is no need for one. this means that oauth2 configurations can easily be shared without storing any username/password or client secrets. 

### Additional context

additional information links:

[https://tools.ietf.org/id/draft-ietf-oauth-native-apps-12.html#rfc.section.7.1](https://tools.ietf.org/id/draft-ietf-oauth-native-apps-12.html#rfc.section.7.1)
[https://datatracker.ietf.org/doc/html/rfc8252](https://datatracker.ietf.org/doc/html/rfc8252)

**Comment by remicres** [comment]
Event basic OAuth2 Authorization Code Flow would be better that the existing (no login, pass, secret, etc. would be stored in QGIS).

Also QGIS could store the refresh token somewhere (after each refresh operation), which would be quite convenient when `offline_access` scope is used.
This way it could try to reuse this token before starting the auth code flow from the beginning, and instead get a fresh `access_token`. If it's failing (likely because the refresh token has expired), just restart the auth code flow from the beginning.

**Comment by elpaso** [comment]
@remicres I would be available for developing this feature, please get in touch with me privately if you are interested.

**Comment by ElecSmurf** [comment]
Is there any update on this request? Having a secure connection with OGI API features is an important feature.

**Comment by elpaso** [comment]
@ElecSmurf yes, I've found a client willing to fund this development.

**Comment by elpaso** [comment]
@ElecSmurf if you have test endpoint I can use please contact me privately with the instructions.
