### ISSUE TITLE
Georeferencer hangs on import

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#48103]
### What is the bug or the crash?

See title 

### Steps to reproduce the issue

1. Try to import the following PDF
[Plan Topo 1983 modifie en 1984 de Pelgros a St Amand 1de2.pdf](https://github.com/qgis/QGIS/files/8428226/Plan.Topo.1983.modifie.en.1984.de.Pelgros.a.St.Amand.1de2.pdf)
 

### Versions

3.24.1-2 OSGeo4W
GDAL 3.4.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Confirmed on Windows 10: using QGIS 3.24.1 (qgis 3.24.1-2) and QGIS 3.22.5 (qgis-ltr 3.22.5-2) from OSGeo4W v2 (with GDAL 3.4.2) and also using QGIS 3.16.16 (qgis-ltr 3.16.16-1) from OSGeo4W v2 (with GDAL 3.4.1) and from OSGeo4W v1 (with GDAL 3.1.4).

**Comment by nicogodet** [comment]
@agiudiceandrea It seems specific to this PDF, works fine with others.
I will open a GDAL issue.

**Comment by nicogodet** [comment]
@Pedro-Murteira You can add "Upstream" label on this

**Comment by nicogodet** [comment]
https://github.com/OSGeo/gdal/pull/5840 fix the long process but the above PDF appears blank (I remember a similar issue...)

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/issues/44522

**Comment by agiudiceandrea** [comment]
> [OSGeo/gdal#5840](https://github.com/OSGeo/gdal/pull/5840) fix the long process but the above PDF appears blank

@nicogodet, have you reported this issue to OSGeo/gdal?

**Comment by nicogodet** [comment]
@agiudiceandrea Blank PDF is linked to #49175

Georef still hangs on import...
I need to test with environment var described in https://github.com/OSGeo/gdal/issues/5589

**Comment by nicogodet** [comment]
Env var have no effect.
Still hangs

Using gdal_translate from 3.5.0, convert this PDF in Tiff in few seconds and georeferencer imports tiff file without issue.

**Comment by agiudiceandrea** [comment]
@nicogodet see comment https://github.com/OSGeo/gdal/issues/5589#issuecomment-1170857926.

**Comment by pathmapper** [comment]
Came across this slowness with a PDF despite I used GDAL option `TILED=YES` to create it (https://github.com/OSGeo/gdal/issues/8233).

When you build GDAL with [PDFium](https://gdal.org/development/building_from_source.html#pdfium) the sample PDF here opens nearly instantly (GIF below).

Would be nice if OSGeo4W could use PDFium instead of Poppler - this would also solve https://github.com/qgis/QGIS/issues/54274 for the official QGIS Windows builds.

But according to @rouault, building PDFium is kind of PITA -> https://github.com/OSGeo/gdal/issues/8236#issuecomment-1682912929
(I've used the pre-build binaries from https://github.com/rouault/pdfium_build_gdal_3_8)

Not sure if there a side effects or other disadvantages when using PDFium instead of Poppler though.



![qgis_48103](https://github.com/qgis/QGIS/assets/20856381/b1351893-d586-4034-99eb-415fa9782122)

**Comment by agiudiceandrea** [comment]
@nicogodet, @pathmapper, maybe this issue will be fixed by https://github.com/OSGeo/gdal/pull/8278.

**Comment by nyalldawson** [comment]
This can be closed now, right?

**Comment by pathmapper** [comment]
Yes, can be closed.
