### ISSUE TITLE
When setting a SQL filter in PG from the source select dialog the number of filtered rows might be wrong

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS#48446]
### What is the bug or the crash?

When setting a SQL filter in PG from the source select dialog the number of filtered rows might be wrong.

This happens when the trust layer metadata flag is set, we should unset it before performing the row count or the test is pointless.

### Steps to reproduce the issue

Create a PG connection and set the "trust layer metadata" flag.

- Set a filter from the source select dialog with the SQL editor
- Click on "Test"
- All rows are returned, even if the filter is correct.

### Versions

All supported.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by troopa81** [comment]
> This happens when the trust layer metadata flag is set, we should unset it before performing the row count or the test is pointless.

It won't be enough because if you add a filtered layer and estimated metadata is True, you'll get a wrong estimation (you'll get an estimation of the size of the whole table).

I think we need to fix [featurecount](https://github.com/qgis/QGIS/blob/test_ci/src/providers/postgres/qgspostgresprovider.cpp#L3757) this way when estimated metadata is True :
- if we have a view or a sql where clause, we parse explain plan json output
- else we use reltuples::bigint from pg_class

@Djedouas is actually fixing the same thing for Oracle, he may take care of the issue if you're not working on.

**Comment by elpaso** [comment]
@troopa81 I'm not working on it, go ahead please.
