### ISSUE TITLE
Layer Styling: Fill color irregularly transparent/opaque

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#48610]
### What is the bug or the crash?

If a transparent fill color or opacity is defined my expectation would be that each feature should have the same color. But it hasn't. Is this how it's intended to be?

Fill color transparency:
![grafik](https://user-images.githubusercontent.com/67278094/169028864-4ea1edb9-cf68-42d4-8b54-44270e326ac5.png)

Opacity:
![grafik](https://user-images.githubusercontent.com/67278094/169029130-9e6c2968-44f5-4271-803b-b4795c4ff8b6.png)

No weird fill color definition has been applied - just a simple one:
![grafik](https://user-images.githubusercontent.com/67278094/169029643-1e9185e4-bb6e-4126-b1ca-c2eba4d439ff.png)

### Steps to reproduce the issue

Load the attached files (project, raster layer, object layer) into C:\temp\QGIS\featureRequest
Layers: [featureRequest.zip](https://github.com/qgis/QGIS/files/8715868/featureRequest.zip)
Project file: [project_transparent_bug.zip](https://github.com/qgis/QGIS/files/8715874/project_transparent_bug.zip)

### Versions

3.22.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by andreasneumann** [comment]
See this screenshot here

![image](https://user-images.githubusercontent.com/884476/169042346-3402c210-5dab-41fd-a08d-53cac3db44c5.png)

**Comment by andreasneumann** [comment]
I don't understand what you mean by "why the remaining 'white' part is meant to get darker as well?" As you can see in the above screenshots, white always stays white. Can you explain this statement?

As to user expectations: I think it is the opposite - users would be quite confused if they couldn't see geometries in the same layer shining through in case geometry overlap.

If you don't want stroke color to be affected, you could try blend modes (e.g. mode multiply) instead of transparency.
