### ISSUE TITLE
Can't import vector (line) layer into grass mapset

### ISSUE THREAD

**Issue by louisdoe** [qgis/QGIS#48691]
### What is the bug or the crash?

I have created a Line vector layer from elevation points, using the Contour plugin.
Now I'm trying to import it to the GRASS mapset with v.in.ogr.qgis, and I get the following error:

`v.in.ogr "input=/home/louisro/elevation points contours.shp" output=contours_bis snap=-1 min_area=0.0001 -o
Over-riding projection check
Check if OGR layer <elevation points contours> contains polygons...
Creating attribute table for layer <elevation points contours>...
DBMI-SQLite erreur de pilote :
Error in sqlite3_prepare():
near "index": syntax error
DBMI-SQLite erreur de pilote :
Error in sqlite3_prepare():
near "index": syntax error
￼Impossible de créer la table : 'create table contours_bis (cat integer, index integer, ELEV double precision, label varchar ( 254 ))'
Finished with error`

### Steps to reproduce the issue

create points layers with ELEV value
use Contour plugin to generate the contour lines from this layer
import the contour layer to GRASS with v.in.ogr.qgis

### Versions

QGIS version | 3.24.3-Tisler | QGIS code revision | cf22b74e01
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
Active Python plugins
openlayers_plugin | 2.0.0
MultipleLayerSelection | 2.0
VectorBender | 0.2.1
searchlayers | 3.0.7
contour | 2.0.10
cadastre | 1.14.2
planet_explorer | 2.2.0
shapetools | 3.4.4
autoSaver | 2.6
pointsamplingtool | 0.5.3
FreehandRasterGeoreferencer | 0.8.3
GeometryShapes | 0.7
AzimuthMeasurement | 0.2.2
quick_map_services | 0.19.29
db_manager | 0.1.20
MetaSearch | 0.3.6
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

**Comment by agiudiceandrea** [comment]
@louisdoe the issue is due to the use of a field named "index" since "index" is a reserved keyword in SQL.
Could you please specify how exactly are you "trying to import it to the GRASS mapset with v.in.ogr.qgis" and what is "v.in.ogr.qgis" (I only know the GRASS command v.in.ogr)?
Anyway it seems to me the underlying issue is a GRASS-GIS issue and nothing can be done in QGIS.
See also: 
- https://trac.osgeo.org/grass/ticket/578
- https://trac.osgeo.org/grass/ticket/1755
- https://trac.osgeo.org/grass/ticket/3071
- https://trac.osgeo.org/grass/ticket/3563
- https://gis.stackexchange.com/questions/331282/error-when-importing-shapefile-as-vector-layer-into-grass-gis
- https://grass.osgeo.org/grass81/manuals/v.in.ogr.html#:~:text=ERROR%20MESSAGES,driver)%2C%20see%20here
- https://github.com/OSGeo/grass/blob/8b4ccfb47f34da4178bb24df5649fdf0f3ff4857/db/drivers/sqlite/create_table.c#L31

**Comment by louisdoe** [comment]
Thanks for answering. 
I am basically following this procedure : https://www.lifeingis.com/generating-dem-from-contours-in-qgis/
So I am doing this to import the layer to the GRASS mapset : 
Plugin > Grass > Open Grass Tools
In “Module List” search choose v.in.ogr.qgis
In “Options” tab select the vector layer (Line type) containing the contours
Name the output map and also the name for the new location and click “RUN”.

The .shp file is binary when I try to open it in a text editor. In Qgis, in the attribute table or in the properties of this layer, I don't see any field named "index". Can you help further please ? 
Thanks
