### ISSUE TITLE
QGIS Unexpectedly Ended

### ISSUE THREAD

**Issue by alpineda11** [qgis/QGIS#49189]
### What is the bug or the crash?

Crash ID: [0c262dff226ff078b11c310dd9845d70ba6b7343](https://github.com/qgis/QGIS/search?q=0c262dff226ff078b11c310dd9845d70ba6b7343&type=Issues)

Stack Trace

QObject::thread :
QgsNetworkAccessManager::instance :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyDict_GetItemString :
PyArena_New :
PyRun_StringFlags :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QgsPresetSchemeColorRamp::clone :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QgsPresetSchemeColorRamp::clone :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

a few re-starts

### Versions

3.22.8 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
While doing what ?
Is there any steps to follow to reproduce this crash ?

**Comment by sophieoudry** [comment]
same issue here since yesterday ; crashing after using the research bar, or when trying to launch a treatment
crashes around 7 times per hour


Crash ID: [bf62299f065320b80c180062fc99b76755f3b318](https://github.com/qgis/QGIS/search?q=bf62299f065320b80c180062fc99b76755f3b318&type=Issues)


Stack Trace


PySet_Clear :
PySet_Clear :
PySet_Clear :
PySet_Clear :
PySet_Clear :
PySet_Clear :
PyType_GenericAlloc :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyTraceback_Add :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyType_GenericNew :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyType_GenericNew :
PyType_GenericNew :
PyObject_MakeTpCall :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by RBWMMAPMAN** [comment]
I'm getting the same issue when saving a project to a network drive or Microsoft One Drive.
