### ISSUE TITLE
Snapping on segment with vertex tool does not create topological points if geometry precision is enabled

### ISSUE THREAD

**Issue by komima** [qgis/QGIS#49311]
### What is the bug or the crash?

If geometry precision option is enabled for the currently edited layer, using vertex tool and snapping to a segment of another layers feature does not create a topological point on the other layers feature.

### Steps to reproduce the issue

- Open [vertextool.zip](https://github.com/qgis/QGIS/files/11673802/vertextool.zip) project file (open from - geopackage) 
- Enabled editing on all vector layers
- Use vertex tool on first layer, and snap a vertex on the segment of a feature on the second layer, observe that a topological vertex is created on the second layer
  - ![image](https://user-images.githubusercontent.com/58747243/178243343-ab071c79-80dd-43df-a923-162b6cf18275.png)
- Use vertex tool on first-mm-grid layer, and snap a vertex on the segment of a feature on the second-mm-grid layer, observe that a topological vertex is not created on the second-mm-grid layer (and the created vertex was snapped to specified precision)
  - ![image](https://user-images.githubusercontent.com/58747243/178243371-fe23245e-01f4-432f-9987-80bf588f2222.png)

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.0
Running against GDAL/OGR
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Snapping to a segment of another feature on the same layer creates a topological point on the other feature.

**Comment by komima** [comment]
I updated the attachment project, it indeed had precision missing from the first-mm-grid layer. With the current project bug is reproducable as described.

**Comment by troopa81** [comment]
According to the tooltip of geometry precision

> The geometry precision defines the maximum precision to of geometry coordinates that should be stored on this layer. A snap to grid algorithm will be applied on every geometry entering this layer, resulting in coordinates being rounded to multiples of this value. The operation is applied in this layer's coordinate reference system

So if the snapped point is for instance 2.589654, 5.96874 and you apply a geometry precision of 0.1, your point become 2.6,6.0 and is no longer on the segment it was originally snapped to. So, it looks like normal to me that as a consequence of the geometry precision, that the point is not on the edge and so no topological points has been added. No?

**Comment by ismogis** [comment]
@troopa81 Thanks for your clarification. I understand your point very well. It seems that we have interpreted differently how this feature should work. We have thought the snapped point should result in a topological point if needed regardless the precision. Just to be sure, does this mean that the topological points are not created hardly ever if the geometry precision is enabled in the layer to be edited?

**Comment by troopa81** [comment]
> Just to be sure, does this mean that the topological points are not created hardly ever if the geometry precision is enabled in the layer to be edited?

I think that it would depends if the snapped point  is still on the segment even with the geometry precision. For instance 2.0 would remains 2.0 even with a precision of 0.1 and so will still be considered on the segment and will generate a topological point. I even think there is an epsilon at play here when we check if point is on the line.

**Comment by LKajan** [comment]
> I think that it would depends if the snapped point is still on the segment even with the geometry precision. For instance 2.0 would remains 2.0 even with a precision of 0.1 and so will still be considered on the segment and will generate a topological point. I even think there is an epsilon at play here when we check if point is on the line.

Could you please clarify whether, in the following scenario, no topological point will be added? Consider a `Linestring(0.0 0.0, 2.0 0.001)` within a layer configured with a precision of 0.001. Now, suppose another `Linestring(1.0 0.0005, 1.0 1.0)` is added. This new linestring is snapped to the grid and becomes `Linestring(1.0 0.001, 1.0 1.0)`. Does this mean that no topological point will be added because the point `(1.0 0.001)` does not fall precisely on the line?  
I haven't had the chance to delve into all the implementation details, so I apologize if this question is not directly relevant.

**Comment by troopa81** [comment]
> I haven't had the chance to delve into all the implementation details, so I apologize if this question is not directly relevant.

The question is relevant because I have to test it and go through the code to understand what happens exactly. To sum up, forget my previous [comment](https://github.com/qgis/QGIS/issues/49311#issuecomment-1715992001), I was wrong

> Does this mean that no topological point will be added because the point (1.0 0.001) does not fall precisely on the line?

I tested with #53632  and yes the topological point is added. In your example: 

- When we create the second line (for instance by snapping the first one in the middle of its segment) QGIS try to add the snapped point (1.0 0.0005) on the first line [here](https://github.com/qgis/QGIS/blob/master/src/core/vector/qgsvectorlayereditutils.cpp#L765)
- You can see here that geometry precision is used as a tolerance on whether or not the point is ON the line.
- the snappedPoint and the real point on segment are identical except that snapped point has more precision (because geometry precision has not been applied yet). But as the geometry precision is used as tolerance, it is considered ON the line and added
- When the point is eventually added to the layer then the geometry precision is applied and (1.0 0.0005) becomes (1.0 0.001) for BOTH points so they share the same value and topology is respected.

I managed to produce your issue without modifications in #53632, but not with those modifications.

Here is the result I get with your use case. Topo points are added with respect to the geometry precision (and break the straight line as a result).

![topomap](https://github.com/qgis/QGIS/assets/14358135/b8ac9dde-6f24-4898-a57f-d811a109779c)



It's very hard to unit test this because I think double precision is different on CI and gonna produce different results. 

I propose to wait until #53632 is merged, or try it on your side If you can build the given code branch. Meanwhile, I propose to re-open this issue.
