### ISSUE TITLE
MetaSearch: GetCapability successfull but any search returns `Connection error: Opening and ending tag mismatch`

### ISSUE THREAD

**Issue by arkanoid87** [qgis/QGIS#49377]
### What is the bug or the crash?

MetaSearch plugin behaves badly with some CSW:
- GetCapability is successfull
- Search fails with `Connection error: Opening and ending tag mismatch: HR line 1 and body, line 1, column 975 (<string>, line 1)`

### Steps to reproduce the issue

Add European Space Agency Land Services CSW (https://land.copernicus.eu/global/web-services): 
http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw

- click `Service Info` button: success
- go to search tab
- click Search: `Connection error: Opening and ending tag mismatch: HR line 1 and body, line 1, column 975 (<string>, line 1)`

### Versions

3.22.4-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Ubuntu Linux 22.04 - x64

**Comment by agiudiceandrea** [comment]
@arkanoid87, the correct URL for the CSW server is https://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw (with HTTPS) and not http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw (with HTTP).
Any request to the HTTP URL is redirected by the server to the HTTPS URL.
Nevertheless, the GetCapabilities document reports the incorrect HTTP http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw URL.
This instructs the MetaSearch plugin to make the GetRecords HTTP POST request using the incorrect HTTP http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw URL, then the server responds with the redirection response code "302 Moved Temporarly" but then the redirection cannot be correctly followed.

It seems to me the issue is in the CSW service configuration, where the GetCapabilities document reports the incorrect HTTP http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw instead of the correct HTTPS https://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw URL.
So I think this issue should be fixed by the CSW server admins.

**Comment by arkanoid87** [comment]
It really seems to me that the issue here is MetaSearch not following relocations. It handles HTTP > HTTPS redirect correctly in the GetCapability action but fails in other operations.

Given HTTP is a stateless protocol, I'd say that this is a MetaSearch inconsistency, not service issue.

If the GetCapabilities response returns an HTTP address than when requested returns a relocation to HTTPS, it's up to the client to follow it.

**Comment by agiudiceandrea** [comment]
@arkanoid87, the MetaSearch plugin uses the very common OWSLib library to communicate with the server. While the OWSLib library is capable to follow the redirection of HTTP GET requests, but not the redirection of HTTP POST requests when the "302 Found / Moved Temporarily" response code is sent by the server instead of the appropriate "307 Temporary Redirect" (or "308 Permanent Redirect") response code: see for example https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307 and https://stackoverflow.com/questions/31620987/redirecting-http-post-requests-to-https-post-requests.
Anyway, why the server should advertise incorrect URLs in the GetCapabilities document?

**Comment by agiudiceandrea** [comment]
> @arkanoid87, the MetaSearch plugin uses the very common OWSLib library to communicate with the server. The OWSLib library is capable to follow the redirection of HTTP GET requests (for GetCapabilities), but not the redirection of HTTP POST requests (for GetRecords) when the "302 Found / Moved Temporarily" (with the incorrect Location parameter "https://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw") response code is sent by the server instead of the appropriate "307 Temporary Redirect" (or "308 Permanent Redirect") response code: see for example https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307 and https://stackoverflow.com/questions/31620987/redirecting-http-post-requests-to-https-post-requests. Anyway, why the CSW server should advertise incorrect URLs in the GetCapabilities document?

**Comment by arkanoid87** [comment]
So the issue here is HTTP 302 response for POST request, where HTTP 307 should be used instead.

It does not smell like a geonetwork configuration problem, but a reverse proxy problem.

**Comment by arkanoid87** [comment]
To answer specifically to your questio. Web client is not required to call location A before calling location B, so the response for GetCapabilities is irrelevant to the problem.

The remote server does return a redirect, just one inappropriate per POST?

**Comment by agiudiceandrea** [comment]
> Web client is not required to call location A before calling location B

For OGC (not Web) services like WMS/WFS/CSW, a compliant client needs to retrieve the Capabilities document in order to know the exact URL for each operation (like the GetRecords operation), then the client must adhere to the instructions reported in the Capabilities document and then it must send the proper request to the URL reported in the Capabilities document.

**Comment by arkanoid87** [comment]
Is it possible that they are using a reverse proxy that does not implement using 307 instead of 302 if incoming quest if POST?

**Comment by arkanoid87** [comment]
Actually, be digging into some history around this, it doesn't seem an error to return  a 302 instead of 307 to redirect a POST request.

https://stackoverflow.com/questions/2068418/whats-the-difference-between-a-302-and-a-307-redirect

It just seems that browser did it wrong initially and kept doing so forcing w3c to invent 307

**Comment by agiudiceandrea** [comment]
Anyway, the error reported in my system is: `Connection error: Document is XML, but not CSW-ish`.

**Comment by arkanoid87** [comment]
> Anyway, the error reported in my system is: `Connection error: Document is XML, but not CSW-ish`.

Im my context, no matter if I use HTTP or HTTPS
- http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw
- https://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw

"Service" tab works, "Search tabs" returns

```Connection error: Opening and ending tag mismatch: HR line 1 and body, line 1, column 975 (<string>, line 1)```

QGIS version | 3.22.4-Białowieża | QGIS code branch | Release 3.22

![Screenshot from 2022-07-18 12-57-28](https://user-images.githubusercontent.com/1446586/179497521-6666c7f4-8c6e-404a-9461-598980776454.png)
![Screenshot from 2022-07-18 12-57-48](https://user-images.githubusercontent.com/1446586/179497535-ba0e7e4c-a0fb-4a9e-bcbf-dfb484fe4fd3.png)

**Comment by arkanoid87** [comment]
The "default services" are all working correctly on my Qgis

Maybe is a Linux vs Windows issue? Or maybe a "default" vs "custom" issue?

Also is interesting how I get ```Connection error: Opening and ending tag mismatch: HR line 1 and body, line 1, column 975 (<string>, line 1)``` also for ```http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw```, this means my issue comes before that line

**Comment by agiudiceandrea** [comment]
I've reported via e-mail the `Connection error: Document is XML, but not CSW-ish` issue with http://land.copernicus.vgt.vito.be/geonetwork/srv/eng/csw (due to the incorrect http:// URLs in the Capabilities document) to the vgt.vito.be Help Desk.

The Help Desk has responded in a couple of days 
> Thanks for pointing out this problem to us.
>  
> Indeed, the URLs listed should have https:// and not http://
> This should be fixed now.

and has fixed the `Connection error: Document is XML, but not CSW-ish` issue.

The not yet fixed `Connection error: Opening and ending tag mismatch: HR line 1 and body, line 1, column 975 (<string>, line 1)` issue (whose cause has not yet been discovered) doesn't occur on my Windows system, so it could be an Ubuntu Linux 22.04 specific issue.

**Comment by arkanoid87** [comment]
anybody else can confirm that the issue is present on linux only? I'd like to exclude the possibility the problem exists on just my machine.

**Comment by kikislater** [comment]
It works for me on 3.26.1 under Manjaro Linux : 

![image](https://user-images.githubusercontent.com/13238064/180614876-bdda1230-24be-419d-9088-4a5295ad4388.png)


![image](https://user-images.githubusercontent.com/13238064/180614584-609ccd1d-ae2f-4963-809c-db8cf9528b11.png)

![image](https://user-images.githubusercontent.com/13238064/180614765-c7213a76-a780-4a3c-809b-6e8b46b889fd.png)

![image](https://user-images.githubusercontent.com/13238064/180614864-988b6c57-3f49-4d21-b729-126959266bb7.png)


But I have others issues with csw : Like here, it seems to be a server side configuration problem. These ssl errors are annoying, I saw some reverse proxy with geonetwork and wrong configuration (redirecting to localhost or local domain etc) .... Another nightmare is csw-t supposedly supported on some platform but in fact it doesn't work

**Comment by arkanoid87** [comment]
Thanks, I'll try updating to 3.26ish
