### ISSUE TITLE
Native CLIP function

### ISSUE THREAD

**Issue by Jrm-Bghn** [qgis/QGIS#49456]
### What is the bug or the crash?

With QGIS  version over 3.16 (e.g. 3.22.5 or 3.26)

When clipping vector points layer with another vector layer (e.g. polygon vector layer) and exporting the result in *.shp in a folder, the log reports a bug/crash: (Erreur OGR : Attempt to write non-point (MULTIPOINT) geometry to point shapefile).

Bug not reproduced with temporrary layer as  output or with other formats as output (e.g geojson, and so on).

### Steps to reproduce the issue

1. Load two vector layers. One with points and the other with a polygon.
2.  Use the native function for clipping (CLIP).
3.  Select points as first layer and polygno as the overlapping one.
4. Define the output for clipping as a *.shp in a folder.
5. Run the native function.
6. The log reports (Erreur OGR : Attempt to write non-point (MULTIPOINT) geometry to point shapefile).

### Versions

3.22.5 or 3.26 (maybe all version over 3.16.11)

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Jrm-Bghn, could you please attach sample layers with which the issue occurs?

**Comment by Jrm-Bghn** [comment]
@agiudiceandrea 
![image](https://user-images.githubusercontent.com/39045909/180637462-30376e4d-e284-4780-8e81-2ba03bed3def.png)
![image](https://user-images.githubusercontent.com/39045909/180637493-1cd21312-8605-4e84-b278-d26bb6112e7d.png)
[Samples.zip](https://github.com/qgis/QGIS/files/9175343/Samples.zip)

**Comment by agiudiceandrea** [comment]
Confirmed on Windows with QGIS 3.26.1 and 3.22.9.
The issue does not occur with QGIS 3.22.0 and previous versions (it is a regression).
It seems to me this issue may be related to https://github.com/qgis/QGIS/pull/46418.

**Comment by agiudiceandrea** [comment]
> So it is a regression.

@Pedro-Murteira, please also add the `Regression` label.

It seems to me the issue is due to the fact that
- after https://github.com/qgis/QGIS/pull/46418, for an input Point (Point) layer an output Point (Point) layer is created; before https://github.com/qgis/QGIS/pull/46418, for an input Point (Point) layer an output Point (MultiPoint) layer was created
- the Clip algorithm uses the `QgsOverlayUtils::sanitizeIntersectionResult` function https://github.com/qgis/QGIS/blob/e593fde4dc2a35a28a0ca95c0490a0414847c17d/src/analysis/processing/qgsalgorithmclip.cpp#L211-L212 which always returns a multi-part geometry https://github.com/qgis/QGIS/blob/e593fde4dc2a35a28a0ca95c0490a0414847c17d/src/analysis/processing/qgsoverlayutils.cpp#L48-L50 converting the input clipped Point geometries to MultiPoint geometries which cannot be written to a Point (Point) Shapefile layer as created after https://github.com/qgis/QGIS/pull/46418 (while before https://github.com/qgis/QGIS/pull/46418 a Point (MultiPoint) layer was created in which the MultiPoint geometries could be written)
