### ISSUE TITLE
Not able to set scale parameter for SAGA Topographic Position Index

### ISSUE THREAD

**Issue by drdebivre** [qgis/QGIS#49508]
### What is the bug or the crash?

This bug seems related to the implementation of the SAGA TPI tool in QGIS. In the dialog window it is not possible to change the 'scale parameter'. Upon running the plugin, the log shows that the default values of 0;100 are used.

### Steps to reproduce the issue

1. Go to SAGA Topographic Position Index (TPI)

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
processing_r
3.1.1
TerrainShading
0.9.3
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
The SAGA provider is kinda deprecated with the shipped version of SAGA in OSGeo4W (you should have a warning in alg dialog).
See https://github.com/qgis/QGIS-Enhancement-Proposals/issues/230 for more detail.

Please try https://plugins.qgis.org/plugins/processing_saga_nextgen/ and report the issue here: https://github.com/north-road/qgis-processing-saga-nextgen/issues if you still have an issue.
