### ISSUE TITLE
App is absurdly large (macOS)

### ISSUE THREAD

**Issue by bgulanowski** [qgis/QGIS#49584]
### Feature description

This is more general feedback, but didn't seem correct to put in as a bug.

Your app on Mac is enormous: nearly 3GB. It has enlarged by an entire gigabyte since version 3.10.

Do you need everything that is inside the executable? There is an 800MB folder with what looks like the entire source code for Python. There is another folder that is 1GB in size, called "proj". What is that for?

Consider making these folders optional.

**Comment by andreasneumann** [comment]
@bgulanowski - the proj folder contains a lot of large grid shift files from several countries to do coordinate transformations taking into account datum transformations. You could delete the grid shift files from countries you don't need.

Can't comment about the Python folder.

The MSI on Windows is also quite large due to these reasons.

Ideally, the grid shift files could be installed "on demand" - whenever the user tries to use such a transformation requiring grid shift files. Some users do not reproject at all and remain in one local coordinate system for all of their work.

**Comment by gioman** [comment]
Should we move this to the repository that is about the macOS installer?

**Comment by DelazJ** [comment]
@gioman I'm not sure this is a macOS only issue. The Windows MSI installer is also large, for the same reasons: they embed some huge dependencies...

**Comment by gioman** [comment]
> @gioman I'm not sure this is a macOS only issue. The Windows MSI installer is also large, for the same reasons: they embed some huge dependencies...

@DelazJ maybe the Windows one is not so large, anyway it because of the datum transformation grids (mainly, I think) and it is a packaging "issue" (not an issue for me) not really an issue with QGIS code base, which this tracker is about.

**Comment by DelazJ** [comment]
You are right indeed; it's more a packaging matter than QGIS'

**Comment by andreasneumann** [comment]
@gioman and @DelazJ - packaging is also the responsibility of the QGIS community. And I think it affects all OS.

I am disappointed that QGIS turns into a "bloatware" like ESRI or Autocad did some years ago - and I think we (the community) should invest into a more flexible packaging system.

For proj and the grid shift files we should collaborate with the proj team to find a better solution.

The FOSS4G conference in Firenze might be a good opportunity to discuss things across projects.

**Comment by DelazJ** [comment]
@andreasneumann have you got opportunity to discuss this issue with other projects at foss4g?
