### ISSUE TITLE
ArcGIS server layer does not appear on export or prints

### ISSUE THREAD

**Issue by HardyWeinberg** [qgis/QGIS#49933]
### What is the bug or the crash?

This bug appeared with the last LTR issue (3.22.10). I have a raster ArcGIS server layer that displays correctly on the main app and the Layout Manager but appears totally blank when I export it (PDF, PNG, prints...).

### Steps to reproduce the issue

1. Get the layer at https://lacarto.ledepartement82.fr/carte/rest/services/Fond_de_Plan/Cadastre_Napoleonien/MapServer
2. Open layout manager and add a map
3. export it in jpg, png, pdf or anything else. 

### Versions

Version de QGIS | 3.22.10-Białowieża | Révision du code | 6a63fd37
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.5.1
Version de Proj | 9.0.1
Version de la base de données du registre EPSG | v10.064 (2022-05-19)
Version de GEOS | 3.10.3-CAPI-1.16.1
Version de SQLite | 3.38.1
Version de PDAL | 2.4.2
Version du client PostgreSQL | 14.3
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
profiletool | 4.2.2
Qgis2threejs | 2.7.1
StreetView | 3.2
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Version de QGIS
3.22.10-Białowieża
Révision du code
[6a63fd37](https://github.com/qgis/QGIS/commit/6a63fd37)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.5.1
Version de Proj
9.0.1
Version de la base de données du registre EPSG
v10.064 (2022-05-19)
Version de GEOS
3.10.3-CAPI-1.16.1
Version de SQLite
3.38.1
Version de PDAL
2.4.2
Version du client PostgreSQL
14.3
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
profiletool
4.2.2
Qgis2threejs
2.7.1
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ar-siddiqui** [comment]
I was able to recreate and debug the issue. 

The issue is with the server, not QGIS. Let me explain.

The Server is not responding when you zoom in a lot. You can confirm this by zooming in too much in your QGIS.
QGIS would send a request like this but would get a `404` response.
[https://lacarto.ledepartement82.fr/carte/rest/services/Fond_de_Plan/Cadastre_Napoleonien/MapServer/tile/12/1432/1323](https://lacarto.ledepartement82.fr/carte/rest/services/Fond_de_Plan/Cadastre_Napoleonien/MapServer/tile/12/1432/1323
)

Now the reason you see the image in layout/canvas but not in the exported PDF etc. is because layout/canvas has a zoomed-out image, while during export QGIS would try to get high quality images and then stitch them together but your server is failing to respond to those zoomed in requests. 

### Solution
Reduce your print DPI and QGIS will send requests for zoomed-out images. 
![image](https://user-images.githubusercontent.com/53625184/186274489-f875bbd2-d632-46d6-8854-3180be5aa476.png)

![image](https://user-images.githubusercontent.com/53625184/186274514-69fb5c3a-ca17-449d-96b7-9c37f8f83549.png)

This is not a QGIS bug IMO.

The ArcGIS servers are notorious for having scale-based layer visibility turned on. Make sure that is not the case.

**Comment by nicogodet** [comment]
@HardyWeinberg Can you confirm ?

**Comment by HardyWeinberg** [comment]
Thank you very much for your help. I can confirm that @ar-siddiqui was right and the bug is related to the server and not QGIS.

**Comment by nicogodet** [comment]
Let's close
