### ISSUE TITLE
Layout with 3d map export hangs indefinitely (3.16 -> 3.26 regression)

### ISSUE THREAD

**Issue by AaronJohnsonSpambox** [qgis/QGIS#50067]
### What is the bug or the crash?

I created a simple print layout containing a 3d map.  In 3.16 I can successfully export this as an image and it takes a few seconds.  On 3.26, it never seems to terminate.  I have another more complicated project that takes a minute or so to export the image in 3.16, but in 3.26 I've let it run for several hours and it doesn't finish.

Zipped QGIS project file
[3d.zip](https://github.com/qgis/QGIS/files/9478061/3d.zip)

### Steps to reproduce the issue

Add a DEM raster layer to the project
Create a new 3d map view (set the terrain type to DEM, and elevation to the raster layer you added).  Set the camera as needed
Create a new print layout, adding a map item, and a 3d map item.  Set the 3d map item's view scene and camera from the view
Export the print layout as an image.  It finishes successfullly in 3.16, but never in 3.26

### Versions

QGIS version
3.26.2-Buenos Aires
QGIS code revision
feec3d3b12f
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.1
MBTiles2img
0.4
profiletool
4.2.2
qchainage
3.0.1
ReverseFlow
0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by AaronJohnsonSpambox** [comment]
Results of more testing:
3.22.10 - export is successful
3.24.3 - export never finishes

So it seems to have broken between 3.22 and 3.24

**Comment by nyalldawson** [comment]
Please try with 3.26.3 - there's been relevant changes in that patch release

**Comment by AaronJohnsonSpambox** [comment]
It still hangs with: 3.26.3-Buenos Aires

**Comment by agiudiceandrea** [comment]
@AaronJohnsonSpambox could you please try again using actually a new QGIS user profile? (judging from the Active Python plugins list you didn't). Could you also share the raster layer used in the provided project?

**Comment by AaronJohnsonSpambox** [comment]
This is on 3.26.3 with a clean profile on Windows 11.  My original DEM was about 1 GB, but was able to reduce it in size to about 4 MB and still reproduce the problem with the latest release build.

[project.zip](https://github.com/qgis/QGIS/files/9556878/project.zip)

Simply unzip and open the project, open the _Bug_ print layout and try to "Export as Image".

Version information on clean 3.26.3 profile:

QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdada
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

**Comment by saberraz** [comment]
Thanks, I can replicate your issue with both QGIS 3.26 and 3.27. I have added Regression, so it will be visited during the bug fixing in coming days/weeks.

**Comment by agiudiceandrea** [comment]
It seems the issue occurs on Windows with QGIS 3.24 and 3.26, while it doesn't occur with QGIS 3.22 and 3.20 and previous versions.

**Comment by drobbins2014** [comment]
I have encountered this issue, starting in QGIS 3.24 and continuing up to 3.28. I have investigated to the point of seeing what I believe is an explanation for why it is occurring -- it appears to be a conflict around the use of the Qt thread pool.

Beginning in 3.24, QgsLayoutItem3DMap::draw() creates a new instance of QgsOffscreen3DEngine, deleting the one that was previously there (which was used to draw the on-screen preview). Prior to 3.24, it simply used the one that was already there. (I presume that this change resolved an issue with rendering maps for export).

Within QgsOffscreen3DEngine, there is an instance of Qt3DCore::QChangeArbiter (a part of Qt3DCore::QAspectEngine). The constructor and destructor of QChangeArbiter require the use of *every* thread in the Qt thread pool.

When QgsLayoutItem3DMap::draw() is called to export (e.g., to an image or PDF), the export action (e.g., QgsLayoutDesignerDialog::exportToRaster()) has activated a QgsProxyProgressTask in the Qt thread pool.

Because the QgsProxyProgressTask occupies one of the threads in the thread pool, the QChangeArbiter constructor or destructor is unable to complete its work. Those of its threads that were able to run remain active, waiting for the last thread to finish, but that last thread is unable to run due to the presence of the active QgsProxyProgressTask. Thus we see the QGIS process sitting there consuming mass quantities of CPU time but making no progress.

In a stack trace of the application, you can see one of the pooled threads running QgsProxyProgressTask::run() and all other threads running Qt3DCore::SyncTaskRunnable::run(). There is one Qt3DCore::SyncTaskRunnable::run() task waiting to be run in a thread, and the others will not exit until that last one has completed, which it never will because QgsProxyProgressTask will not exit until the rendering has been completed. Which it never will.

I have nowhere near sufficient understanding of the QGIS application or the Qt library to propose a solution for this issue. For me, I can continue to use 3.22.

**Comment by nyalldawson** [comment]
@drobbins2014 thanks for the detailed research and thorough reporting! You've helped me greatly in fixing this :+1:
