### ISSUE TITLE
Delimited Text files will not load anymore

### ISSUE THREAD

**Issue by Emilie21** [qgis/QGIS#50362]
### What is the bug or the crash?

So, I have been trying to put delimited text -csv files into QGIS. I crashed on me and since then, they wont work. I'm using comma, I'm using the right SRS and the encoding is all correct. Nothing is wrong I'm sure of that, they simply wont load anymore as a points file. I uninstalled the software and reinstalled it, checked it was a version still in circulation and ok. It is. So no clue what's going on, my best guess is that when it crashed it got bugged maybe? I've also checked my CSV on other devices with the software and it works fine. I just can't seem to get it to work anymore on my computer. The attribute table still opens on my device once ive brought in the data. And it looks right I just cannot see or do anything with the data.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/114464588/192441684-bdc47aeb-df41-4ec7-8947-808deef56a4d.png)
![image](https://user-images.githubusercontent.com/114464588/192441751-1264a094-777a-4d5e-bd44-d25eb5117c4f.png)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Can you share the CSV?

**Comment by agiudiceandrea** [comment]
@Emilie21, you have checked the "DMS coordinates" option, but it seems to me the coordinates are not DMS (Degrees, Minutes, Seconds). Could you try again without checking the "DMS coordinates" option?
Please see https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/opening_data.html#geometry-definition.

**Comment by Emilie21** [comment]
@agiudiceandrea, I've just unchecked the DMS coordinates and that seems to have done the trick so thank you very much, I don't understand why that has worked though? What exactly does that function do? Just so I understand in future when to and not to use it.

**Comment by agiudiceandrea** [comment]
@Emilie21, as pointed out in my previous comment, you can find the meaning of each option of the Delimited Text import dialog window in the user manual at https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/opening_data.html#importing-a-delimited-text-file and of the DMS option in particular at https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/opening_data.html#geometry-definition:

>  If the coordinates are defined as degrees/minutes/seconds, activate the DMS coordinates checkbox

Since, in your case, the coordinates are not in degrees minutes seconds format, you need to not activate the "DMS coordinates" checkbox.
