### ISSUE TITLE
light text color for cascade menù for nightmapping theme

### ISSUE THREAD

**Issue by Beschito** [qgis/QGIS#50674]
### Feature description

With the new version 3.22.12-Białowieża, for the theme nightmapping, the colors of the texts in the cascade menù of QGIS are black and quite invisible right now. The same problem occurred also in the log messages tabs where the time of the infos logged are black.
It would be better to return to the colors o the 3.22.11 version. This guarantee a very better and readable view.
![log message](https://user-images.githubusercontent.com/49171940/197550197-2e678002-2484-462a-be70-072feb22dc5f.PNG)
![qgis menù](https://user-images.githubusercontent.com/49171940/197550200-510bbcd5-4843-406a-9b68-45152320dfab.PNG)

**Comment by edurojasr** [comment]
Hi don't know if this is a feature request, form me its more like a bug since the previews version have a light text color for drop down menu. 

![Screenshot from 2022-10-24 22-13-40](https://user-images.githubusercontent.com/35645729/197680935-3f51f036-2962-445e-b0da-120e4e3f06a9.png)

for me this should be a bug since you can't read the text in the menus

**Comment by Beschito** [comment]
Yes i think like you but i was not sure that this wasn't a new choice of the development team. Actually it is impossible to read the texts... How can i move  it in the bug session?

**Comment by nirvn** [comment]
I'm on it.

**Comment by nirvn** [comment]
(Later this week when free time emerges :) )

**Comment by Beschito** [comment]
Ok, thank you! ;)
