### ISSUE TITLE
Option to export SSL keys to file

### ISSUE THREAD

**Issue by velle** [qgis/QGIS#51164]
### Feature description

Allow the user to run QGIS such that QGIS exports SSL keys to a file. With such a key file, it is possible to decrypt any SSL encrypted, including HTTPS. That way one can actually use Wireshark to study for instance WFS messages and debug various issues. 

### Additional context

This article describes how to decrypt SSL/HTTPS in Wireshark. https://www.comparitech.com/net-admin/decrypt-ssl-with-wireshark/. Supposedly many applications, on both Unix and Windows, check for an environment variable called "SSLKEYLOGFILE", and if one is set, it will write SSL keys to this file. Wireshark can then be set up to read the necessary keys from this file. 

I have not found a way to export SSL keys from QGIS.

**Comment by agiudiceandrea** [comment]
Hi @velle, I think this feature requires an upstream Qt library feature implementation, since AFAIK the QGIS networking depends on Qt.
There is the Qt ticket "Support SSLKEYLOGFILE variable for debugging connections over SSL/TLS" https://bugreports.qt.io/browse/QTBUG-64310 which was closed as "Won't Do".

**Comment by luipir** [comment]
hre is the hugly code https://github.com/planetfederal/win-os-pki-export/blob/master/exportrsa/exportrsa/exportrsa.cpp
