### ISSUE TITLE
Invisible Features When Saving Large GeoPackage

### ISSUE THREAD

**Issue by anthony-scarth** [qgis/QGIS#51188]
### What is the bug or the crash?

When exporting a layer as a GeoPackage, some features of the resulting dataset will become invisible.

The new dataset will retain attributes of the "missing" features. The geometries must also be present in the file (just invisible) as re-saving the new layer to a different format will then correctly display the features.

The affected features are non random (the same ones are invisible every time), but can change if features are selected and then saved (so it's unrelated to corrupted geometries or other things I can think of).

This affects both Windows builds of 3.28.1 and 3.22._13_, and the latest Linux Flatpak. However, QGIS 3.22.13 built for Ubuntu 22.04 (not ubuntu-gis) is unaffected. Windows build for 3.22._12_ is working correctly

I am aware that this is unlikely to be a problem with QGIS code itself, but rather a bundled library that has been updated between 3.22.12 and 3.22.13. 

- only occurs with GeoPackage; saving as Shapefile seems to be fine (other formats untested)
- can happen when exporting all features, selected features, or as the output of Processing Tools
- seems to happen reliably on any dataset with many features (>100,000)
- sometimes the invisible features will not manifest until zooming in.

### Steps to reproduce the issue

1. Obtain some vector dataset with ~100,000+ features 
(e.g. This crop map of West Yorkshire, England https://environment.data.gov.uk/DefraDataDownload/?mapService=RPA/CropMapOfEngland2020WYR&mode=spatial)
2. Load into QGIS
3. Rick click layer -> Export -> Save Features As...
4. Ensure Format is GeoPackage and save to a file.
5. Resulting dataset should appear to contain missing features

### Versions

**Broken build 3.22.13**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.22.13-Białowieża | QGIS code revision | 02ff117c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.0
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009

</body></html>

**Working build 3.22.12**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.22.12-Białowieża | QGIS code revision | b8534cb1
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
GeoPackage is written by the GDAL/OGR data provider, can you check if this issue is related to a particular GDAL version?

There is also a windows package build by our CI workflow that can be tested, I'm not sure which GDAL version it uses:
 https://github.com/qgis/QGIS/actions/runs/3681704189/ (see zip packages at the end of that page).

**Comment by agiudiceandrea** [comment]
I can confirm the described behaviour.

Exporting the layer using QGIS 3.28.1 or QGIS 3.22.13 (both with GDAL 3.6.0) the exported GPKG layer does contain the hidden geometries which are not visibile neither with QGIS 3.28.1 or QGIS 3.22.13 (both with GDAL 3.6.0) or QGIS 3.22.10 (with GDAL 3.5.1). The exported GPKG layer is about 139'452 KB large.

Exporting the layer using QGIS 3.22.10 (with GDAL 3.5.1) the exported GPKG layer doesn't contain the hidden geometries and all the geometries are visible using QGIS 3.28.1 or QGIS 3.22.13 (both with GDAL 3.6.0) or QGIS 3.22.10 (with GDAL 3.5.1). The exported GPKG layer is 140'828 KB large.

The same behaviour occur using directly ogr2ogr: with GDAL 3.6.0 the exported layer (138'756 KB) has hidden geometries, while with GDAL 3.5.1 (140'612 KB) the exported doesn't have hidden features.

So it seems to me the issue is related to the GDAL/OGR version. Probably @rouault knows if this is a known GDAL/OGR issue.

**Comment by anthony-scarth** [comment]
Thank you, @agiudiceandrea  for doing that investigation. I was attempting to build QGIS with the different GDAL versions but that has saved me some time. I did also note that the change-log for GDAL 3.6 notes several changes to the GPKG driver so it possible the problem has been introduced there.

**Comment by rouault** [comment]
Yes, confirmed as a GDAL 3.6.0 bug related to the parallel RTree building optimization. Setting OGR_GPKG_ALLOW_THREADED_RTREE=NO environment variable works around the issue. Investigating

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/6911 . We'll probably do a 3.6.1 release very soon: https://lists.osgeo.org/pipermail/gdal-dev/2022-December/056621.html

**Comment by agiudiceandrea** [comment]
The patch has been integrated in the new *gdal* 3.6.0-4 OSGeo4W packages (waiting for GDAL 3.6.1). Updating the *gdal* packages to 3.6.0-4 should fix the issue.
https://trac.osgeo.org/osgeo4w/ticket/771
https://github.com/jef-n/OSGeo4W/commit/697c608bf2d4a52f3ffb9c6f8f5c82b12aa33e8c
