### ISSUE TITLE
Data loss when using the "split parts" tool

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#51321]
### What is the bug or the crash?

When using the "split parts" tool on a part of a multipart polygon, another untouched part disappears completely.

The layer/polygon has no errors.

https://user-images.githubusercontent.com/1951107/209822246-c6336925-1073-4685-b9fa-dea63d0300b4.mp4

### Steps to reproduce the issue

Load the attached layer

Toggle editing and try split one of the parts.

### Versions

Latest 3.22 and 3.28 on Windows (untested other platforms but I will).

This is a regression as in older versions (i.e. 3.10) the bug is not present.

[teste.zip](https://github.com/qgis/QGIS/files/10314514/teste.zip)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Got a report it happens also on Linux. Apparently does not happen if the datasource is a shapefile (the attached sample is GPKG).

**Comment by uclaros** [comment]
Yikes, that's quite bad!
I can replicate this on 3.14.15 and also on shapefiles

**Comment by agiudiceandrea** [comment]
I can confirm the issue with a memory layer on Windows using QGIS 3.28, 3.22, 3.18, 3.16. The issue doesn't occur using QGIS 3.10.

**Comment by roya0045** [comment]
Not sure if the error comes from geos or https://github.com/qgis/QGIS/blob/d13a7b72787b5557860a38cdceda482a9dd4831e/src/core/vector/qgsvectorlayereditutils.cpp#L534-L565

**Comment by YoannQDQ** [comment]
This implementation clearly does not work. But the previous one created an invalid geometry, and prevented further split / manipulation on the new geometry. (https://github.com/qgis/QGIS/issues/50348)

Actually, any MultiPolygon split in the middle of one of its parts would be invalid, since a polygon with 2 adjacent parts is an invalid geometry for GEOS.

There has been discussion to ditch the split part tool altogether https://github.com/qgis/QGIS/issues/20853#issuecomment-495846012
