### ISSUE TITLE
Blank project when opened

### ISSUE THREAD

**Issue by ctmorrison** [qgis/QGIS#51439]
### What is the bug or the crash?

I created a project, saved it and later when I open it, the entire project screen is blank.  I also used QuickOSM to identify roadways.

I'm using MacOS 13.1 on an M2 MacBook Air.

### Steps to reproduce the issue

Using OpenStreetMap to find my home location

Added streets via QuickOSM.

Saved project.

Opened project--blank screen.

### Versions

There is no About in the Help menu and the About in the QGIS menu is grayed out.

However, in the Finder it shows version 3.28.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by ctmorrison** [comment]
I think it has something to do in part with not saving layers.  I saved those and also learned a bit about the Zoom Full button at the top.  That seems to have resolved my issues.

**Comment by nicogodet** [comment]
If you consider this issue fixed or not planned, feel free to close it

**Comment by ideogram** [comment]
I would like to request if this issue could be re-opened or if @ctmorrison could explain how he managed to solve it. I run into the exact same issue, on an M1 mac using QuickOSM.

I tried zooming, panning.... nothing helps to see anything at all, the project is empty.

I suspect that nothing had actually been really saved at all, because:

1. The saved QGZ fileis really small (52kb) whereas the exported PDF is 700kb.
2. When I turn on "Show Feature Count" in a layer, the amount of features is equal to `0`.

So, either _I_ save in the wrong way or _something_ gets saved in the wrong way. (?)

(Fortunately, I have saved my queries as presets, so I can quickly re-create the map.)

**Comment by ideogram** [comment]
### Solution

For anybody running into the same issue: the layers imported by QuickOSM are _scratch_ layers. That means they will be disregarded after closing QGis.  ( Scratch layers are indicated by an icon that looks like a small white IC to the right of the layer name. )

**To avoid losing your work, every layer must be made permanent by right-clicking on the name of the layer in the layers-panel, select 'Make permanent...' and following along from there. Repeat for every layer. **

I find this very counter-intuitive for beginners like me, but this is something that should be dealt with in the Quick-OSM plugin, not QGis itself.

(Disclaimer: at the time of writing, I only have spend a couple of hours in the QGis, so my information might not be 100% accurate or correctly worded.)

**Comment by nicogodet** [comment]
> this is something that should be dealt with in the Quick-OSM plugin, not QGis itself.

100%
And QGIS warns you this is memory layers, there a message box when closing QGIS and memory icon in layer tree.

**Comment by ideogram** [comment]
Yes, you are right. I completely missed that alert. But I did not recognize the IC as a 'memory icon' either.
