### ISSUE TITLE
Float fields created in ArcGIS are converted into Real 12, 11 - Precision is too high

### ISSUE THREAD

**Issue by epc-aac** [qgis/QGIS#51849]
### What is the bug or the crash?

![float_vs_real](https://user-images.githubusercontent.com/112855481/218718528-a3ac43c5-09a8-46d6-a157-856f8ef22e24.png)

Float fields of a shapefile created with other platform / software are converted into real(12,11). You can see the values correctly but if you try to overwrite them you can only add values from -9,99999999999 to 9,99999999999.

![float_vs_real_attribute_table](https://user-images.githubusercontent.com/112855481/218723637-57c494ff-b945-49c7-ab8d-53d9fe5e9213.png)

### Steps to reproduce the issue

1. Add a vector file with fields defined as 'Float'
2. Start editing
3. Try to insert a 2 digit number, it is not possible

### Versions

3.22.8-Białowieża
3.28.2-Firenze

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Can you add a test shapefile please?

Also, can you attach a snapshot of your language settings from 

![immagine](https://user-images.githubusercontent.com/142164/218726979-1670223b-9117-4cb6-9cc0-acde2eac373c.png)

**Comment by epc-aac** [comment]
Yes, of course!

![options](https://user-images.githubusercontent.com/112855481/218730198-107b1fbd-aa4e-4946-853a-92129052f8a3.png)

[Test.zip](https://github.com/qgis/QGIS/files/10732282/Test.zip)

**Comment by elpaso** [comment]
@epc-aac your shapefile does not contain any field (missing dbf?).

**Comment by epc-aac** [comment]
Yes, sorry, you can telll this is my first report 
[Test.zip](https://github.com/qgis/QGIS/files/10732387/Test.zip)

**Comment by elpaso** [comment]
Ok, this is what happens (to my understanding):

GDAL reports width 13 and precision 11.

```
Carr_PK_I: Real (13.11)
```

But, according to https://issues.qgis.org/issues/11755 the width includes the decimal separator (and the minus sign)  , so we reduce the width by 1 to accomodate QGIS field model (based on PostGIS where the decimal point is not included)

This was discussed before: https://github.com/qgis/QGIS/issues/23127

I'm not sure if there is something we can do here because there is not an exact solution to the problem.

IIRC an application can ignore the width and precision in a DBF, in your test file for instance there is
```
Tram_IMD (Real) = 6000.00000000000
```
which seems out of bounds to me.

See also https://trac.osgeo.org/gdal/ticket/6960

**Comment by elpaso** [comment]
Note that we might enhance GDAL to handle different conventions when reporting width and precision, this would make it easier to access these informations from QGIS and other applications consistently.

**Comment by epc-aac** [comment]
Ok, thank you! I get an idea of the issue. 

The thing is that someone created shapefile templates for a project and we can't handle them with QGIS. I've used 'refactorfields', so I've changed the template. Hope there will be no problem this time because it is not a final delivery.

**Comment by elpaso** [comment]
For reference: https://github.com/OSGeo/gdal/pull/7264
