### ISSUE TITLE
Error in opening qgz files

### ISSUE THREAD

**Issue by medhaslr** [qgis/QGIS#51974]
### What is the bug or the crash?

Not able to access old QGZ files
2023-02-22T10:30:10     WARNING    Error opening zip archive

### Steps to reproduce the issue

![error qgz]

### Versions

Version 3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Houska1** [comment]
Some suggested additional information to help triage this better. Right now it's hard to tell if this is some random corruption on your system or indeed some bug needing eradicating.

1. Does this happen to one old .qgz (which may be corrupt) or a whole slew of them in a newly installed QGIS version upgrade (which might indicate some sort of installation issue in your setup)?
2. Can you use a .zip utility (e.g. 7-Zip on Windows) to open the .qgz? It should be a normal zip archive, with a project .qgs file and likely other sidecar files. If it can't be opened with a zip utility, it has somehow become corrupt, and QGIS can't really help
3. Can you extract the contents of the .qgz zip file into the same directory, temporarily, and open the .qgs file instead?

**Comment by roya0045** [comment]
I'm having the same issues with mingw builds, though it's intermittent. Alternating the method of loading : open the project though the menu as a recent project or using the `open...` might work, otherwise drag & drop might also work. Sometimes it takes a few repetition. 

Though I never had this issue with version installed properly.
