### ISSUE TITLE
OMBB BUG

### ISSUE THREAD

**Issue by SaraGISengineer** [qgis/QGIS#52074]
### What is the bug or the crash?

mauvaise orientation des polygones lors du lancement de l'algorithme OMBB. ce ci est lié à la version QGIS 3.22 
L'algorithme fonctionne parfaitement sur les version précédentes 
Voici un exemple 
![CaptureOMBBBUG](https://user-images.githubusercontent.com/126791588/222453448-30dbb55e-b938-4655-821d-2d2fb57923dd.PNG)

### Steps to reproduce the issue

TOOLBOX => OMBB 
polygone réorienté par rotation 

### Versions

QGIS 3.22.2

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Might be clearer IF 'OMBB' was replace by the full 'Oriented Minimal Bounding Box'

**Comment by agiudiceandrea** [comment]
@SaraGISengineer please
- clarify what processing algorithm you are using (by its English full name or its id)
- provide the processing algorithm parameters and a sample layer with which the issue occurs
- clarify the expected result vs the actual result of the processing algorithm and what is the previous version with which the algorithm has the expected behaviour
- try if the issue occurs using the latest currently supported QGIS version
