### ISSUE TITLE
Legend problem afther update to 3.30.0-1

### ISSUE THREAD

**Issue by NvBgm** [qgis/QGIS#52134]
### What is the bug or the crash?

Ather update QGis to 3.30.0-1 i lost my legend in atlas layouts.
Also filtering inside map is not working.
![Schermafbeelding 2023-03-07 210223](https://user-images.githubusercontent.com/8125819/223539413-6e5e41fc-8be6-463a-bee0-8a8b174e327b.png)

### Steps to reproduce the issue

Atlas layouts

### Versions

QGIS-versie
3.30.0-'s-Hertogenbosch
QGIS code revisie
f186b8efe0e
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.6.2
PROJ versie
9.1.1
EPSG-register databaseversie
v10.076 (2022-08-31)
GEOS versie
3.11.1-CAPI-1.17.1
SQLite versie
3.39.4
PDAL versie
2.4.3
PostgreSQL client versie
unknown
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
bfvw_tools
1.3
changeDataSource
3.1
export_to_sql_server
0.4
lizmap
3.10.1
pdokservicesplugin
4.1.2
pluginbuilder3
3.2.1
qconsolidate3
0.2.0
qgis2web
3.16.0
SelectWithin
0.4
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Do you have a theme enabled?

**Comment by NvBgm** [comment]
Yes also with theme enable i have the same issue. Ialso use multiply QGis instalation and i do not have this issue with the previus version..

**Comment by roya0045** [comment]
Welp, I'm glad to know I'm not the only one affected and I didn't cause that,  if another contributor has a moment it would be appreciated if they could validate that forcing the linked map to follow a theme breaks the legend. Thanks

@NvBgm as a workaround you can disable the 'follow theme' in the layout map options, you can set your main canvas to follow your theme until this is addressed. If that is indeed the root cause. ( I would also suggest changing the title to something like ' Layout Map Theme causes error with Legend event filtering' )

**Comment by NvBgm** [comment]
@roya0045 The 'follow theme'  is not the root cause here because if i disable it or don't use theme at all i have the same problem.
So i wait for another update and hope it is back to normal. In the meantime I use the LTR version which works fine.

**Comment by roya0045** [comment]
Thanks for the validation!

**Comment by NvBgm** [comment]
Still not working afther update
