### ISSUE TITLE
QGIS stops working

### ISSUE THREAD

**Issue by guilldet** [qgis/QGIS#52314]
### What is the bug or the crash?

hello,

 QGIS regularly stops being active while I am working. That happens even if I don't us any plugin and the following window appears : QGIS unexpectedly ended. I see the software is looking and I have to wait but that lasts very long and I have to close the program.
 
I thank you in advance.

### Steps to reproduce the issue

That happens when I am using the layout page in order to create a png document, but actually I am always using this menu, that is why I am note sure the behaviour of QGIS has anything to do with that. I use a csv document and I create a graded colour scale.

### Versions

3.10.13

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
3.10.13 is wayyyyy too old.
Please update to a supported version: 3.28.4 or 3.30.0

Try with a new profile too.

**Comment by guilldet** [comment]
I thank you for your reply. I knew it was not the latest version but can that explain the fact that this problem occurs ? That is surprising.

**Comment by nicogodet** [comment]
@guilldet Many things have been fixed since. I need to try on supported version. Try on new profile (even if you don't use plugin, you could have change some settings) and last, if it still happens, provide sample data and step by step instruction to reproduce.
Furthermore, you didn't filled all requested info (system for exemple).


The more detailed your problem report, the more likely you are to get help.

**Comment by guilldet** [comment]
Now I use the version 3.28.4. Actually the same problem occured first and then I created a profile and so far it has not happened yet. I thank you.
