### ISSUE TITLE
Unable to change negative values under raster symbology

### ISSUE THREAD

**Issue by GustyLa** [qgis/QGIS#52341]
### What is the bug or the crash?

When the raster symbology values are negative, it is not possible to change the values to other negative values. To do this you have to change the value to '0' first, before typing in new negative value.

### Steps to reproduce the issue

1. go to 'Layer Properties'
2. go to 'Symbology'
3. select Render type 'Singleband pseudocolor'
4. select Interpolation 'Discrete'
5. under 'Value <=' type in negative value e.g. -0.1
6. commit change
7. under 'Value <=' type in negative value e.g. -0.2
8. commit change.
![qgis_neg_raster_values](https://user-images.githubusercontent.com/60964669/226871585-17217c83-bc3f-4c6e-91c4-17671b29f5f1.JPG)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.11-Białowieża | QGIS code revision | 106d33d7
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
clipper | 1.2
CSMapMaker | 0.5
dem_slicer | 0.4.1
FreehandRasterGeoreferencer | 0.8.3
geoscience | 1.9
HCMGIS | 23.2.1
LineDirectionHistogram | 3.1.1
NNJoin | 3.1.3
profiletool | 4.2.2
qdraw | 3.0.2
rvt-qgis | 0.9.4.1
Serval | 3.10.5
shapetools | 3.4.10
ViewshedAnalysis | 1.8
volume_calculation_tool | 0.4
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.11-Białowieża
QGIS code revision
[106d33d7](https://github.com/qgis/QGIS/commit/106d33d7)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
clipper
1.2
CSMapMaker
0.5
dem_slicer
0.4.1
FreehandRasterGeoreferencer
0.8.3
geoscience
1.9
HCMGIS
23.2.1
LineDirectionHistogram
3.1.1
NNJoin
3.1.3
profiletool
4.2.2
qdraw
3.0.2
rvt-qgis
0.9.4.1
Serval
3.10.5
shapetools
3.4.10
ViewshedAnalysis
1.8
volume_calculation_tool
0.4
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@GustyLa, it seems to me the issue does not occur using QGIS 3.30.0 on Windows. Could you please check if the issue does occur on your system also using a currently supported QGIS version and using a new QGIS user profile?

**Comment by agiudiceandrea** [comment]
@GustyLa, what is the locale set in the new QGIS user profile with which the issue does not occur? If it is not Norwegian, does setting it to Norwegian make the issue occur also with the new QGIS user profile?

**Comment by GustyLa** [comment]
@agiudiceandrea, in the new profile, I have simply turned off the locale override button. Note that the decimal issue only affects numbers in the negative. Numbers in the positive can be changed without any problem. I forgot to mention that I have upgraded to 3.30, but it is also an issue in this version.

**Comment by agiudiceandrea** [comment]
@GustyLa I cannot replicate the described behaviour using QGIS 3.30 on Windows even setting the locale to Norwegian nb_NO.

https://user-images.githubusercontent.com/16253859/234541844-8b6391dc-0c92-4b7a-a2e0-fe6249c053f4.mp4

Have you tried if the issue occurs in the new QGIS user profile even setting the locale to Norwegian nb_NO? If it does occur, could you please provide a sample layer and more detailed steps in order to replicate the issue?

**Comment by GustyLa** [comment]
https://user-images.githubusercontent.com/60964669/234563267-b59938a5-7198-4f43-b99b-bbaca5c8e308.mp4

It seems to be a problem when the interpolation is set to Linear, but no longer a problem if it is set to Discrete. It is not possible to delete the decimals by pressing backspace. The values can only be changed by deleting the number completely, then typing in a positive number, deleting that and then typing in a negative number.

**Comment by GustyLa** [comment]
[sample_qgis_neg.zip](https://github.com/qgis/QGIS/files/11332740/sample_qgis_neg.zip)

Here is a sample of the file I have tested this on.

**Comment by agiudiceandrea** [comment]
@GustyLa it seems to me the issue is about changing only the decimal part or the integer part of a negative number for "Paletted/Unique values" or for "Singleband pseudocolor" (Linear, Discrete of Exact) values when the locale is set to Norwegian nb_NO.

The issue does not occur if you just directly select the whole negative number (minus sign included) and type the new negative number (no need to "delete the number completely, then typing in a positive number, delete that and then typing in a negative number").

The issue does not occur for other locale such as Italian it_IT or Spanish es_ES.

It seems to me the issue is due to the fact that the negative value is displayed using a `−` character [`Unicode Character “−” (U+2212)`] which is not recognised as valid. When typing a whole new negative value, the `-` character [`Unicode Character “-” (U+002D)`] is used which is recognised as valid.

This happens for all the following locales that have the `−` character [`Unicode Character “−” (U+2212)` as negative sign:
eu_ES
hr_HR
hr_BA
eo_001
et_EE
fo_FO
fo_DK
fi_FI
kl_GL
lt_LT
nb_NO
nb_SJ
rm_CH
sl_SI
sv_SE
sv_FI
sv_AX
nn_NO
gsw_CH
gsw_FR
gsw_LI
se_NO
se_FI
se_SE
ksh_DE

Maybe @elpaso knows if it possible to fix this issue by allowing such character as a valid character for negative numbers in the validator.

**Comment by elpaso** [comment]
> @GustyLa it seems to me the issue is about changing only the decimal part or the integer part of a negative number for "Paletted/Unique values" or for "Singleband pseudocolor" (Linear, Discrete of Exact) values when the locale is set to Norwegian nb_NO.
> 
> The issue does not occur if you just directly select the whole negative number (minus sign included) and type the new negative number (no need to "delete the number completely, then typing in a positive number, delete that and then typing in a negative number").
> 
> The issue does not occur for other locales such as Italian it_IT or Spanish es_ES.
> 
> It seems to me the issue is due to the fact that, when locale is set to Norwegian nb_NO, the negative value is displayed using a `−` character [`Unicode Character “−” (U+2212)`] which is not recognised as valid. When typing a whole new negative value, then the `-` character [`Unicode Character “-” (U+002D)`] is inserted which is recognised as valid.
> 
> This happens for all the following locales that have the `−` character [`Unicode Character “−” (U+2212)`] as negative sign: eu_ES hr_HR hr_BA eo_001 et_EE fo_FO fo_DK fi_FI kl_GL lt_LT nb_NO nb_SJ rm_CH sl_SI sv_SE sv_FI sv_AX nn_NO gsw_CH gsw_FR gsw_LI se_NO se_FI se_SE ksh_DE
> 
> Maybe @elpaso knows if it possible to fix this issue by allowing such character as a valid character for negative numbers in the validator.

Probably yes, but you have to check how QLocale (and QVariant) toInt, toDouble and toLongLong behave with such charachter.

**Comment by agiudiceandrea** [comment]
@elpaso, please see the PR https://github.com/qgis/QGIS/pull/52923 I've proposed in order to fix the issue.
