### ISSUE TITLE
Changing language from German to American English breaks Vector Menu, leaves some german menu entries

### ISSUE THREAD

**Issue by momentmal** [qgis/QGIS#52449]
### What is the bug or the crash?

When changing from German to American english (either by overriding system locale or starting QGIS with parameter --lang en_US), the Vector Menu does not open anymore, also, some menu entries remain german

![image](https://user-images.githubusercontent.com/9054832/228875876-7df3216b-0446-402d-84d2-498874936fe2.png)

### Steps to reproduce the issue

Start QGIS on a german Windows 10 with start parameter --lang en_US
Try opening vector menu or look at raster menu entries

**Creating a new user profile after this seems to fix the issue.** However, this was a pretty new installation with not much done to the default profile, so this issue should be looked at for future versions

### Versions

QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
f186b8efe0e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
This is a long standing issue, back to early QGIS 3 versions, despite some attempts to fix it. see #45586 or #35028, or #26093 (at this stage I stopped searching).

**Comment by marisn** [comment]
The problem comes from Processing configuration store. When a Processing Menu settings are opened (Settings -> Options -> Processing -> Menus), they get pre-filled with default values. Up on close, those settings are stored into QGIS.ini file. When next time QGIS is started, settings are read back from the QGIS.ini file and take precedence over default settings. The default values are menu layout in translated form thus just navigating to Processing Menu configuration section will write translated menu layout as the user preference into configuration.

Solution:
* apply PR #57291
* press "Reset to defaults" in Settings -> Options -> Processing -> Menus
