### ISSUE TITLE
Cannot rendering while dragging (do not release the mouse)

### ISSUE THREAD

**Issue by Advatalong** [qgis/QGIS#52479]
### What is the bug or the crash?

When I drag the map without releasing the mouse, the edge of the map is white, and the layer is not rendered. Most other open source frameworks on the market support rendering while dragging, and the effect is relatively smooth. Why? In the latest 3.30 version of qgis, the (Render only when map is still) check box in the settings tab is removed, and this problem will also be encountered when using c++ for secondary development. The current interface displays the map The outside is all white, which greatly affects the display effect. Is there any solution?

### Steps to reproduce the issue

Drag the map(canvas) without releasing the mouse

### Versions

QGIS3.30

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by uclaros** [comment]
> When I drag the map without releasing the mouse, the edge of the map is white, and the layer is not rendered

This should not be happening. For each map render QGIS renders the visible extent as well as the 8 same sized adjacent extents and displays them while panning. On mouse release a new set of 9 extents is rendered. You should be getting white canvas only if you pan further away than that, which is quite unusual.
Please provide more accurate steps to reproduce or a sample project.

**Comment by Advatalong** [comment]
> > When I drag the map without releasing the mouse, the edge of the map is white, and the layer is not rendered
> 
> This should not be happening. For each map render QGIS renders the visible extent as well as the 8 same sized adjacent extents and displays them while panning. On mouse release a new set of 9 extents is rendered. You should be getting white canvas only if you pan further away than that, which is quite unusual. Please provide more accurate steps to reproduce or a sample project.

Thank you very much for your patient reply, maybe I didn't describe the problem clearly before. What you said about releasing the mouse after dragging can indeed render, and the white border will disappear immediately. But what I am talking about is: do not release the mouse when dragging (note!! do not release the left button of the mouse), the map moves, and then the edge part slides into the software interface, forming a white border, and this white border will not render. It’s like a huge white paper with a picture on it, the size of this picture is exactly the size of your screen, once you drag this white paper, then unknown white will be displayed on your screen‘s edge, and If you don't release the left mouse button, the white part will not be replaced by a new picture(layer rendering process). If you have used openlayers for gis-related secondary development, you should know that the layer has an 'updateWhileInteracting' attribute. As long as this attribute is set to true, the layer will be dragged without releasing the left mouse button. But the secondary development of qgis does not provide this property. I must inherit qgsMapCanvas, then rewrite the mouseMoveEvent() method, then use the setCenter() method to set the offset, and then call the refresh() method to meet my requirements. But the effect of writing in this way is very poor. So the question I want to ask is is there a method or code sample to solve this problem. Thank you very much.

**Comment by velle** [comment]
I experience the same behavior. 

The vector layers (both WMS and geopackage) seem to be pre-rendered so that they are instantly shown when I pan. However WMS layers are not rendered/drawn and appear as white - until when I let go of the mouse. See this screenshot (the screenshot tool renders the mouse cursor incorrectly making it appear as if I have already let go, while in fact the screenshot is taken while the button is still pressed). 

I found this issue because I was looking for ways to change this behavior. I wasnt sure if it was a bug, and I don't know for how long it has behaved like this. 

![Screenshot from 2023-05-01 18-24-02](https://user-images.githubusercontent.com/4488298/235489883-abd3dc7f-2501-451e-aa08-89d6272e8268.png)

I tried with various projects, and this was the behavior on all of them. I tried on both Linux and on Windows, both version 3.22.4. My WMS sources are: 1) Open Street Map and 2) various official ortophotos from the Danish authorities. Both of them show this behavior. 

Bonus information: QField app (and Mergin Maps which I believe is built on QFfield) show similar behavior, except worse. They don't even render the vector layers, so its entirely white until I let my finger go of my phone screen. On a phone screen this behavior is much more annoying than on a desktop, and it makes the experience much inferior to similar apps.

**Comment by velle** [comment]
> For each map render QGIS renders the visible extent as well as the 8 same sized adjacent extents and displays them while panning. 

@uclaros What you describe is how I would expect QGIS (and similar tools) to behave, but that is just not how it actually behaves (see my [earlier comment](https://github.com/qgis/QGIS/issues/52479#issuecomment-1529935296)), at least not on any of my machines. I just tested again on:

- QGIS 3.30 on Windows 10
- QGIS 3.22 on Ubuntu 22.04 

Does it behave differently at your setup than at mine?
