### ISSUE TITLE
Geojson problem with Windows regional settings != english

### ISSUE THREAD

**Issue by icgcaadell** [qgis/QGIS#52731]
### What is the bug or the crash?

If I load a geojson file on a QGIS >= 3.22 Windows with regional settings != English, QGIS seems to have problems detecting the selected elements.

### Steps to reproduce the issue

[photo.json.txt](https://github.com/qgis/QGIS/files/11248554/photo.json.txt)

Interactively:
- Execute in console: 
        import locale
        locale.setlocale(locale.LC_ALL, '')
- Load the attached geojson (photo.json with a single element and id=1)
- Select the item
- Move the map view to move away from the item
- Zoom to selection: fails and does not zoom to selection

With pyqgis:
- import locale
- locale.setlocale(locale.LC_ALL, '')
- l = iface.addVectorLayer("path_to_file/photo.json", "test_1_item", "ogr")
- l.select([1]) #shown selected in map view
- l.selectedFeatures() -> #return [] error, empty!
- l.selectedFeatureIds() -> #return [1] correct!

It seems that the access to ids is correct but when retrieving the selected element with all its fields it fails

### Versions

[3.22 to 3.31]

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

https://user-images.githubusercontent.com/47522822/232729229-70ad6e70-2659-4428-9b98-7f697d8066f1.MP4

**Comment by agiudiceandrea** [comment]
@icgcaadell I cannot replicate the issue using QGIS 3.28.5 and 3.30.1 on Windows

https://user-images.githubusercontent.com/16253859/232480463-7ad40916-c444-4c57-9db1-dd780a7dcef6.mp4

Could you please try again using a new QGIS user profile and add the info in Help->About window as requested in the issue report form?

**Comment by icgcaadell** [comment]
Sorry, a couple of lines were missing to reproduce the problem. I have updated the incident description.
Because the locale python configuration is changed, I don't know if it can be considered a QGIS problem.

**Comment by icgcaadell** [comment]
In a version 3.20.3 it also works, it seems that the problem started in version 3.22...

**Comment by agiudiceandrea** [comment]
Probably @rouault knows if the issue could be related to the GDAL/OGR library or to the OGR provider in QGIS.

The issue does not occur on Windows with QGIS 3.22.7 (GDAL 3.4) and previous versions, while it does occur with QGIS 3.22.8 (GDAL 3.5) and next versions.

Forcing QGIS 3.22.7 to use GDAL 3.5 instead of GDAL 3.4, makes the issue occurring even in QGIS 3.22.7.
Forcing QGIS 3.22.8 to use GDAL 3.4 instead of GDAL 3.5, makes the issue not occurring even in QGIS 3.22.8.

So it seems the issue is triggered by some change between GDAL 3.4 and 3.5 or in the way it is build in OSGeo4W.

**Comment by rouault** [comment]
GDAL upstream fix in https://github.com/OSGeo/gdal/pull/7725
