### ISSUE TITLE
QGIS changes coordinates

### ISSUE THREAD

**Issue by cuzzafin** [qgis/QGIS#53272]
### What is the bug or the crash?

QGIS changes the coordinates slightly whenever I create a shapefile from a temporary layer, e.g. a layer created from a .csv exported as an ESRI shapefile. The change is subtle. For example, it changed eastings and northings from 715418.82 / 7455224.71 to 7151418.81999999000 / 7455224.709999900. The same thing happens with lats and longs. The issue also happens when you choose to 'make permanent'.

We found a way to stop this happening by creating the shapefile straight from the browser within QGIS (top left above the layers), i.e. right clicking on the csv you want to create a shapefile of, choosing Export Layer -> To File and then saving it as per usual shapefile export procedure. 

This issue affects several versions of QGIS.

### Steps to reproduce the issue

As above

### Versions

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
zoomtopaste
3.0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Llaves** [comment]
Numbers like 715418.82 cannot be represented exactly in binary floating point. The "changed" number you are seeing is the internal IEEE754 floating point value.  I'm not quite sure why doing the conversion from the browser maintains the value unless perhaps it is treating the value as a string, not a number. Regardless, once the shapefile is loaded into QGIS, the internal representation will be the changed value.

**Comment by agiudiceandrea** [comment]
@cuzzafin, in addition to the previous comment, the coordinates in a temporary (memory) layer and in an ESRI Shapefile layer are stored as 64-bit (double) floating point IEEE754 binary. The decimal number 715418.82 should be stored as 0x4125D535A3D70A3D 64-bit IEEE754 binary which corresponds to the most accurate representation of 715418.819999999948777258396149... decimal number.
Could you please provide a sample csv file and the exact procedure you follow in order to replicate the issue? In particular, could you please specify how do you retrieve the coordinates from the exported ESRI Shapefile layer?
