### ISSUE TITLE
Adding point clouds through HTTP from public Azure blob storage

### ISSUE THREAD

**Issue by jakubstaszel** [qgis/QGIS#53612]
### What is the bug or the crash?

It is not possible to display COPC files that are stored on public blob storage on Azure. There is no problem with the data, it can be easily displayed from e.g. AWS S3, there is just a problem with the validation that is made in QGIS. Azure supports range requests, there is just no Accept-Ranges query in header. The validation method on QGIS site may be changed, so it is less strict.
Please refer to https://github.com/copcio/copcio.github.io/discussions/61

### Steps to reproduce the issue

1. Upload COPC file to Azure blob storage that is public
2. Enable CORS
3. Add point cloud to QGIS using HTTP

### Versions

3.28.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by wonder-sk** [comment]
This is checked in `QgsLazInfo::supportsRangeQueries()` - with a HEAD request.

We're using `QgsBlockingNetworkRequest` there, but this class does not have functionality to just check for HTTP status code (we want 206 instead of 200), so we would need some bigger adjustments there, or switch to custom way of doing requests (that works well when run on the main thread).

Alternatively, we could just introduce an option to disable this check...

**Comment by msmitherdc** [comment]
Doing this in QgsBlockingNetworkRequest would allow 206 with other types like raster and vector wouldn't it?
