### ISSUE TITLE
QGIS mix language use English/German

### ISSUE THREAD

**Issue by g-terziev** [qgis/QGIS#53652]
### What is the bug or the crash?

QGIS is not showing completely everything in English language.

For example I go to Project->Properties->CRS, then everything is in English, exceptthe buttons for example Cancel is translated in german Abbrechnen, also for Apply and Help.

And this is issue is everywhere around QGIS in all Menus and Submenus. For example I want to change Symbology and then Apply button is also in German.

It looks like QGIS is mixing two languages.... 
![image](https://github.com/qgis/QGIS/assets/117976490/1d0dc181-c1c9-4940-a441-5d97a8d2824f)

### Steps to reproduce the issue

1. Go to Project
2. Properties
3. CRS
4. Button Ok, Apply, Cancel, Help are in German not in English

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a65
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
coordinates_converter
1.0
copy_coords
0.2
kmltools
3.1.29
latlontools
3.6.11
map-coords-plugin
2.0.0
mmqgis
2021.9.10
OpenTopography-DEM-Downloader
2.0
profiletool
4.2.6
QuickOSM
2.2.2
quick_map_services
0.19.33
SRTM-Downloader
3.1.17
tile_plus
0.1
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
Strange, transifex show that german translation should cover every string at https://explore.transifex.com/qgis/QGIS/

**Comment by g-terziev** [comment]
@roya0045 the problem is If I decide to use QGIS in English, I want to be everything in English.

If I decide for German, I want everything to be in German. Not mixing both languages.....

This was not issue with previous version. The issue started when I updated to the newest QGIS 3.32 Lima version

**Comment by T3xtM4rk3r** [comment]
I can confirm this behaviour after updating to QGIS 3.32 just this morning.

![grafik](https://github.com/qgis/QGIS/assets/92782306/89074bfb-54df-40e3-b9fd-7e3cda1783f9)

**Comment by DelazJ** [comment]
I suspect this to be a Qt issue than QGIS' because here is what I get running en-US QGIS under French environment
![image](https://github.com/qgis/QGIS/assets/7983394/c06624aa-f0ec-44fa-b900-685b78e3c0cc)
![image](https://github.com/qgis/QGIS/assets/7983394/6dc3e6bd-9e3d-481d-b18e-1fd609a81c5c)

And afaik these are QDialogButtonBox items and are not strings translated by QGIS community, and instead inherited from upstream

**Comment by agiudiceandrea** [comment]
A similar issue was reported at https://github.com/qgis/QGIS/issues/53592#issuecomment-1608393191.

The en_US language for QGIS was added with PR https://github.com/qgis/QGIS/pull/47204 by @m-kuhn.
See also the comment https://github.com/qgis/QGIS/issues/53592#issuecomment-1608393191 by @YoannQDQ.

Maybe those are related.

**Comment by DelazJ** [comment]
I don't think #52449 is related. It was there already in QGIS 3.2 (see https://github.com/qgis/QGIS/issues/27823) and I from time to time have it when playing in multilingual environment.

**Comment by snuup** [comment]
I face the same issue and this highly confusing. It should be boosted in priority.

**Comment by YoannQDQ** [comment]
Related to #51800.
This pr introduces an optional user selector dialog, which is displayed BEFORE any profile is selected. In order to display this dialog in the user (probable) native language, the system language is preloaded (as a QTranslator). 

When a profile is selected, its language is loaded in another QTranslator installed on top of the other. 

Thud for any gui string, Qgis looks for translations in the following order
- qgis_<profile_langage>.qm
- qgis_<system_language>.qm
- fallback to original string (in source code)

The English translation (qgis_en.ts) is typically not as up to date as some other languages, which kind of make sense as it can be seen as lower priority: QGIS without any translation appears in English after all. 

Problem may occur on non English system. Say we are on a Spanish system. A newly added feature is not present in qgis_en.ts but was translated in Spanish. When the user set the UI language to English, strings related to this new feature will appear in Spanish.

Possible solution would be to uninstall the system language QTranslator as soon as the profile is selected. Then the resolution order would become (as before #51800)
- qgis_<profile_langage>.qm
- fallback to original string

**Comment by agiudiceandrea** [comment]
> The English translation (qgis_en.ts) is typically not as up to date as some other languages
> When the user set the UI language to English, strings related to this new feature will appear in Spanish.

@YoannQDQ what seems weird to me is the the English "translation" qgis_en.ts is not up to date... Why doesn't it contain all the untranslated strings, since the strings are already in English?

**Comment by YoannQDQ** [comment]
AFAIK, the qgis_en was added to handle plurals. It does not get a special treatment compared to other translation files, meaning newly added strings in the UI are parsed (by lupdate presumably) and added as "untranslated" strings in qgis_en.ts. Which did not cause any issue prior to #51800 since the fallback string was the original string. We could maybe add another script to autofill non plural strings in the qgis_en.ts with the original strings. 

In the meantime, I submitted a PR (#55591) to fix the issue.

**Comment by m-kuhn** [comment]
> We could maybe add another script to autofill non plural strings in the qgis_en.ts with the original strings.

https://github.com/qgis/QGIS/pull/47204#issuecomment-1030628975

@rduivenvoorde proposed a script there, ideally this is run always before files are pushed to transifex -- and I think it might also be good to do the same when pulling as well.

**Comment by DelazJ** [comment]
Well, I'll let @jef-n confirm or not, but qgis_en has always been afaik; it is the source language and source strings are _de facto_ translation strings. Do you have example of untranslated strings in qgis_en.ts? I can't find any in Qt Linguist.
What was introduced for pluralization is qgis_en_US and I don't think there was a release without it being fully translated either (it takes a few clicks to get done).

Back to the initial comment of this issue report 
> Button Ok, Apply, Cancel, Help are in German not in English

These strings are from Qt, the QDialogButtonBox strings, and are not available in our qgis_en.ts file. Whatever language I choose for QGIS GUI, these strings are in French here. Does anyone see any other (custom) strings showing in the OS native language while the GUI language is another one?

**Comment by agiudiceandrea** [comment]
See e.g. https://github.com/qgis/QGIS/issues/53592.

**Comment by DelazJ** [comment]
I forgot to ask earlier but was this issue actually fixed for someone? Whatever profile  (new or older) I've been trying since, overriding the locale on a French machine still results in the QDialogButtonBox buttons in French.
EN
![image](https://github.com/qgis/QGIS/assets/7983394/c96094ca-20ec-4127-8720-3950906b12fb)
IT
![image](https://github.com/qgis/QGIS/assets/7983394/29f910a7-b362-4684-86cf-62e19da64f81)

**Comment by g-terziev** [comment]
@DelazJ I posted this post last year on 29.06.2023. For me, the issue still exists, despite using the newest QGIS version...

**Comment by agiudiceandrea** [comment]
On a Windows 10 Italian locale, I don't see the issue either using QGIS 3.34.3 or QGIS 3.35.0 b572110ec4 (OSGeo4W) either without overriding the system locale:

![image](https://github.com/qgis/QGIS/assets/16253859/c2c91679-07db-4ca5-b5f4-c5eeb4f2dfb4)

or overriding the system locale: user interface translation set to America English

![image](https://github.com/qgis/QGIS/assets/16253859/049d0a0d-9d84-4d12-8ce4-814f99108e67)

**Comment by agiudiceandrea** [comment]
@DelazJ @YoannQDQ I've seen today a notification by Transifex about "A new file 'qgis_en.ts' was added to the project QGIS Desktop". Was this perhaps the missing peace?

**Comment by DelazJ** [comment]
> I've seen today a notification by Transifex about "A new file 'qgis_en.ts' was added to the project QGIS Desktop". Was this perhaps the missing peace?

Not at all @agiudiceandrea this is a message you get every 4 months as a translator when Jürgen pushes new branch strings to Transifex
> overriding the system locale: user interface translation set to America English

Indeed. Seems to work on Windows here also. But my need is for making adequate screenshots for docs and Windows is not my daily environment for contributing to QGIS. 
I've trashed my user profile, restarted the build in another folder from scratch and I still have French buttonbox 😱 . And I'm not the only one as I could see recently in https://github.com/qgis/QGIS/pull/56984#issue-2210702502
Some quirkies with Debian?
