### ISSUE TITLE
composer css text 

### ISSUE THREAD

**Issue by Frankd66** [qgis/QGIS#53919]
### What is the bug or the crash?

The CSS style does not work properly in the text windows in the composer.

### Steps to reproduce the issue

Create a HTML label window in the composer. 
Insert :
```
<style type="text/css">
h2 {font-size:10px}
</style>

<h2>Hello world </h2>
```

Try to change font-size = no effect

### Versions

3.32.0 and 3.32.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context
Debian GNU/Linux 11 (bullseye)
_No response_

**Comment by nirvn** [comment]
@Frankd66 , since 3.32, users have to rely on HTML item (instead of an HTML-enabled label item) when wanting to rely on <style> tags. That followed a change to allow for functional hyperlinks in HTML-enabled label items.

**Comment by Frankd66** [comment]
I don't really understand the change in principle. So, how can we format the content of text boxes using HTML interpretation?

I noticed that -webkit-linear-gradient (very useful for simulating non-lenary scales) no longer works. How to do ?

```
<html> <head> <style type="text/css">
body { background: -webkit-linear-gradient(bottom,#ffffff,#3ad3fd,#8ecd10,#ffea01,#fe003b,#8901ff);  }
* { color: white}
</style></head>
<body>
</body> </html>
```

**Comment by ChameleonScales** [comment]
To clarify what @nirvn meant by relying on an html item instead of an html-enabled label item, it's the type of object you add in the composer:
![Screenshot_2023-11-10_10-02-09](https://github.com/qgis/QGIS/assets/19158847/d4528ff2-0320-4a36-ab21-c4c39aef63eb)
With the html object, the code works :
![Screenshot_2023-11-10_10-04-08](https://github.com/qgis/QGIS/assets/19158847/c6f567b2-cad0-4c83-aa41-a4c52739117c)
