### ISSUE TITLE
Python run error

### ISSUE THREAD

**Issue by Nana-Bright** [qgis/QGIS#53961]
### What is the issue about the documentation?

I have been having a python run error whenever i try to do atmospheric correction with SCP. it used to work correctly about a week or two ago. What should i do?

**Comment by agiudiceandrea** [comment]
Hi @Nana-Bright, thanks for reporting. Anyway, since the issue concerns a third party plugin then this is not the right place to report it and it can't be fixed by the QGIS core team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)
