### ISSUE TITLE
vertex editor highlight not working on first and last vertex of polygon

### ISSUE THREAD

**Issue by FabienHory** [qgis/QGIS#54034]
### What is the bug or the crash?

The vertex editor highlight vertex with red circle and the selected vertex in the list with blue circles but in the case of polygon features, the first and the last vertex wich have the same coordinates are never highlighted with blue circle. 
The same thing happens when 2 vertex are similar (green cross highlight).
It seems that the red highlight is always over the blue one. 
![vertexeditor](https://github.com/qgis/QGIS/assets/111418033/091d37fc-5809-4609-8b1a-d827436cd7e6)

### Steps to reproduce the issue

activate vertex tool
right clic on a polygon
clic on the first vertex in the list 

### Versions

tested in 3.20.3  and 3.32.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by baswein** [comment]
I played around with this a little and found that I could fix this in 2 ways. Either by getting the vertex marker to draw on top or by making the selected marker slightly bigger. 
Here is a GIF of the current behavior. Notice that the first and last vertices selections are not visible when selecting a single one in the table but are when selecting both in the table or in the canvas. Also notice that the two vertices right next to each other are also not visible unless both are selected: 
![msrdc_lNHoodZ7O6](https://github.com/user-attachments/assets/8a7f1b0d-d37f-471c-a1d1-c0b2e5c2d7be)

And here is a GIF where the selection vertex marker is forced to be on top by setting the z value to +1. `marker->setZValue( marker->zValue() + 1 );` Notice while it solves the issue with the first and last vertices in the doubled up vertices case the selected one obscures the unselected one:
![msrdc_POgD3eVMGp](https://github.com/user-attachments/assets/009b126e-5dde-48cd-af45-b31e52f10149)

And here is a GIF where the selection marker is made larger 12 rather than 10.  ` marker->setIconSize( QgsGuiUtils::scaleIconSize( 12 ) );` This is my preferred method because it shows selected and unselected vertices even if they are right on top of each other. However it reveals the when the vertex is selected in the table the unselected icon is not present but when selected on the canvas it remains.
![msrdc_1dKwAVvkZY](https://github.com/user-attachments/assets/a65042c6-d102-48ca-a904-75627a5b5eba)

I was thinking of putting in a pull request that adds the z value and makes the circle bigger. Anyone have any preferences?

**Comment by FabienHory** [comment]
I like your second proposal 👍
