### ISSUE TITLE
Not possible to start the QT Designer

### ISSUE THREAD

**Issue by TNogatz** [qgis/QGIS#54128]
### What is the bug or the crash?

The QT Designer is placed in "apps\qt5\bin". It's not possible to start this application. Some DLLs are missing: 
libpng16.dll, zlib.dll, libssl-1_1-x64.dll and more. They are located in "bin\" - the former location of designer.exe. 
But after copying the missing files to "apps\qt5\bin" a new issue occurs: "This application failed to start because no Qt platform plugin could be initialized."
I'm running QGIS 3.28.9 and 3.32.1 on Windows 10.
Sorry, I'm not sure if this topic is placed correctly here.

### Steps to reproduce the issue

.

### Versions

.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @TNogatz, thanks for reporting. Since the issue is related to the OSGeo4W install/packaging system, you need to file a new ticket at https://trac.osgeo.org/osgeo4w/.
Anyway, to start the Qt Designer you need to use the "Qt Designer with QGIS custom widgets" Windows shortcut link in the QGIS/OSGeo4W folder of the Start Menu.
