### ISSUE TITLE
QgsGeometryUtils.circleCircleIntersections does not work properly

### ISSUE THREAD

**Issue by qgis2000** [qgis/QGIS#54322]
### What is the bug or the crash?

Incorrect results for example:

(1, <QgsPointXY: POINT(nan nan)>, <QgsPointXY: POINT(nan nan)>)

(2, <QgsPointXY: POINT(nan nan)>, <QgsPointXY: POINT(nan nan)>)

### Steps to reproduce the issue

#Example1
x0=5.17140812687688189
y0=0.57209787912912891
r0=2.2602305137548804

x1=11.33315669032675643
y1=-2.99891549287022841
r1=4.8615165936742235

center0=QgsPointXY(x0,y0)
center1=QgsPointXY(x1,y1)

print(QgsGeometryUtils.circleCircleIntersections(center0,r0,center1,r1))

#Example2
x0=-1.33611111111111125
y0=-0.08333333333333348
r0=0.8101402103918971

x1=-0.19561185568356954
y1=-0.68452673929513763
r1=2.0993927314298557

center0=QgsPointXY(x0,y0)
center1=QgsPointXY(x1,y1)

print(QgsGeometryUtils.circleCircleIntersections(center0,r0,center1,r1))

### Versions

3.28.4

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
It seems to me the issue is due to the fact that the expression at https://github.com/qgis/QGIS/blob/eba2cb8598878c6cf76fb886a3d27030bd2b9478/src/core/geometry/qgsgeometryutils.cpp#L423
may returns a very slightly incorrect result (due to floating point rounding errors) when the two circles intersects each other at a single point, i.e. when the distance between the two centers is equal to the sum of the two radii ("external intersection") or when it is equal to the absolute value of the difference of the two radii ("internal intersection"). In such cases, the expression should be simplified to `const double a = r1` or `const double a = -r1`, avoiding most of the floating point rounding errors.
