### ISSUE TITLE
very large icon sizes, they look messy.

### ISSUE THREAD

**Issue by 016852902FREDY** [qgis/QGIS#54338]
### What is the bug or the crash?

very large icon size, they look messy, it must be set to a value of 16 to make them look neat on a hd resolution screen.

### Steps to reproduce the issue

very large icon size, they look messy, it must be set to a value of 16 to make them look neat on a hd resolution screen.

### Versions

3.32.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

very large icon size, they look messy, it must be set to a value of 16 to make them look neat on a hd resolution screen.
<img width="670" alt="QGIS 3 32 2" src="https://github.com/qgis/QGIS/assets/86328327/4fd00c6c-5a8b-4ab2-92b6-121f89ba3567">

**Comment by nirvn** [comment]
@016852902FREDY , since QGIS 3.32, high-dpi auto scaling, which insures that widgets have similar proportions across normal and high dpi screens. It did result in larger icons by default (which roughly matches what you'd have on a normal screen).

As you're pointing out yourself, QGIS does allow you to shrink icons if you don't like the default size. I'm inclined to close this issue as "default size is too big" is subjective and you've found your way into reducing the size. Is it OK with you?
