### ISSUE TITLE
When you zoom in a circle drawn with painter.drawEllipse in python, the circle is displayed not preserving radius length

### ISSUE THREAD

**Issue by qgis2000** [qgis/QGIS#54494]
### What is the bug or the crash?

Radius and circle match for 0 or 90 degree radius like in figures below. 

![obraz](https://github.com/qgis/QGIS/assets/142023542/29700bfa-bdbb-4aea-bec5-0b11e0fedffa)
![obraz](https://github.com/qgis/QGIS/assets/142023542/c04d0a74-7eac-4542-ab0a-0e84f18f8549)

For the other angles, the circumference of the circle does not lie at the end of the radius for example below.

![obraz](https://github.com/qgis/QGIS/assets/142023542/4fa70d5b-383b-4eb1-ad95-a71a218b5193)

### Steps to reproduce the issue

The situation can be observed using the advanced digitization panel.
1. Enable the advanced digitization panel.
2. Select to draw a line segment and left click the mouse to insert the first vertex of the segment.
3. Press d and enter the segment length. Press enter to lock the length. A circle will be displayed.
4. Try to zoom in the intersection of the distance lock circle with the length of the segment.

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @qgis2000, thanks for reporting. Could you please clarify why in the issue's title do you mention to "draw with painter.drawEllipse in python", while in the issue description there it is only described an issue about the Advanced Digitizing panel.

**Comment by agiudiceandrea** [comment]
It seems to me the issue about QPainter.drawEllipse in Python is an upstream issue, judging from the QT issue reports https://bugreports.qt.io/issues/?jql=text%20~%20%22drawEllipse%22

The Advanced Digitizing tool uses the QPainter.drawEllipse function to draw the locked distance circle https://github.com/qgis/QGIS/blob/31d793d8abbacec16db7aa848e0eca7ad790df80/src/gui/qgsadvanceddigitizingcanvasitem.cpp#L159-L165 so we need to find a workaround.

I think a possible solution would be to rotate the circle around its center in order to have its x axis aligned with the distance line.

**Comment by agiudiceandrea** [comment]
It seems to me the QPainter.drawEllipse issue in Python is a QT upstream issue, judging from the QT issue reports https://bugreports.qt.io/issues/?jql=text%20~%20%22drawEllipse%22, so we cannot do anything in QGIS to fix the QPainter.drawEllipse issue in Python.

The Advanced Digitizing tool uses the QPainter.drawEllipse function to draw the locked distance circle https://github.com/qgis/QGIS/blob/31d793d8abbacec16db7aa848e0eca7ad790df80/src/gui/qgsadvanceddigitizingcanvasitem.cpp#L159-L165 so we need to find a workaround.
I think a possible solution would be to rotate the circle around its center in order to have its x axis aligned with the distance line. I will propose a Pull Request to fix this issue.

It seems to me the issue with the "Circle by a center point and another point" tool is similar but may have a different root cause and a different way to be fixed.

@qgis2000, please change the title of this issue report mentioning only one issue (i.e. the Advance Digitizing issue with the locked distance circle) and open another issue report about the "Circle by a center point and another point" tool.

**Comment by nyalldawson** [comment]
@qgis2000 I'm cautioning you on your wording here. Your reply could be taken as aggressive toward @agiudiceandrea , who is a valued member of the qgis community. Please take care to adjust your tone and language used in future communication.

**Comment by uclaros** [comment]
The root cause seems to be that `QPainter::drawElipse()` draws a segmentized ellipse. You can see that the radius is correct roughly every 1.44 degrees, which is where the straight segments meet.

I wonder if using `QPainter::drawArc()` when zoomed in would give better results...

**Comment by uclaros** [comment]
@agiudiceandrea yes, I saw your PR. Rotating the ellipse is quite clever but it only works when tracking the mouse (which is the case for both the advanced digitizing and the circle tool, though). If `drawEllipse()` was used to render two intersecting circles they would appear intersecting at the wrong point and rotating the ellipse would not be possible (again, this is purely theoretical though, as those two seem the only parts were drawEllipse is used and could suffer from zooming in too much)

**Comment by agiudiceandrea** [comment]
"Circle by a center point and another point" issue -> new issue report: https://github.com/qgis/QGIS/issues/54984.
