### ISSUE TITLE
Different text color for legend hierachies in the print composer

### ISSUE THREAD

**Issue by Mario-Valiante** [qgis/QGIS#54694]
### Feature description

It would be useful to be able to edit the text color of title, groups, subgroups and labels individually instead of having a single color option for all of them.

**Comment by DelazJ** [comment]
@Mario-Valiante Is this not already possible: https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_legend.html#fonts-and-text-formatting?

**Comment by mblesius** [comment]
It is possible since Version 3.30 see the [Changelog](https://www.qgis.org/en/site/forusers/visualchangelog330/index.html#feature-use-text-renderer-in-layout-legends) for reference.

@Mario-Valiante if you are using QGIS LTR Version 3.28 "Firenze", you may want to upgrade to the newest Version 3.32 "Lima", to use this feature, but if you have to rely on LTR version, you will have to wait until the next long-term-release which according to the roadmap will be in late February.

**Comment by Mario-Valiante** [comment]
I'm sorry for the dumb question, but I only use LTR versions at work.
Didn't thought oh trying other versions. Anyway I'm glad it has been introduced as a feature and will be be available on the next LTR.
Thanks!
