### ISSUE TITLE
OSGeo4W installer bug

### ISSUE THREAD

**Issue by ARTCON2020** [qgis/QGIS#55121]
### What is the bug or the crash?

Eventhough I ticked SAGA under plugin menu it does't appear under processing TollBox as showen in attached pictures

### Steps to reproduce the issue

QGIS installed from Installer
SAGA, PCRaster and GRASS are included

### Versions

QGIS 3.32

![SAGA SAGA NG](https://github.com/qgis/QGIS/assets/72500978/bdbdc514-c1f5-4c70-bfe7-60f668bc2b1f)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@ARTCON2020, thanks for reporting.
You mentioned QGIS 3.28 in the issue report title and QGIS 3.32 in the issue report description: could you please clarify with which QGIS version the issue occurs?
Please:
- change the issue report title to a more meaningful one
- provide the info requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.")
- try if the issue does occur also using a new QGIS user profile as requested in the issue report form
- specify which installer have you used: the OSGeo4W stand-alone all-in-one .msi installer or the OSGeo4W network installer .exe

**Comment by ARTCON2020** [comment]
@agiudiceandrea, thank you for your quick response.
I will try to answer your questions(comments) as follow:

- 
QGIS version
3.28.12-Firenze
QGIS code revision
dcc633b2de
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AGT
3.1.3
crayfish
3.6.0
LAStools
1.5
pcraster_tools
0.3.0
processing_saga_nextgen
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

- The same problem occured as I changed with new profile

- I used OSGeo4W network installer .exe
[QGIS 3.28.12 and QGIS 3.34.0 are installed on my computer]

Thank you in advance:)

**Comment by agiudiceandrea** [comment]
@ARTCON2020, QGIS 3.32 no longer have a sagaprovider core plugin, while QGIS 3.28 still has it.
It seems you have both sagaprovider core plugin and processing_saga_nextgen external plugin installed in your user profile (besides other non core plugins): have you actually used a new QGIS user profile? Could you please provide the full text of any error message displayed in the "Log Messages" panel? Could you please modify the issue report title to a meaningful one?

If the issue still occurs with QGIS 3.28.12 actually using a new QGIS user profile without any external non core plugin installed, please file a bug report on https://trac.osgeo.org/osgeo4w/ since the issue, if any, looks like not related to QGIS itself, but to the OSGeo4W installer or may be related to your system.

**Comment by ARTCON2020** [comment]
@agiudiceandrea, thanks again.
I did all based on your recommendation,"QGIS 3.28.12 actually using a new QGIS user profile without any external non core plugin installed". But the problem is still there.



QGIS version
3.28.12-Firenze
QGIS code revision
dcc633b2de
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009




Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
processing_saga_nextgen
1.0.0

**Comment by agiudiceandrea** [comment]
@ARTCON2020, it's weird that the "processing_saga_nextgen" seems installed even in a new QGIS user profile.
Anyway, could you please provide the full text of any error message displayed in the "Log Messages" panel? Are you sure SAGA-GIS is installed in your system using the OSGeo4W installer (saga package)?
Since the issue, if any, is not related to QGIS itself, but to the OSGeo4W installer or may be related to your system, I suggest you again to file a bug report on https://trac.osgeo.org/osgeo4w/.

**Comment by agiudiceandrea** [comment]
@ARTCON2020 , it looks like the latest screenshots provided by you clearly indicate that the issue is not due to QGIS.
As already previously suggested, Since the issue, if any, is not related to QGIS itself, you need to file a bug report on https://trac.osgeo.org/osgeo4w/ providing the installation log.
