### ISSUE TITLE
Processing interpolation crash

### ISSUE THREAD

**Issue by arnige** [qgis/QGIS#55138]
### What is the bug or the crash?

When attempting to run interpolation algorithms in the processing toolbox, python crashes before opening the dialog with the following error:
File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged
 rows = max(round(self.extent.height() / cell_size) + 1, 1)
 OverflowError: cannot convert float infinity to integer

### Steps to reproduce the issue

Open the processing toolbox and try to run "TIN interpolation" or "IDW interpolation".

### Versions

3.34.0-Prizren
Happens both in Windows and Ubuntu

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by arnige** [comment]
I should include the full traceback:

              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 428, in executeAlgorithm
              dlg = AlgorithmDialog(alg, in_place, iface.mainWindow())
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 69, in __init__
              self.setMainWidget(self.getParametersPanel(alg, self))
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 93, in getParametersPanel
              panel = ParametersPanel(parent, alg, self.in_place, self.active_layer)
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\ParametersPanel.py", line 69, in __init__
              self.initWidgets()
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\ParametersPanel.py", line 197, in initWidgets
              wrapper.postInitialize(list(self.wrappers.values()))
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 383, in postInitialize
              self.setLayers(wrapper.parameterValue())
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 393, in setLayers
              self.widget.setLayers(layersData)
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 285, in setLayers
              self.pixelSizeChanged()
              File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged
              rows = max(round(self.extent.height() / cell_size) + 1, 1)
             OverflowError: cannot convert float infinity to integer

**Comment by agiudiceandrea** [comment]
The issue doesn't occur using QGIS 3.28.
@strk, may it be related to recent changes in `QgsRectangle()`?
The issue semms due to the fact that since QGIS 3.34.0, `QgsRectangle()` returns 
`<QgsRectangle: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368, -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368 -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368>`
and `QgsRectangle().height()` returns `-inf` while in previous versions `QgsRectangle()` returns `<QgsRectangle: 0 0, 0 0>` and `QgsRectangle().height()` returns `0.0`.

**Comment by ReghardNell** [comment]
Can confirm that I have had the same issue when trying to open the Tin interpolation processing tool.


QGIS version
3.34.0-Prizren
QGIS code revision
ffbdd67881
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.7.2
Running against GDAL/OGR
3.7.3
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009




Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

**Comment by cesarcorreo** [comment]
Same problem with TIN and IDW interpolations.


Versión de QGIS
3.34.0-Prizren
Revisión del código de QGIS
ffbdd67881
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.7.2
Versión de PROJ
9.3.0
Versión del registro de base de datos EPSG
v10.094 (2023-08-08)
Versión de GEOS
3.12.0-CAPI-1.18.0
Versión de SQLite
3.41.1
Versión de PDAL
2.5.5
Versión del cliente de PostgreSQL
15.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.4
Versión del SO
Windows 10 Version 2009




Complementos activos de Python
ClipMultipleLayers
3.2.0
color_attribute
0.2.1
dataexplorer
3.1.1
DataPlotly
4.0.3
geetimeseriesexplorer
2.0
GroupStats
2.2.7
ImportPhotos
3.0.5
kmltools
3.1.31
LayerBoard
1.0.1
LinearReferencing
1.0.2
mapflow
2.3.0
mapswipetool_plugin
1.2
mmqgis
2021.9.10
OSMDownloader
1.0.3
PluginLoadTimes
4.0.2
pointsamplingtool
0.5.4
polystrip
3.0.1
postgisQueryBuilder
2.0.1
processing_saga_nextgen
1.0.0
profiletool
4.3.0
qfieldsync
v4.6.0
Qgis2threejs
2.7.1
qgis2web
3.16.0
QGISSortAndNumber-master
1.0
QGIS_Dashboard-master
0.1
quick_map_services
0.19.33
refFunctions
1.6
rvt-qgis
0.9.6
searchlayers
3.0.14
SelectionFilter
1.0
SentinelHub
2.0.2
Serval
3.32.0
Spanish_Inspire_Catastral_Downloader
2.0
SpreadsheetLayers
2.1.0
SRTM-Downloader
3.2.1
StreetView
3.2
valuetool
3.0.17
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

**Comment by robricks86** [comment]
I, too, am experiencing this same issue and it is critical to my project. I am dead in the water until this issue is resolved.

**Comment by agiudiceandrea** [comment]
@robricks86, you can use QGIS 3.28 LTR.

**Comment by robricks86** [comment]
Thanks, I will!
