### ISSUE TITLE
plugin IBGE

### ISSUE THREAD

**Issue by moreiraalves** [qgis/QGIS#55192]
### What is the bug or the crash?

Instalei o complemento IBGE, porem quando coloco o estado aparece:
Erro Python: Um erro ocorreu enquanto executava o código Python: Consulte o registro de mensagens (Erro Python) para mais detalhes.

ja tentei em varias versões, porem sem sucesso 

### Steps to reproduce the issue

va complementos;
click em gerenciar e instalar complementos;
procure IBGE; instale
depois clica no icone IBGE, seleciona o estado e ja aparece o erro 

### Versions

Versão do QGIS
3.28.12-Firenze
Código da versão do QGIS
dcc633b2de
Versão Qt
5.15.3
Versão do Python
3.9.5
Versão GDAL/OGR
3.7.2
Versão PROJ
9.3.0
Versão da base de dados do registro EPSG
v10.094 (2023-08-08)
Versão GEOS
3.12.0-CAPI-1.18.0
Versão SQLite
3.41.1
Versão PDAL
2.5.5
Versão cliente PostgreSQL
unknown
Versão SpatiaLite
5.1.0
Versão QWT
6.1.6
Versão QScintilla2
2.13.4
Versão OS
Windows 10 Version 2009

Plugins Python ativos
dados_censo
0.40
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

conversando com outros usuarios tAMBEM RELATARAM O MESMO PROBLEMA

**Comment by agiudiceandrea** [comment]
@moreiraalves, if I understand correctly, you are reporting a QGIS plugin issue. As stated in the "New issue" page: "If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS core team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)".
If it is not the case, please reopen this issue report and add an English description with detailed info on the issue.
