### ISSUE TITLE
MetaSearch does not support OGC API

### ISSUE THREAD

**Issue by frafra** [qgis/QGIS#55384]
### Feature description

MetaSearch allows adding resources from a CSW endpoint. It supports various type of protocols, but not OGC API. Since usage of OGC API are gaining traction and support for OGC API Features has been added to QGIS (it is possible to add a "WFS/OGC API" layer), it would be useful to be able to add support for that in MetaSearch as well.

**Comment by agiudiceandrea** [comment]
@frafra, thanks for suggestion. Anyway, I'm closing this feature request as "duplicate", since it seems to me the feature has been already requested https://github.com/qgis/QGIS/issues/41568, although not yet implemented. If you think your request is different from the previous one, please add a comment describing the difference.
