### ISSUE TITLE
Layer-properties-Attribute form: allow a set of Strings as entries but nothing else using a dropdown menu

### ISSUE THREAD

**Issue by firefoxlover** [qgis/QGIS#55415]
### Feature description

When you digitize objects, you might have discrete cathegories:

- street
- building
- water

If you create string entries in the attribute table though, there seems to be no way to disable "allow editing" and preset an array of multiple entries that the  creator can then choose from.

### Additional context

ChatGPT and internet searches couldnt find anything close. Some things like "Value Relation" or "Widgets" I couldnt find so I guess they are gone?

This is extremely important for sharing maps, and in general mapping discrete objects. Currently I have to workaround this using a clipboard or external text file, which is completely bad.

Having an easy way for Attribute table rows to set
- allow a set of strings

with the presets:
- no editing allowed
- but be not null

would be of great help!

Then in the for example polygon creation dialog, you would have a dropdown menu for the field instead of a freeform text entry, or autocompletion

**Comment by DelazJ** [comment]
Please look at the layer properties --> [Attributes Form](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#configure-the-field-behavior) tab and you will probably find your answers.

**Comment by firefoxlover** [comment]
Yes I mean that form. I could not find this feature

**Comment by DelazJ** [comment]
Did you try the "unique values" or "value map" widget types?

**Comment by zezzagio** [comment]
I don't understand. Do you want a check for already present values, or a widget for entring or changing the value?
If new entries should be allowed, then the field must be editable, of course. Then you have "Value map", "Value relation" and "Unique values" widgets to chose from. They allow an "array of multiple entries" to chose from, with a drop down menu for "Value map" and "Value relation".

**Comment by firefoxlover** [comment]
I find it pretty confusing to need some widgets and all? I dont know.

I just want to label objects with discrete values, not variable.

So when creating polygons and filling in the attributes, I have 5 values as option and nothing more, with NOT NULL, and NOT EDITABLE etc. set.

If there is another way that would be great of course but the FR is to make this more accessible through the normal labelling options.

**Comment by zezzagio** [comment]
Talking about confusing, NOT EDITABLE means NOT EDITABLE: the user can't put any value in it, it's not theyr concern, this is a read only value or a value automatically assigned by the application.
But you want to chose a value; this means EDITABLE.

It seems you are asking to change the entire logic of the interface, in order to achieve something that's allready achieavable in at least 3 ways: unique values, value map, value relation.
This is the value map widget definition, from the manual:

> Value Map: A combo box with predefined items. The value is stored in the attribute, the description is shown in the combo box. You can define values manually or load them from a layer or a CSV file.

To me it seems exactly what you want. Your proposal seems just another confusing way, with (to me) confusing logic, to do the same thing. I am maybe biased by years of use of QGis, but so are a lot of QGis users.
Or maybe I still don't understand.

**Comment by DelazJ** [comment]
@zezzagio I think, by "not editable", @firefoxlover meant the options would not be editable; just only the 5 options forever.
@firefoxlover you want a combobox with specific values. But that is your use case. Someone else may want a combobox allowing NULL, or editable value, or another type of widget like calendar, or file picker, or .... At this point you see there are many different ways one could fill their layer attributes and not all the options could be directly exposed in the attribute table (and you'll agree that your use case is not superior to the other ones). This is why the default way to fill attribute table is by typing the values in the cell (which works for every case), and if you need something specific because of your data, there is a dialog where to pick what is more suitable among the different possibilities (aka the forms properties tab). Have you at least tested the options previously suggested?
What I can retain from this thread is maybe to provide a button from within the attribute table to access the attribute form properties tab. But I don't think exposing those options within the attribute table would make sense and not confuse users.
Hope that clarifies!

**Comment by zezzagio** [comment]
Then I think this could only be achieved by a constraint or a type definition in the data source: an "enum" in PostgreSQL for example, but this works only on PostgreSQL.

@firefoxlover Would you want to try this project? is this what you want to achieve?
https://github.com/zezzagio/qgis_value_map

**Comment by firefoxlover** [comment]
Hey, thanks for your help! I am very new and also to SQL, so I tried to achive this somehow but didnt find a way.

I also didnt find any button or menu or anything saying "widgets" so this didnt occur to me.

If there is some menu with presets, plus you can insert any custom sql widget in there, this would be great. 

I dont think "my use case" is rare though. For maany projects you would want cathegories with fixed values, and avoid issues in the table by allowing easy input of those. I will try to load that widget

**Comment by firefoxlover** [comment]
To make it unstale:

If this (in my eyes essential) feature already exists, there needs to be a change in UI to make it accessible. I could not find it.

At least having a dropdown menu with previously used polygon names is essential to avoid spelling mistakes.

The workaround is to use clipboard history of the OS which is pretty bad.

**Comment by DelazJ** [comment]
@firefoxlover Did you read the docs link previously suggested or tested the project @zezzagio uploaded for you? Because what you ask already exists and works that way. You just HAVE to configure it as this is not a "model" that applies to all digitizing scenarios. The configuration is done in the layer properties --> Attributes form, selecting a field and in the right tab replacing "text edit" entry with the widget type you want (in your case ["value map" or "unique values"](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#edit-widgets) should be appropriate).
Hope that clarifies...

**Comment by zezzagio** [comment]
@firefoxlover UIs can always be improved, 'accessible' features made more accessible, 'intuitive' commands made more intuitive... but at some point, you have to resign yourself to learning something. Not everything can be made immediate, and not for everyone, especially if the operations to be performed are complex, like those carried out by QGIS.

Not everyone has the same notion of what is 'accessible' and obvious; furthermore, UIs build users too: a lot of QGis users got accostumed to its UI as it is, however convoluted it may seems to you; this must be taken into account when considering what can or cannot be changed.

Please, read the suggested documentation; you can find all you need at [attributes form properties](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#). Many tutorial can be found even on other sources, like Youtube.
