### ISSUE TITLE
3DTiles: QGIS fails to render the transparency that Skyline's 3DTiles set to the floor tiles

### ISSUE THREAD

**Issue by yanivday** [qgis/QGIS#55579]
### What is the bug or the crash?

Skyline is a leading provider of 3D earth visualization software. It provides 3D Tiles mesh layers with an embedded Floor (DTM), in addition to the mesh texture. Loading the mesh layer, QGIS fails to render the transparency that Skyline's 3DTiles set to the floor tiles. As a result, we can see white areas where the floor penetrates the mesh's texture. 
![Screenshot 2023-12-12 145604](https://github.com/qgis/QGIS/assets/48534097/c207e215-2c3b-45c6-8fb6-11c3be0f80fc)

### Steps to reproduce the issue

1. Open QGIS
2. Load Scene > URL = https://cloud.skylineglobe.com/sg/demos/b3dm/857700/tileset.json
3. Note the white areas, which should be transparent. 

### Versions

 QGIS 3.34.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Can you share a site showing what these tiles are supposed to look like?

**Comment by yanivday** [comment]
Hi, 
I appreciate your response.
Here is a web project of the same dataset:
https://cloud.skylineglobe.com/sg/tef/te.html?project=https://cloud.skylineglobe.com/sg/tutorialvideos/projects/washu.898400
![3](https://github.com/qgis/QGIS/assets/48534097/ec42921b-be31-4666-8b2a-1463b8722400)

Otherwise, you can load the 3Dtiles to ESRI ArcGIS Online:

1. Connect to https://www.arcgis.com/home/webscene/viewer.html
2. Sign in with an ArcGIS account.
3. Click the + button > ArcGIS Web Service > Enter Layer URL: https://cloud.skylineglobe.com/SG/demos/arcgis/rest/services/857700/SceneServer 
4. Click Add Layer
![2](https://github.com/qgis/QGIS/assets/48534097/4f4bb42e-4dae-43fe-a700-02c6b56012e5)

**Comment by yanivday** [comment]
You can also load it with Cesium Sandcastle:

1. Browse to: https://sandcastle.cesium.com/
2. Add the following JavaScript code, and click Run:

const viewer = new Cesium.Viewer("cesiumContainer", {
  terrain: Cesium.Terrain.fromWorldTerrain(),
});

try {
  const tileset = await Cesium.Cesium3DTileset.fromUrl('https://cloud.skylineglobe.com/sg/demos/b3dm/857700/tileset.json');
  viewer.scene.primitives.add(tileset);
  viewer.zoomTo(tileset);
} catch (error) {
  console.log(`Error loading tileset: ${error}`);
}



![5](https://github.com/qgis/QGIS/assets/48534097/09493c9d-8484-4f81-8728-31e70c0fd512)

**Comment by yanivday** [comment]
Hi,
Has this been reviewed?

**Comment by yanivday** [comment]
Hi @nyalldawson, Were you able to look at it?

**Comment by Skyline4Airwise** [comment]
Hi @nyalldawson , how can we promote this? Do you need any other information we can provide?

**Comment by P-SLISSE** [comment]
Hello,
I've had the same issue with 3DTiles produced with Skyline software.
In the 3DTiles, there is some meshes with transparency value 0.0; this ones are displayed by QGis as it doesn't use the transparency of the material

                "materials":[
{
"alphaMode":"BLEND",
"name":"m0",
"pbrMetallicRoughness":
{
"baseColorFactor":[0.80000001192092896,0.80000001192092896,0.80000001192092896,**_0.0_**],
"metallicFactor":0,
"roughnessFactor":1
}
}]

I agree it would be great if QGis can use the transparency.

Other solutions :
*) There is an option when Skyline exported the 3DTiles files : you can say not to export embedded floor. In fact, that embedded floor is just unuseful in 3DTiles.

*) With CesiumGS/3d-tiles-tool you can identify the b3dm files who doesnt have textures but only materials -> this ones are the embedded floor files
Use b3dmToGltf so you can see the b3dm files which don't have an associated texture
When identified, I remove the b3dm files from the data and the problem is solved

I think the solution can be on both sides :
*) On short terms, don't produce 3DTiles containing embedded floor 
Other softwares like Bentley Context Capture or Metashape don't integrate embedded floor so you don't encouter this issue
*) On middle terms, il would be great that QGis display meshes according to transparency value

I hope this will help

**Comment by saberraz** [comment]
I am not sure if this is a bug or an unsupported feature (see https://www.lutraconsulting.co.uk/blog/2023/11/16/3d-tiles-in-QGIS/)

You can always directly contact Nyall or Lutra to address the issue.

**Comment by yanivday** [comment]
Hi @nyalldawson and the team, 
Thanks for your effort in implementing this! Greatly appreciated. 
Is there a beta or a nightly version we can test (3.360.0)?
