### ISSUE TITLE
Cannot create multipart feature in a shp file.

### ISSUE THREAD

**Issue by CoachGD** [qgis/QGIS#55684]
### What is the bug or the crash?

I have a shape file layer and wanted to create a multipart feature. Therefore I've used the following workflow.
1. Select the feature.
2. Toggle editing.
3. Add Part (from the Advanced Digitizing Toolbar)
4. Draw new geometry.
5. Save.

However once saved the feature is only selectable within the original geometry. I have also then tried to split the multipart feature only to see a log message that the polygon is not a multipart feature!

What am I doing wrong? Is there a known bug with shp format? Note I don't get the same error when following the same steps in a gpkg file.

### Steps to reproduce the issue

See bug.

### Versions

3.28.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@CoachGD, thanks for reporting. Please provide the full QGIS version info as requested in the issue report form ("Versions
In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.").
I suppose the reported issue is the same already previously reported at https://github.com/qgis/QGIS/issues/54537 and fixed with PR https://github.com/qgis/QGIS/pull/54761 since QGIS 3.28.12.
