### ISSUE TITLE
Column aliases are not written to geopackage when editing them in Attributes form window

### ISSUE THREAD

**Issue by Hajna** [qgis/QGIS#55821]
### What is the bug or the crash?

related issue: https://github.com/qgis/QGIS/issues/47344

 **context**: column aliases are not written to geopackage when editing them in Attributes form window.

**problem**: there is no way (at least through UI) to edit aliases of existing columns

if this is expected behavior, please excuse me and close this issue.

when creating a new field, we can set up its alias, which is then stored to geopackage system table (gpkg_data_columns)
however for existing fields, the option to set up the alias is not enabled

reading the related issue, it is evident that alias setting has been moved to Attributes form window,
however, setting the alias in the Attributes form, does not save its value to gpkg_data_columns table

### Steps to reproduce the issue

Create a new geopackage with one dummy field  
  
![image](https://github.com/qgis/QGIS/assets/44726555/9d3d2853-f75b-407e-927b-a3b86f32f41f)

Opening the layer properties and navigating to Field section, you are unable to edit the field alias  
  
![image](https://github.com/qgis/QGIS/assets/44726555/b6fd1b75-8629-47ad-ba70-409863b9235a)

When adding a new field, we are able to set its alias  
  
![image](https://github.com/qgis/QGIS/assets/44726555/e4db8d5d-81e2-46dd-af7a-6af0e682f578)

which is in return stored to the gpkg_data_columns system table  
  
![image](https://github.com/qgis/QGIS/assets/44726555/29fdbf82-4c25-4931-8575-3006417884a7)

if we try to set the alias in the Attributes forms, the alias is not stored to the system tables, and it does not persist if we try to remove and reload the layer:  
  
![image](https://github.com/qgis/QGIS/assets/44726555/70248ecd-76f8-460d-8672-f00d786c3013)

### Versions

3.34.2-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by phidrho** [comment]
Hi,

alias field in Layer Properties panel is saved within QGIS project, and is not pushed back to layer data source. Therefore this is an expected behavior, because you are not editing layer this way, but only representation within QGIS application. Since QGIS supports many data formats, and only some can have Aliases written inside the data source. So this is actually not a bug report but rather an Feature request for special case (when data is stored in GPKG).

You can access Alias editing on Browser panel, then it will be stored inside GPKG as you expect:
![image](https://github.com/user-attachments/assets/7d2cff2a-9616-4698-bcc7-f4e9d7a7e36f)

**Comment by phidrho** [comment]
@agiudiceandrea
Can we change label to Feature request or close bug report since there is no response from @Hajna?
