### ISSUE TITLE
Fill Sink Wang and Liu dont work and can not create right layers 3.34.2 QGIS. 

### ISSUE THREAD

**Issue by konsvord** [qgis/QGIS#55887]
### What is the bug or the crash?

Fill Sink Wang and Liu dont work and can not create right layers 3.34.2 QGIS. how can i fix it? 

### Steps to reproduce the issue

Fill Sink Wang and Liu dont work and can not create right layers 3.34.2 QGIS. how can i fix it? I hace plugin i set by options path at Saga GIS STILL dont work right it create some layers but they are wrong. Files is an aster dem for hydrology .

### Versions

3.34.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

saga gis problem

**Comment by agiudiceandrea** [comment]
@konsvord, thanks for reporting. QGIS 3.34 no longer natively supports SAGA-GIS processing algorithms. Are you using the "Processing Saga NextGen Provider" https://plugins.qgis.org/plugins/processing_saga_nextgen/ external plugin or any other external plugin? If yes, please file the issue report following the "Browse and report bugs" link in the plugin page.

**Comment by konsvord** [comment]
![problem](https://github.com/qgis/QGIS/assets/157079988/0086a6d6-a626-46d3-ba11-c678fd221398)
![Στιγμιότυπο οθόνης (150)](https://github.com/qgis/QGIS/assets/157079988/2c3fe281-ae27-4b27-aa2d-c5356d2acfea)
I know that and i have the plugin but still doesnt work.

**Comment by agiudiceandrea** [comment]
@konsvord thank you for confirming that you are using the external third-party plugin "Processing Saga NextGen Provider" https://plugins.qgis.org/plugins/processing_saga_nextgen/ 

As already written in my previous comment and as explained in the issue report page:

![image](https://github.com/qgis/QGIS/assets/16253859/9a11a1e5-29c3-436a-847d-603c2f4dbe45)

<<if the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS core team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)>>

The bug tracker for that specific plugin is at https://github.com/north-road/qgis-processing-saga-nextgen/issues
