### ISSUE TITLE
Cannot load specific WMS URL

### ISSUE THREAD

**Issue by fclof** [qgis/QGIS#56145]
### What is the bug or the crash?

In QGIS, when I tried to add WMS layer "https://tile.osgeo.cn/service?service=WMS", it says "failed to parse capabilities". 

However, "https://tile.osgeo.cn/service?service=WMS&request=GetCapabilities" can return a meaningful list of services.

When I re-open the WMS setting window, I found that it automaitcally swallowed everything after the "?", that is, only "https://tile.osgeo.cn/service" is remained.

I suspect that this issue is caused by this "automatically split by '?' " behavior.

### Steps to reproduce the issue

1.In "Browser", right click on "WMS/WMTS".
2.Choose "New Connection..."
3.Fill "https://tile.osgeo.cn/service?service=WMS" into "URL", give it a random name, and save it.

### Versions

3.32.0

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@fclof, thanks for reporting. It looks like The URL "https://tile.osgeo.cn/service?service=WMS&request=GetCapabilities" doesn't return a valid capabilities xml document but only a web page, so it is not a valid WMS server URL.

**Comment by fclof** [comment]
It seems that you shouldn't open the URL by clicking the link, but rather copy and paste it into the browser.

**Comment by agiudiceandrea** [comment]
@fclof, you are right. Anyway it looks like the xml document is malformed: in contains an error at line 10025 column 45 (and similar errors at other lines):
`      <Title>2014 U.S. SVI Minority Status & Language Score Distribution Map</Title>`
Such line contains an `&` character which is an escape character in XML and should be correctly escaped, otherwise an "Entity" name is expected to immediately follow the `&` character (which is not the case).
