### ISSUE TITLE
Duplicate Layer does not work on layers loaded with SQL Queries from GPKG

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#56345]
### What is the bug or the crash?

If I load a layer with SQL Query (from the Browser panel) starting from a GeoPackage and then duplicate it, and in the duplicated layer I delete the query, a different layer is displayed.

GPKG for example
[limitiISTAT2023.zip](https://github.com/qgis/QGIS/files/14277854/limitiISTAT2023.zip)

https://github.com/qgis/QGIS/assets/7631137/32d2f61c-1d55-4464-9dd1-bda717333230

### Steps to reproduce the issue

1. Start QGIS
2. from the layers panel, create a SQL query in a GeoPakage and load the layer;
3. duplicate the layer you just loaded in the layers panel and delete the query
4. the layer does not display the geometry of the starting layer, but will display a random layer present in the geopackage

## OSGeo4W 64b - win 11

QGIS version
3.35.0-Master
QGIS code revision
26ff0b7235
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.9.0dev-d7aed6e0b0
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
hsa
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

the problem is also present in QGIS 3.34.3

**Comment by pigreco** [comment]
It's probably not a bug, but you need:
1. disable duplicate layer for layers created via SQL query
2. warn the user that the described problem could occur with GPKGs

**Comment by agiudiceandrea** [comment]
@pigreco, doesn't also the original layer suffer of the same issue?

**Comment by pigreco** [comment]
> @pigreco, doesn't also the original layer suffer of the same issue?

Yes, if I delete the filter in the original layer, the layer from which I launched the query changes.

**Comment by agiudiceandrea** [comment]
So the issue is not only for duplicate layers.

**Comment by pigreco** [comment]
> Imagine a complex SQL query that involves the creation of a table on the fly built of various tables within the geopackage, or even simpler, a union between two point tables (e.g. SELECT geom,fid,name FROM table_1 UNION SELECT geom,fid,name FROM table_2). In those scenarios, you're not really filtering a layer per say.

I agree, but a warning would be useful, or disabling the Duplicate layer function in the context menu.

**Comment by agiudiceandrea** [comment]
@pigreco as stated in a previous comment, it seems to me the issue is not in the Duplicate functionality: it correctly duplicates the layer. In fact, also the original layer added to the project with an SQL Query from the Browser panel is affected by the described behaviour, not only the layer duplicated from such layer.

@nirvn, while you are correct, it looks like the issue is in the (inconsistent?) way the Browser adds the layer to the project when an SQL Query is executed.

1) When the GPKG sub layer is added to the project without a subset SQL query (right clicking on the sub layer and selecting "Add Layer to Project"), then it is added with source:
`/path/file_name.gpkg|layername=sub_layer_name` (note the presence of the `layername=` part)
and the sub_layer_name data is displayed

   If an SQL filter is subsequently added to the layer, then the source becomes:
`/path/file_name.gpkg|layername=sub_layer_name|subset=the_SQL_query` (note the presence of both the `layername=` part and the `subset=` part)
and the the_SQL_query result data is displayed

   If the SQL filter is subsequently removed, then the source becomes:
`/path/file_name.gpkg|layername=sub_layer_name` (note the presence of the `layername=` part)
and the sub_layer_name data is displayed

2) When the GPKG sub layer is instead added to the project with a subset query (right clicking on the sub layer and selecting "Execute SQL"), then it is added with source:
`/path/file_name.gpkg|subset=the_SQL_query` (note the missing `layername=` part)

   If the SQL filter is subsequently removed, the the layer source becomes:
`/path/file_name.gpkg` (note the missing `layername=` part)

   **Since the geopackage file contains more then one sublayer, and the `layername=` part is not present, then it is no longer clear what sublayer data will be displayed for such layer and the result is difficult to predict! For example, which sublayer will be affected by an editing session!!!**

   It seems to me this is a glitch, since there is no other way to add a multilayer GPKG with source `/path/file_name.gpkg` (without the `layername=` part), apart from adding it with an SQL query via Browser or DB Manager, and then remove the filter from the layer.


*** For consistency, I would suggest that, when the "Execute SQL" is executed for a sublayer, then the `layername=` part is added to the source of the layer besides the `subset=` part. After all the "Execute SQL" dialog window reports the layer name in the dialog title, so we are explicitly referring to the very layer

![image](https://github.com/qgis/QGIS/assets/16253859/a81e5b88-46cf-4031-a58e-11962c1c7f74)

**Comment by elpaso** [comment]
@agiudiceandrea while it is true that the SQL window displays the name of the layer from where it was invoked, it is also true that you can execute any query, not just queries on that layer.

Maybe we should replace the layer name in the window title with something that describes the connection (GPKG file name in case of GPKG, connection name in case of a client-server DB).

**Comment by agiudiceandrea** [comment]
> @agiudiceandrea while it is true that the SQL window displays the name of the layer from where it was invoked, it is also true that you can execute any query, not just queries on that layer.


@elpaso, this is also true when the SQL filter is added afterward. You can add a specific sublayer of the GPKG and then add an SQL "filter" which selects the features from another layer in the GPKG. Anyway in this case, removing the filter, the layer remains in a predictable state, since the `layername=` part is still there.

The issue IMO is that, the other way, the layer remains in an ambiguous state, since the `layername=` part and a random (?) GPKG sub layer is displayed. You can also start an edit session for such layer, but which sublayer are you actually editing?
