### ISSUE TITLE
When I used  'r.fill.dir', occur error "Concurrent mapset locking is not supported on Windows" in Windows 11 x64

### ISSUE THREAD

**Issue by SeongjunLee4473** [qgis/QGIS#56782]
### What is the bug or the crash?

QGIS 버전: 3.36.0-Maidenhead
QGIS 코드 리비전: 09951dc0
Qt 버전: 5.15.3
파이썬 버전: 3.9.18
GDAL 버전: 3.8.4
GEOS 버전: 3.12.1-CAPI-1.18.1
PROJ 버전: Rel. 9.3.1, December 1st, 2023
PDAL 버전: 2.6.0 (git-version: 3fced5)
알고리즘이 2024-03-09T19:43:29 에서 시작했습니다
'r.fill.dir' 알고리즘 시작…
입력 파라미터:
{ '-f' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'areas' : 'TEMPORARY_OUTPUT', 'direction' : 'TEMPORARY_OUTPUT', 'format' : 0, 'input' : 'C:/Users/LeeSeongjun/Downloads/n36_e127_1arc_v3 (1).tif', 'output' : 'TEMPORARY_OUTPUT' }

g.proj -c wkt="C:/Users/LeeSeongjun/AppData/Local/Temp/processing_YByKvJ/106bea6b37a74032b5bdc7c8f9ab468e/crs.prj"
r.in.gdal input="C:\Users\LeeSeongjun\Downloads\n36_e127_1arc_v3 (1).tif" band=1 output="rast_65ec3d518df983" --overwrite -o
g.region n=37.000138888888884 s=35.99986111111111 e=128.0001388888889 w=126.99986111111112 res=0.000277777777777779
r.fill.dir input=rast_65ec3d518df983 format="grass" output=outputd78de7f357cf49698c38179759c71e91 direction=directiond78de7f357cf49698c38179759c71e91 areas=areasd78de7f357cf49698c38179759c71e91 --overwrite
g.region raster=outputd78de7f357cf49698c38179759c71e91
r.out.gdal -t -m input="outputd78de7f357cf49698c38179759c71e91" output="C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\e4fc083920d74956af7e4b0af6fcd44e\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=directiond78de7f357cf49698c38179759c71e91
r.out.gdal -t -m input="directiond78de7f357cf49698c38179759c71e91" output="C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\6fb33571db534d8093f083474d943047\direction.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=areasd78de7f357cf49698c38179759c71e91
r.out.gdal -t -m input="areasd78de7f357cf49698c38179759c71e91" output="C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\90e0e63c66fd4eadb2538c4a100c0fae\areas.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
**WARNING: Concurrent mapset locking is not supported on Windows**
C:\Users\LeeSeongjun\Documents>chcp 949 1>NUL
C:\Users\LeeSeongjun\Documents>g.proj -c wkt="C:/Users/LeeSeongjun/AppData/Local/Temp/processing_YByKvJ/106bea6b37a74032b5bdc7c8f9ab468e/crs.prj"
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
C:\Users\LeeSeongjun\Documents>r.in.gdal input="C:\Users\LeeSeongjun\Downloads\n36_e127_1arc_v3 (1).tif" band=1 output="rast_65ec3d518df983" --overwrite -o
Over-riding projection check
Importing raster map <rast_65ec3d518df983>...
0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
C:\Users\LeeSeongjun\Documents>g.region n=37.000138888888884 s=35.99986111111111 e=128.0001388888889 w=126.99986111111112 res=0.000277777777777779
C:\Users\LeeSeongjun\Documents>r.fill.dir input=rast_65ec3d518df983 format="grass" output=outputd78de7f357cf49698c38179759c71e91 direction=directiond78de7f357cf49698c38179759c71e91 areas=areasd78de7f357cf49698c38179759c71e91 --overwrite
C:\Users\LeeSeongjun\Documents>g.region raster=outputd78de7f357cf49698c38179759c71e91
ERROR: Raster map <outputd78de7f357cf49698c38179759c71e91> not found
C:\Users\LeeSeongjun\Documents>r.out.gdal -t -m input="outputd78de7f357cf49698c38179759c71e91" output="C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\e4fc083920d74956af7e4b0af6fcd44e\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
ERROR: Raster map or group <outputd78de7f357cf49698c38179759c71e91> not found
C:\Users\LeeSeongjun\Documents>g.region raster=directiond78de7f357cf49698c38179759c71e91
ERROR: Raster map <directiond78de7f357cf49698c38179759c71e91> not found
C:\Users\LeeSeongjun\Documents>r.out.gdal -t -m input="directiond78de7f357cf49698c38179759c71e91" output="C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\6fb33571db534d8093f083474d943047\direction.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
ERROR: Raster map or group <directiond78de7f357cf49698c38179759c71e91> not found
C:\Users\LeeSeongjun\Documents>g.region raster=areasd78de7f357cf49698c38179759c71e91
ERROR: Raster map <areasd78de7f357cf49698c38179759c71e91> not found
C:\Users\LeeSeongjun\Documents>r.out.gdal -t -m input="areasd78de7f357cf49698c38179759c71e91" output="C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\90e0e63c66fd4eadb2538c4a100c0fae\areas.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
ERROR: Raster map or group <areasd78de7f357cf49698c38179759c71e91> not found
C:\Users\LeeSeongjun\Documents>exit
계속하려면 아무 키나 누르십시오 . . .
Execution completed in 18.48 초
Results:
  output: C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\e4fc083920d74956af7e4b0af6fcd44e\output.tif
  direction: C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\6fb33571db534d8093f083474d943047\direction.tif
  areas: C:\Users\LeeSeongjun\AppData\Local\Temp\processing_YByKvJ\90e0e63c66fd4eadb2538c4a100c0fae\areas.tif

산출 레이어 불러오기
다음 레이어가 제대로 생성되지 않았습니다.
• C:/Users/LeeSeongjun/AppData/Local/Temp/processing_YByKvJ/6fb33571db534d8093f083474d943047/direction.tif
• C:/Users/LeeSeongjun/AppData/Local/Temp/processing_YByKvJ/90e0e63c66fd4eadb2538c4a100c0fae/areas.tif
• C:/Users/LeeSeongjun/AppData/Local/Temp/processing_YByKvJ/e4fc083920d74956af7e4b0af6fcd44e/output.tif
알고리즘 실행과 관련된 더 많은 정보를 찾으려면 QGIS 메인 창에서 '로그 메시지 패널'을 확인하면 됩니다.

### Steps to reproduce the issue

1. Drag DEM(tiff file) to layer tab.
2. Search 'r.fill.dir' in toolbox and click it.
3. Select DEM layer and run.

### Versions

3.34.4 LTR and 3.36.0 RC

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@SeongjunLee4473, thanks for reporting. The "Concurrent mapset locking is not supported on Windows" message logged is not an error message, it is only a warning message.
Anyway it looks like the algorithm doesn't correctly create the output raster layers.
Please provide the layer with which the issue occurs.
Please also provide the full version info about QGIS as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.").

**Comment by SeongjunLee4473** [comment]
@agiudiceandrea thanks for reply. I attached tiff file used at QGIS and here the full version info about QGIS

QGIS 버전
3.36.0-Maidenhead
QGIS 코드 리버전
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009




Active Python plugins
SemiAutomaticClassificationPlugin
8.2.2
tmsforkorea
3.0.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

[n36_e127_1arc_v3.zip](https://github.com/qgis/QGIS/files/14546665/n36_e127_1arc_v3.zip)

**Comment by agiudiceandrea** [comment]
@SeongjunLee4473, the issue is due to the fact that the GRASS-GIS module r.fill.dir.exe crashes during the computation of the whole provided raster layer: such issue is not a QGIS issue and should be reported to the [GRASS-GIS GitHub repository](https://github.com/OSGeo/grass/issues).
To avoid such issue, you need to set a "GRASS GIS region extent" parameter (in the processing algorithm's GUI section "Advanced Parameters") narrower than the input layer extent or use a smaller raster layer.
Anyway, even if, setting a narrower "GRASS GIS region extent" parameter, the r.fill.dir algorithm succeeds, the "Depressionless DEM" and "Flow Direction" output rasters will take several minutes to be imported in QGIS. This is due to a bug https://github.com/qgis/QGIS/issues/56652 in QGIS already reported which is being fixed https://github.com/qgis/QGIS/pull/56784 https://github.com/qgis/QGIS/pull/56677. So, until the bug is fixed, I suggest you to uncheck the "Open output file after running algorithm" for such output raster layers.

**Comment by agiudiceandrea** [comment]
@SeongjunLee4473, the issue is due to the fact that the GRASS-GIS module r.fill.dir.exe crashes during the computation of the whole provided raster layer: such issue is not a QGIS issue and should be reported to the [GRASS-GIS GitHub repository](https://github.com/OSGeo/grass/issues).
To avoid such issue, you need to set a "GRASS GIS region extent" parameter (in the processing algorithm's GUI section "Advanced Parameters") narrower than the input layer extent or use a smaller input raster layer.
Anyway, even if, setting a narrower "GRASS GIS region extent" parameter, the r.fill.dir algorithm succeeds, the "Depressionless DEM" and "Flow Direction" output rasters will take several minutes to be imported in QGIS. This is due to a bug https://github.com/qgis/QGIS/issues/56652 in QGIS already reported which is being fixed https://github.com/qgis/QGIS/pull/56784 https://github.com/qgis/QGIS/pull/56677. So, until the bug is fixed, I suggest you to uncheck the "Open output file after running algorithm" for such output raster layers. Otherwise, you can use QGIS 3.28.15, which is not affected by the https://github.com/qgis/QGIS/issues/56652 issue, in the meantime.
