### ISSUE TITLE
Plugin list unavailable

### ISSUE THREAD

**Issue by Bavarello** [qgis/QGIS#57245]
### What is the bug or the crash?

I can not see the list of plugins.

Edizione	Windows 11 Pro
Versione	23H2
Data installazione:	‎27/‎12/‎2023
Build sistema operativo	22631.3447
Esperienza	Windows Feature Experience Pack 1000.22688.1000.0

### Steps to reproduce the issue

Going under Plugins / manage and install plugins / settings says "not available":

URL https://plugins.qgis.org/plugins/plugins.xml
PARAMETERS? Qgis = 3.36

I can not see the list of plugins,

<img width="927" alt="image" src="https://github.com/qgis/QGIS/assets/22433856/400eb04b-556f-4756-b252-5b7ac8ad8443">

### Versions

![image](https://github.com/qgis/QGIS/assets/22433856/822cca99-a0d2-46bf-8128-fee8d5d136fe)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

![image](https://github.com/qgis/QGIS/assets/22433856/744172ad-4e7e-4040-b3d9-424e3af95a9f)

Thanks for the attention

**Comment by rduivenvoorde** [comment]
@Bavarello is this still true for you? For me all is ok (at this moment)

Can you get this url in a browser?
https://plugins.qgis.org/plugins/plugins.xml?qgis=3.36

Or are you maybe in an environment where you need to use a Proxy to access the web?

**Comment by Bavarello** [comment]
Unfortunately, I still haven't been able to understand if it's a problem with my PC or with QGis.
I don't have to access via proxy, I have direct access to the internet.
Thanks you for feedback.

**Comment by agiudiceandrea** [comment]
> However at the following address:\nhttps://plugins.qgis.org/plugins/plugins.xml\n\nthe response is: 404 Not Found

It is normal. You have to check the URL https://plugins.qgis.org/plugins/plugins.xml?qgis=3.36 as requested.

**Comment by Bavarello** [comment]
> It is normal. You have to check the URL https://plugins.qgis.org/plugins/plugins.xml?qgis=3.36 as requested.

With this address there is no access problem except that from within QGis access to the official plugin repository is given by the following:

https://plugins.qgis.org/plugins/plugins.xml

QGIS.ini

<img width="1324" alt="image" src="https://github.com/qgis/QGIS/assets/22433856/9b818b86-1f5d-46b8-b022-1869c7115dd6">

**Comment by agiudiceandrea** [comment]
> within QGis access to the official plugin repository is given by the following:
> 
> https://plugins.qgis.org/plugins/plugins.xml

It is normal. QGIS always adds the `?qgis=` part to the base URL before fetching the plugin list:

https://github.com/qgis/QGIS/blob/0f9e0cbd61d633fdbcc170ed10ae2fd4981edc96/python/pyplugin_installer/installer_data.py#L214-L217

https://github.com/qgis/QGIS/blob/0f9e0cbd61d633fdbcc170ed10ae2fd4981edc96/python/pyplugin_installer/installer_data.py#L285-L289

You can check the actual URL fetched by QGIS using the Network Logger in the Debugging/Development Tools panel https://docs.qgis.org/3.34/en/docs/user_manual/introduction/general_tools.html#network-logger.

Anyway the reported issue looks like a local issue due to some proxy / firewall / other interfering software that intercepts / filters / blocks Internet requests made by QGIS.

**Comment by Bavarello** [comment]
All this with a fresh and clean installation

<img width="774" alt="image" src="https://github.com/qgis/QGIS/assets/22433856/717085ff-8310-414d-8384-c036db135465">

**Comment by rduivenvoorde** [comment]
And in a your internet browser it works? 

It looks you have a 'timeout', going to plugins.qgis.org.

Did this ever work? Or is this the first time you are using QGIS?

How did you install QGIS (or who dit how)?

I know Windows has a 'firewall', can you check(disable) that? 
Is it possible that QGIS is (by Windows) not allowed to go to the internet?

**Comment by Bavarello** [comment]
I did a clean install via OSGeo4W.
My internet connection via browser (Google) is normal, no problems.
The previous version of QGis (3.36.1) worked without problems.

**Comment by Gjanosh61** [comment]
Some time ago I reported in the forum that I could no longer automatically update the plugin list in QGIS.

After about a year of attempts and research, I finally identified the problem: the block was caused by Google DNS (8.8.8.8 and 8.8.4.4). By changing the DNS to those of **Cloudflare (1.1.1.1 and 1.0.0.1)**, I was able to resolve the situation.

Since then, the plugin update works correctly, except for a few rare attempts needed to complete the operation.

QGIS version: 3.42.2

I hope this solution can be useful to other users who find themselves in the same situation!
