### ISSUE TITLE
The race for new functionality is killing QGIS. Fix bugs and make QGIS stable again.

### ISSUE THREAD

**Issue by erydit** [qgis/QGIS#57298]
### Feature description

Dear development team and contributors!

Each new release QGIS adds new functionality. And today, QGIS is truly one of the most impressive open source projects, without which I cannot imagine my professional activity. 

Releases and development roadmap is planned for the year ahead and is strictly followed by the development team. It is quite clear that the [development plan](https://www2.qgis.org/en/site/getinvolved/development/roadmap.html) is aimed primarily at constantly expanding the capabilities of the program. And as far as one can judge (and as, unfortunately, practice shows), the roadmap is not capable of ensuring the stability of the software product.

QGIS works great... well, as long as your project remains fairly simple. But as soon as you want to delve into the program's capabilities (complex multi-level styles, formatting captions using HTML, map layouts using the capabilities of the atlas and various map design themes, complex data processing models, etc.), you will be disappointed due to the inability to use the program functionality because of a bug that you will definitely encounter. Even if you use LTR version.

Of course, complex projects give rise to difficult-to-track bugs. And it seems that such bugs can remain uncatched for years. The oldest bugs in the issues tracker have been published in 2012 and even in 2009  year, and these bugs are still reproducible in 2024! Doesn't this mean that the roadmap is not capable of ensuring stable operation of the program?

I'm not a developer or a professional programmer. But what I see is that QGIS works worse and worse with each release. They added many new features, yay! ...Which again broke the old one.

**Comment by NathanW2** [comment]
While I can understand the frustration a qep isn't the right place for this
discussion.  This type of this is better placed on the mailing lists.

I can assume you the development team takes stability seriously and efforts
are always being made to make the product more stable.   Every growing
features is the nature of software especially something as widely used as
QGIS in many industries.

**Comment by nyalldawson** [comment]
This isn't an actionable ticket. Please file individual tickets for any specific regressions you encounter.

**Comment by Guts** [comment]
Thanks @erydit for taking the time to write your feedback even it's not the right place to do.

As mentioned by @NathanW2, and while waiting for the migration to Discourse, which would facilitate this kind of discussion, could you please send your message to the PSC and/or dévs and/or users mailing lists?

You'll need an OSGeo account to register to a list: https://qgis.org/en/site/getinvolved/mailinglists.html

To answer your question on the substance (which sounds more like a general impression than a list of tickets), I admit that I regularly get this kind of feedback from users who keep a "fragile" or unstable image of QGIS and turn it into a secondary GIS software when they have the financial means to use something else (i.e. Esri). Lately, I had talks about the sudden version change of Python (3.9 ---> 3.12) in the middle of the LTR, or the resurgence of self-merged PRs observed by informed professionals via semi-auto sensors to measure the quality of a project, continue to contribute to this image of a tinkerer's software. Oh and, of course, I always get the perennial question about the real difference between atlas mode and report mode, which seem to do the same thing but not exactly (same, same but different), and to know which one to invest in terms of skills.

I sometimes have to argue strongly to convince important organizations to link their value chains to a GIS foundation built around QGIS.  
But to see the bright side, it's also the best way to spark a discussion about their willingness and capacity to invest in strengthening and stabilizing the software (and its dependencies). This gives me the opportunity to discuss the involvement and the virtuous circle of open source with the goal to making them not only consumers but also contributors. Because, sadly, it's much more easy to raise funds for a new super cool feature or just a feature required by the ecosystem evolution (LiDAR, 3D, etc.) than raising funds to fix bugs and increase stability.

For a couple of years, I have been convinced that the QGIS project should place 'classical' end users (not people like me ;) ) more at the center of the project's direction to balance the emphasis given to developers. The migration to Discourse is a step in the right direction.

See? You definitely should start a thread somewhere else to have a proper discussion out of developer realm :wink:!
