### ISSUE TITLE
Running gdal_rasterize from QGIS produces incorrect output

### ISSUE THREAD

**Issue by mjb62** [qgis/QGIS#57341]
### What is the bug or the crash?

Using memory layer as 'Input Vector Layer' for 'Rasterize (overwrite with attribute)' tool only appears to process first feature.

### Steps to reproduce the issue

Was exploring use of the Earthworks tool in the CivilEng plug-in and got an unexpected output. Looked into the python code and simulated the steps in code using tools in QGIS, generating memory layers from each tool as inputs for the next tool. Eventually built the workflow using Model Builder, and output memory layer to debug. Problem is with 'Rasterize (overwrite with attribute)'. When using memory layers QGIS outputs 'gdal_rasterize -l layer_name -a cut_level path_to_data_file C:/Users/Michael/AppData/Local/Temp/processing_rFMGpa/26c31b9d26754c6da6ab0e4549c1f483/OUTPUT.tif'. Exported memory layer as local files and from terminal ran 'gdal_rasterize -l values -a cut_level values.shp dem.tif' and got expected result. Tried again in QGIS using combinations of local files and memory layers and only got the expected output when using local file for 'Input Vector Layer'.

### Versions

QGIS version
3.36.1-Maidenhead
QGIS code revision
3e589453
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
CivilEng
0.2
Go2NextFeature3
2.1
HCMGIS
24.1.12
joinmultiplelines
Version 0.4.1
kmltools
3.1.33
pcraster_tools
0.3.0
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qgis_resource_sharing
1.0.0
quick_map_services
0.19.34
Serval
3.32.0
valuetool
3.0.19
whitebox_workflows_for_qgis
1.2.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@mjb62, thanks for reporting. I cannot replicate the described behaviour using QGIS 3.36.2 on Windows.

https://github.com/qgis/QGIS/assets/16253859/02cf03c3-ec7f-4c1f-8827-e600a48594ff

Please provide a the full processing algorithm's log and a simple project and layers and exact steps and parameters in order to replicate the issue. Since the issue is related to a "memory" layer, you can use the "Memory Layer Saver" plugin or provide steps or Python script to create the memory layer in a reproducible way.

**Comment by mjb62** [comment]
Since reporting the issue I’ve uninstalled, reinstalled, restarted … no change. As indicated in the initial post the results are repeatable using the CivilEng plug-in Earthworks tool. I also included a .model3 file that does almost the same thing as the CivilEng plug-in.

**Comment by mjb62** [comment]
Michael Barnett would like to recall the message, "[qgis/QGIS] Running
gdal_rasterize from QGIS produces incorrect output (Issue #57341)".

**Comment by mjb62** [comment]
[rasterize_problem.zip](https://github.com/qgis/QGIS/files/15209203/rasterize_problem.zip)

**Comment by agiudiceandrea** [comment]
@mjb62, since you have closed the issue, does this means that you have managed to fix it?

**Comment by mjb62** [comment]
I’ve never used GitHub before. Didn’t realise I’d closed it. Couldn’t figure out how to re-open it.

**Comment by agiudiceandrea** [comment]
@mjb62, I've reopened the issue report.
Anyway in the issue report you claimed that the "Rasterize (overwrite with attribute)" processing algorithm doesn't work well with memory layers. As you can see in the previously provided screen recording, such processing algorithm works without issues using a memory layer. May you please check if it also actually works well in your system and report back? If it works as expected, then the issue may be in your model probably not in the "Rasterize (overwrite with attribute)" processing algorithm. May you please try a very simple model almost only involving such processing algorithm and check if the result is correct?
As you can see in the following screen recording, I've created a simple model using a memory layer as input, processing it through the Buffer algorithm and using its output as input of the "Rasterize (overwrite with attribute)" algorithm: it seems to me to model output is the expected and correct one:

https://github.com/qgis/QGIS/assets/16253859/016d0a83-3cc4-4e76-9222-f0a431f9e3e4

**Comment by mjb62** [comment]
[log_memory_layer.txt](https://github.com/qgis/QGIS/files/15209682/log_memory_layer.txt)
[log_file_layer.txt](https://github.com/qgis/QGIS/files/15209683/log_file_layer.txt)
https://github.com/qgis/QGIS/assets/72381417/083ad1ed-7a9a-417f-9255-93163c8cddc6

**Comment by agiudiceandrea** [comment]
@mjb62 , thanks for adding more details.

The issue is due to the fact that:
- the provided ESRI Shapefile vector file layer "values" has a field named "fid" and all the 100 features contained in such layer have the value "74" in such field.
- a GDAL/OGR external program cannot directly process QGIS vector "memory / scratch" layers
- if a vector memory layer is used as input of a GDAL/OGR processing algorithm which uses a GDAL/OGR external program, then QGIS needs to automatically export the vector memory layer to a file layer in order to use such file layer as input of the GDAL/OGR external program. In such case, QGIS exports the vector memory layer to a GeoPackage file layer.
- the "fid" field is a "special" field for the GeoPackage format as it must contain a unique value for each feature

When the ESRI Shapefile vector file layer "values" is directly used as input of the "Rasterize (Overwrite With Attributes)" GDAL/OGR processing algorithm, then it is directly used as input of the GDAL "gdal_rasterize" external program.

Instead, when the same 100 features are contained in a memory layer used as input of the GDAL/OGR processing algorithm, then QGIS automatically exports the memory layer to a GeoPackage layer and use the latter as input of "gdal_rasterize": since all the 100 features have the same value in the "fid" field and a GeoPackage layer cannot store more than 1 feature having the same value in a "fid" field, then the automatically exported GeoPackage will actually contain only 1 feature while the export of the other 99 features will be rejected.
In fact, you will find 99 error messages in the OGR tab of Log Messages Panel:

```
WARNING    Feature creation error (OGR error: failed to execute insert : UNIQUE constraint failed: INPUT.fid)
WARNING    Feature creation error (OGR error: failed to execute insert : UNIQUE constraint failed: INPUT.fid)
WARNING    Feature creation error (OGR error: failed to execute insert : UNIQUE constraint failed: INPUT.fid)
....
```

So, to workaround the issue, you need to either ensure the "fid" field of the memory layer contains a unique value for each feature or to remove such field from the memory layer.

**Comment by mjb62** [comment]
Thank you. Overlooked the obvious - wondering if the plug-in ever worked properly.
