### ISSUE TITLE
GetFeatureInfo not working with WMTS layers - request URL not well formed

### ISSUE THREAD

**Issue by bchartier** [qgis/QGIS#57696]
### What is the bug or the crash?

When using the Identify Features tool on a features in a WMTS layer, the GetFeatureInfo request sent by QGIS to the WMTS service contains on error that make the requests unsuccessful.

### Steps to reproduce the issue

1. Open the Log Messages Panel
2. Add a WMTS layer to QGIS map using the Data Source Manager.
For example, try this layer :
- layer geograndest:ocs_grand_est_2010_d67 from service https://www.datagrandest.fr/geoserver/gwc/service/wmts?service=WMTS&request=GetCapabilities
3. Select this WMTS layer in the Layers Panel
4. Activate the Identifiy Features Tool
5. Click on features of the WMTS layer
6. See the lack of identify results
7. See the new warning message in the Log Messages Panel (indicating that the WMTS service has not been able to process the GetFeatureInfo request)
The request URL contains a double "/" in its middle:
`https://www.datagrandest.fr/geoserver/gwc/service/wmts/rest/geograndest:ocs_grand_est_2010_d67//EPSG:3857/EPSG:3857:18/90505/136735/120/40?format=text/html`

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
Version de QGIS | 3.34.7-Prizren Révision du code 6f7d735c
-- | -- 
Version de Qt | 5.15.13
Version de Python | 3.12.3
Version de GDAL/OGR | 3.9.0
Version de Proj | 9.4.0
Version de la base de données du registre EPSG | v11.004 (2024-02-24)
Version de GEOS | 3.12.1-CAPI-1.18.1
Version de SQLite | 3.45.1
Version de PDAL | 2.6.3
Version du client PostgreSQL | 16.2
Version de SpatiaLite | 5.1.0
Version de QWT | 6.2.0
Version de QScintilla2 | 2.14.1
Version de l'OS | Windows 11 Version 2009
  |   |   |  
Extensions Python actives
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@bchartier, thanks for reporting. The issue occurs because the GetCapabilities document reports the following FeatureInfo template url for the layer "geograndest:ocs_grand_est_2010_d67": `https://www.datagrandest.fr/geoserver/gwc/service/wmts/rest/geograndest:ocs_grand_est_2010_d67/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=text/html
`
Since such layer doesn't have a style name, then `{style}` in the template url will be substituted with an empty string  -> `https://www.datagrandest.fr/geoserver/gwc/service/wmts/rest/geograndest:ocs_grand_est_2010_d67//...`
Such url is considered "insecure" by the server's firewall and rejected as reported in the error message (`HTTP ERROR 500 org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.`) displayed browsing at `https://www.datagrandest.fr/geoserver/gwc/service/wmts/rest/geograndest:ocs_grand_est_2010_d67//EPSG:3857/EPSG:3857:18/90505/136735/120/40?format=text/html`

I think the WMTS server shouldn't use the `{style}` variable in the template url —in the first place, since there is no style name for such layer, or should provide a style name, and that the server's firewall shouldn't reject such url.

Not sure what is the standard to follow when a variable in the template url has en empty value.

**Comment by bchartier** [comment]
@agiudiceandrea, thanks a lot for your analysis.
I checked my WMTS service options and I can't see any way to set the names of the styles for my WMTS layers.
I have to check this with the GeoServer/GeoWebCache community.
Strangely enough the second example you provided is also a GeoWebCache service provided by GeoServer. It does not contain any style name and its GetFeatureInfo templates are identical to mine.

Thanks a lot again.

I close this issue since it should be addressed to GeoServer/GeoWebCache.

**Comment by agiudiceandrea** [comment]
Actually it is the server's firewall that rejects such the featureinfo url.

**Comment by bchartier** [comment]
Nonetheless, the identifier of the style should be present in the capabilities since it's mandatory from the WMTS specification point of view. I will also signal the fact that the GetFeatureInfo is rejected by the firewall to the administrator of the service.
