### ISSUE TITLE
ogr2ogr Incorrect Transformation EPSG:9989(Epoch2024.0401) to EPSG:22717(Epoch2010.001)

### ISSUE THREAD

**Issue by DrawQuick** [qgis/QGIS#57713]
### What is the bug or the crash?

Using:
ogr2ogr -f "GPKG" -s_srs EPSG:9989 -s_coord_epoch 2024.090 -t_srs EPSG:22717 -t_coord_epoch 2010.001
Input:
GPKG layer with CRS EPSG:9989-ITRF2020
Points were recorded using QField app, Sensor U-Blox C099-F9P board, GNSS Master app.
Correction data was provided by Thingstream(PointPerfect) ITRF2020(Epoch April 1, 2024 changes quarterly)

Input: Recorded Coordinates(Geographic)                     
lat: 43.918799362083334
long: -80.09282164175
h: 387.746 
Transformed Coordinates(Nad83(CSRS)V7-UTM17) epoch 2010.001
x: 572831.693
y: 4863254.060
z: 386.644

Result by Natural Resources Canada TRX tool (https://webapp.csrs-scrs.nrcan-rncan.gc.ca/geod/tools-outils)
x: 572832.228
y: 4863253.064
z: 388.857

### Steps to reproduce the issue

All Points were recorded on the same control point
Attached project file and 3 layers
Layer 1: Points2020 - recorded using corrections from PointPerfect
Layer 2: Converted - Transformed using ogr2ogr
Layer 3: PointsN83V7 - recorded using corrections from RTK2Go base station: OvilleOne

The Converted Layer should end up on top of  Layer 3+-
I believe this was working on the previous version of QGIS(Prizren)

[basestationnad83v7.zip](https://github.com/user-attachments/files/15745211/basestationnad83v7.zip)

![ogr2ogrLog](https://github.com/qgis/QGIS/assets/124696872/b3ba3d3c-3399-4d67-8d3b-311b3dd0df01)
![ogr2ogrParameters](https://github.com/qgis/QGIS/assets/124696872/12fe80c0-d447-4be3-9db9-60e7eb687408)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.3-Maidenhead | QGIS code revision | 2df96554
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.9.0
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
contour | 2.0.14
FreehandRasterGeoreferencer | 0.8.3
Mergin | 2024.1
multilayerselect | 1.5.0
OSMDownloader | 1.0.3
qfieldsync | v4.9.1
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.36.3-Maidenhead
QGIS code revision
[2df96554](https://github.com/qgis/QGIS/commit/2df96554)
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
contour
2.0.14
FreehandRasterGeoreferencer
0.8.3
Mergin
2024.1
multilayerselect
1.5.0
OSMDownloader
1.0.3
qfieldsync
v4.9.1
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@DrawQuick, thanks for reporting. AFAIK, the algorithm "Convert format" actually relies on a GDAL/OGR library's program which in turn relies on the PROJ library for the coordinate transformation. So, if there is an issue transforming the coordinates using such algorithm, I think the issue should be reported to the GDAL/OGR library's repository and / or the PROJ library's repository.

Using the PROJ 9.4.0 tool cs2cs (on Windows 10 / OSGeo4W) to transform the coordinates indicated in the example, it seems to me the transformed coordinates are almost the same as expected:

```
cs2cs -d 3 --s_epoch 2024.090 --t_epoch 2010.001 EPSG:9989 EPSG:22717
43.918799362083334 -80.09282164175 387.746
572832.225      4863253.064 388.857
```

The file Points2020.gpkg contains 2 vector layers: pointsitrf2020 and Points2020. I've failed to find a feature in either of such layers having a point geometry with the coordinates indicated in your example (X: -80.09282164175, Y: 43.918799362083334, Z: 387.746).

So I've created a new layer [PointZ_9989.zip](https://github.com/user-attachments/files/15747392/PointZ_9989.zip) with just 1 PointZ feature having such coordinates (X: -80.09282164175, Y: 43.918799362083334, Z: 387.746).

Then I've used the "Convert format" algorithm to convert the PointZ_9989 layer with the given additional options `-s_srs EPSG:9989 -s_coord_epoch 2024.090 -t_srs EPSG:22717 -t_coord_epoch 2010.001`: the resulting layer [Converted_22717.zip](https://github.com/user-attachments/files/15747433/Converted_22717.zip) contains 1 PointZ feature with the expected coordinates 'PointZ (572832.225 4863253.064 388.857)'.

May you please double check?

**Comment by DrawQuick** [comment]
Hello Andrea,
Did you open the project file and look at the Points2020 layer?
In that layer under "properties/information/Information from provider" it
lists the Geometry as Point(PointZM). The Points2020 layer was a copy from
a previous layer "pointsitrf2020". When copying a layer I assumed it would
make a copy and not point to the same data set. Also I first started this
project as not being connected to QField cloud. QField cloud converted my
layers from shape point layers to gpkg layers.
Attached is a screen capture(SelectedPoint.JPG) showing highlighted in red
the point I used in my example. You can see the coordinates in the image.
Did you run ogr2ogr on the Points2020 layer or a new layer of the same
definition and 'confirm/not confirm' my result?
Can I run cs2cs from within QGis and how would I do that? I would like if
it would run the way ogr2ogr works?
I posted the bug on QGIS as the Process plugin is a core plugin of QGIS. I
would assume that the developers would pass this to the GDAL project.

**Comment by DrawQuick** [comment]
Hi Andrea,
I created another GPKG Layer "TestITRF2020.gpkg". Uploaded this to QField Cloud and observed 2 points. The points ended near to the points in layer Points2020. However, when I download the "TestITRF2020.gpkg", the points end up near the points in layer "PointsN83V7.gpkg". I then ran the ogr2ogr on the "TestITRF2020.gpkg" and it transforms the points to the correct position. Does QField not apply the "on-the-fly transform" to the project CRS when recording points? I'm a little confused? I zipped the updated project and attached to this comment.

[basestationnad83v7.zip](https://github.com/user-attachments/files/15748960/basestationnad83v7.zip)

**Comment by agiudiceandrea** [comment]
@DrawQuick, please use the GitHub web interface if you need to use images or attach files to the comment, otherwise they will be not viible.

The Points2020 layer in the provided project contains the following 6 points none of which has coordinates that corresponds to the ones indicated as "Input: Recorded Coordinates(Geographic)" lat: 43.918799362083334 long: -80.09282164175 h: 387.746


| wkt_geom | fid | Pt |
| --- | --- | --- |
| PointZM (-80.09282816168358465 43.91880838331383075 385.53331949003040791 1717622319000) | 26 | 7 |
| PointZM (-80.09282810010023468 43.9188083337305244 385.52751948498189449 1717622377000) | 27 | 8 |
| PointZM (-80.09282826710030179 43.91880833414714402 385.52821949031203985 1717622410000) | 28 | 9 |
| PointZM (-80.09282827226695645 43.91880835956384033 385.52776948921382427 1717622520000) | 29 | 10 |
| PointZM (-80.09282830451694224 43.91880826556386808 385.52076948154717684 1717622583000) | 30 | 11 |
| PointZM (-80.09282819310030277 43.91880830156384263 385.52196948509663343 1717622637000) | 31 | 12 |

You can check the points geometry using the `geom_to_wkt(@geometry)` expression in the Field Calculator or just copying the records in the attribute table and pasting them elsewhere.

**Comment by agiudiceandrea** [comment]
@DrawQuick, please use the GitHub web interface if you need to use images or attach files to the comment, otherwise they will be not viible.

The Points2020 layer in the provided project contains the following 6 points none of which has coordinates that correspond to the ones indicated as "Input: Recorded Coordinates(Geographic)" lat: 43.918799362083334 long: -80.09282164175 h: 387.746


| wkt_geom | fid | Pt |
| --- | --- | --- |
| `PointZM (-80.09282816168358465 43.91880838331383075 385.53331949003040791 1717622319000)` | 26 | 7 |
| `PointZM (-80.09282810010023468 43.9188083337305244 385.52751948498189449 1717622377000)` | 27 | 8 |
| `PointZM (-80.09282826710030179 43.91880833414714402 385.52821949031203985 1717622410000)` | 28 | 9 |
| `PointZM (-80.09282827226695645 43.91880835956384033 385.52776948921382427 1717622520000)` | 29 | 10 |
| `PointZM (-80.09282830451694224 43.91880826556386808 385.52076948154717684 1717622583000)` | 30 | 11 |
| `PointZM (-80.09282819310030277 43.91880830156384263 385.52196948509663343 1717622637000)` | 31 | 12 |

You can check the points geometry using the `geom_to_wkt(@geometry)` expression in the Field Calculator or just copying the records in the attribute table and pasting them elsewhere.

Using the "Convert format" algorithm with such layer as input and the given additional options `-s_srs EPSG:9989 -s_coord_epoch 2024.090 -t_srs EPSG:22717 -t_coord_epoch 2010.001` produces a layer with the following features:

| wkt_geom | fid | Pt
| --- | --- | ---
| `PointZM (572831.69098839734215289 4863254.06060034409165382 386.64425286278128624 1717622319000)` | 26 | 7
| `PointZM (572831.6959930257871747 4863254.05514758639037609 386.6384528586640954 1717622377000)` | 27 | 8
| `PointZM (572831.68258512776810676 4863254.05504660494625568 386.63915286213159561 1717622410000)` | 28 | 9
| `PointZM (572831.68213932309299707 4863254.05786499753594398 386.63870286010205746 1717622520000)` | 29 | 10
| `PointZM (572831.67966484243515879 4863254.04739628732204437 386.63170285802334547 1717622583000)` | 30 | 11
| `PointZM (572831.68856587179470807 4863254.05149293318390846 386.63290285971015692 1717622637000)` | 31 | 12

Transforming the coordinates of the geometry of the first feature of Points2020 (`-80.09282816168358465 43.91880838331383075 385.53331949003040791`) using the Natural Resources Canada TRX tool gives the following coordinates: `572831.694 4863254.060 386.644` which are almost the same as the ones calculated by "Convert format".

The little difference (about 3mm) is due to the fact that you wrote that the correction were given for "Epoch April 1, 2024", but you specified an incorrect option `-s_coord_epoch 2024.090`: the decimal value of the epoch corresponding to April 1, 2024 is about 2024.262, not 2024.090.
Using the correct additional options `-s_srs EPSG:9989 -s_coord_epoch 2024.262 -t_srs EPSG:22717 -t_coord_epoch 2010.001` produces a layer with coordinates that are the very same as calculated using the Natural Resources Canada TRX tool.

> Can I run cs2cs from within QGis and how would I do that?

You can use the cs2cs program provided by the PROJ library in the OSGeo4 Shell. I've used it only to check if the PROJ library (which is responsible for the coordinate transformation) correctly transforms the coordinates.

**Comment by DrawQuick** [comment]
I thought the Epoch date is expecting the number of days from the beginning of the year. April 1, 2024 is "92". The documentation doesn't appear to define this. How did you arrive at 249?

**Comment by agiudiceandrea** [comment]
> I thought the Epoch date is expecting the number of days from the beginning of the year. April 1, 2024 is "92". The documentation doesn't appear to define this. How did you arrive at 249?

Please see, for example:
- https://gdal.org/user/coordinate_epoch.html#:~:text=The%20coordinate%20epoch%20is%20expressed%20as%20a%20decimal%20year%20(e.g.%202021.3%20for%20April%2021%2C%202021).
- https://docs.ogc.org/as/18-005r4/18-005r4.html#:~:text=In%20this%20document%20%E2%80%9CEpoch,tectonic%20plate%20linear%20motion.
- https://www.xyht.com/surveying/links-need-seeing-to-datum-epochs-and-how-to-understand-them/#:~:text=The%20decimal%20year%20is%20equal%20to%3A%20year%20%2B%20day-in-year/365%20(366%20for%20leap%20years).%20For%20example%2C%20January%201%2C%202010%20is%20written%20as%202010.00%3B%20May%205%2C%201991%20is%20the%20128th%20day%20and%20written%20as%201991.35

It seems to me there is actually no issue in the "Convert format" algorithm: the coordinate are transformed the same way as the Natural Resources Canada TRX tool does.

Can we close this issue report?

**Comment by DrawQuick** [comment]
I think it would have been better to have answered the question as "the epoch is calculated as the number of days from the beginning of the year divided by 365.25(number of days in the year). Example April 1, 2024 is calculated as 2024+(92 days/365.25)=2024.252
You haven't answered my other question about why QField has a different coordinate location for my points as compared to Qgis?
Yes you can close the report now.
Thank you for your help

**Comment by agiudiceandrea** [comment]
> You haven't answered my other question about why QField has a different coordinate location for my points as compared to Qgis?

I don't know. I suggest you to report the issue to the QField developers at https://github.com/opengisch/QField.
