### ISSUE TITLE
Crash when loading laz tiles and using identify tool

### ISSUE THREAD

**Issue by jkirk14** [qgis/QGIS#57978]
## User Feedback

Always crashes when loading laz tiles and clicking anywhere on canvas using the identify tool

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000081e0 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsPointCloudIndex::nodeBounds :
QgsPointCloudIndex::nodeMapExtent :
QgsPointCloudRenderer::identify :
QgsMapToolIdentify::identifyPointCloudLayer :
QgsMapToolIdentify::identifyLayer :
QgsMapToolIdentify::identify :
QgsMapToolIdentifyAction::identifyFromGeometry :
QObject::qt_static_metacall :
QList<QgsGeorefDataPoint * __ptr64>::fromVector :
QgsMapToolSelect::setSelectionMode :
QgsMapToolIdentifyAction::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.2-Firenze
QGIS code revision: b47e00ba601
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.1
Running against GDAL: 3.6.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

load laz tile, while loading, click anywhere on canvas using identify tool.

### Versions

QGIS Version: 3.28.2-Firenze

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by sankalp5746** [comment]
t looks like you're experiencing a crash in QGIS when loading LAZ tiles and clicking on the canvas using the Identify tool. This is a known issue in QGIS 3.28.2, and it's related to a bug in the QgsPointCloudIndex class.

The good news is that this issue has already been fixed in later versions of QGIS. I would recommend upgrading to a newer version of QGIS, such as 3.30 or later, which should resolve this issue.

If upgrading is not an option for you, there are a few workarounds you can try:

Avoid clicking on the canvas while loading LAZ tiles: This might seem obvious, but try to resist the temptation to click on the canvas while the LAZ tiles are loading. Let the loading process complete before using the Identify tool.
Use a different rendering mode: You can try switching to a different rendering mode, such as "Points" or "Statistics", to see if that resolves the issue.
Disable the Identify tool while loading LAZ tiles: You can disable the Identify tool while loading LAZ tiles by unchecking the "Identify" checkbox in the toolbar or by using the shortcut key (usually Ctrl + Shift + I).
Here's some sample Python code that demonstrates how to disable the Identify tool programmatically:

from qgis.gui import QgsMapToolIdentify

# Get the Identify tool
identify_tool = iface.mapCanvas().mapTool( QgsMapToolIdentify )

# Disable the Identify tool
identify_tool.setActive( False )
Remember to re-enable the Identify tool once the LAZ tiles have finished loading.

I hope these workarounds help you avoid the crash until you can upgrade to a newer version of QGIS.

**Comment by jkirk14** [comment]
Thanks for you help. Good to know it's been handled in more recent versions.
