### ISSUE TITLE
installing QGIS

### ISSUE THREAD

**Issue by Marks2023** [qgis/QGIS#58187]
### What is the bug or the crash?

I want to install QGIS not on C drive but my D drive and still the software tells me that there is not enough discspace on C drine. But everything must be installed on my D drive.

This is for 3.34 and 3.38 version. In the past installed 3.30.0 without any problems

### Steps to reproduce the issue

steps download QGIS and install,
choose D drive and a map QGIS 

### Versions

This is for 3.34 and 3.38 version. In the past installed 3.30.0 without any problems

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by JoKra8833** [comment]
I have acually almost the same problem, C: full, D: has enough space, but despite choice of a Dir in D: it does'nt work. Only difference to Marks2023: I'm beginner and because I can not install QGIS at all, I can not change the profile file. 
[2024-07-19 Screenshots QGIS install problem.pdf](https://github.com/user-attachments/files/16313724/2024-07-19.Screenshots.QGIS.install.problem.pdf)

**Comment by agiudiceandrea** [comment]
@Marks2023 @JoKra8833, thanks for reporting. Did you use the all-in-one stand-alone QGIS-OSGeo4W-*.msi installer or the OSGeo4W network installer osgeo4w-setup.exe?

**Comment by JoKra8833** [comment]
I used the all-in-one stand-alone QGIS-OSGeo4W-*.msi installer, because I'm beginner with QGIS. Regards Jo

**Comment by jef-n** [comment]
That's because the Windows installer copies the MSI to `%TEMP%` and later to `%WINDIR%\Installer`, which are both  usually located on `C:`.  AFAICS that cannot be changed.  And it should have been that way since we switched from NSIS to MSI.  Using `osgeo4w-setup.exe` will use less space (although `%TEMP%` will also be used to download and cache packages by default) and moreover open the option to install less packages (eg. leave out Oracle support).
