### ISSUE TITLE
QGIS 3.38.1-1 embedded symbols not loading

### ISSUE THREAD

**Issue by wesmacaulay** [qgis/QGIS#58208]
### What is the bug or the crash?

New unwanted behaviour in 3.38.1-1 (code version 3d4177afc6): embedded symbology from imported KMLs are ignored. This happens in both upgraded and new projects.

I am an admin on Trailforks, and download KMLs of trails in our riding areas to import into QGIS for planning purposes. In previous versions of QGIS (including 3.38.0) the symbology (trail difficulty rating - black, blue, green, etc) for the trails would be given for all trails.

In 3.38.1, that symbology is ignored, and I must categorize the trails by difficulty myself. Is this an intended change, or a bug?

### Steps to reproduce the issue

Import KML with embedded symbology.  The symbology will be ignored.

### Versions

3.38.1-1 (code version 3d4177afc6)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Can you share a sample kml please?

**Comment by wesmacaulay** [comment]
[vedder-mountain_trails_trailforks.zip](https://github.com/user-attachments/files/16341224/vedder-mountain_trails_trailforks.zip)

**Comment by nyalldawson** [comment]
Works OK here. Can you check under the layer properties, information tab, and look what is reported under the "storage" value (under "information from provider")?

**Comment by wesmacaulay** [comment]
Interesting.  Storage reports LIBKML

**Comment by agiudiceandrea** [comment]
@wesmacaulay, on my Windows 10 system, the symbology of the provided layer is not displayed even using QGIS 3.38.0 from OSGeo4W (with GDAL 3.9.1, either by the GDAL/OGR LIBKML driver or the GDAL/OGR KML driver).

The symbology of the provided layer is instead displayed using QGIS 3.36.1 or QGIS 3.34.5 from OSGeo4W (with GDAL 3.8.4, only by the GDAL/OGR LIBKML driver) on the same system, while it is not displayed using QGIS 3.34.8 (with GDAL 3.9.1, either by the GDAL/OGR LIBKML driver or the GDAL/OGR KML driver).

So I suppose the issue may be due to a change in the GDAL/OGR library (from 3.8 to 3.9) or in the rebuild of the libkml library after https://lists.osgeo.org/pipermail/qgis-user/2024-April/054334.html.

**Comment by agiudiceandrea** [comment]
The symbology of the provided layer is also displayed using either QGIS 3.34.8 (with GDAL/OGR 3.9.0) or QGIS 3.34.9 (with GDAL/OGR 3.9.0) while it is not displayed using either QGIS 3.34.8 (with GDAL/OGR 3.9.1) or QGIS 3.34.9 (with GDAL/OGR 3.9.1).

So it looks like the issue is due to GDAL/OGR 3.9.1.

**Comment by rouault** [comment]
Confirmed as a GDAL 3.9.1 bug. Fix in https://github.com/OSGeo/gdal/pull/10473
