### ISSUE TITLE
QGIS for Peace: Palestinian flag is missing if Ukraine flag is shown.

### ISSUE THREAD

**Issue by arminiusresistance** [qgis/QGIS#58416]
### Feature description

Hi,

It is been since several versions that we see the Flag of Ukraine to be in QGIS. As an open source tool which combines the opinion of all of the developers, I believe it is fair to put the flag of Palestine as well if QGIS community would like to include politics in this open source tool. Otherwise, it is perceived as a double standard. 
I hope this post is seen with open mind and let the community to be fair on include all wars in its first page or make the tool free of this topic.

Looking forward to the reaction

Best!

**Comment by agiudiceandrea** [comment]
Hi @arminiusresistance, please read https://lists.osgeo.org/pipermail/qgis-psc/2023-November/010159.html.
@mbernasocchi, should this request be brought to the attention of the PSC?

**Comment by blacktesta** [comment]
My father is Russian and my mother is Ukrainian. IMHO only peace sign must be in open source worldwide application to describe that people all over the world want peace.

**Comment by yekruz** [comment]
@arminiusresistance @agiudiceandrea @mbernasocchi @blacktesta 

I think this shall definitely be brought to the attention of the PSC. According to the IJC, a genocide is happening right now in Palestine and every human being has the duty to stand up and show that we can are against it to protect children.

I would strongly ask the QGIS team to take this into attention to carry out necessary actions to show that all human lives are important. We shall show that we have no double standard to stand with. This way GIS community can see this a positive sign of QGIS and continue to contribute to that. Otherwise, it will be seen as a tool controlled by politics and not the humanitarian values.


Hopefully, as a European member of GIS member could see the flag of Palestine is raised when I open my QGIS as soon as possible.

**Comment by kannes** [comment]
As you can see in the [qgis-psc message linked above](https://lists.osgeo.org/pipermail/qgis-psc/2023-November/010159.html), this was already discussed by the PSC.

Let me add a quote so it is not missed again:

> At the PSC we lengthy discussed [...] and came to the decision not
> to do that.
> To be clear, this has nothing to do with this specific conflict. After
> putting out the Ucraine message we realised that by focusing on that
> conflict we were neglecting many other conflicts that unfortunately are
> burdening our world and that if QGIS was to put a flag on its news feed for
> each conflict, well, I'll let you imagine our news feed.
> 
> As Raymond nicely wrote, we've very little (and precious) time we give to
> the QGIS project and we want this to be as much value for QGIS.org as
> possible so we'd rather put our focus on helping our community making
> (quoting the newsfeed again ) "tools like QGIS to the benefit of all
> citizens on earth, to support a sustainable environment, an orderly society
> and, in particular, to establish and preserve sovereign dignity, security
> and freedom from oppression".

**Comment by yekruz** [comment]
@blacktesta 
I understand, but how come the result of this lengthy discussion is that we see Ukrainian flag in our news feed and not the Palestinian flag? According to the UN, Palestinian territories are under occupation since 1948.

How about we would remove the Ukranian flag and other could also imagine that flag in their new feed? Wouldn't this be leading to closing this feature request as suggested initially by @arminiusresistance 

> As you can see in the [qgis-psc message linked above](https://lists.osgeo.org/pipermail/qgis-psc/2023-November/010159.html), this was already discussed by the PSC.
> 
> Let me add a quote so it is not missed again:
> 
> > At the PSC we lengthy discussed [...] and came to the decision not
> > to do that.
> > To be clear, this has nothing to do with this specific conflict. After
> > putting out the Ucraine message we realised that by focusing on that
> > conflict we were neglecting many other conflicts that unfortunately are
> > burdening our world and that if QGIS was to put a flag on its news feed for
> > each conflict, well, I'll let you imagine our news feed.
> > As Raymond nicely wrote, we've very little (and precious) time we give to
> > the QGIS project and we want this to be as much value for QGIS.org as
> > possible so we'd rather put our focus on helping our community making
> > (quoting the newsfeed again ) "tools like QGIS to the benefit of all
> > citizens on earth, to support a sustainable environment, an orderly society
> > and, in particular, to establish and preserve sovereign dignity, security
> > and freedom from oppression".

**Comment by haubourg** [comment]
Hi all, we made this entry expire tomorrow. The plan was to let it burry in the newsfeed but we currently have very little published news and it popped up again.

**Comment by yekruz** [comment]
@haubourg @kannes @agiudiceandrea @blacktesta 
I am a former European and German Aerospace Centers e.V. (ESA-DLR). I would like to ask kindly to put the flag of Palestine next to the Ukrainian flag as the latest version seems to still only show the Ukrainian flag.
I have contributed to QGIS in the past both financially and technically and since a while, I have founded a company in Munich in GIS sector.
This is my last time request. In case the QGIS team would fail to address this humanitarian issue and ignore the ongoing Genocide recognized by International Court of Justice (ICJ) and the United Nations, I have no choice to stop using it. Use an old version fork of QGIS, recompile it again with appropriate UI aligned with international humanitarian values, making it open source, resuming contributing to that version  within the terms of the original license.

The reason of this decision will also clearly be mentioned in the first page of that open source project.
It would definitely hurt my feeling to do so which I was a fond member of QGIS for so long.

**Comment by agiudiceandrea** [comment]
> the latest version seems to still only show the Ukrainian flag.

QGIS doesn't currently show any flag in the newsfeed. The newsfeed is currently totally empty.

Try creating and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
