### ISSUE TITLE
Raster Calculator not working 3.34.10

### ISSUE THREAD

**Issue by Pippo-90** [qgis/QGIS#58791]
### What is the bug or the crash?

Starting from today I am experiencing a series of problems with the raster calculator, even for the simplier task.
The final output has wrong values, geometry and geolocalization.
This is how it looks now:
![Screenshot 2024-09-18 192401](https://github.com/user-attachments/assets/681e4506-bb16-4dda-8c5c-a25eeab8bfa7)

This is how it should look/be

![Screenshot 2024-09-18 192913](https://github.com/user-attachments/assets/e6061015-aeea-478a-9abd-b7729ece7000)

### Steps to reproduce the issue

1. Go to "raster calculator" under the toolbar
2. write the formula to calculate the Top of Atmosphere radiance (TOA): 0.0003345 * Band 10 +0.10000 -0.29
3. Either click or not to "Use Selected Layer Extent" --> it gives problem in both cases
4. Save output layer as "TOA"

### Versions

3.34.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
@Pippo-90 it may help to share your dataset, so that people can reproduce the error.

**Comment by agiudiceandrea** [comment]
@Pippo-90, you report the the issue occurs "starting from today": have you update to a new version or installed a new version of QGIS or have you installed / uninstalled any external plugin have you made other changes to your QGIS installation configuration, or have you changed the tool (there are various raster calculator tools, which one have you used exactly?) or the parameters or the input layer used?

Moreover, other than providing a sample layer and exact parameters and detailed steps in order to replicate the issue, as requested in the previous comment, please try if the issue does occur also using a new QGIS user profile and please provide the QGIS full version info ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.")
