### ISSUE TITLE
QGIS 3.39 tries to create files with SNAP_TIFF read-only driver

### ISSUE THREAD

**Issue by jratike80** [qgis/QGIS#59112]
### What is the bug or the crash?

I am using QGIS version 3.39.0-Master, QGIS code revision 40246d3509 installed with OSGeo4W. When I try for example to clip a raster layer a GDAL command like this is created:
`gdal_translate -projwin 360853.6639 6714413.7697 360961.8182 6714257.3265 -of SNAP_TIFF C:\data\dem2m.tif C:/Users/JRAHKONEN/AppData/Local/Temp/processing_giGcnu/ad37cba320a145848a03c12bed16db8d/OUTPUT.tif`

Notice the output format SNAP_TIFF, that means this brand new read-only driver https://gdal.org/en/latest/drivers/raster/snap_tiff.html. The SNAP_TIFF driver cannot be used at all for writing, and it should be used only for reading some peculiar TIFF variants.

### Steps to reproduce the issue

Try to clip a raster layer with `GDAL - Raster extraction - Clip raster by extent`. Process fails and the meaningful part of the error message is
```
GDAL command output:
Output driver `SNAP_TIFF' not recognised. 
```

### Versions

QGIS version
3.39.0-Master
QGIS code revision
40246d3509
 
Libraries
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.10.0dev-b6edb5191e
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009
This copy of QGIS writes debugging output.
 
Active Python plugins
FreehandRasterGeoreferencer
0.8.3
latlontools
3.7.1
Qgis2threejs
2.7.3
rasmover-master
version 0.2
simplewcs
0.2
wfsclient
0.9.11
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Even Rouault claims that he could not reproduce on Linux, see comments at https://github.com/OSGeo/gdal/pull/10867

**Comment by agiudiceandrea** [comment]
I can confirm the issue using QGIS 3.39.0-Master bb9a7165e6 with GDAL/OGR 3.10.0dev-4e28921731 from OSGeo4W on Windows 10.

@jratike80 @rouault the issue is due to the fact that QgsRasterFileWriter.driverForExtension('tiff') [which is used by the processing algorithms and other tools in order to derive the correct driver for an extension] outputs "SNAP_TIFF", which, in turn, is due to the fact that the SNAP_TIFF driver has a driver index (3) lower than the driver index (4) of the GTiff driver.

https://github.com/qgis/QGIS/blob/047cab15a8b4bddd0aab19919673d04ba2d0dae7/src/core/raster/qgsrasterfilewriter.cpp#L1066-L1099

**Comment by rouault** [comment]
oh well, let's not declare file extensions for the SNAP_TIFF driver: https://github.com/OSGeo/gdal/pull/11037
