### ISSUE TITLE
Problem opening mapinfo file

### ISSUE THREAD

**Issue by q1165600785** [qgis/QGIS#59262]
### What is the bug or the crash?

I have two types of mapinfo files, one is. tab. map. id. dat, and the other is. tab. map. id. dbf. The first type can be opened, but the second type is that the dbf property sheet cannot be opened and is left empty. How can I solve this situation

### Steps to reproduce the issue

My QGIS did not crash, but it cannot be opened. I want to use QGIS to convert mapinfo to an SHP file

### Versions

3.22.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@q1165600785, QGIS 3.22 is non longer supported. Moreover, according to https://gdal.org/en/latest/drivers/vector/mitab.html it looks like only the ".dat" extension is taken in consideration and not the ".dbf" extension. In order to change such behaviour you need to report it to the GDAL/OGR GitHub repository.
Have you tried just renaming the "*.dbf" files to "*.dat"?
