### ISSUE TITLE
Field Calculator Uses Original Units After Layer Reprojection

### ISSUE THREAD

**Issue by changlu12** [qgis/QGIS#59571]
### What is the bug or the crash?

After reprojecting a layer in QGIS, the layer properties correctly display the units of the new coordinate system. However, when using the Field Calculator to calculate geometry, the calculations still use the units of the original coordinate system, resulting in incorrect outputs.

### Steps to reproduce the issue

1. Load a layer into QGIS with an initial coordinate system that uses feet as the unit (e.g., EPSG:2277).
2. Use the "Reproject Layer" function to transform the layer to another coordinate system that uses meters as the unit (e.g., EPSG:32633).
3. Verify in the layer properties that the units have been updated to meters according to the new coordinate system.
4. Use the Field Calculator with the $area or $length function to calculate geometry. The results still use the original units (feet) instead of the units of the new projection (meters).

### Versions

QGIS 3.38.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@changlu12, please read the User Guide / Manual:

13.2.13.4. $area
https://docs.qgis.org/3.34/en/docs/user_manual/expressions/functions_list.html#area
> The area calculated by this function respects both the current project’s ellipsoid setting and area unit settings.


13.2.13.58. $length
https://docs.qgis.org/3.34/en/docs/user_manual/expressions/functions_list.html#length
> The length calculated by this function respects both the current project’s ellipsoid setting and distance unit settings.


Use the `area` and `length` function instead.

**Comment by changlu12** [comment]
Dear Sir/Madam,
  I hope this message finds you well. I am reaching out to seek assistance
with an issue I encountered while calculating feature areas in QGIS after
reprojecting a layer.
Problem Description

After reprojecting the layer, the feature area calculated using the field
calculator seems to have errors. Specifically, the results in square feet
differ significantly from those calculated in ArcGIS.
Operation DetailsLayer Information

The operations were performed on the polygon layer *Vegetation*. The
layer's CRS is *EPSG:3857 - WGS 84 / Pseudo-Mercator*, with the unit in
*meters*.
The layer's attribute fields are as follows:

   - *Shape_Area*: A default field indicating the feature area in square
   meters.
   - *areaac*: Feature area calculated in ArcGIS in square meters,
   consistent with the *Shape_Area* field, confirming ArcGIS's results are
   accurate.
   - *areaacfeet*: Feature area calculated in ArcGIS in square feet, used
   for verification.

Operations Performed in QGIS

   1.

   *Calculations in the Original Projection (EPSG:3857)*
   - *area_qigs*: Calculated using $area. The result differs from
      *Shape_Area* and *areaac*.
      - *area_qigs2*: Calculated using area($geometry). The result matches
      *Shape_Area* and *areaac*.
   2.

   *Reprojecting the Layer to EPSG:2913 - NAD83(HARN) / Oregon North (ft)*
   - *area_qigs3*: Calculated using $area. Since the unit of the projection
      is in feet, the result should theoretically be in square feet.
However, it
      does not match *areaacfeet*.
      - *area_qigs4*: Calculated using area($geometry). Similarly, the
      result does not match *areaacfeet*.

Request

I have recorded a video of the entire process and attached the *Vegetation*
layer file for your reference.

Could you kindly help analyze and identify the cause of the discrepancy?
Your insights and support would be greatly appreciated.

Thank you very much for your time and assistance.

Best regards,
Lu Chang
 Operation.mp4
<https://drive.google.com/file/d/1ZR8WhiC2oIyRxTYWGzKdlSl-AODywbIg/view?usp=drive_web>
 Vegetation.zip
<https://drive.google.com/file/d/1bNEgfllrGAthaFmTAgJ7SWftpwUivtab/view?usp=drive_web>

**Comment by agiudiceandrea** [comment]
@changlu12, it looks like it is not possible to download the resources due to missing sharing authorization. Please make them downloadable or directly attach the files in a comment of this issue report using the GitHub Web interface.

**Comment by changlu12** [comment]
I have updated the sharing permissions. The resources should now be downloadable. Please let me know if you encounter any further issues. Thank you!

**Comment by agiudiceandrea** [comment]
@changlu12, as mentioned in the docs, while the `area` function measures the area in the Cartesian plane of the layer CRS in the same unit of the layer (i.e., in other words, it is agnostic about both the layer's CRS and the unit of measure, and it just measure the area on the layer's CRS Cartesian plane using the actual X and Y coordinates values of the vertices), the `$area` function measure the area on the Ellipsoid set in the Project->Properties->General->Measurements dialog window and using the unit of measure set in the same dialog window.

You should also know that while the EPSG:3857 CRS represent geometries introducing great distortion in the area measurement (i.e. the area of a polygon measured on such CRS Cartesian Plane may be very different from the actual area of the polygon measured on the Ellipsoid using the same unit of measure), the EPSG:2913 introduces smaller distortion in area measurement (i.e. the value of area measured on such CRS Cartesian Plane is usually very close to the actual value of the area measured on the Ellipsoid using the same unit of measure).
In other words, the area measured on the EPSG:3857 CRS Cartesian plane is actually different from the area measured on the EPSG:2913 CRS Cartesian plane after reprojecting the layer on the latter CRS, and this is not due to square metres to square feet conversion: in fact it will also be very different even reprojecting the layer to the EPSG:3740 NAD83(HARN) / UTM zone 10N CRS (which has the metre as unit of measure).

The behaviour described by you is actually correct and expected.

I suggest you to read the "Gentle Introduction to GIS" https://docs.qgis.org/3.34/en/docs/gentle_gis_introduction/coordinate_reference_systems.html.

For more questions about such matter, I also suggest you to search and ask using a support forums such as https://gis.stackexchange.com/ or the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user.
