### ISSUE TITLE
Generate XYZ tiles (MBTiles): MBTiles 1.1 spec violation

### ISSUE THREAD

**Issue by oarchner** [qgis/QGIS#59986]
Created MBTile files are missing the description record in table metadata. According to the [MBTiles 1.1 specification](https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md), this entry is mandatory. 

### Steps to reproduce the issue

1. Raster Tools/Generate XYZ Tiles (MBTiles) 
2. Enter a valid map extent
3. Define the output as: test.mbtiles 
4. Run the tool 
5. Open the output with a SQLite DB viewer like dbeaver
6. The description record is missing 
![image](https://github.com/user-attachments/assets/faf54c78-3cff-4bfa-94ea-88d4f5114c1d)
7. Fix to fulfill the spec: `insert into metadata (name,value) values ('description','test'); 
![image](https://github.com/user-attachments/assets/4c31f75a-1f33-44a9-ac4a-095bd91e7ca1)

### Versions

3.40.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context
MBTile files with a missing description record can't be added as custom maps to DJI Pilot 2

**Comment by agiudiceandrea** [comment]
@oarchner, while I see that the value of the `version` key metadata is set to "1.1" by the algorithm itself https://github.com/qgis/QGIS/blob/0b60e0f86605efc55fc65e72f2dbe18e0d9aa0c8/src/analysis/processing/qgsalgorithmxyztiles.cpp#L497 I'm not sure it refers to the MBTiles specification version since the MBTiles specifications say that "This refers to a revision of the tileset itself, not of the MBTiles specification".

Since the processing algorithm has been developed in Python in 2019 (https://github.com/qgis/QGIS/pull/9857) by @marcel-dancak and ported to C++ in 2023 (https://github.com/qgis/QGIS/pull/54321) by @alexbruy, I guess the algorithm was developed referring to the version 1.3 (2018) of MBTiles specification where the `description` key is not mandatory.

Anyway it shouldn't difficult to make the algorithm also add such key in the metadata in order to be compatible with versions 1.1 and 1.2.

**Comment by agiudiceandrea** [comment]
@oarchner, while I see that the value of the `version` key metadata is set to "1.1" by the algorithm itself https://github.com/qgis/QGIS/blob/0b60e0f86605efc55fc65e72f2dbe18e0d9aa0c8/src/analysis/processing/qgsalgorithmxyztiles.cpp#L497 I'm not sure it refers to the MBTiles specification version number, since the MBTiles specifications say that such key "refers to a revision of the tileset itself, not of the MBTiles specification".

Since the processing algorithm has been developed in Python in 2019 (https://github.com/qgis/QGIS/pull/9857) by @marcel-dancak and ported to C++ in 2023 (https://github.com/qgis/QGIS/pull/54321) by @alexbruy, I guess the algorithm was developed referring to the version 1.3 (2018) of MBTiles specification where the `description` key is not mandatory. Another clue is the fact that the algorithm sets the `minzoom` and `maxzoom` keys which are only defined in 1.3 version.

Anyway it should be simple to make the algorithm also add such key in the metadata in order to be compatible with versions 1.1 and 1.2.

Are you going to propose a Pull Request?

**Comment by agiudiceandrea** [comment]
Looking better at how the algorithm worked before and after the porting to C++ since QGIS 3.34, it seems to me this is a regression probably due o an oversight in https://github.com/qgis/QGIS/pull/54321.
